### ISSUE TITLE
Get rid of static Evm class

### ISSUE THREAD

**Issue by oleksandrchainsafe** [ChainSafe/web3.unity#1000]
**Summary**
Remove the static `Evm` class as it provides an outdated SDK approach.

**Suggested features or ways to address the summary**
Remove the intermediate `Evm` class the way we did it with `ErcXX` static classes. Inline contents of each method to the call sites.

**Motivation**
The codebase is currently oversaturated with wrapper classes. It also lacks uniformity in the public interface. All methods of Evm class are essentially code samples, as they simply call functionality provided by the SDK with predefined values. It's better to show users how they can use the functionality we provide instead of hiding it behind wrapper classes like `Evm`. These classes were convenient before as the interface of many components was dirty and hard to understand by newbies, but they are not serving their function anymore.

**Acceptance Criteria**

1. `Evm` class is removed.
2. Its methods' contents are inlined to the place of usage.
3. Tests are functional and now operate on the Sample MonoBehaviours.

**Comment by sneakzttv** [comment]
Combined into https://github.com/ChainSafe/web3.unity/issues/1028 for organization purposes.
