### ISSUE TITLE
How could I skip the MetaMask login and transfer directly?

### ISSUE THREAD

**Issue by milkare** [ChainSafe/web3.unity#101]
![Snipaste_2022-02-19_22-32-25](https://user-images.githubusercontent.com/80621440/154805241-4e7dcadd-f000-4d67-a388-2d5c96ea7afa.png)
  Hi there! I've found this method of Web3Wallet, but obviously invoking this method will open my browser to transfer, that's not what I want. I just want to transfer from the program rather than in my browser. I 'll appreciate for your help!

**Comment by milkare** [comment]
Nah,I'm so stupid that I find that now.
Don't mind this , I'll close this.

**Comment by flyarong** [comment]
> commented
How to do this？Is it a sample code？ Thks。

**Comment by milkare** [comment]
> > commented
> > How to do this？Is it a sample code？ Thks。

Yeah, there's one thing you need to do is offering your private key as parameter to "EVM.method" such things.
