### ISSUE TITLE
React to events that are happening on the smart contract side 

### ISSUE THREAD

**Issue by kantagara** [ChainSafe/web3.unity#1013]
**Summary**
Very similar to #510 but now we know what we need 😁 

**Suggested features or ways to address the summary**
Nethereum itself already has the event subscription. We should try and heavily utilize it on our end with the use of DI and all the other beautiful architectual things we have in our own SDK

**Motivation**
Would allow us to react to certain events in the smart contracts, which we'd greatly benefit from.

**Acceptance Criteria**
- [ ] We can react to the events from smart contract
- [ ] Utilize DI for creating the event poller system

**Blockers**
Potential blocker is WebGL since I'm not sure how doable that is on the WebGL side

**Comment by sneakzttv** [comment]
complete with ABI generation merge https://github.com/ChainSafe/web3.unity/issues/1038
