### ISSUE TITLE
TypeError: Cannot set properties of null (setting 'onclick')

### ISSUE THREAD

**Issue by AbdelNabut** [ChainSafe/web3.unity#102]
**Describe the bug**
When loading up a WebGL Unity project using the web3 login scene, the following error pops up: TypeError: Cannot set properties of null (setting 'onclick'). It seems also to happen only when running the webgl build on a server, since I do not get the error when using Unity's build and run.

**To Reproduce**
1. Build project with web3 login scene as as the first scene in the build.
2. Host build on server
3. Connect to build

**Expected behavior**
I don't expect to see this pop-up error.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] So far MacOS and Windows
 - Browser [e.g. chrome, safari]: Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by KBryan** [comment]
Are you using the Web3GLTemplate. Also, can you verify that your project does work using the Unity webserver
