### ISSUE TITLE
ImportNftTexture sample is not working

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#1022]
**Describe the bug**
The NFT texture is not being imported and being displayed in SampleMain

**Steps**
1. Use the scene [SampleLogin - Wallet connect or SampleLogin - Web3Auth]
2. Login with [Web3Auth or Remote wallet]
3. Click on ImportNftTexture sample

**Expected behavior**
Image is upload and appears in the screen

**Console errors**
Web3Exception: Metadata request failure: Cannot resolve destination host
Scripts.EVM.Token.Erc1155UnityExtensions.ImportTexture (ChainSafe.Gaming.Evm.Contracts.BuiltIn.Erc1155Contract contract, System.String tokenId) (at /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/EVM/Token/Erc1155UnityExtensions.cs:26)
Erc1155Calls.ImportNftTexture1155 () (at Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc1155/Erc1155Calls.cs:133)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <e307bbb467104258887a104f6151f183>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:153)
UnityEngine.UnitySynchronizationContext.Exec () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:83)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:107)

**Desktop (please complete the following information):**
 - Chainsafe SDK version: [dev]
 - Unity Version: [e.g., 2022.1]
 - Operating System: [Mac]

**Additional context**
I guess is not the same https://github.com/ChainSafe/web3.unity/pull/952#pullrequestreview-2057943373 but I remember that we had this issue recently

**Comment by sneakzttv** [comment]
pretty sure this is storage side, ssl cert related possibly, will ping arun.

**Comment by juans-chainsafe** [comment]
Looks like the issue got fixed, working now
<img width="334" alt="Screenshot 2024-06-19 at 12 05 31 PM" src="https://github.com/ChainSafe/web3.unity/assets/104365141/39d97dbc-c12e-471a-8999-7b0cd503b9c8">
