### ISSUE TITLE
Handle non happy paths in Add Custom Token modal 

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#1026]
**Summary**
The happy path to add a new custom token works as expected, but what happens if the user tries to add a empty token? or a wrong address? or a wrong token name? is not pretty.

**Suggested features or ways to address the summary**
There is different ways to address this feature, one is to have the "Add token" button disabled until it meets the expected conditions

**Motivation**
To give the user a better user experience

**Acceptance Criteria**

- User cannot add a empty token address and/or empty token name
- User cannot add a invalid token address
- User cannot add a token address that doesnt match a token (maybe here we can check the token name, if we dont get one, then is invalid

**Additional Context**
(OPTIONAL) [Add any other context, files, images (screenshots/videos), diagrams, or documents about the feature request here.]
<img width="894" alt="Screenshot 2024-06-19 at 9 22 36 AM" src="https://github.com/ChainSafe/web3.unity/assets/104365141/b05502e1-add4-45d8-9c12-a563f6823baf">
<img width="336" alt="Screenshot 2024-06-19 at 9 23 44 AM" src="https://github.com/ChainSafe/web3.unity/assets/104365141/14190616-fd8a-4520-af12-261de86d9397">
```
Exception: contract address is not set
ChainSafe.Gaming.Evm.Contracts.Contract.Call (System.String method, System.Object[] parameters, ChainSafe.Gaming.Evm.Transactions.TransactionRequest overwrite) (at <c7f1782906ad426ca37ecb7560dc0263>:0)
ChainSafe.Gaming.Evm.Contracts.BuiltIn.Erc20Contract.GetBalanceOf (System.String accountAddress) (at <c7f1782906ad426ca37ecb7560dc0263>:0)
Web3AuthWalletGUITokenManager.SetTokens () (at /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity.web3auth/Runtime/WalletGUI/Scripts/Web3AuthWalletGUITokenManager.cs:77)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <e307bbb467104258887a104f6151f183>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:153)
UnityEngine.UnitySynchronizationContext.Exec () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:83)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:107)
```

**Estimations**

| Story Point | Amount of effort | Amount of time | Task Complexity | Task Risk or Uncerntainty |
|----------|----------|----------|----------|----------|
| 1 | Minimum efort | A few minutes | Little complexity | None |
| 2 | Minimum effort | A few hours | Little complexity | None |
| 3 | Mild efort | A day | Low complexity | Low |
| 5 | Moderate efort | A few days | Mediium complexity | Moderate |
| 8 | Severe efort | A week | Medium complexity | Moderate |
| 13 | Maximum effort | A few month | High complexity | High |

**Comment by sneakzttv** [comment]
on it.

**Comment by sneakzttv** [comment]
fixed in https://github.com/ChainSafe/web3.unity/pull/1019

token button wont display now until a proper contract address is entered that returns a symbol
