### ISSUE TITLE
private key transaction broadcast error

### ISSUE THREAD

**Issue by sneakzttv** [ChainSafe/web3.unity#103]
**Describe the bug**
When I'm trying to sign for a message hash using esdca verification i get to the last step of signing with a pk. It errors on broadcasting transaction telling me that I have "insufficient funds for intrinsic transaction cost". I'm trying to call a get hash function in solidity here using the code below. It's a simple verification system which I'm sure you guys are already aware of.

    function getMessageHash(address _to, uint _amount, string memory _message, uint _nonce) public view returns(bytes32){
        //require(msg.sender == AuthWallet, "you cant do this"); //commented out for testing
        return keccak256(abi.encodePacked(_to, _amount, _message, _nonce));
    }

    function getEthSignedMessageHash(bytes32 _messageHash) public pure returns (bytes32){
        return keccak256(abi.encodePacked(
        "\x19Ethereum Signed Message:\n32",
        _messageHash
        ));
    }

    function verify(address _signer, address _to, uint _amount, string memory _message, uint _nonce, bytes memory _signature) public view returns (bool){
        bytes32 _messageHash = getMessageHash(_to, _amount, _message, _nonce);
        bytes32 ethSignedMessageHash = getEthSignedMessageHash(_messageHash);
        return recoverSigner(ethSignedMessageHash, _signature) == _signer;
    }

    function recoverSigner(bytes32 _ethSignedMessageHash, bytes memory _signature) public pure returns(address){
        (bytes32 r, bytes32 s, uint8 v) = splitSignature(_signature);
        return ecrecover(_ethSignedMessageHash, v, r, s);
    }

    function splitSignature(bytes memory _sig) public pure returns (bytes32 r, bytes32 s, uint8 v){
        require(_sig.length == 65, "invalid signature length");
        assembly {
        r := mload(add(_sig, 32))
        s := mload(add(_sig, 64))
        v := byte(0, mload(add(_sig, 96)))
        }
    }
    
I'm then calling this in csharp from within unity on the bsc test network like so

                string _nonce = "1";
                string _amount = "100";
                string _message = "testing";
                string _authWallet = Web3PrivateKey.Address(AUTH_PK);
                // private key of account
                string privateKey = AUTH_PK;
                // set chain: ethereum, moonbeam, polygon etc
                string chain = "binance";
                // set network testnet, testnet
                string network = "testnet";
                // smart contract method to call
                string method = "getMessageHash";
                // account of player 
                string account = WalletID;
                // smart contract address
                string contract = NFT_CA;
                // amount of wei to send
                string value = "0";
                // abi to interact with contract
                string abi = NFT_ABI;
                // optional rpc url
                string rpc = RPC_URL;

                string[] obj = { account, _amount, _message, _nonce};
                string args = JsonConvert.SerializeObject(obj);
                string chainId = await EVM.ChainId(chain, network, rpc);
                string gasPrice = await EVM.GasPrice(chain, network, rpc);
                string data = await EVM.CreateContractData(abi, method, args);
                string gasLimit = "21000";

                string transaction = await EVM.CreateTransaction(chain, network, _authWallet, contract, value, data, gasPrice, gasLimit, rpc);
                string signature = Web3PrivateKey.SignTransaction(privateKey, transaction, chainId);
                string messageHash = await EVM.BroadcastTransaction(chain, network, account, contract, value, data, signature, gasPrice, gasLimit, rpc);

                Debug.Log("transaction: " + transaction);
                Debug.Log("auth wallet sig: " + signature);
                Debug.Log("messasge hash: " + messageHash);
                Debug.Log("signer: " + _authWallet);
                Debug.Log("to: " + account);
                Debug.Log("amount: " +_amount);
                Debug.Log("message: " +_message);
                Debug.Log("nonce: " +_nonce);

I know this should be done using a send contract function but there isn't one and i figured this was how it converted. Theoretically if I'm not mistaken this should sign & return a message hash to me, but it fails. I've tried altering gas limits, checking if there's tokens in the acc etc, in the ca. If there's anything i can alter or help with please let me know.

**Comment by sneakzttv** [comment]
If I'm misreading something or using something incorrectly please let me know so i can improve :D

**Comment by KBryan** [comment]
We will look into this today. As the team is back from the weekend.

**Comment by sneakzttv** [comment]
Thanks Kb!

**Comment by sneakzttv** [comment]
kwame mentioned he logged something similar to this earlier too, could be some info there too.

**Comment by KBryan** [comment]
Fixed has been released and API is updated. All good now. Please test so I can close this issue.

**Comment by sneakzttv** [comment]
ok will test!

**Comment by sneakzttv** [comment]
ecdsa verification is now 100% functional with this sdk ^^

**Comment by sneakzttv** [comment]
great job team!

**Comment by sneakzttv** [comment]
question

**Comment by sneakzttv** [comment]
as it was an api update i dont need to update from git do I just tested with 1.2.2. and that works. I saw a couple merges, just curious is all.

**Comment by sneakzttv** [comment]
if i try to circumvent ecdsa and just go for a direct method i get an out of gas error on bsc but ingame it fires off fine, This could possiblly be my end with solidity. https://testnet.bscscan.com/tx/0x1b864c36c78de620920464ad039d2e871d5a5080198c5adfffe5e430ee226ccf Thought id add it anyway.

**Comment by sneakzttv** [comment]
as such

string _authWallet = Web3PrivateKey.Address(CSFConfiguration.AUTH_PK);
                // private key of account
                string privateKey = CSFConfiguration.AUTH_PK;
                // set chain: ethereum, moonbeam, polygon etc
                string chain = "binance";
                // set network testnet, testnet
                string network = "testnet";
                // smart contract method to call
                string method = "addBoard";
                // account of player 
                string account = WalletID;
                // smart contract address
                string contract = CSFConfiguration.NFT_CA;
                // amount of wei to send
                string value = "0";
                // abi to interact with contract
                string abi = CSFConfiguration.NFT_ABI;
                // optional rpc url
                string rpc = CSFConfiguration.RPC_URL;

                string[] obj = { CSFConfiguration.NFT_CA, account, rarity.ToString(), NameID.ToString(), listedAmount.ToString(), ((0 + (rarity)) * 1).ToString()};
                string args = JsonConvert.SerializeObject(obj);
                string chainId = await EVM.ChainId(chain, network, rpc);
                string gasPrice = await EVM.GasPrice(chain, network, rpc);
                string data = await EVM.CreateContractData(abi, method, args);
                string gasLimit = "75000";

                string transaction = await EVM.CreateTransaction(chain, network, _authWallet, contract, value, data, gasPrice, gasLimit, rpc);
                string signature = Web3PrivateKey.SignTransaction(privateKey, transaction, chainId);
                string messageHash = await EVM.BroadcastTransaction(chain, network, _authWallet, contract, value, data, signature, gasPrice, gasLimit, rpc);

**Comment by sneakzttv** [comment]
will keep tinkering incase ive missed something

**Comment by sneakzttv** [comment]
function im trying to call is here, odd

function addBoard(address _to, address _from, uint _rarity, uint _nameID, uint _listedAmount, uint _authKey) public nonReentrant() {
        //require(msg.sender == AuthWallet, "you cant do this");
        require(_to == address(this), "you can only buy nfts from the csf website");
        require(_rarity <= 5, "rarity wrong");
        require(_nameID <= 3, "name wrong");
        require(_listedAmount == 0, "listed amount wrong");
        require (_authKey == ((0+(_rarity))*1), "you can only trade nfts on the csf marketplace");
        require(ownerboardCount[_from] <= 9, "you can only have 10 nfts at one time");
        boardToOwner[NFTID] = _from;
        listedBoardToOwner[NFTID] = _from;
        nameID[NFTID] = _nameID;
        speed[NFTID] = 0;
        weaponSlots[NFTID] = 0;
        damage[NFTID] = 0;
        health[NFTID] = 0;
        rarity[NFTID] = _rarity;
        listedAmount[NFTID] = _listedAmount;
        listedBool[NFTID] = false;
        ownerboardCount[_from] = ownerboardCount[_from].add(1);
        ownerNFTIds[_from].push(NFTID);
        NFTID ++;
        totalNFTCount ++;
        emit Transfer(_from, _to, NFTID);
    }

**Comment by sneakzttv** [comment]
oh maybe my gas is too low, ill try upping it

**Comment by KBryan** [comment]
Okay, hope that works out. Closing this as your initial error has been resolovd.
