### ISSUE TITLE
Hyperplay not prompting wallet

### ISSUE THREAD

**Issue by JAlbertCode** [ChainSafe/web3.unity#1039]
**Describe the bug**
The hyperplay sample scene does not prompt the wallet when running it in the editor or as a desktop build. I think this may be due to an update on the Hyperplay side, as the error in the editor reads "Release of invalid GC handle. The handle is from a previous domain. The release operation is skipped."

When the button is pressed, the wallet pop up opens in Hyperplay, but it doesn't prompt you to do anything. 

**Steps**
1. Install the hyperplay package
2. Use the sample scene SampleLogin - Hyperplay
3. Open Hyperplay app.
4. Connect Wallet to hyperplay app.
5. Run the scene in the editor or as a desktop build.
6. Click Login with HyperPlay.

**Expected behavior**
The pop up in hyperplay should prompt you to sign and upon signing, the game should load the next scene.

**Console errors**
"Release of invalid GC handle. The handle is from a previous domain. The release operation is skipped."

**Desktop (please complete the following information):**
 - Chainsafe SDK version: 2.6
 - Unity Version: 2022.3.19f1
 - Operating System: Windows 11 Pro

**Comment by juans-chainsafe** [comment]
@JAlbertCode I just did a hyperplay login in the editor and is working for me, but Im on Mac.
So, I guess this issue is happening on Windows, and we need to see if is just in windows 11 or 10 as well.

**Comment by rob1997** [comment]
@JAlbertCode working on my end
![image](https://github.com/ChainSafe/web3.unity/assets/36323674/dcd122ec-f16e-4f70-8eea-1708ecfdf2b7)
@juans-chainsafe please confirm when you can

**Comment by rob1997** [comment]
> @JAlbertCode working on my end ![image](https://private-user-images.githubusercontent.com/36323674/343309889-dcd122ec-f16e-4f70-8eea-1708ecfdf2b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MzEzMzcsIm5iZiI6MTcxOTQzMTAzNywicGF0aCI6Ii8zNjMyMzY3NC8zNDMzMDk4ODktZGNkMTIyZWMtZjE2ZS00ZjcwLThlZWEtMTcwOGVjZmRmMmI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDE5NDM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiYzkwN2VmYzg5YTRiMmY4ZWMzOGExYmNlMjFiOGY5OTJhZTA3MmVkYjMwOGQ3OGEyNGYxZDQ0MThjZjRkNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b6t3H0x1tmFWEsOH9x_BNldQMFhd_DooPsazkKREvDo) @juans-chainsafe please confirm when you can

I'm on windows

**Comment by JAlbertCode** [comment]
I just created a new project and reinstalled our SDK and the Hyperplay package, and it's working. It doesn't force you to switch windows, but the pop-up does appear in Hyperplay. My guess is that it was an old version of the SDK that didn't work.
