### ISSUE TITLE
Add network doesn't show with HyperPlay

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#1044]
**Summary**
Add network is not working with WebGL + HyperPlay with HyperPlay app by adding the webgl build as a game.
In this case, I don't get the option to add the network, and the current network is selected.

**Suggested features or ways to address the summary**

- Once is solved by the HyperPlay team, implement the fix in our SDK, if is necessary.

**Motivation**
Keep consistency between WebGL behaviour and HyperPlay

**Acceptance Criteria**
[List specific criteria for this issue to be considered complete. These should be concrete and measurable.]

**Blockers**
We need to wait for the HyperPlay to fix this issue and then see if we need to implement something else

**Dependencies**
HyperPlay client

**Comment by kantagara** [comment]
@juans-chainsafe this fixed?

**Comment by juans-chainsafe** [comment]
> @juans-chainsafe this fixed?

Yes, I dont know why it was not closed automatically
