### ISSUE TITLE
ImportNftTexture not working in WebGL

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#1053]
**Describe the bug**
This sample is not working again only in WebGL, not sure if is related to the same error that we had last time, but I see 2 errors: a CORS error and a Metadata request failure

**Steps**
1. Use the scene [SampleLogin - Metamask or SampleLogin - Web3Auth]
2. Login with [Web3Auth or Metamask]
3. Click on **ImportNftTexture** sample in ERC-1155 section

**Expected behavior**

- Image is imported and displayed on the screen

**Console errors**
`Access to fetch at 'https://ipfs.chainsafe.io/ipfs/QmfUHuFj3YL2JMZkyXNtGRV8e9aLJgQ6gcSrqbfjWFvbqQ' from origin 'http://localhost:49764' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`
`GET https://ipfs.chainsafe.io/ipfs/QmfUHuFj3YL2JMZkyXNtGRV8e9aLJgQ6gcSrqbfjWFvbqQ net::ERR_FAILED`
```
webgl.framework.js:30 Web3Exception: Metadata request failure: Unknown Error
  at Scripts.EVM.Token.Erc1155UnityExtensions.ImportTexture (ChainSafe.Gaming.Evm.Contracts.BuiltIn.Erc1155Contract contract, System.String tokenId) [0x00000] in <00000000000000000000000000000000>:0 
```

**Screenshots/Video**
<img width="1290" alt="Screenshot 2024-07-05 at 10 42 45 AM" src="https://github.com/ChainSafe/web3.unity/assets/104365141/affa87f2-e434-4715-b84d-a60f74c7239a">

**Desktop (please complete the following information):**
 - Chainsafe SDK version: [main branch]
 - Unity Version: [2022.1]
 - Platform: [WebGL]
 - Operating System: [Mac]

**Additional context**
Happens with Metamask login or Web3Auth

**Comment by sneakzttv** [comment]
could be maintenance

**Comment by juans-chainsafe** [comment]
> could be maintenance, check it again later

Still getting the error

**Comment by kantagara** [comment]
Fixed 
![image](https://github.com/user-attachments/assets/7aeb537a-a90e-44af-bc96-4af95fcdb5df)
if you're not using python -m http.server maybe that's causing the issue.
