### ISSUE TITLE
Intermittent login error with Web3Auth in WebGL build

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#1054]
**Describe the bug**
When I was testing https://github.com/ChainSafe/web3.unity/pull/1037 I got this error only the first time and then I wasn't able to reproduce it again. But now it happen 3 times in a row to me.

Basically, when the Web3Auth modal appears to login and says "Redirecting back to..." you can see in the console a error that says "login popup has been closed by the user" which is not true, I didnt close it.
After is closed, you get the Login screen and nothing happens.

**Steps**
1. Build with WebGL
2. Use the scene [SampleLogin - Web3Auth]
3. Login with [Web3Auth]
4. If you don't get the error, logout and retry

**Expected behavior**
Login is always successful

**Console errors**
```
openlogin-adapter:2 Failed to connect with openlogin provider LoginError: login popup has been closed by the user,
    at Tr.fromCode (openlogin-adapter:2:408268)
    at Tr.popupClosed (openlogin-adapter:2:408634)
    at jr.<anonymous> (openlogin-adapter:2:421303)
    at o.emit (openlogin-adapter:2:280720)
    at openlogin-adapter:2:411188
```

**Desktop (please complete the following information):**
 - Chainsafe SDK version: [main]
 - Unity Version: [2022.1]
 - Platform: [WebGL]
 - Operating System: [Mac]

**Comment by kantagara** [comment]
Waiting for the web3auth team to tackle this with me since this seems to be an issue on their end.

**Comment by kantagara** [comment]
@juans-chainsafe the actual issue is 🥁 🥁 🥁  Unitys Cross Origin policy bug that also prevents Ramp.Network from working directly with the Build & Run method 🫠🫠  With 2022.3.4 version it works perfectly.

**Comment by kantagara** [comment]
This error is tied to Unitys CORS issue they introduced in 2022.3.20 onwards. It's fixed in previous versions (so anything older than 2022.3.20 ) Or newest version 6 (6000.10f), so closing it as it's directly related to Unity.
