### ISSUE TITLE
Transactions not being displayed or not working with Web3Auth + WebGL

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#1058]
**Describe the bug**
We have 2 different situations depending if we are using dev code or 2.6.0 release version.
DEV: Nothing is displayed in the browser console.
2.6.0: error appears (check console errors section)

**Steps**
1. Use the scene [SampleLogin - Web3Auth]
2. Login with [Web3Auth]
3. Click a sample that requires to spend funds like GetNonce or any Mint/Transfer

**Expected behavior**
- Tx hash is displayed in the console and a successful message
- Tx is displayed in etherscan, in my case: https://sepolia.etherscan.io/address/0x3043048E083B16dB76f8875e20f774455CDD66C6

**Console errors**
In 2.6.0:
```
webgl22.loader.js:1 Invoking error handler due to
RuntimeError: null function or function signature mismatch
```

**Screenshots/Video**
Error in 2.6.0 version:
<img width="445" alt="Screenshot 2024-07-10 at 6 23 29 PM" src="https://github.com/ChainSafe/web3.unity/assets/104365141/8006e0bf-3cd7-4c8c-bb2c-3866229752c7">

**Desktop (please complete the following information):**
 - Chainsafe SDK version: [dev and 2.6.0]
 - Unity Version: [2022.1]
 -  Platform: [WebGL]
 - Operating System: [Mac]

**Additional context**
This is working in the editor, the issue is with WebGL.

**Comment by juans-chainsafe** [comment]
@rob1997 here is the issue
@kantagara very weird issue that happened to me today, will be nice if someone else can try it.

**Comment by kantagara** [comment]
![image](https://github.com/user-attachments/assets/f197e04c-f0be-4f85-84ff-227d55c41eb3)
Fixed
