### ISSUE TITLE
Sometimes when I use WalletLogin on my Android phone I log in with another wallet.

### ISSUE THREAD

**Issue by mcdeimon** [ChainSafe/web3.unity#106]
Hello! I am having a problem when trying to login with WalletLogin and Metamask. Sometimes when I access Metamask I find the tab blank, without the message to sign the message (Image 1).

![1](https://user-images.githubusercontent.com/39587826/156070804-d6dc4c18-345f-4fe7-863d-d9a3ed0e1ecd.jpg)

So I click on the metamask tabs and I see this (Image 2).

![2](https://user-images.githubusercontent.com/39587826/156070917-241fdd10-8d04-4cc0-ae15-5a53aae3e25a.jpg)

One of the tabs is empty, the one I had already seen, and the other, the first, shows the normal message (Image 3).

![3](https://user-images.githubusercontent.com/39587826/156071083-763bb61d-3f6a-4060-b3a6-02c1d19272c7.jpg)

When I press the button to sign it connects with another wallet. None of those wallets are mine and I don't know where they come from.

This error does not always occur. But very frequently.

Thanks for your work its fantastic!

I am working on Binance Smart Chain - ChainID 56

**Comment by KBryan** [comment]
Thank you for posting this issue. Our team will look into this and get back to you.

**Comment by KBryan** [comment]
I have looked into this issue and I'm not currently able to reproduce this error.

**Comment by mcdeimon** [comment]
Can I help in any way?

**Comment by KBryan** [comment]
Is it possible for you to do a video of the issue?

**Comment by mcdeimon** [comment]
I attach a video. Before recording that video I have installed the application and I have connected correctly. After that I have closed the application and Metamask, and tried to connect again without checking the "Remember" box. This is where the error appears. When I sign in metamask a blank window opens without the "Copy" button.

https://user-images.githubusercontent.com/39587826/156669859-3023266a-ddba-4088-a699-d18324ddbd08.mp4

**Comment by mcdeimon** [comment]
I have found a partial solution to the problem. When the blank page appears without the copy button, if I reload that tab from metamask the copy button appears and everything works fine. It seems that the problem is that sometimes after signing the message the copy button does not appear and if you open other tabs the addresses that are copied are different.

**Comment by KBryan** [comment]
Okay, that helps a lot. Will make a note of this and review it with the team.

**Comment by mcdeimon** [comment]
Hello! Any update on this?

**Comment by KBryan** [comment]
This doesn't seem to be specific to the SDK itself. We have tried to reproduce this error and cannot. Can you verify that this account doesn't exist in your wallet?
