### ISSUE TITLE
Wallet Connect WebGL Support (Especially Mobile)

### ISSUE THREAD

**Issue by felixnomina** [ChainSafe/web3.unity#1060]
**Summary**
An easy way for devs to connect their MetaMask wallet (or others) from mobile browser which doesn't have extension (ie. chrome)

**Suggested features or ways to address the summary**
I have tried using the web3modal package from wallet connect here
https://docs.walletconnect.com/appkit/unity/core/installation

I follow the installation document and just add a script (in pic) and a button with text in a scene (Unity 2022.3.10f1)
![main](https://github.com/user-attachments/assets/653b5247-ad6b-4747-beeb-f1ccd7139181)

I build it in a new unity webgl project and test it using vscode live server from both my desktop and mobile device. It successfully connect the MetaMask wallet in both desktop and mobile browser, so I assume this implementation of Wallet Connect works in WebGL. It would be nice if this could be integrated into current ChainSafe SDK, so that Wallet Connect work on WebGL too, especially on mobile browser.

**Motivation**
While people can play WebGL game on desktop to connect with their wallet extension, I think it is crucial to support mobile devices too because it is more accessible to a lot of people. A lot of people spend times way more on mobile devices now, so this feature will be really helpful

**Acceptance Criteria**
Successfully connect a wallet from wallet app like MetaMask when opening WebGL build from mobile browser

**Additional Context**
Some screenshots of connecting wallet from mobile browser
![image](https://github.com/user-attachments/assets/93d6900a-149b-4296-a47c-1fcf219cd712)
![image](https://github.com/user-attachments/assets/6a80834b-77dc-4543-b00a-45544a482739)
![image](https://github.com/user-attachments/assets/d00ef4f6-df95-49d3-b33b-d12ff442b88b)
![image](https://github.com/user-attachments/assets/85709ae9-2af1-4549-ba07-3c7bdfc75b29)
![image](https://github.com/user-attachments/assets/16fdddb4-d1dd-437f-b418-db2c6a7b86c1)

**Final Steps**
* Give it one of these labels `Type: Feature` `Type: Enhancement`
* Add your estimation

**Estimations**
| 5 | Moderate efort | A few days | Mediium complexity | Moderate |

**Comment by sneakzttv** [comment]
Thank you, we will look into this :)

**Comment by kantagara** [comment]
@felixnomina we're adding back the experimental support to wallet connect back to webGL in 3.0
