### ISSUE TITLE
Minor issues with Marketplace prefab

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#1066]
List of things to fix

- Description shouldn't be mandatory for creating a Marketplace
- Description shouldn't be mandatory for creating a Collection
- I can't enter Marketplaces or Collections that are empty because of `Index out of bonds error` this is because is trying to get elements of marketplace/collections but fails because is empty
- In the future, will be nice to be able to add additional properties and additional files when minting a new NFT (like in the dashboard)

**Comment by sneakzttv** [comment]
Forgot to close this one, new issues superseed.
