### ISSUE TITLE
required to use two web GL template 

### ISSUE THREAD

**Issue by irfanshah22** [ChainSafe/web3.unity#107]
hello how are you?
i am using chainsafe SDK for metamask connectivity with unity ,
my project have photon voice feature/ chat feature and many other features.
now my question is that, that my photon project is working with default web GL template.
and metamask SDK is working with Web3GL template.
so when i build my game with default the other features working but metamask didn't
but when i build my game and than create a link and open in web browser, it give me error message
 something like :

var loaderUrl = buildUrl + "/metaBuild.loader.js"; var config = { dataUrl: buildUrl + "/metaBuild.data", frameworkUrl: buildUrl + "/metaBuild.framework.js", codeUrl: buildUrl + "/metaBuild.wasm", streamingAssetsUrl: "StreamingAssets", 

and more lengthy message .
please help me in this issue .
thank you very much

**Comment by KBryan** [comment]
I just want to clarify that the connection to MetaMask is working when using the Web3GL Template provided by ChainSafe and the Photon plugin doesn't work anymore. You should not have an issue with Photon when using the Web3GL provided.

**Comment by KBryan** [comment]
Has your problem been resolved? We have tested and can ensure that Photon works with our plugin and web template.

**Comment by irfanshah22** [comment]
Thank you it is working . Sent from Mail for Windows From: kwameSent: Thursday, March 17, 2022 6:58 PMTo: ChainSafe/web3.unityCc: irfanshah22; AuthorSubject: Re: [ChainSafe/web3.unity] required to use two web GL template (Issue #107) Has your problem been resolved? We have tested and can ensure that Photon works with our plugin and web template.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>
