### ISSUE TITLE
Brave browser Bug

### ISSUE THREAD

**Issue by sneakzttv** [ChainSafe/web3.unity#108]
**Describe the bug**
Unsure if this has been posted but making transactions on brave browser goes a bit haywire. All of my transactions are trying to process as the full wei amount before conversion so 5000 looks like 5000000000000 etc. The same code works fine on chrome.

**To Reproduce**
Run a token transfer on chrome on a token with 9 decimals for 5000 - executes correctly asks for 5000 tokens
Run a token transfer on brave on a token with 9 decimals for 5000 - asks for 5000000000000 tokens

**Desktop (please complete the following information):**
Desktop, chrome, brave browser. Windows 10.

**Comment by KBryan** [comment]
Just for clarification, you are also using MetaMask as your browsers web3 wallet extension?

**Comment by sneakzttv** [comment]
yah metamask

**Comment by KBryan** [comment]
I haven't seen that before. Going to triage this might not have an answer until the morning. Will try and reproduce this tonight.

**Comment by KBryan** [comment]
Are you still seeing this issue?

**Comment by sneakzttv** [comment]
this is fixed now, confirmed in my game aswell as csf demo.
