### ISSUE TITLE
walletconnect error

### ISSUE THREAD

**Issue by ThetaDogZilla** [ChainSafe/web3.unity#1082]
**Description of the failure**
Unable to connect to the theta wallet app using walletconnect (android, ios)

**Steps**

ChainSafe SDK version: 2.6
Unity version 2022.3.26f
Use the SampleLogin - WalletConnect scene.
Configure the Theta network (365)
Click play button in the unity editor, in the SampleLogin - WalletConnect scene.
Click on connect with connectwallet
Scan the QR code with the app ThetaWallet 
Enter your wallet pin in the theta wallet app
Click on accept connection in the theta wallet app

The following error will appear:
Connection failed:
Non conforming namespaces. approve() namespaces methods dont satisfy namespace methods for eip155:365

![Screenshot theta wallet](https://github.com/user-attachments/assets/966de131-ab8c-4caa-9913-4d38f9de082f)

**Comment by bradstevens1** [comment]
Are you still getting the connection failed?

**Comment by kantagara** [comment]
@creeppak I think this is the ideal scenario for us to add that custom namespace that we talked about yesterday.

**Comment by kantagara** [comment]
Ah it's not related to anything like that. @ThetaDogZilla I've pinged Theta Wallet Community to hopefully resolve the issue together.

**Comment by ThetaDogZilla** [comment]
> Ah it's not related to anything like that. @ThetaDogZilla I've pinged Theta Wallet Community to hopefully resolve the issue together.

Thank you very much, I also wrote to theta wallet mobile support, but I have not received a reply.

**Comment by kantagara** [comment]
Their founder forwarded the message to their dev team, so I hope we can resolve this asap.

**Comment by creeppak** [comment]
Due to unresponsiveness of the developers, unfortunately this wallet will remain unsupported.
