### ISSUE TITLE
ERROR: URI TOO LONG when passing data through 

### ISSUE THREAD

**Issue by bryercowan** [ChainSafe/web3.unity#110]
While using ChainSafe/web3.unity's v1.2.2 package on the web, haven't tested it on mobile since deeplinks just got patched through metamask mobile recently I get this bug:

When passing a considerable amount of data through Web3Wallet.SendTransaction() you get ERROR: URI TOO LONG

**To Reproduce**
Create a transaction that uses data parameter and pass through a relatively long string. I.E. bytecode of a contract.
send that data with Web3Wallet.SendTransaction()
Presented with ERROR: URI TOO LONG in browser

**Expected behavior**
I expected the api to pass the transaction to metamask to be signed and sent to the blockchain to be mined.
**Screenshots**
![URI Too Long](https://user-images.githubusercontent.com/27735687/157936669-c620a873-3ce5-49bc-b53a-45d83a5f0c6c.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 21H2

**Smartphone (please complete the following information):**
N/A

**Additional context**
This is more than likely going to be fixed by just updating server URI to accept a large amount of characters, 20k+ depending on the data needed to pass to the blockchain.

**Comment by KBryan** [comment]
Thank you for posting this. We will look into this further. My apologies for this getting lost in the discord chat.

**Comment by bryercowan** [comment]
No problem at all, I know how busy development can be especially when you are leading the charge!

**Comment by KBryan** [comment]
Here are a couple of questions that I wanted to address. First,  2048 characters are the max length in the URL field. The `to` entry in your example is empty and what is the contract and function you are calling.

**Comment by bryercowan** [comment]
If the url will max out with 2048, what I am trying to do won't work, I will be passing through 20k+ characters to deploy a contract. The `to` entry can be optional if deploying a contract using eth_sendTransaction. You can read up on this method here: https://eth.wiki/json-rpc/API#eth_sendtransaction
