### ISSUE TITLE
CORS error in Marketplace login with WebGL

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#1100]
**Describe the bug**
The issue only appears with WebGL build, is after you click send email button in the marketplace login prefab, because is failing on the API endpoint.

**Steps**
1. Create a sample scene with MarketplaceLogin.prefab inside 
2. Use SampleLogin - Connect wallet scene
3. Build with **WebGL**
4. Login with web3auth or metamask
5. Set **email** input and click **Send email** button

**Expected behavior**

- Verification code screen appears and the email with the code is received

**Console errors**
```
localhost/:1 Access to fetch at 'https://api.chainsafe.io/api/v1/user/email' from origin 'http://localhost:51115' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.Understand this error
webgl22.loader.js:1 
        
POST https://api.chainsafe.io/api/v1/user/email net::ERR_FAILED
```

**Screenshots/Video**
<img width="1146" alt="Screenshot 2024-08-13 at 1 39 36 PM" src="https://github.com/user-attachments/assets/c1d9febd-5da7-4eb2-9287-f852a8b5ff8a">

**Desktop (please complete the following information):**
 - Chainsafe SDK version: [dev]
 - Unity Version: [e.g., 2022.3.26]
 - Operating System: [Mac]

**Additional context**
Please add any other relevant context or information about the problem. This could include device specifications, project configuration, or any other details that might be helpful in diagnosing the issue.

**Comment by sneakzttv** [comment]
checking this

**Comment by sneakzttv** [comment]
have spoken to Arun to see if we can get CORS opened up on these endpoints, awaiting response.

**Comment by sneakzttv** [comment]
Cors are open now, please check again @juans-chainsafe

**Comment by juans-chainsafe** [comment]
Error is fixed now!
