### ISSUE TITLE
NFT image not being upload when minting NFT in Marketplace prefab

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#1101]
**Describe the bug**
When minting a new NFT inside a collection in the Marketplace prefab, the NFT is minted but the image is not being uploaded.

**Steps**
1. Use the scene [SampleLogin - Connect modal]
2. Login with [Web3Auth or WC]
3. Login with Marketplace email (you need to add the MarketplaceLogin.prefab into a new scene before)
4. Click on Collections button
5. Click on any of the collections inside your project
6. Click on Mint NFT button
7. Set the name
8. Click on UPLOAD IMAGE button

**Expected behavior**
A prompt to upload the image appears

**Console errors**
No console errors, the image is never uploaded

**Desktop (please complete the following information):**
 - Chainsafe SDK version: [dev]
 - Unity Version: [e.g., 2022.3.26]
 - Operating System: [Mac]

**Comment by sneakzttv** [comment]
Above should be fixed, moving to web request errors here https://github.com/ChainSafe/web3.unity/issues/1107
