### ISSUE TITLE
Disable Remember me not working as expected

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#1103]
**Describe the bug**
If you do the login with remember me enabled, and then you disable the remember me but try to login again, it will remember the previous session.

**Steps**
1. Use the scene [SampleLogin - Connect Modal]
2. Login with remember me enabled
3. Stop the execution
4. Disable the remember me option
5. Try to login again

**Expected behavior**
User needs to restore the session again.

**Screenshots/Video**
https://github.com/user-attachments/assets/97361ead-3469-436d-b041-16ab01f02197

**Desktop (please complete the following information):**
 - Chainsafe SDK version: [dev]
 - Unity Version: [2022.3.26]
 - Operating System: [Mac]

**Additional context**
Unless this is expected behaviour and the user needs to logout first.

**Comment by sneakzttv** [comment]
similarly if logging in, when pressing the login button and choosing web3auth the authentication window will pop up and then it will remember the session and continue to the next scene as if email authentication was successful with the auth screen having no interactions.

to reproduce, login a few times with web3auth and you will see it.
