### ISSUE TITLE
Metamask not connect wtih android and ios device when am click connect button

### ISSUE THREAD

**Issue by AsadullahW** [ChainSafe/web3.unity#1104]
**Describe the bug**

**Steps**
1. Use the scene [SampleLogin or SampleLogin - Web3Auth]
2. Login with [Web3Auth or Remote wallet]
3. Add/Modify '...' in '...' C# script
4. Interact with [button name] in SampleMain scene

**Expected behavior**

**Console errors**
Please include any console errors, warnings, or log messages related to this bug. If possible, provide a full error message and stack trace.

**Screenshots/Video**
If applicable, add screenshots or screen recordings that help visualize the issue.

**Reproducible Code Snippet (if applicable):**
If the issue is related to a specific piece of code, provide the relevant code snippet here.

```csharp```
// Your code snippet here

**Desktop (please complete the following information):**
 - Chainsafe SDK version: [e.g., 2.5.0]
 - Unity Version: [e.g., 2022.1]
 - Operating System: [e.g., Windows 10]

**Mobile (please complete the following information):**
 - Chainsafe SDK version: [e.g., 1.0.6]
 - Platform: [e.g., Android/iOS]
 - Device Type: [e.g., Real device or Emulator/Simulator]
 - OS Version: [e.g., Android 11]

**Additional context**
Please add any other relevant context or information about the problem. This could include device specifications, project configuration, or any other details that might be helpful in diagnosing the issue.

**Comment by kantagara** [comment]
Hello @AsadullahW , please make a detailed repro step and description of a bug otherwise the issue will have severly lower priority.
Thank you.

**Comment by AsadullahW** [comment]
when am click metaMask connect button go to google and i think try to find
extension of meta mask which not find out in android and ios device  than
game stuck not directly connected to meta mask app that is my issue while
mac desktop platform work fine.

**Comment by kantagara** [comment]
I am sorry but what scene are you on? It's not super clear what the issue is to me still.
