### ISSUE TITLE
Marketplace prefab requests

### ISSUE THREAD

**Issue by sneakzttv** [ChainSafe/web3.unity#1107]
System loads but is terribly slow and has a hanus amount of requests which is causing odd errors when minting.
Fields aren't populating properly. A fast connection seems fine, a slower connection seems to have issues.
I need to refactor the web requests so they're either batched or chat with the backend team to see if there is a more efficient call.

**Comment by sneakzttv** [comment]
Fixed by Nikola with #1135, PR merge will close this issue.

**Comment by sneakzttv** [comment]
Closed in order to make the proper implementation that we already had in place. Moving this back to in progress for now.

**Comment by kantagara** [comment]
Marketplace samples are looking a bit different now
