### ISSUE TITLE
Paste from clipboard not working in Marketplace verification code in WebGL

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#1108]
**Describe the bug**
You can't put the verification code from your clipboard in Marketplace verification code view in a WebGL build

**Steps**
1. Use the scene [SampleLogin - Connect modal]
2. Login with [Metamask]
3. Copy verification code from the email received
4. Use ctrl + V or cmd + V

**Expected behavior**
Verification code appears on the verification code input

**Screenshots/Video**
If applicable, add screenshots or screen recordings that help visualize the issue.
<img width="1043" alt="Screenshot 2024-08-23 at 11 13 00 AM" src="https://github.com/user-attachments/assets/fa15cdf5-297f-4fb1-8b15-82d1e024efc1">

**Desktop (please complete the following information):**
 - Chainsafe SDK version: [dev]
 - Platform: [WebGL]
 - Unity Version: [e.g., 2022.3.26]
 - Operating System: [Mac]

**Comment by sneakzttv** [comment]
I forgot to apply the helper class to the input field, good catch Juan. Will fix when I return.
