### ISSUE TITLE
Web3Auth not working in iOS

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#1119]
**Describe the bug**
Because we changed the clientId of web3auth, looks like it was not updated properly in all platforms

**Steps**
1. Build in iOS
2. Try to login with Web3Auth

**Expected behavior**
User is able to login with gmail

**Console errors**
`could not validate redirect, please whitelist your domain: torusapp://io.chainsafe.gamingsdk.sdkdemoscene for provided clientId BDoIQpmwh4ow7oDMshLsPTj0JHGnS-0ZsB14fMzZ6CnxB0kMJf4o3oWvFWiISuL_p7PzyGx4v7iGHDQQF4lNL-s at https://dashboard.web3auth.io/. Also, this project is on testnet network. Please ensure the the used Client ID belongs to this network.`

**Mobile (please complete the following information):**
 - Chainsafe SDK version: [dev]
 - Platform: [iOS]
 - Device Type: [Real device]
 - OS Version: [17]

**Comment by kantagara** [comment]
@juans-chainsafe test this out please, I've whitelisted the domain.

**Comment by juans-chainsafe** [comment]
> @juans-chainsafe test this out please, I've whitelisted the domain.

I'm still having the same issue, do I need to do a new build in a specific branch? I'm in dev branch.

**Comment by kantagara** [comment]
@juans-chainsafe please pull again from the dev. Proper client id should be inside of it and is now working (tested it myself on iOS)

**Comment by juans-chainsafe** [comment]
> @juans-chainsafe please pull again from the dev. Proper client id should be inside of it and is now working (tested it myself on iOS)

Working now!
