### ISSUE TITLE
RPC from custom network returns empty json string.

### ISSUE THREAD

**Issue by grandwiz** [ChainSafe/web3.unity#112]
**Describe the bug**
I am trying to use LRC's L2 network to check for tokens. I have completed authentication, but when I try to run a balanceOf function, I cannot get it working,

**To Reproduce**
1. run this snippet of code in unity c# (or the equivilent)

            string chain = "loopring";
            string network = "mainnet";
            string contract = "0x33af5f2a46d8132ca7d948ee51ba156b1aca1bcd";
            string account = PlayerPrefs.GetString("Account");
            string tokenId = "35414740236405772405913560861357254370622004460479475350057932473547997942368";
            string rpc = "https://api3.loopring.io";

       
            BigInteger balance = await ERC1155.BalanceOf(chain, network, contract, account, tokenId, rpc);``

**Expected behavior**
Should show balanceOf 1 (for me)

**Additional context**
Just trying to return balanceOf from another chain.

**Comment by KBryan** [comment]
Thank you for your post. Being an EVM compatible chain this should work with the SDK. We will look into this when the team is back in the office tomorrow.
