### ISSUE TITLE
Server Settings Popup not working properly

### ISSUE THREAD

**Issue by JAlbertCode** [ChainSafe/web3.unity#1126]
**Describe the bug**
I am installing the package from the dev environment and the popup for server settings displays improperly and the auto save doesn't work. 

**Steps**
1. Install the package https://github.com/ChainSafe/web3.unity.git?path=/Packages/io.chainsafe.web3-unity#dev
2. Copy your project ID from the gaming dashboard https://dashboard.gaming.chainsafe.io/
3. Paste into server settings

**Expected behavior**
It should auto save. You can see that Unity attempts to save it but runs into an issue with the GUI

**Console errors**
```
GUI Error: Invalid GUILayout state in ChainSafeServerSettings view. Verify that all layout Begin/End calls match
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
```

**Screenshots/Video**
![server settings](https://github.com/user-attachments/assets/587206ea-b93b-4731-8fc6-1539e58750b8)

**Desktop (please complete the following information):**
 - Chainsafe SDK version: 2.6
 - Unity Version: 2022.3.19f1
 - Operating System: Windows 11 Pro

**Additional context**
If you change the chain and switch it back, then it works as expected.

**Comment by juans-chainsafe** [comment]
Wow! I wasn't able to reproduce it, I'm on Mac though, maybe is a screen resolution? but for me the modal always opens correctly

**Comment by kantagara** [comment]
Thanks Jay, was able to reproduce it. Fixing it right away.
