### ISSUE TITLE
Marketplace sample scene keeps purchased items listed

### ISSUE THREAD

**Issue by JAlbertCode** [ChainSafe/web3.unity#1131]
**Describe the bug**
When a user purchases an NFT from the marketplace it remains listed. It should not be available in the marketplace once the purchase is made.

**Steps**
1. Create a collection on the gaming dashboard.
2. Create a marketplace on the gaming dashboard.
3. List NFTs on the marketplace.
4. Run the MarketplaceSampleScene in Unity for WebGL. 
5. Click on marketplaces > your marketplace > purchase.
6. Notice that the item is still listed in the scene and on your dahsboard.

**Expected behavior**
The NFT should no longer be available for purchase.

**Desktop (please complete the following information):**
 - Chainsafe SDK version: 2.6.0, Marketplace V2.6.1 
 - Unity Version: 2022.3.19f1
 - Operating System: Windows 11 Pro

**Additional context**
I am testing the development branch

**Comment by kantagara** [comment]
@JAlbertCode I can close this one?
