### ISSUE TITLE
Upload image button does not work in marketplace sample scene

### ISSUE THREAD

**Issue by JAlbertCode** [ChainSafe/web3.unity#1132]
**Describe the bug**
When you try to upload an image to deploy a new marketplace, it does not do anything and therefore you can't proceed with minting the marketplace.

**Steps**
1. Run the MarketplaceSampleScene as a WebGL build
2. Click on marketplace > create.
3. Fill out the name, description, and click upload image.
4. You'll see that it does not upload the image.

**Expected behavior**
The user should be able to upload an image and then mint a marketplace contract.

**Console errors**
SendMessage: object ImageUploader not found!

**Desktop (please complete the following information):**
 - Chainsafe SDK version: 2.6.0, Marketplace V2.6.1
 - Unity Version: 2022.3.19f1
 - Operating System: Windows 11 Pro

**Additional context**
I am using the dev branch to test the marketplace sample scene.

**Comment by kantagara** [comment]
Marketplace samples should just be used for dispaying and purchasing items from the marketplace itself.
