### ISSUE TITLE
Marketplace sample scene not retrieving images

### ISSUE THREAD

**Issue by JAlbertCode** [ChainSafe/web3.unity#1133]
**Describe the bug**
The marketplace sample scene should be displaying the NFTs listed but the images do not load. The same applies for the marketplace image.

**Steps**
1. Create an NFT collection on the gaming dashboard
2. Create a marketplace on the gaming dashboard.
3. Use the scene MarketplaceSampleScene
4. Run the scene as a WebGL build. 
5. Click on collections
6. You'll see that the ChainSafe logo appears instead of the NFT images because the images fail to load.

**Expected behavior**
The NFT images should load in the scene.

**Console errors**
builds.framework.js.gz:10 Error getting image ChainSafe.Gaming.Web3.Web3Exception: Texture request failure: Data Processing Error, see Download Handler error
  at ChainSafe.Gaming.Collection.BrowseCollectionManager.ImportTexture (System.String uri) [0x00000] in <00000000000000000000000000000000>:0 

**Desktop (please complete the following information):**
 - Chainsafe SDK version: 2.6.0, Marketplace V2.6.1
 - Unity Version: 2022.3.19f1
 - Operating System: Windows 11 Pro

**Additional context**
I am running the marketplace sample scene from the dev branch.

**Comment by juans-chainsafe** [comment]
@JAlbertCode to clarify, do you see in the console 500 error in the API? Because this happened to me, but in my case had sense, because it was for marketplaces that didnt have a image (due that is not mandatory)

**Comment by kantagara** [comment]
Marketplace sample is completely revamped so the bug of this type shouldn't exist anymoore.
Also we did figure out that the root cause of this issue is uploading a non-jpg or non-png type of image to the markeplaces dashboard.

**Comment by JAlbertCode** [comment]
@kantagara isn't that a Unity issue? From what I remember, Unity just doesn't support the other image types.
