### ISSUE TITLE
Amount of ERC20 token not displayed correctly in Wallet GUI

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#1141]
In Web3Auth, inside the Wallet GUI modal, after you add a ERC20 token, the balance is always 0.

I added this erc20 token that I have 9837 amount, but it shows 0

### Web3Auth wallet GUI
<img width="246" alt="Screenshot 2024-09-11 at 12 33 25 PM" src="https://github.com/user-attachments/assets/c5c1cee9-689c-4c37-84e6-23b93e1a3dd4">

### Metamask
<img width="349" alt="Screenshot 2024-09-12 at 11 14 23 AM" src="https://github.com/user-attachments/assets/2f713034-d2a0-487c-956a-fe40bbd7390f">

**Comment by sneakzttv** [comment]
on it

**Comment by sneakzttv** [comment]
the default rpc https://rpc.sepolia.org/ is broken
change it to https://rpc2.sepolia.org and it works

![Image](https://github.com/user-attachments/assets/8bc9cb60-7039-4f1b-94aa-b1764a11ae6f)

**Comment by sneakzttv** [comment]
in the meantime ill figure out how to omit the ones with a broken score from selection for a better UX

**Comment by sneakzttv** [comment]
closing RE internal convo with @kantagara
