### ISSUE TITLE
Metamask connection in iOS build not working

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#1142]
I get redirected to Metamask, and a popup appears and disappears but I'm not able to connect the wallet. 

I see this deep link generated but maybe is missing something: [Web3] Generated deep link: https://metamask.app.link/wc?uri=wc%3a5c8753645c6f2950dae3a8ad1c7ab53a8785293d34e307a524813997a85eea9d%402%3fsymKey%3dc8703d410274571cee7d18ac6be68f3da6d448c6050c878b92bb5dba819e5dcd%26relay-protocol%3dirn 

This was working 1 week ago when I tested a PR in iOS

### Evidence
https://github.com/user-attachments/assets/fba4ced7-b226-40f5-a96c-fbd3a6a6da5f

**Comment by juans-chainsafe** [comment]
@kantagara the issue is related to a default configuration in Player settings in iOS build. Because is working for me in Chain switching branch using the UnitySampleProject, I tried disable the strip engine code and Optimize Mesh data but is the same.

**Comment by kantagara** [comment]
@juans-chainsafe seems like it was some sort of a fluke, since now I've built from dev, and it's working as expected.
I did realize now that Metamask is not redirecting you back to the original app. Will investigate that for the next release.
