### ISSUE TITLE
Countly is not logging events

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#1146]
Make sure you enable analytics to test this.

I see user profiles being populated and sessions in "Incoming Data Logs" but I don't see a single event when triggering samples in SampleMain.

Events should appear in the user profile and in "Incoming Data Logs" page with the "Events" filter applied

**Comment by kantagara** [comment]
Even in Editor? Okie, checking tmrw.

**Comment by juans-chainsafe** [comment]
> Even in Editor? Okie, checking tmrw.

yes, profiles and sessions are being displayed. Events not

**Comment by kantagara** [comment]
It was a countly issue obviously, now everything seems to be working correctly. 
![image](https://github.com/user-attachments/assets/9aeacd8c-bdd0-4fa1-93b0-a2a2b8f5598e)
Maybe just press couple of buttons in the sdk sample scene so that it batches all of them together
