### ISSUE TITLE
Mobile metamask and desktop connection

### ISSUE THREAD

**Issue by ugurberkecan** [ChainSafe/web3.unity#115]
*User Story**
I want to use chainsafe on desktop and send transactions to mobile metamask account and if i press accept that on mobile, the desktop game will know that.

**Suggested features or ways to address the user story**
Metamask wallet -> is another plugin doing this for only login.

**Completion Criteria**
- [ ] Criteria 1

**Additional context**

**Comment by KBryan** [comment]
What you are trying to achieve is done via smart contract interactions and listening for events. Unfortunately, the SDK doesn't support listening to smart contract events atm. This is something we do want to add.
