### ISSUE TITLE
Loading spinner is not displayed in WC in a WebGL build

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#1156]
For some reason, the loading spinner that was made on https://github.com/ChainSafe/web3.unity/pull/1118/commits/06a9473d7612f0bf401203cf6326467856cbd70c is not displayed in dev branch when you build on WebGL.

We should add it again.

**Comment by kantagara** [comment]
This seems to be fixed (i.e. it's popping up)
