### ISSUE TITLE
Verifyed signature and message dont give the right address

### ISSUE THREAD

**Issue by TooSizzle** [ChainSafe/web3.unity#116]
**Describe the bug**
With a signature from message and private key i cant found the correct address with the recover/verify

**To Reproduce**

        string message = "Message";
        string hashedMessage = Web3Wallet.Sha3(message);

        string privateKey = { MyPrivateKey };

        string signature = Web3PrivateKey.Sign(privateKey, hashedMessage);
        string address = await EVM.Verify(hashedMessage, signature);

**Expected behavior**
The address should be the address of the privateKey.
But is not.

**Comment by KBryan** [comment]
Okay, so you are working with `ecrecover` ? do you have the smart contract and address you are working with.

**Comment by TooSizzle** [comment]
Yes im using a smart contract i deployed on the testnet its exaclty this u can find here 
https://solidity-by-example.org/signature/
0x1618bD1F2BfE84Ce0665cFEB6C412065c3d181Ce

**Comment by KBryan** [comment]
Yes, this is not working as expected. Looking into a fix and will get back to you.

**Comment by KBryan** [comment]
Okay, so. This is working but looks like another hash was added in this example.  My apologies for not picking this up. Try something like the following and see if you get the result you are looking for.
```
        string message = "Message";
        string signature = Web3PrivateKey.Sign(privateKey, message);
        print("Signature: " + signature);

        string r = signature.Substring(0, 66);
        print("R: " + r);
        string s = "0x" + signature.Substring(66, 64);
        print("S: " + s);
        int v = int.Parse(signature.Substring(130, 2), System.Globalization.NumberStyles.HexNumber);
        print("V: " + v);
        // get account from private key
        string account = Web3PrivateKey.Address(privateKey);
        print("Account from PK: " + account);
        string address = await EVM.Verify(message, signature);
        print("Address From Verify: " + address);
```

**Comment by TooSizzle** [comment]
First thanks for your answer ! 
I tryed a lot of things but.. Looks like its not working.. 

If i use the message without hashing (SHA3) the EVM.Verify(notHashedMessage, _signature) function work good. But look like he's not taking the message into consideration. And the ecrecover() function need a hashed message to work. 
When it take a hashed message like that -> 0x3142bcab0c4d21cb9e3d5ac70c975fbc52b2977f237999f36dc9dedb14029357
it give a address, but not the good one. I tested with the r v s directly in the ecrecover() function, its look like its not the probleme. 


I think the problem could be in the signature -> Web3PrivateKey.Sign(privateKey, hashedMessage);
it should have the same behavior as the function -> web3.eth.accounts.sign(hashedMessage, privateKey);

**Comment by GilbertoBitt** [comment]
right now I'm also having problem with private key and getting the address but I'm doing different 
i try using "**string account = Web3PrivateKey.Address(privateKey);**" but is returning with the exception: "**ArgumentException: Scalar is not in the interval [1, n - 1]**"

**Comment by TooSizzle** [comment]
@GilbertoBitt  
I just tester the string "account = Web3PrivateKey.Address(privateKey)" and the result is correct ! I think your problem should be somewhere else ! 

@KBryan 
I tested somethings ! 
Im pretty sure the problem is the signature "Web3PrivateKey.Sign(privateKey, hashedMessage);"
I tested the EVM.Verify(message, signature); and the ecrecover() in a smart contract and it give the same result.

If i use the JS function web3.eth.accounts.sign(hashedMessage, privateKey); and give it to the EVM.verify() and the ecrecover() it give the good address ! But when i take exactly the same hashedMessage and signature and i use the Web3PrivateKey.Sign(privateKey, hashedMessage); i have a different address, not correct ! 

I hope this can help you to fix this !

**Comment by Bombonator** [comment]
I have the same issue when trying to verify on-chain through a smart contract. I debugged both the Unity script and the smart contract that uses the hash.toEthSignedMessage and the recover to obtain the address of the signer and the recovered address does not correspond the signer.

Signing in Unity:
` string hashedMessage = Web3Wallet.Sha3(message);
  string signature = Web3PrivateKey.Sign(gameKey, hashedMessage);`

The signature is used as a parameter for the smart contract, which does the following:
`// This recreates the message hash that was signed on the client.
  bytes32 hash = keccak256(abi.encodePacked(_message));
  bytes32 messageHash = hash.toEthSignedMessageHash();

  // Verify that the message's signer is the admin address 
  address signer = messageHash.recover(_signature);
  require(hasRole(ADMIN_ROLE, signer));`

signer in the smart contract does not match the private key used to sign the message.

**Comment by KBryan** [comment]
Okay, I'm currently reimplementing Sha3 starting from Web3GL and moving down the SDK. There is a new build marked 1.3.0.  This is still in beta. If you guys could give these initial prefabs a test. That would be great. Then I'll be moving down the SDK over the next couple of days.  

https://github.com/ChainSafe/web3.unity/releases/tag/beta.1.3.0

**Comment by KBryan** [comment]
I've updated this with a new signing mechanism. It has passed early tests and should be able to get a build-out today.
