### ISSUE TITLE
Upgrade Block Racerz

### ISSUE THREAD

**Issue by boorich** [ChainSafe/web3.unity#1172]
**Summary**
Add asset streaming to Block Racerz and load high-resolution race car assets at runtime.

**Suggested features or ways to address the summary**
Use plain Streaming Assets or Cloud Content Delivery to load race car models from a resource outside the build.

**Motivation**
This is important to prove a potential business case.

**Acceptance Criteria**

- NFT representing a car is present in the running instance of the game
- The currently connected wallet owns that NFT
- Car model gets dynamically loaded from a remote resource
- Car model gets initialized within the game for the player to equip and race

**Blockers**
(OPTIONAL) [Do you see any blocker that needs to be done before implementing this feature?]

**Dependencies**
(OPTIONAL) [Do you know about dependencies that directly affect this issue?]

**Additional Context**
(OPTIONAL) [Add any other context, files, images (screenshots/videos), diagrams, or documents about the feature request here.]

**Final Steps**
* Give it one of these labels `Type: Feature` `Type: Enhancement`
* Add your estimation

**Estimations**

| Story Point | Amount of effort | Amount of time | Task Complexity | Task Risk or Uncerntainty |
|----------|----------|----------|----------|----------|
| 1 | Minimum efort | A few minutes | Little complexity | None |
| 2 | Minimum effort | A few hours | Little complexity | None |
| 3 | Mild efort | A day | Low complexity | Low |
| 5 | Moderate efort | A few days | Mediium complexity | Moderate |
| 8 | Severe efort | A week | Medium complexity | Moderate |
| 13 | Maximum effort | A few month | High complexity | High |

**Comment by kantagara** [comment]
@boorich we can close this one since we're focusing on snailtrail?

**Comment by boorich** [comment]
Close
