### ISSUE TITLE
Switching Chain when connected trough WC doesn't work.

### ISSUE THREAD

**Issue by kantagara** [ChainSafe/web3.unity#1189]
**Describe the bug**
When I am trying to switch the chain, WC disproves my request almost immediately.
**Steps**
1. Try to switch the chain in any of the samples.
2. Run the sample where you tried to switch the chain
3. You will immediately get an error/exception in unity that says that you can't switch the chain.

**Expected behavior**
Your wallet (Metamask in my case) prompts you to switch the chain to an appropriate one.

**Comment by creeppak** [comment]
Works for Reown with the chains supported by wallet. Often times it excludes testnet chains (used in our samples).
