### ISSUE TITLE
How can I listen the Transaction Receipt Event?

### ISSUE THREAD

**Issue by 271264921** [ChainSafe/web3.unity#12]
When I launch a transaction throw the method of "Web3GL.Send", I want to listen the Event defined in the contract.How can I do it?It is similar to the function described in Web3.js 's doc like below:
![image](https://user-images.githubusercontent.com/15072454/133192331-5954c79a-e46e-4b17-bfa5-d8c58c5bdc74.png)

**Comment by leon-do** [comment]
new update should have this https://github.com/ChainSafe/web3.unity/releases/tag/v1.0.3

**Comment by hailg** [comment]
Hi @leon-do

I tried to look into the release above but I cannot find this functionality. Can you help to point it out? Thank you.

**Comment by 17612491225** [comment]
I can't find it either. Can you help me find it？

**Comment by leon-do** [comment]
We currently have `TxStatus`. Will this work?

https://chainsafe.github.io/game-docs/#transaction-status
