### ISSUE TITLE
Missing stuff upon install 

### ISSUE THREAD

**Issue by sweetpea22** [ChainSafe/web3.unity#120]
**Describe the bug**
Hey when I download the SDK from Unity Store I get errors, not sure what they are/mean.

**To Reproduce**
1. Go to SDK on Unity Asset Store. https://assetstore.unity.com/packages/tools/game-toolkits/web3-chainsafe-gaming-sdk-216507
2. Click on 'Open in Unity'
3. In Unity Editor, click Download. When it's done downloading, click import.
4. Open console tab and see error.

**Expected behavior**
idk

**Screenshots**
<img width="1217" alt="Screen Shot 2022-03-30 at 10 55 13 AM" src="https://user-images.githubusercontent.com/47398578/160865777-f3c18a98-3c6a-41e4-a270-472b3ff8af96.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Version: Unity 2020.2.16

**Comment by alexvotofuture** [comment]
You will need to download JSON.net. Here are the [installation instructions for the SDK](https://docs.gaming.chainsafe.io/installation), which walk you through that process.
