### ISSUE TITLE
Loading spinner doesn't disappear after signing a transaction with Reown

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#1201]
**Describe the bug**
In mobile, after you connect Metamask and you click a sample that requires to sign a transaction, you get redirected to Metamask, sign the transaction, go back to the Unity app and the loading spinner is there forever, even when the transaction finishes. And it also happens with simple things like Sign Message sample

**Steps**
1. Build in iOS
2. Login with [Reown] and connect [Metamask]
3. Click on Mint sample or Sign Message sample
4. Sign message/transaction
5. Go back to Unity app

**Expected behavior**
Spinner disappears after the transaction is confirmed, or if is the sign message sample, automatically when you switch back.

**Console errors**
No errors in console, but also no output of the transaction/signed message

**Screenshots/Video**
https://github.com/user-attachments/assets/1f563405-32b1-401c-bc5d-91e040bc3fb5

**Mobile (please complete the following information):**
 - Chainsafe SDK version: [https://github.com/ChainSafe/web3.unity/pull/1199]
 - Platform: [iOS]
 - Device Type: [Real device]
 - OS Version: [iOS 18.0.1]
 - Device: [iPhone 16 Pro)

**Comment by kantagara** [comment]
@juans-chainsafe is this still happening?

**Comment by juans-chainsafe** [comment]
> [@juans-chainsafe](https://github.com/juans-chainsafe) is this still happening?

yes, is still happening the same as the video attached in this ticket. I just retested it just in case
