### ISSUE TITLE
metamask webgl template missing (web3.unity 3.0.4)

### ISSUE THREAD

**Issue by TheOneVries** [ChainSafe/web3.unity#1207]
**Describe the bug**
For the MetaMask connector to work for webGL builds, we're supposed to select the MetaMask webGL template in project settings, but it is not available (nor seem to be present in any of the repository files)

**Steps**
1. go to project settings for a project with web3.unity 3.0.4 installed
2. under player > resolution and presentation, there should be a 'MetaMask' webGL template available... which there is not

**Desktop (please complete the following information):**
 - Chainsafe SDK version: [3.0.4]
 - Unity Version: [2022.3.49f1]
 - Operating System: [Windows 10]

![2024-10-24 14_38_07-Window](https://github.com/user-attachments/assets/a3a068a6-30f9-4a9f-8859-6635910cfe56)

**Comment by TheOneVries** [comment]
a few uninstalls/reinstalls got webgl synchronization to work. I suspect upgrading from 2.5 caused a number of issues. The template is also not called 'metamask' as it is according to the documentation, but something is there at least.

**Comment by kantagara** [comment]
Hey The new webgl template is now called Web3Unity. If you are upgrading from 2.5, we advise a clean reinstall of the packages and samples since there are some breaking changes in 3.0 .
