### ISSUE TITLE
CSWebsocket `ObjectDisposedException: Cannot access a disposed object.`

### ISSUE THREAD

**Issue by TheOneVries** [ChainSafe/web3.unity#1215]
When connecting to wallet using the 'remember me' functionality, using admittedly not the most reliable internet connection, I regularly find unity crash when calling `public async Task Close()` on CSWebSocket.cs

This is a connection made via WalletConnect, connecting to MetaMask. Mostly this works fine, but occasionally this error occurs, leading me to believe the issue lies with internet connection.

I am afraid I cannot provide a sample project or anything.

**Console errors**

> ObjectDisposedException: Cannot access a disposed object.
> Object name: 'MobileAuthenticatedStream'.
> Mono.Net.Security.MobileAuthenticatedStream.StartOperation (Mono.Net.Security.MobileAuthenticatedStream+OperationType type, Mono.Net.Security.AsyncProtocolRequest asyncRequest, System.Threading.CancellationToken cancellationToken) (at <09cbc7ca916345fdbceb45137018efd3>:0)
> System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync (System.Int32 minimumRequiredBytes, System.Threading.CancellationToken cancellationToken, System.Boolean throwOnPrematureClosure) (at <09cbc7ca916345fdbceb45137018efd3>:0)
> System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult] (System.Memory`1[T] payloadBuffer, System.Threading.CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter) (at <09cbc7ca916345fdbceb45137018efd3>:0)
> Rethrow as OperationCanceledException: Aborted
> System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult] (System.Memory`1[T] payloadBuffer, System.Threading.CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter) (at <09cbc7ca916345fdbceb45137018efd3>:0)
> System.Net.WebSockets.ManagedWebSocket.CloseAsyncPrivate (System.Net.WebSockets.WebSocketCloseStatus closeStatus, System.String statusDescription, System.Threading.CancellationToken cancellationToken) (at <09cbc7ca916345fdbceb45137018efd3>:0)
> NativeWebSocket.WebSocket.Close () (at ./Library/PackageCache/io.chainsafe.web3-unity@f92323a1ea/Runtime/Plugins/WebSocket/CSWebSocket.cs:709)
> ChainSafe.Gaming.WalletConnect.WebSocketConnection.Dispose () (at ./Library/PackageCache/io.chainsafe.web3-unity@f92323a1ea/Runtime/Scripts/WalletConnect/WebSocketConnection.cs:279)
> System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <31687ccd371e4dc6b0c23a1317cf9474>:0)
> UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <50e5acd061cd4a73b7fc8eecbf07e915>:0)
> UnityEngine.UnitySynchronizationContext.Exec () (at <50e5acd061cd4a73b7fc8eecbf07e915>:0)
> UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at <50e5acd061cd4a73b7fc8eecbf07e915>:0)

**Desktop (please complete the following information):**
 - Chainsafe SDK version: [3.0.4]
 - Unity Version: [2022.3.49f1]
 - Operating System: [Windows 10]

**Comment by TheOneVries** [comment]
Yes I do, but this is not happening via contract calls; this happens on initial wallet connect. So in my connect script I call `await Web3Unity.Instance.Initialize(rememberMe);`
Somewhere in this process it seems `public async Task Close()` is called on CSWebSocket.cs, which is where this error _can_ occur...

I should mention that this happens in the editor, and I've also noticed that this never happens on first play, so this might have to do with objects not properly being disposed of when stopping a game and starting again?
Either way, I've put the code in Task Close() in a try-catch like so:
```
        public async Task Close()
        {
            if (State == WebSocketState.Open)
            {
                try
                {
                    await m_Socket.CloseAsync(WebSocketCloseStatus.NormalClosure, string.Empty, m_CancellationToken);
                }
                catch (Exception e)
                {
                    UnityEngine.Debug.LogWarning(">> WebSocket exception: " + e.Message);
                }
            }
        }
```
And this seems to work fine... even when I try to connect and it catches an exception, the connection still ends up being successful.

**Comment by kantagara** [comment]
If you want , you can add that fix to our repo and help us out in true open-source manner. We would be more than happy to accept your PR!

**Comment by kantagara** [comment]
I've included your code. It should be available in the next version of the SDK planned to launch before the holidays.

**Comment by TheOneVries** [comment]
Cool, thanks! I appreciate the offer that I could have added this one myself, but I'm not comfortable enough with GitHub to involve myself with open source projects yet.
