### ISSUE TITLE
customized connection URL instead of default chainsafe.io

### ISSUE THREAD

**Issue by ViperTechnologies-RnD** [ChainSafe/web3.unity#122]
*User Story**
As a Unity Developer I want to access to more Metamask Functions like encryption and Decryption with Private/Public keys via Metamask so that I can Encrypt a file and save it to a server and Decrypt it when fetching it from the server.
Scenario:
Suppose there are 2 users one is the requester and the other is the participant.
The requester asks for a file.
a participant sends the file.
in short, the scenario is about p2p encryption.
when the participant uploads a file he/she should receive a prompt from metamask to encrypt this file before saving the file/uploading the file to the destination metamask has an encryption feature.
after that the requester in order to open the file, should decrypt the uploaded file by the participants.
in the Web3Wallet.cs file, there are two links:

`    #if (UNITY_ANDROID || UNITY_IOS) && !UNITY_EDITOR
        private static string url = "https://metamask.app.link/dapp/chainsafe.github.io/game-web3wallet/";
    #else
        private static string url = "https://chainsafe.github.io/game-web3wallet/";
    #endif`

is there a way that we can setup a custom link and add more features and/or end points, actions to this?

**Suggested features or ways to address the user story**
refer to here: https://zarela.io/zarela-angels and watch the second video, please.

**Completion Criteria**
- [ ] https://zarela.io/technology

**Additional context**

**Comment by KBryan** [comment]
This currently isn't open source but we are looking into it. I'll look into this for you further and get back to you.

**Comment by sneakzttv** [comment]
You can now authorise using signatures and verify whatever you need to with our sign and verify prefabs. You can do then run your actions from that.
