### ISSUE TITLE
Polishing. Add an easy-way to add Web3Unity object to the scene.

### ISSUE THREAD

**Issue by creeppak** [ChainSafe/web3.unity#1224]
Web3Unity should be added to the scene first in order to work, but there is no easy way to do it.

The prefab is buried down in the packages and there is no way anyone would figure it out without going through documentation.

One possible solution I can think of is adding a new Menu Item to the `GameObject/ChainSafe` group called `Web3 Client`. This will add a new menu item to the context menu raised by right-clicking in the Hierarchy panel as [described in this page](https://docs.unity3d.com/2020.1/Documentation/ScriptReference/MenuItem.html).

![image](https://github.com/user-attachments/assets/1f316fae-d062-4939-b40e-95a1a82e4452)

**Comment by creeppak** [comment]
Done. Menu name "Web3/Web3 Client".

**Comment by kantagara** [comment]
Closing the issue
