### ISSUE TITLE
Web3 WebGL stuck on first wallet connected, even after switching wallet.

### ISSUE THREAD

**Issue by LiamVisionary** [ChainSafe/web3.unity#124]
Hi, I've put together this project https://FantomSurvivor.com/ where I have a WebGL player embedded in my page using the web3 WebGL login plugin. It works as expected when connecting a metamask wallet for the first time, and pulls the users NFTs from their wallet. However, when switching wallets and reloading the game, it still tries to pull the NFTs from the first wallet. I'm not sure if this is a bug or intentional, but I'd really appreciate some input on this.

**Comment by LiamVisionary** [comment]
@KBryan Hey! Thanks for the response and I apologize for the delay in getting back to you -- just moved to NYC :')

How would I go about logging the player out? Couldn't find that in the documentation. And looking through the code, it seems PlayerPrefs should overwrite the previous one upon successful web3 connection. Is that not the case and should I then clear the PlayerPrefs manually before writing to it?

**Comment by KBryan** [comment]
Yes, there is also LogOutCanvas.prefab that you can use. 
![LogOutPrefab](https://user-images.githubusercontent.com/681817/164282805-00b701ca-8f56-45d1-898c-47352bd9518c.png)
