### ISSUE TITLE
Reown wallet options are not displayed correctly

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#1258]
**Describe the bug**
The wallet providers are not displayed as expected in Reown, the QR code works as expected, the issue are the wallet providers.
This happens in the editor and iOS

**Steps**
1. Click on Reown option
2. Try to select one of the options

**Expected behavior**
The operation continues in the provider selected and the name of the provider is displayed correctly

**Console errors**
Not sure if related to this, but I see the log:
```
NullReferenceException: Object reference not set to an instance of an object
ChainSafe.Gaming.Reown.Dialog.LocalWalletButton.Set (ChainSafe.Gaming.Reown.Models.WalletModel data, System.String walletIconEndpoint, ChainSafe.Gaming.Web3.Environment.Http.HttpHeader[] httpHeaders, System.Action onClick) (at ./Library/PackageCache/io.chainsafe.web3-unity@86c1ba5f92/Runtime/Scripts/Reown/Dialog/LocalWalletButton.cs:53)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <606c2e0a56af495988c860a4ac613e74>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:153)
UnityEngine.UnitySynchronizationContext.Exec () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:83)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:107)
```

**Screenshots/Video**
![Image](https://github.com/user-attachments/assets/5e8a6cfb-d8ca-4acc-9946-d64a3a037f6c)

**Desktop (please complete the following information):**
 - Chainsafe SDK version: [e.g., 2.5.0]
 - Unity Version: [e.g., 2022.1]
 - Operating System: [e.g., Windows 10]

**Additional context**
This is working in UnitySampleProject, the issue is when I import the SDK using Package manager

**Comment by creeppak** [comment]
Works fine on my end. Did you import the package using the git url? Does it only break for iOS in editor?

![Image](https://github.com/user-attachments/assets/0a9b1c4f-f88b-4c3d-9518-4e7b0bdfa267)

The only issue I keep encountering is sprites not loading from the package in the editor. I believe they should work fine in the actual builds.

**Comment by creeppak** [comment]
Judging from your logs, this should happen if this field is not set on the prefab in the package.
![Image](https://github.com/user-attachments/assets/d2223c47-0448-4fca-882d-8f7ebf6762c8)

OR (which is unlikely IMO) the data for a wallet app gets lost at some point.
