### ISSUE TITLE
Possible Fake Payments.

### ISSUE THREAD

**Issue by MohamedNourSadek** [ChainSafe/web3.unity#126]
**Describe the bug**
The SDK notifies me that the payment is done successfully even if the user didn't pay.

**To Reproduce**

If the user copied any string that starts with "0x" and is 66 characters long, the SDK will think that the payment is done, even if this string is an old one or any other random one, which allows the player to get around payment.

Look at this Unlisted Video to see an example of that:
https://youtu.be/3XsuFLaZfrA

*Request*
Is There's anyway around to stop this from happening?

**Comment by KBryan** [comment]
Is it making multiple transactions or just waiting for that one to be completed? Is it possible to send the link to the transactions?

**Comment by MohamedNourSadek** [comment]
> I'm not currently able to reproduce the error you are receiving.

Well, the reason why this is happending is because of the fact that unity knows about the payment success is by checking the clipboard content, and if it starts with 0x and 66 in length, it will consider the payement a success, even if the clipboard had an old transaction hash, or any other hash.

here's a link of the part of the code in your SDK that i am mensioning: 

![image](https://user-images.githubusercontent.com/71439813/163108025-2cc6367a-1fea-4100-b728-f999e6ca2059.png)

**Comment by KBryan** [comment]
Okay, then in your game logic you will need to do some sanity checks.
