### ISSUE TITLE
a string response convert 2d arrays

### ISSUE THREAD

**Issue by z79422957** [ChainSafe/web3.unity#127]
Hi,
(1)in solidity,This function have a value that returns a two-dimensional array,
function getOnwerNFTsAttrOf(address _address, uint256 _type)external view returns(uint256[][] memory)

(2)in unity, call to getOnwerNFTsAttrOf method.
 public async void OnEVMCall()
    {
        string response = await EVM.Call(chain, network, contract, abi, method, args);
        print(response);
    }
 The string result is [["2","1","3","13","3","3","3"],["1","1","4","14","4","4","4"],["4","1","4","9","4","4","4"]]
But I want the result of a two-dimensional array in c# scripts, not a string. How can I convert a string into a multidimensional array? Thanks.

**Comment by KBryan** [comment]
Have you tried `JsonConvert.SerializeObject(response)` on it?

**Comment by z79422957** [comment]
JsonConvert.DeserializeObject<int[][]>(response);
Thank you very much. It succeeded!

**Comment by KBryan** [comment]
Okay, great. Closing this issue. Sorry, mistype. Glad you could read between the line here.
