### ISSUE TITLE
Don't open Metamask for confirmation

### ISSUE THREAD

**Issue by Xunlai-13** [ChainSafe/web3.unity#128]
Hey.
I tried some smartcontracts also with multiple args. I used the example of your docs. 
This worked fine but when i tried to use this smartcontrct nothing happens after i clicked on the button. (so no confirmation window ind metamask) . The args arent a problem, because i tested this style with your smartcontract and it works fine. 
The only logical thing is the ABI but i dont know.

I send you all data you need to reproduce the process (Smart Contract, The Unity Code and the Log of my Browser).
I use rinkeby and my settings are default. I used a complete new project. 

**Expected behavior**
Metamask opens and i can confirm the contract.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Brave (Chrome)

[browserlog.log](https://github.com/ChainSafe/web3.unity/files/8473181/browserlog.log)
[smartcontractscript.txt](https://github.com/ChainSafe/web3.unity/files/8473182/smartcontractscript.txt)
[unityscript.txt](https://github.com/ChainSafe/web3.unity/files/8473184/unityscript.txt)

**Comment by KBryan** [comment]
There doesn't seem to be a method name `transferERC20` in the ABI you provided.

**Comment by Xunlai-13** [comment]
![1](https://user-images.githubusercontent.com/78625156/163008234-740f043c-7eda-434c-a8fb-911c343ac327.PNG)

.......

thank you :)
