### ISSUE TITLE
Obfuscation

### ISSUE THREAD

**Issue by hankdangerfield** [ChainSafe/web3.unity#129]
I am using https://assetstore.unity.com/packages/tools/utilities/obfuscator-pro-89589#description to obfuscate my code.

When obfuscating the entire Assembly-CSharp file I am no longer able to login using metamask as the redirect fails. I have tried to create a new assembly definition for the Web3Unity folder and the scripts folder I want to be obfuscated, however, I receive the following error:

![image](https://user-images.githubusercontent.com/91743546/162976172-685da639-763e-4a98-9727-bc70e41f810f.png)

**Comment by KBryan** [comment]
Okay, first do you have this folder in the plugins directory?
![Uploading awaiter_plugin.png…]()

**Comment by hankdangerfield** [comment]
Yes, I do. Everything works fine until I try to obfuscate or change assembly definitions. 

![image](https://user-images.githubusercontent.com/91743546/162977924-5f3d012c-2134-43e0-b458-6c345d25de83.png)

**Comment by hankdangerfield** [comment]
I am using this https://assetstore.unity.com/packages/tools/utilities/obfuscator-pro-89589#description

**Comment by hankdangerfield** [comment]
The obfuscation works just fine, however, the metamask redirect does not work after obfuscating.

**Comment by KBryan** [comment]
Is there any error you are getting with this? Is it possible for you to add this also?

**Comment by sneakzttv** [comment]
you need to disable some obfuscation options, turn them all off and turn things on 1 by 1 and build till it fails, then you'll know what's stopping it,
