### ISSUE TITLE
Memory leak at EVM.cs, line 51

### ISSUE THREAD

**Issue by LiamVisionary** [ChainSafe/web3.unity#131]
**Describe the bug**
When using the EVM.Call method, I get the error: "A native collection has not been disposed, resulting in a memory leak." from line 51: UnityWebRequest webRequest = UnityWebRequest.Post(url, form);
Upon some research, I see that it can be fixed with a 'using' construct as such: https://docs.unity3d.com/2021.2/Documentation/ScriptReference/Networking.UnityWebRequest.Dispose.html

**To Reproduce**
1. Enable Unity Jobs and Burst compilation
2. Enable full stack trace
3. Run the EVM.Call method
4. Trace the error to EVM.Call

**Expected behavior**
Expected no memory leak

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS Monterey
 - Browser [e.g. chrome, safari] N/A
 - Version [e.g. 22] N/A

**Smartphone (please complete the following information):**

**Additional context**

**Comment by KBryan** [comment]
I did add this in the latest update as was previously reported. May need more hooks around it in other areas. Thanks for posting.

**Comment by KBryan** [comment]
This has been updated in the latest release. Are you still seeing this issue?
