### ISSUE TITLE
Got "processing response error" on broadcastTransaction service when sending erc1155 token with private key

### ISSUE THREAD

**Issue by bgunduz55** [ChainSafe/web3.unity#135]
**Describe the bug**
I got "processing response error" on broadcastTransaction service when sending erc1155 token with private key
I use the same code as in documentation. Also the code about ERC20 token worked before. 
But ERC1155 not worked.
Actually, I tried to mint on opensea before. And that give me "invalid signature string" error on same code.
Then I tried to mint a smart contract and got this one.

**To Reproduce**
I want to transfer an ERC1155 NFT from my wallet to players wallet.

Mywallet = 0x8ec5dc03b2E9Ec9bf40841e7aC5B07a089d9B741

Contract = 0x123cF00c7FAcA17668589B1ba7912DE1f13a7223

PlayersWallet(also mine) = 0x503d03488353A03Ebefb8C3E14be1612006Bf07f

TokenID = 2

Ethereum - Rinkeby 

**Screenshots**
![image](https://user-images.githubusercontent.com/8244985/165100233-f2d785a3-64c7-49a4-9196-1a43a5632c68.png)

**Additional context**

        string privateKey = "PRIVATEKEY_OF_MY_ACCOUNT";
        // set chain: ethereum, moonbeam, polygon etc
        string chain = "ethereum";
        // set network mainnet, testnet
        string network = "rinkeby";
        // smart contract method to call
        string method = "safeTransferFrom";
        // account of player 
        string account = Web3PrivateKey.Address(privateKey);
        // ERC-1155 contract address 
        string contract = "0x123cF00c7FAcA17668589B1ba7912DE1f13a7223";
        // account to send to
        string toAccount = "0x428066dd8A212104Bc9240dCe3cdeA3D3A0f7979";
        // ERC-1155 token id
        string tokenId = "2";
        // amount of erc1155 tokens
        string amount = "1";
        // amount of wei to send
        string value = "0";
        // abi to interact with contract
        string abi = "[ { \"inputs\": [ { \"internalType\": \"string\", \"name\": \"uri_\", \"type\": \"string\" } ], \"stateMutability\": \"nonpayable\", \"type\": \"constructor\" }, { \"anonymous\": false, \"inputs\": [ { \"indexed\": true, \"internalType\": \"address\", \"name\": \"account\", \"type\": \"address\" }, { \"indexed\": true, \"internalType\": \"address\", \"name\": \"operator\", \"type\": \"address\" }, { \"indexed\": false, \"internalType\": \"bool\", \"name\": \"approved\", \"type\": \"bool\" } ], \"name\": \"ApprovalForAll\", \"type\": \"event\" }, { \"anonymous\": false, \"inputs\": [ { \"indexed\": true, \"internalType\": \"address\", \"name\": \"operator\", \"type\": \"address\" }, { \"indexed\": true, \"internalType\": \"address\", \"name\": \"from\", \"type\": \"address\" }, { \"indexed\": true, \"internalType\": \"address\", \"name\": \"to\", \"type\": \"address\" }, { \"indexed\": false, \"internalType\": \"uint256[]\", \"name\": \"ids\", \"type\": \"uint256[]\" }, { \"indexed\": false, \"internalType\": \"uint256[]\", \"name\": \"values\", \"type\": \"uint256[]\" } ], \"name\": \"TransferBatch\", \"type\": \"event\" }, { \"anonymous\": false, \"inputs\": [ { \"indexed\": true, \"internalType\": \"address\", \"name\": \"operator\", \"type\": \"address\" }, { \"indexed\": true, \"internalType\": \"address\", \"name\": \"from\", \"type\": \"address\" }, { \"indexed\": true, \"internalType\": \"address\", \"name\": \"to\", \"type\": \"address\" }, { \"indexed\": false, \"internalType\": \"uint256\", \"name\": \"id\", \"type\": \"uint256\" }, { \"indexed\": false, \"internalType\": \"uint256\", \"name\": \"value\", \"type\": \"uint256\" } ], \"name\": \"TransferSingle\", \"type\": \"event\" }, { \"anonymous\": false, \"inputs\": [ { \"indexed\": false, \"internalType\": \"string\", \"name\": \"value\", \"type\": \"string\" }, { \"indexed\": true, \"internalType\": \"uint256\", \"name\": \"id\", \"type\": \"uint256\" } ], \"name\": \"URI\", \"type\": \"event\" }, { \"inputs\": [ { \"internalType\": \"address\", \"name\": \"account\", \"type\": \"address\" }, { \"internalType\": \"uint256\", \"name\": \"id\", \"type\": \"uint256\" } ], \"name\": \"balanceOf\", \"outputs\": [ { \"internalType\": \"uint256\", \"name\": \"\", \"type\": \"uint256\" } ], \"stateMutability\": \"view\", \"type\": \"function\" }, { \"inputs\": [ { \"internalType\": \"address[]\", \"name\": \"accounts\", \"type\": \"address[]\" }, { \"internalType\": \"uint256[]\", \"name\": \"ids\", \"type\": \"uint256[]\" } ], \"name\": \"balanceOfBatch\", \"outputs\": [ { \"internalType\": \"uint256[]\", \"name\": \"\", \"type\": \"uint256[]\" } ], \"stateMutability\": \"view\", \"type\": \"function\" }, { \"inputs\": [ { \"internalType\": \"address\", \"name\": \"account\", \"type\": \"address\" }, { \"internalType\": \"address\", \"name\": \"operator\", \"type\": \"address\" } ], \"name\": \"isApprovedForAll\", \"outputs\": [ { \"internalType\": \"bool\", \"name\": \"\", \"type\": \"bool\" } ], \"stateMutability\": \"view\", \"type\": \"function\" }, { \"inputs\": [ { \"internalType\": \"address\", \"name\": \"_address\", \"type\": \"address\" }, { \"internalType\": \"uint256\", \"name\": \"_amount\", \"type\": \"uint256\" } ], \"name\": \"ownerMint\", \"outputs\": [], \"stateMutability\": \"nonpayable\", \"type\": \"function\" }, { \"inputs\": [ { \"internalType\": \"address\", \"name\": \"from\", \"type\": \"address\" }, { \"internalType\": \"address\", \"name\": \"to\", \"type\": \"address\" }, { \"internalType\": \"uint256[]\", \"name\": \"ids\", \"type\": \"uint256[]\" }, { \"internalType\": \"uint256[]\", \"name\": \"amounts\", \"type\": \"uint256[]\" }, { \"internalType\": \"bytes\", \"name\": \"data\", \"type\": \"bytes\" } ], \"name\": \"safeBatchTransferFrom\", \"outputs\": [], \"stateMutability\": \"nonpayable\", \"type\": \"function\" }, { \"inputs\": [ { \"internalType\": \"address\", \"name\": \"from\", \"type\": \"address\" }, { \"internalType\": \"address\", \"name\": \"to\", \"type\": \"address\" }, { \"internalType\": \"uint256\", \"name\": \"id\", \"type\": \"uint256\" }, { \"internalType\": \"uint256\", \"name\": \"amount\", \"type\": \"uint256\" }, { \"internalType\": \"bytes\", \"name\": \"data\", \"type\": \"bytes\" } ], \"name\": \"safeTransferFrom\", \"outputs\": [], \"stateMutability\": \"nonpayable\", \"type\": \"function\" }, { \"inputs\": [ { \"internalType\": \"address\", \"name\": \"operator\", \"type\": \"address\" }, { \"internalType\": \"bool\", \"name\": \"approved\", \"type\": \"bool\" } ], \"name\": \"setApprovalForAll\", \"outputs\": [], \"stateMutability\": \"nonpayable\", \"type\": \"function\" }, { \"inputs\": [ { \"internalType\": \"bytes4\", \"name\": \"interfaceId\", \"type\": \"bytes4\" } ], \"name\": \"supportsInterface\", \"outputs\": [ { \"internalType\": \"bool\", \"name\": \"\", \"type\": \"bool\" } ], \"stateMutability\": \"view\", \"type\": \"function\" }, { \"inputs\": [ { \"internalType\": \"uint256\", \"name\": \"\", \"type\": \"uint256\" } ], \"name\": \"uri\", \"outputs\": [ { \"internalType\": \"string\", \"name\": \"\", \"type\": \"string\" } ], \"stateMutability\": \"view\", \"type\": \"function\" } ]";
       
        string rpc = "";

        string accnt = PlayerPrefs.GetString("Account");
		print("Account: " + accnt);
        toAccount = accnt;  

        string[] obj = { account, toAccount, tokenId, amount, "0x00" };
        string args = JsonConvert.SerializeObject(obj);
        //string args = "[\""+ obj+"\"]";
        string chainId = await EVM.ChainId(chain, network, rpc);
        string gasPrice = await EVM.GasPrice(chain, network, rpc);
        string data = await EVM.CreateContractData(abi, method, args);
        string gasLimit = "9927423499700";
        string transaction = await EVM.CreateTransaction(chain, network, account, contract, value, data, gasPrice, gasLimit, rpc);
        string signature = Web3PrivateKey.SignTransaction(privateKey, transaction, chainId);
        string response = await EVM.BroadcastTransaction(chain, network, account, contract, value, data, signature, gasPrice, gasLimit, rpc);
        print(response);
    }

**Comment by Hadwick** [comment]
Did you end up finding a fix? I suddenly started getting this same issue.

**Comment by bgunduz55** [comment]
Nope, still waiting for a response.

**Comment by bgunduz55** [comment]
> Did you end up finding a fix? I suddenly started getting this same issue.

You've been made it successfully before?

**Comment by Hadwick** [comment]
Yea although I was using the ERC-20 version, it was working fine, then it just suddenly started giving me that error. It was working fine yesterday

**Comment by KBryan** [comment]
I've run both examples and they are working. https://rinkeby.etherscan.io/tx/0xb4c4598311d6e1e7ab4324d65e2368b267ac4895dc337fe07657d7829782433b 
https://rinkeby.etherscan.io/tx/0xc84cb5d6c468e5c60c1215c9097f4c2209bca46ee4a76d4acc900dd44225bbd0

**Comment by KBryan** [comment]
Here's a link to our docs also. 
https://docs.gaming.chainsafe.io/mobile-and-desktop#send-transaction-with-private-key

**Comment by bgunduz55** [comment]
I used the same code as the documentation. But error is same. Can you show me the network request parameters and response too? Also your code sample would be good. I attached the my code in description.

**Comment by Hadwick** [comment]
I ended up realizing that the account attached to the  private key  didn't have enough to cover the gas fee. Fixed my issue :/

**Comment by bgunduz55** [comment]
> I ended up realizing that the account attached to the private key didn't have enough to cover the gas fee. Fixed my issue :/

Sadly, It's not same for me

**Comment by KBryan** [comment]
Your issue may be. Try using. `string[] obj = { account, toAccount, tokenId, amount, "0x" };`

**Comment by bgunduz55** [comment]
@KBryan @Hadwick Actually I could tested on testnet when I increase the balance of wallets test amount. But when I mint the smart contract to mainnet. Now it's giving "invalid signature string" error to me. But mainnet balance is even more than test. There are 34.5 matic. 
Doesn't it enough? Should we increase it too?

**Comment by KBryan** [comment]
Seems like for polygon network you and other will need to change.
`string signature = EthECDSASignature.CreateStringSignature(key.SignAndCalculateV(hashByteArr, chainId));`
to
`string signature = EthECDSASignature.CreateStringSignature(key.SignAndCalculateYParityV(hashByteArr));`

Can you verify this fixed your issue and I'll close this?
