### ISSUE TITLE
Harmony PK Transaction Invalid Signature String Response

### ISSUE THREAD

**Issue by sneakzttv** [ChainSafe/web3.unity#136]
**Describe the bug**
When trying to make a pk transaction on harmony testnet to make a chain change i get "invalid signature string" as a response on EVM.BrodcastTransaction. All the previous steps fire off correctly and i have testnet funds in the account. The previous code works fine on BSC and other calls are working fine so far on harmony it just doesn't seem to like PK transactions.

**To Reproduce**
Try to make a pk transaction on harmony testnet and you should see the same result.

**Desktop (please complete the following information):**
windows 10
Desktop browser chrome

**Comment by KBryan** [comment]
Will look into this in a bit. Thanks for posting. Strange that it is not working.

**Comment by KBryan** [comment]
In Web3PrivateKey.cs can you change the line 
`string signature = EthECDSASignature.CreateStringSignature(key.SignAndCalculateV(hashByteArr, chainId));`
to
` string signature = EthECDSASignature.CreateStringSignature(key.SignAndCalculateYParityV(hashByteArr));`
and see if that makes a difference?

**Comment by sneakzttv** [comment]
yup that fixed it, thanks :D
