### ISSUE TITLE
 'Toggle' does not contain a definition for 'isOn'

### ISSUE THREAD

**Issue by RadhwaneDZ** [ChainSafe/web3.unity#137]
Assets\Web3Unity\Scripts\Scenes\WalletLogin.cs(40,28): error CS1061: 'Toggle' does not contain a definition for 'isOn' and no accessible extension method 'isOn' accepting a first argument of type 'Toggle' could be found (are you missing a using directive or an assembly reference?)

**Comment by KBryan** [comment]
Make sure you are installing the SDK via the package found here. https://github.com/ChainSafe/web3.unity/releases/tag/v1.2.8
