### ISSUE TITLE
Fantom ERC721s Endpoint

### ISSUE THREAD

**Issue by LiamVisionary** [ChainSafe/web3.unity#139]
I have a project and work for a client that requires being able to access all 721s in a users wallet on the fantom chain. 

Attempting to run AllERC721 returns an invalid response. Seems the API is missing an endpoint to Fantom. Is this currently a limitation of the Fantom chain, or do we just need the chain safe integration?

**Comment by KBryan** [comment]
Yes, unfortunately at this time Fantom isn't supported as a collection for AllERC721/1155. There will be an update in a few days with a workaround for this.

**Comment by LiamVisionary** [comment]
Sounds great, thanks for the update!

**Comment by KBryan** [comment]
We will not be adding an FTM endpoint at this time. We will have an update coming up that will give more control to the developer.
