### ISSUE TITLE
Load Custom ABI

### ISSUE THREAD

**Issue by gtspencer** [ChainSafe/web3.unity#14]
My goal is to find all ERC721 tokens from a certain contract that are owned by an address.

To do this I brought in the custom ABI for the contract.
The ABI was loaded from Etherscan https://etherscan.io/address/0x2bd58a19c7e4abf17638c5ee6fa96ee5eb53aed9.
And I want to call a method called "tokensByOwner" (the method is called tokensByOwner on Etherscan but the abi specifies tokensOfOwner --  I tested tokensByOwner and it doesn't work).

I added a method to ERC721 that roughly copies to implantation from BalanceOf, but instead calls tokensOfOwner.

Calling BalanceOf with my custom loaded ABI works, both in editor and localhost.

When I test in editor by just calling the method I added to ERC721.cs, it works fine and I get a list of tokens owned by the address.

However I have a demo where I can log in to the app via MetaMask (I'm hosting on Live Server in VS Code), but I can't call that same ERC721 method to find all tokensOfOwner.

I get a mix of different errors depending on how I run it.  Sometimes it's "Can't autodetect provider for [contract address]", and sometimes it's "Returned error: execution reverted."

Am I doing something wrong?  Do I need to recompile some of the JS stuff?

Also, is there a simpler way to find all tokens by owner?  I know it's not in the ERC721 standard but its pretty common across NFTs.

I absolutely love this package btw; I believe this is going to become to standard for Web3 game development.

**Comment by KBryan** [comment]
Hi, you may want to look at Balance of Batch that will get you started. It gives you a list of accounts and token id's  
https://chainsafe.github.io/game-docs/#balance-of-batch 

Also, join our discord if you haven't already.
https://discord.gg/evfk7z64

**Comment by gtspencer** [comment]
Thanks, I should've looked more in to the default function calls, that's exactly what I need!  I did also get the custom ABI to work; there was an issue with my json (the raw JSON on etherscan doesn't work nicely).  I have also just joined the discord; thanks for the link!  Super excited about what this project can do!
