### ISSUE TITLE
Web3PrivateKeySendTransactionExample is not working on Pulsechain testnet (chain 941)

### ISSUE THREAD

**Issue by vmel47** [ChainSafe/web3.unity#143]
Web3PrivateKeySendTransactionExample is not working on Pulsechain testnet (chain 941).

First I made a change in SignTransaction as it was said on discord:

You will need to update Web3PrivateKey.cs in the SDK from
signature = EthECDSASignature.CreateStringSignature(key.SignAndCalculateV(hashByteArr, chainId));
to
signature = EthECDSASignature.CreateStringSignature(key.SignAndCalculateYParityV(hashByteArr));

After this changes the response from EVM.BroadcastTransaction() looked correct: 0x38af98b144c0638d7e3c491d8c7eb38cacf46f7a3bd9b2d6e137907cf2ed2085, but not actual transaction happens. TPLS not moved to another wallet.
and the transaction did not appear on scan: https://scan.v2b.testnet.pulsechain.com/search-results?q=0x38af98b144c0638d7e3c491d8c7eb38cacf46f7a3bd9b2d6e137907cf2ed2085

**Comment by KBryan** [comment]
Could you please provide a code sample that you are using?

**Comment by vmel47** [comment]
This is an example from your library.

In this case I removed my private and public addresses from example.

public class Web3PrivateKeySendTransactionExample : MonoBehaviour
{
    async public void OnSendTransaction()
    {
        // private key of account
        string privateKey = ""; //your private key
        // set chain: ethereum, moonbeam, polygon etc
        string chain = "pulsechain";
        // set network mainnet, testnet
        string network = "testnet";
        // account of player        
        string account = Web3PrivateKey.Address(privateKey);
        // account to send to
        string to = ""; //your public key
        // value in wei
        string value = "1000000000000000000";
        // optional rpc url
        string rpc = "https://rpc.v2b.testnet.pulsechain.com";
        string chainId = "941";
        string gasPrice = "100000";
        string data = "";
        string gasLimit = "21000";
        string transaction = await EVM.CreateTransaction(chain, network, account, to, value, data, gasPrice, gasLimit, rpc);
        string signature = Web3PrivateKey.SignTransaction(privateKey, transaction, chainId);
        string response = await EVM.BroadcastTransaction(chain, network, account, to, value, data, signature, gasPrice, gasLimit, rpc);
        print(response);
        Application.OpenURL("https://scan.v2b.testnet.pulsechain.com/tx/" + response);
    }
}

**Comment by sneakzttv** [comment]
your solidity code please

I'd like to check if you are running your event and transfer calls correctly.

**Comment by sneakzttv** [comment]
Closing as it has been open for months. Will reattend if the issue appears again.
