### ISSUE TITLE
Installing web3 plugin to Unity results in series of Newtonsoft issues

### ISSUE THREAD

**Issue by niftybowling** [ChainSafe/web3.unity#144]
**Describe the bug**
Brand-new Unity project in 2020 results in spewing Newtonsoft errors

**To Reproduce**
1. Visit Chainsafe github
2. Install the web3 unity package in 2020
3. Immediately spamming Newtonsoft errors

**Expected behavior**
No Newtonsoft errors

**Screenshots**
Attached

**Additional context**
I do not like Newtonsoft, prefer no third-party code and has caused past problems. Why is it required?
![Screen Shot 2022-05-12 at 9 11 30 AM](https://user-images.githubusercontent.com/90650408/168121375-e5c8afb0-b392-4c14-9980-f06a7c91b13c.png)

**Comment by KBryan** [comment]
You are missing the Newton Soft plugin. It's a dependency on the SDK. Please take a look at our docs for the download link.
https://docs.gaming.chainsafe.io/#installing-sdk

**Comment by Orion9909** [comment]
JSON .NET For Unity is no longer available. Having same issues right now.

**Comment by KBryan** [comment]
Windows -> Package Manager -> Add package from git Url. Then add this. 
com.unity.nuget.newtonsoft-json@3.0.2

**Comment by Orion9909** [comment]
Thank you
