### ISSUE TITLE
ArgumentNullException: Array cannot be null.

### ISSUE THREAD

**Issue by rw0xy** [ChainSafe/web3.unity#145]
Hi, I have the following issue,

"ArgumentNullException: Array cannot be null."

I don't understand the reason for it. since I tried adding other Nfts addresses from the same Network and it worked correctly.

But when I add the following address in the code I get that warning.
address: 0x16fea4cb485cc0470a211567932b9301b5ff0c1c

![TestNft - SampleScene - Windows, Mac, Linux - Unity 2021 3 2f1 Personal _DX11_ 13_5_2022 15_27_34](https://user-images.githubusercontent.com/48665362/168345496-7c5d343f-2bc5-4b22-819a-fae5ea4889c4.png)

**Comment by KBryan** [comment]
You can refer to our docs if you are still having an issue.

https://docs.gaming.chainsafe.io/tutorial
