### ISSUE TITLE
sent Boolean variable is always true

### ISSUE THREAD

**Issue by reguig-abdelilah** [ChainSafe/web3.unity#147]
**Describe the bug**
Trying to send transactions to smart contract functions that accept Boolean variable, but the Boolean variable sent is always of a value of true

**To Reproduce**
Steps to reproduce the behavior via the code:
1. Prepare the arguments
```
string[] obj = { targetSmartContract.contract, price.ToString(), tokenId.ToString(), "false", "false" };
string args = JsonConvert.SerializeObject(obj);
```
2. Create Contract Data
`string data = await EVM.CreateContractData(abi, method, args);`
3. Send the transaction
```
string response = await Web3Wallet.SendTransaction(chainId, SmartContractsInfos.Instance.landplots_sectors_trading_SC.contract,
            value, data, gasLimit, gasPrice);
```

**Expected behavior**
Doing this the input should include 2 Boolean variables of value false, but the final stored values on the smart contract are always true.

**Additional context**
Calling the same function with the same arguments from within the remix editor works fine.

**Comment by KBryan** [comment]
Sorry for the late response. Could you supply the contract you are using so that we can test this on our end?
