### ISSUE TITLE
Mobile transaction does not come up

### ISSUE THREAD

**Issue by JespervdWeideSWC** [ChainSafe/web3.unity#150]
**Describe the bug**
When we do a transaction on mobile on metamask it won't pop up the transaction sign popup.

**To Reproduce**
1. Go to Web3GL.SendContract function
2. Call it through webgl build via metamask app
3. It wont show any error but it also does not popup the transaction verification popup

**Expected behavior**
 Show the the transaction verification popup

**Screenshots**

**Desktop (please complete the following information):**
 - OS: IOS and Android
 - Browser Metamask dapp browser
 - Version [v1.2.9](https://github.com/ChainSafe/web3.unity/releases/tag/v1.2.9)

**Smartphone (please complete the following information):**
 - Device: ALL Mobile devices

**Additional context**
It worked before but does not work now

**Comment by KBryan** [comment]
I'm not sure I fully understand your question. Are you using WebGL builds on a mobile browser?
