### ISSUE TITLE
Web3Wallet.Sign does not appear to respect currently selected account in Metamask

### ISSUE THREAD

**Issue by longda** [ChainSafe/web3.unity#152]
**Describe the bug**
Web3Wallet.Sign does not appear to respect currently selected account in Metamask and shows a "scare warning" to users.

**To Reproduce**
1. In Metamask, have two or more accounts.
2. Select the non-zero index account (e.g. not the primary account - I use my test account in my screenshots)
3. Call Web3Wallet.Sign from Unity code on desktop/ide - should pop the browser w/ a Signature Request window for Metamask
4. Observe that the zero index account is being used and not the currently selected non-zero index account.
5. Note the "circle i" logo which has a hover help text that reads: "Is this the correct account? It's different from the currently selected account in your wallet"

**Expected behavior**
The currently selected account should be used for the signature request.

**Screenshots**
Multiple accounts in Metamask:
<img width="184" alt="image" src="https://user-images.githubusercontent.com/320665/170593701-ae214f22-da59-42ac-984e-3f9d56a6b926.png">
Currently selected account is the second account "Account for Testing":
<img width="182" alt="image" src="https://user-images.githubusercontent.com/320665/170593675-f806efca-8cc3-4f39-8ac1-efec4cc90c65.png">
Signature Request window is shown with Account 1 (not "Account for Testing") and there is no way to switch accounts from this Metamask window.
<img width="247" alt="image" src="https://user-images.githubusercontent.com/320665/170593757-16711d82-eb91-4de6-8208-40e91fb45879.png">

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro, 19044.1706
 - Browser: Chrome, Version 101.0.4951.67 (Official Build) (64-bit), 
 - Metamask: 10.14.6  

**Smartphone (please complete the following information):**
 - N/A

**Additional context**
From Chainsafe Discord discussion:
https://discord.com/channels/593655374469660673/845686120292679761/979206955962875914

is there something like https://chainsafe.github.io/game-web3wallet/?action=connect that let's you connect your current account (this is desktop but guessing we'll face a similar issue on mobile 

- i have multiple metamask accounts and it keeps selecting the first one - the yellow circle "i" icon next to Account 1 has a hover message which reads "Is this the correct account? It's different from the currently selected account in your wallet"

**Comment by KBryan** [comment]
Thank you for posting. Sorry for the late response. We look into this and get back to you on a resolution.
