### ISSUE TITLE
EntryPointNotFoundException when send a smart contract

### ISSUE THREAD

**Issue by AndRockSYS** [ChainSafe/web3.unity#153]
Hello! The problem appeard when i tried to send my own smart contract. After that i tried to reinstall web3.unity package and Newtonsoft form NuGet but i still have this problem. Then i tried to use the contract which is provided by author from docs and i still have this mistake. I also checked many times my abi, contract address etc and it still appear.

The full exception:
EntryPointNotFoundException: SetContractResponse assembly:<unknown assembly> type:<unknown type> member:(null)
Web3GL.SendContract (System.String _method, System.String _abi, System.String _contract, System.String _args, System.String _value, System.String _gasLimit, System.String _gasPrice) (at Assets/Web3Unity/Scripts/Library/WebGL/Web3GL.cs:45)
WebGLSendContractExample.OnSendContract () (at Assets/Web3Unity/Scripts/Prefabs/WebGL/WebGLSendContractExample.cs:26)
UnityEngine.Debug:LogException(Exception, Object)
<OnSendContract>d__0:MoveNext() (at Assets/Web3Unity/Scripts/Prefabs/WebGL/WebGLSendContractExample.cs:29)
System.Runtime.CompilerServices.AsyncVoidMethodBuilder:Start(<OnSendContract>d__0&)
WebGLSendContractExample:OnSendContract()
UnityEngine.EventSystems.EventSystem:Update() (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/EventSystem.cs:501)

**Comment by KBryan** [comment]
Are you building out a WebGL solution using the Web3Template? Can you also provide the script you are using for more context?
