### ISSUE TITLE
NFTs not showing.All ERC 721  

### ISSUE THREAD

**Issue by nikki-tyagi** [ChainSafe/web3.unity#155]
Wallet address:- 0xB5bB13e2fadaa73eDee4f8A036a84f04ef153a69
This is my wallet address which have 3 total NFTs checked from Owner of NFT but there is some issue in EVM.AllERC 721 method which is showing only total 2 NFTs in my wallet.
NFT which is not represent in AllERC have contract 0x7fA2e94893Ce8d64Ac4885A47ec01A66468d3C65
![image_2022_06_01T05_30_59_343Z](https://user-images.githubusercontent.com/76118100/173495267-8f4468dc-9c27-4f8a-9f9c-3a8de051fc27.png)

**Comment by sneakzttv** [comment]
how are you sending that call off in the script?

**Comment by nikki-tyagi** [comment]
> 
![image](https://user-images.githubusercontent.com/76118100/173529238-75041825-8931-48ca-bd2e-bdeb30885823.png)

Thats my code which i am using to fetch all NFTs related to that wallet .

**Comment by sneakzttv** [comment]
what is skip for? usually arrays return counting as 0,1,2,3 etc are you skipping 0?

**Comment by nikki-tyagi** [comment]
> what is skip for? usually arrays return counting as 0,1,2,3. 0 = 1, 1 = 2 etc etc are you skipping 0?

![image](https://user-images.githubusercontent.com/76118100/173549739-d77b9030-f3a1-431c-b021-39491b1e8614.png)
i haven't used skip adn first varliable here . They are commented  from method .

**Comment by sneakzttv** [comment]
ah my mistake, it uses it in both 721 and 115 methods, perhaps it needs it on second thought ill see what kwame thinks!
![image](https://user-images.githubusercontent.com/57473220/173551698-7f584e36-2f84-484b-b292-5d6016bfcf17.png)

**Comment by nikki-tyagi** [comment]
> ah my mistake, it uses it in both 721 and 115 methods, perhaps it needs it on second thought ill see what kwame thinks! i'll also try to duplicate this and see what i come up with! ![image](https://user-images.githubusercontent.com/57473220/173551698-7f584e36-2f84-484b-b292-5d6016bfcf17.png)

Do you get any solution?

**Comment by sneakzttv** [comment]
running through it now for you, sorry i had a lot of meetings today

**Comment by sneakzttv** [comment]
you could also try this :D
https://chainsafe.github.io/game-docs/#all-721s

**Comment by nikki-tyagi** [comment]
> 

I am not able to share NFTs by i can send you the token ids and contracts of NFTs which i am getting and in which i am getting issues.

**Comment by nikki-tyagi** [comment]
> you could also try this :D https://chainsafe.github.io/game-docs/#all-721s

![image](https://user-images.githubusercontent.com/76118100/173995166-08dec6bf-00ee-4638-a797-46724b76d91b.png)
We have used same method to fetch NFTs.

**Comment by sneakzttv** [comment]
sweet! glad it works! awesome!

**Comment by nikki-tyagi** [comment]
> sweet! glad it works! awesome!

![image](https://user-images.githubusercontent.com/76118100/174000053-019ff470-0b49-44b5-8a78-0cf3ec2cdc70.png)
It is not working sir, Still showing 2 NFTs i dont know why not showing 3rd one. According to Binance scan account have 3 NTTs
![image](https://user-images.githubusercontent.com/76118100/174000662-61884cbd-2f46-484d-ab0d-f2107619716a.png)

**Comment by sneakzttv** [comment]
ok i can see that they all erc721s so that's good, i'll have to get Kwame to investigate this one further, that's an odd one :|

**Comment by sneakzttv** [comment]
ok so we think it may be related to the CAs and URIs clashing if you entered them at different times. Can you please try again with new CAs and a new URI. I'm sorry for making you run around a lot it's just we have to check everything when something unusual happens.

**Comment by nikki-tyagi** [comment]
> 

No problem sir,
What do you mean here by CAs , is it something related to minting part or some thing else.
Yes we can see 3 at BSC also we can see 3 NFTs in Metamask application.
Is it someting like crashed NFTs(Because i don't understood exact reason).

**Comment by sneakzttv** [comment]
contract addresses

**Comment by sneakzttv** [comment]
build all 3 of them again so they are new please and give it a new uri and try again

**Comment by sneakzttv** [comment]
also check that the balanceof function in all 3 cas is set to public

**Comment by nikki-tyagi** [comment]
> also check that the balanceof function in all 3 cas is set to public

Actually problem is that balance is showing in balanceof api . but we are not getting it in AllERC api

**Comment by sneakzttv** [comment]
are you able to call balance of separately for all 3 for now as we can see that works as a workaround.

**Comment by nikki-tyagi** [comment]
> are you able to call balance of separately for all 3 for now as we can see that works as a workaround.

Yes i can fetch balance of all three NFTs separately. You can try you have contract address also token I'd too.

**Comment by KBryan** [comment]
You need to iterate over a collection of the list and display your object. In your example, you are calling only the 0 index. Try using a foreach over the collection.
