### ISSUE TITLE
EVM.TxStatus always return the "pending" status.

### ISSUE THREAD

**Issue by huynhApproi** [ChainSafe/web3.unity#156]
**Describe the bug**
Function **EVM.TxStatus** always return the "pending".

**To Reproduce**
1. Create new scene in Unity
2. Drag "TxStatus.prefab" (Assets/Web3Unity/Prefabs/EVM/TxStatus.prefab) to scene.
3. Open TxStatus.cs (Assets/Web3Unity/Scripts/Prefabs/EVM/TxStatus.cs)
4. Change the parameters
string chain = "binance";
string network = "testnet";
string transaction = "0x0417de8ab97f9e12ec5164363a26c95e1daa5d5fff7919810fc30fa2d6e941a1";
5. Click Play button on Edior and check log.

**Expected behavior**
It need show "success" on Console.

**Screenshots**
![image](https://user-images.githubusercontent.com/104558591/173509551-e53e91dd-be44-4a27-9062-43606aecf57b.png).
![image](https://user-images.githubusercontent.com/104558591/173509592-42d3d028-2e07-4271-b94f-0a25852ab382.png)
![image](https://user-images.githubusercontent.com/104558591/173509619-4cfd83ca-f45a-46ef-a997-c24d4956bd21.png)

**Unity ver 2020.3.4f1:**
Chainsafe sdk: ver 1.3.0

**Additional context**
Test on.
Tx: 0x0417de8ab97f9e12ec5164363a26c95e1daa5d5fff7919810fc30fa2d6e941a1
Scan: https://testnet.bscscan.com/tx/0x0417de8ab97f9e12ec5164363a26c95e1daa5d5fff7919810fc30fa2d6e941a1

**Comment by sneakzttv** [comment]
i'll look at this now for you and see if i can produce the same result!

**Comment by KBryan** [comment]
This seems to be an issue with BSC as we have tested this on other EVM-compatible chains and haven't seen this issue.  That being said. We can see if there is a way to have this work. Although, it's a known issue.
