### ISSUE TITLE
Incorrect Wallet Address Returned from Signing

### ISSUE THREAD

**Issue by brian-kryptomon** [ChainSafe/web3.unity#157]
**Describe the bug**
I am using the chainsafe library on Unity to get the wallet address of a player via a signing request - player clicks copy in metamask and then goes back to the app and a wallet address comes in that is different than the one they signed for which is pretty concerning. Its not just a single user as we rolled our game out to 500 mobile users yesterday for beta and I'd say a good 20-30 of them had the issue.

**To Reproduce**
Create a signing request from a unity mobile app on Android, player signs and copies to clipboard, goes back into game and the wrong address shows up.

**Expected behavior**
Correct address should show up.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Various Android
 - OS: Android 10,11,12
 - Browser N/A - Unity App

**Additional context**

**Comment by sneakzttv** [comment]
are you resetting the wallet address to null before they sign in? it may be holding another wallet they used if they were using a diff acc for test it could be clashing there is my best bet.

**Comment by KBryan** [comment]
Thank you for posting this issue. Our team will be looking into this and report back to you.

**Comment by brian-kryptomon** [comment]
@sneakzttv No I've confirmed users who have only a single metamask account loaded in their wallet have experienced the issue as well. I'll try and grab more info - next time a user reports it I'll grab their wallet address and the one that the game picked up and see if maybe theres something related somehow or if the wallet being picked up is even a valid wallet.

**Comment by brian-kryptomon** [comment]
@KBryan Is there anything I can do to assist? This is a pretty bad bug as I have users who are essentially registering in our game with the wrong wallet addresses which as you can imagine is a huge issue for rewards and other features.

**Comment by sneakzttv** [comment]
Kwame's out of the office today, apologies.

**Comment by sneakzttv** [comment]
sidenote, you could also roll the sdk version back to what was previously working for you, hopefully that may help.

**Comment by KBryan** [comment]
We have been added to the beta for MetaMask. I have done some loose testing and am currently in their private beta. I'm thinking this will solve your current issue. Although, will not be back in the office until Monday. You can take a look at it and give it a go. There is a Unity package you can download and install with connect/sign/send transaction functionality. 

https://c0f4f41c-2f55-4863-921b-sdk-docs.github.io/guide/metamask-sdk-intro.html 
https://c0f4f41c-2f55-4863-921b-sdk-docs.github.io/guide/metamask-sdk-gaming.html

**Comment by brian-kryptomon** [comment]
@KBryan Does this replace the chainsafe implementation? We basically just use their SDK for our integration? This would essentially limit us to only devices using Metamask long term vs. possibly chainsafe supporting multiple. Are you planning on dropping the chainsafe support for Unity or are these all somehow related?

**Comment by KBryan** [comment]
I'm not sure what you mean by our integration. Do you have your own binding you are using for mobile or using the Web3Wallet integration provided by the SDK?

**Comment by brian-kryptomon** [comment]
@KBryan So we downloaded the chainsafe for Unity library. https://assetstore.unity.com/packages/tools/game-toolkits/web3-chainsafe-gaming-sdk-216507  We use pretty basic code to prompt for the signing but a large percentage of the time the data returned back from the call has the wrong wallet address.

This is our code:
```
            int timestamp = (int)(DateTime.UtcNow.Subtract(new DateTime(1970, 1, 1))).TotalSeconds;
            int expirationTime = timestamp + 60;
            string message = expirationTime.ToString();
            string signature = await Web3Wallet.Sign(message);
            string wallet = await EVM.Verify(message, signature);
            int now = (int)(DateTime.UtcNow.Subtract(new DateTime(1970, 1, 1))).TotalSeconds;
            if (wallet.Length == 42 && expirationTime >= now)
            {
                return wallet;
            }
```
Its pretty standard but like I said a good percentage of the time the wallet address we get back is wrong which is really scary. 

I was confused by you pointing me to the new Metamask SDK for gaming since its not your library.  I did see the docs on the new Metamask unity SDK where it lets you scan the QR code - this does look interesting but doesn't this replace just creating deep link transactions using Chainsafe?

**Comment by brian-kryptomon** [comment]
@sneakzttv this is our first time using it with our game so I'm not sure if or what to rollback to.

**Comment by sneakzttv** [comment]
I meant to whatever worked prior, if you didn't change anything with the default sdk files then you're fine. Just quickly, are these all coming from mobile users by any chance?

**Comment by brian-kryptomon** [comment]
> I meant to whatever worked prior, if you didn't change anything with the default sdk files then you're fine. Just quickly, are these all coming from mobile users by any chance? Do you know if desktop users are experiencing this?

We use a different mechanic on our Web version of the game - we swapped to use Chainsafe on mobile platforms.

**Comment by sneakzttv** [comment]
ok so it's just mobile users, interesting, someone else is having this issue too, we'll escalate this for you and see if we can't find a solution. Do you know what wallets are succeeding with the correct address and which are failing?

**Comment by brian-kryptomon** [comment]
@KBryan any thoughts on this? I'm just not entirely sure how the code is returning the wrong wallet address on a signing request.

**Comment by KBryan** [comment]
This issue has been fixed. A new version of the SDK 1.3.1 has been released in the releases section. Please give it a test.
https://github.com/ChainSafe/web3.unity/releases/tag/v1.3.1
