### ISSUE TITLE
Transfer 1155 webgl prefab error - Pointer_stringify is not defined at _SendContractJs

### ISSUE THREAD

**Issue by aj2620** [ChainSafe/web3.unity#159]
I'm using the transfer1155 prefab for webgl. After building the project and when i click transfer button the error " Pointer_stringify is not defined at _ SendContractJS " shows up any fix ..??

**Comment by sneakzttv** [comment]
it means an input parameter is incorrect

**Comment by aj2620** [comment]
> it means an input parameter is incorrect

i dont think i made a mistake  I used the webgl transfer 1155 prefab and have all the fields correct

**Comment by KBryan** [comment]
Are you building your project out and using the WebGLTemplate provided. This error usually refers to either. Trying to build the project in the editor or not using the WebGLTemplate that binds Web3 to a WebGL project.
