### ISSUE TITLE
[V2] Decentralization: Sign & Send Transactions

### ISSUE THREAD

**Issue by FSM1** [ChainSafe/web3.unity#168]
@LuaxY commented on [Mon Jun 20 2022](https://github.com/ChainSafe/game-pm/issues/371)

Improve EVM client in the SDK to perform the following actions:

- [x] Signer Base
- [x] Web3Signer (MetaMask/WalletConnect?)
- [x] Sign data
- [ ] Verify data
- [ ] Sign transaction
- [x] Send transaction
- [x] Transaction status

**Comment by KBryan** [comment]
Here's the repo I'll be working on from now on. It's currently private until further notice

https://github.com/ChainSafe/Gaming_SDK_V2

**Comment by FSM1** [comment]
This is completed, except for Private Key (in game) verification and signing transactions.
