### ISSUE TITLE
Try to use network Brise with file : Web3PrivateKeySend20Example

### ISSUE THREAD

**Issue by LoStewePupazzi** [ChainSafe/web3.unity#169]
**File Web3PrivateKeySend20Example**

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Newtonsoft.Json;
using TMPro;

public class Web3PrivateKeySend20Example : MonoBehaviour
{
    public TextMeshProUGUI text;
     private GameManager gm;

     void Start()
    {
        text = gameObject.GetComponent<TextMeshProUGUI>();
        gm = GameManager.GetInstance();
    }
    async public void OnSend20()
    {
        
        
        // private key of account
        string privateKey = "My private key here";
        // set chain: ethereum, moonbeam, polygon etc
        string chain ="64668" ;
        // set network mainnet, testnet
        string network = "testnet o rpc?";
        // smart contract method to call
        string method = "transferERC20";
        // account of player 
        string account = Web3PrivateKey.Address(privateKey);
        // smart contract address: https://rinkeby.etherscan.io/address/0xc7ad46e0b8a400bb3c915120d284aafba8fc4735
        string contract = "0x1Ed72B0BBD478A767962D40AB443ae7Fd6B82c54";
        // account to send to
        string toAccount =  "0x8a86fC9F6bc5a3B9ef213568d8A15d6aD4016A32";//PlayerPrefs.GetString("Account");
        // amount of erc20 tokens to send. usually 18 decimals
        string amount ="100000"+ "000000000000000000"; //$"{gm.points.ToString()}"+ "000000000000000000";
        // amount of wei to send
        string value = "0";
        // abi to interact with contract
        string abi = "[{\"inputs\":[{\"internalType\":\"contract ERC20\",\"name\":\"token\",\"type\":\"address\"}],\"stateMutability\":\"nonpayable\",\"type\":\"constructor\"},{\"anonymous\":false,\"inputs\":[{\"indexed\":true,\"internalType\":\"address\",\"name\":\"owner\",\"type\":\"address\"},{\"indexed\":true,\"internalType\":\"address\",\"name\":\"spender\",\"type\":\"address\"},{\"indexed\":false,\"internalType\":\"uint256\",\"name\":\"value\",\"type\":\"uint256\"}],\"name\":\"Approval\",\"type\":\"event\"},{\"anonymous\":false,\"inputs\":[{\"indexed\":true,\"internalType\":\"address\",\"name\":\"from\",\"type\":\"address\"},{\"indexed\":true,\"internalType\":\"address\",\"name\":\"to\",\"type\":\"address\"},{\"indexed\":false,\"internalType\":\"uint256\",\"name\":\"value\",\"type\":\"uint256\"}],\"name\":\"Transfer\",\"type\":\"event\"},{\"anonymous\":false,\"inputs\":[{\"indexed\":false,\"internalType\":\"address\",\"name\":\"_from\",\"type\":\"address\"},{\"indexed\":false,\"internalType\":\"uint256\",\"name\":\"_amount\",\"type\":\"uint256\"}],\"name\":\"TransferReceived\",\"type\":\"event\"},{\"anonymous\":false,\"inputs\":[{\"indexed\":false,\"internalType\":\"address\",\"name\":\"_from\",\"type\":\"address\"},{\"indexed\":false,\"internalType\":\"address\",\"name\":\"_destAddr\",\"type\":\"address\"},{\"indexed\":false,\"internalType\":\"uint256\",\"name\":\"_amount\",\"type\":\"uint256\"}],\"name\":\"TransferSent\",\"type\":\"event\"},{\"inputs\":[{\"internalType\":\"address\",\"name\":\"owner\",\"type\":\"address\"},{\"internalType\":\"address\",\"name\":\"delegate\",\"type\":\"address\"}],\"name\":\"allowance\",\"outputs\":[{\"internalType\":\"uint256\",\"name\":\"\",\"type\":\"uint256\"}],\"stateMutability\":\"view\",\"type\":\"function\"},{\"inputs\":[{\"internalType\":\"address\",\"name\":\"delegate\",\"type\":\"address\"},{\"internalType\":\"uint256\",\"name\":\"numTokens\",\"type\":\"uint256\"}],\"name\":\"approve\",\"outputs\":[{\"internalType\":\"bool\",\"name\":\"\",\"type\":\"bool\"}],\"stateMutability\":\"nonpayable\",\"type\":\"function\"},{\"inputs\":[],\"name\":\"balance\",\"outputs\":[{\"internalType\":\"uint256\",\"name\":\"\",\"type\":\"uint256\"}],\"stateMutability\":\"view\",\"type\":\"function\"},{\"inputs\":[{\"internalType\":\"address\",\"name\":\"tokenOwner\",\"type\":\"address\"}],\"name\":\"balanceOf\",\"outputs\":[{\"internalType\":\"uint256\",\"name\":\"\",\"type\":\"uint256\"}],\"stateMutability\":\"view\",\"type\":\"function\"},{\"inputs\":[],\"name\":\"decimals\",\"outputs\":[{\"internalType\":\"uint8\",\"name\":\"\",\"type\":\"uint8\"}],\"stateMutability\":\"view\",\"type\":\"function\"},{\"inputs\":[],\"name\":\"name\",\"outputs\":[{\"internalType\":\"string\",\"name\":\"\",\"type\":\"string\"}],\"stateMutability\":\"view\",\"type\":\"function\"},{\"inputs\":[],\"name\":\"owner\",\"outputs\":[{\"internalType\":\"address\",\"name\":\"\",\"type\":\"address\"}],\"stateMutability\":\"view\",\"type\":\"function\"},{\"inputs\":[{\"internalType\":\"uint256\",\"name\":\"j\",\"type\":\"uint256\"}],\"name\":\"sendETHtoContract\",\"outputs\":[],\"stateMutability\":\"payable\",\"type\":\"function\"},{\"inputs\":[],\"name\":\"symbol\",\"outputs\":[{\"internalType\":\"string\",\"name\":\"\",\"type\":\"string\"}],\"stateMutability\":\"view\",\"type\":\"function\"},{\"inputs\":[],\"name\":\"totalSupply\",\"outputs\":[{\"internalType\":\"uint256\",\"name\":\"\",\"type\":\"uint256\"}],\"stateMutability\":\"view\",\"type\":\"function\"},{\"inputs\":[{\"internalType\":\"address\",\"name\":\"receiver\",\"type\":\"address\"},{\"internalType\":\"uint256\",\"name\":\"numTokens\",\"type\":\"uint256\"}],\"name\":\"transfer\",\"outputs\":[{\"internalType\":\"bool\",\"name\":\"\",\"type\":\"bool\"}],\"stateMutability\":\"nonpayable\",\"type\":\"function\"},{\"inputs\":[{\"internalType\":\"address\",\"name\":\"to\",\"type\":\"address\"},{\"internalType\":\"uint256\",\"name\":\"amount\",\"type\":\"uint256\"}],\"name\":\"transferERC20\",\"outputs\":[],\"stateMutability\":\"nonpayable\",\"type\":\"function\"},{\"inputs\":[{\"internalType\":\"address\",\"name\":\"owner\",\"type\":\"address\"},{\"internalType\":\"address\",\"name\":\"buyer\",\"type\":\"address\"},{\"internalType\":\"uint256\",\"name\":\"numTokens\",\"type\":\"uint256\"}],\"name\":\"transferFrom\",\"outputs\":[{\"internalType\":\"bool\",\"name\":\"\",\"type\":\"bool\"}],\"stateMutability\":\"nonpayable\",\"type\":\"function\"},{\"inputs\":[{\"internalType\":\"uint256\",\"name\":\"amount\",\"type\":\"uint256\"},{\"internalType\":\"address payable\",\"name\":\"destAddr\",\"type\":\"address\"}],\"name\":\"withdraw\",\"outputs\":[],\"stateMutability\":\"nonpayable\",\"type\":\"function\"},{\"stateMutability\":\"payable\",\"type\":\"receive\"}]";
        // optional rpc url
        string rpc = "https://testnet-rpc.brisescan.com";

        string[] obj = { toAccount, amount };
        string args = JsonConvert.SerializeObject(obj);
        string chainId = await EVM.ChainId(chain, rpc);
        string gasPrice = await EVM.GasPrice(chain, rpc);
        string data = await EVM.CreateContractData(abi, method, args);
        string gasLimit = "75000";
        string transaction = await EVM.CreateTransaction(chain, account, contract, value, data, gasPrice, gasLimit, rpc);
        string signature = Web3PrivateKey.SignTransaction(privateKey, transaction, chainId);
        string response = await EVM.BroadcastTransaction(chain, network, account, contract, value, data, signature, gasPrice, gasLimit, rpc);
        print(response);
        Application.OpenURL("https://testnet-explorer.brisescan.com/tx/" + response);
    }
}

**Error on unity inspector element :**
for ChainID,GasPrice,CreateTransaction:  {"response":"could not detect network (event=\"noNetwork\", code=NETWORK_ERROR, version=providers/5.6.8)"}

**In unity the error is :** 

FormatException: Input string was not in a correct format.
System.Number.StringToNumber (System.String str, System.Globalization.NumberStyles options, System.Number+NumberBuffer& number, System.Globalization.NumberFormatInfo info, System.Boolean parseDecimal) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Number.ParseInt32 (System.String s, System.Globalization.NumberStyles style, System.Globalization.NumberFormatInfo info) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Int32.Parse (System.String s, System.IFormatProvider provider) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Convert.ToInt32 (System.String value) (at <695d1cc93cca45069c528c15c9fdd749>:0)
Web3PrivateKey.SignTransaction (System.String _privateKey, System.String _transaction, System.String _chainId) (at Assets/Web3Unity2020/Scripts/Library/Web3PrivateKey.cs:16)
Web3PrivateKeySend20Example+<OnSend20>d3.MoveNext () (at Assets/Web3Unity2020/Scripts/Prefabs/PrivateKey/Web3PrivateKeySend20Example.cs:51)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b6_0 (System.Object state) (at <695d1cc93cca45069c528c15c9fdd749>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <82c503977c5347cf82f44677f633fcf6>:0)
UnityEngine.UnitySynchronizationContext:ExecuteTasks()

**Comment by LoStewePupazzi** [comment]
> Are there any examples of a dApp that uses this chain? I'm trying to find information on this token on their explorer and there aren't any tokens or transfer history I can find. tbh. I have never used this chain before. Have you tried transferring tokens with the transfer20 examples? I also wasn't able to get any test tokens from their faucet.

**This is the test of the transaction with the TransferErc20 method on their testnet!**
https://testnet-explorer.brisescan.com/tx/0xa3129b14d9d52096dec78827d6ff6c1f3e402c1237d6c694cba58ce963e279d3/token-transfers

**this is their faucet** 

https://faucet.brisescan.com/

**this is one of project on brise :**
http://app.evofinance.in/

**Comment by KBryan** [comment]
I tried their faucet and it says exceeded the daily limit. Never used this chain.  I would try using the prefabs and see if they work.  Also, are you able to use other EVMs i.e Eth/Poly/BSC?

**Comment by LoStewePupazzi** [comment]
**Contract PupazziTest**

// File: PupazziTest.sol


pragma solidity ^0.8.0;

abstract contract ERC20 {

    function totalSupply() virtual external view returns (uint256);
    function balanceOf(address account) virtual external view returns (uint256);
    function allowance(address owner, address spender) virtual external view returns (uint256);

    function transfer(address recipient, uint256 amount) virtual external returns (bool);
    function approve(address spender, uint256 amount) virtual external returns (bool);
    function transferFrom(address sender, address recipient, uint256 amount) virtual external returns (bool);


    event Transfer(address indexed from, address indexed to, uint256 value);
    event Approval(address indexed owner, address indexed spender, uint256 value);
}


contract PupazziTest is ERC20 {

    string public constant name = "PupazziTest";
    string public constant symbol = "PPST";
    uint8 public constant decimals = 18;
    address public owner;
    uint256 public balance;

    address constant AuthWallet = 0x0f046f46f8bfb3ce5a7a047F5e559A5b1c9710d4; // constant auth wallet to prevent changing
    
    event TransferReceived(address _from, uint _amount);
    event TransferSent(address _from, address _destAddr, uint _amount);


    mapping(address => uint256) balances;

    mapping(address => mapping (address => uint256)) allowed;

    uint256 totalSupply_ = 1000000000000 ether;


   constructor() {
    balances[msg.sender] = totalSupply_;
     owner = msg.sender;
    }

    function totalSupply() public override view returns (uint256) {
    return totalSupply_;
    }

    function balanceOf(address tokenOwner) public override view returns (uint256) {
        return balances[tokenOwner];
    }

    function transfer(address receiver, uint256 numTokens) public override returns (bool) {
        require(numTokens <= balances[msg.sender]);
        balances[msg.sender] = balances[msg.sender]-numTokens;
        balances[receiver] = balances[receiver]+numTokens;
        emit Transfer(msg.sender, receiver, numTokens);
        return true;
    }

    function approve(address delegate, uint256 numTokens) public override returns (bool) {
        allowed[msg.sender][delegate] = numTokens;
        emit Approval(msg.sender, delegate, numTokens);
        return true;
    }

    function allowance(address owner, address delegate) public override view returns (uint) {
        return allowed[owner][delegate];
    }

    function transferFrom(address owner, address buyer, uint256 numTokens) public override returns (bool) {
        require(numTokens <= balances[owner]);
        require(numTokens <= allowed[owner][msg.sender]);
        balances[owner] = balances[owner]-numTokens;
        allowed[owner][msg.sender] = allowed[owner][msg.sender]-numTokens;
        balances[buyer] = balances[buyer]+numTokens;
        emit Transfer(owner, buyer, numTokens);
        return true;
    } 
}



Contract : PupazziTestFunctions


// File: /PupazziTest.sol


pragma solidity ^0.8.0;

abstract contract ERC20 {

    function totalSupply() virtual external view returns (uint256);
    function balanceOf(address account) virtual external view returns (uint256);
    function allowance(address owner, address spender) virtual external view returns (uint256);

    function transfer(address recipient, uint256 amount) virtual external returns (bool);
    function approve(address spender, uint256 amount) virtual external returns (bool);
    function transferFrom(address sender, address recipient, uint256 amount) virtual external returns (bool);


    event Transfer(address indexed from, address indexed to, uint256 value);
    event Approval(address indexed owner, address indexed spender, uint256 value);
}


contract PupazziTest is ERC20 {

    string public constant name = "PupazziTest";
    string public constant symbol = "PPST";
    uint8 public constant decimals = 18;
    address public owner;
    uint256 public balance;

    address constant AuthWallet = 0x0f046f46f8bfb3ce5a7a047F5e559A5b1c9710d4; // constant auth wallet to prevent changing
    
    event TransferReceived(address _from, uint _amount);
    event TransferSent(address _from, address _destAddr, uint _amount);


    mapping(address => uint256) balances;

    mapping(address => mapping (address => uint256)) allowed;

    uint256 totalSupply_ = 1000000000000 ether;


   constructor() {
    balances[msg.sender] = totalSupply_;
     owner = msg.sender;
    }

    function totalSupply() public override view returns (uint256) {
    return totalSupply_;
    }

    function balanceOf(address tokenOwner) public override view returns (uint256) {
        return balances[tokenOwner];
    }

    function transfer(address receiver, uint256 numTokens) public override returns (bool) {
        require(numTokens <= balances[msg.sender]);
        balances[msg.sender] = balances[msg.sender]-numTokens;
        balances[receiver] = balances[receiver]+numTokens;
        emit Transfer(msg.sender, receiver, numTokens);
        return true;
    }

    function approve(address delegate, uint256 numTokens) public override returns (bool) {
        allowed[msg.sender][delegate] = numTokens;
        emit Approval(msg.sender, delegate, numTokens);
        return true;
    }

    function allowance(address owner, address delegate) public override view returns (uint) {
        return allowed[owner][delegate];
    }

    function transferFrom(address owner, address buyer, uint256 numTokens) public override returns (bool) {
        require(numTokens <= balances[owner]);
        require(numTokens <= allowed[owner][msg.sender]);
        balances[owner] = balances[owner]-numTokens;
        allowed[owner][msg.sender] = allowed[owner][msg.sender]-numTokens;
        balances[buyer] = balances[buyer]+numTokens;
        emit Transfer(owner, buyer, numTokens);
        return true;
    } 
}

// File: Inher.sol


pragma solidity ^0.8.0;


contract PupazziTestFunctions is PupazziTest {
    
    ERC20 private _token;

    constructor(ERC20 token) {
    _token = token;
    }

    function sendETHtoContract(uint256 j) public payable {
    
    //msg.value is the amount of wei that the msg.sender sent with this transaction. 
    //If the transaction doesn't fail, then the contract now has this ETH.
    }

  receive() payable external {
        balance += msg.value;
        emit TransferReceived(msg.sender, msg.value);
    }    
    
    function withdraw(uint amount, address payable destAddr) public {
        require(msg.sender == owner, "Only owner can withdraw funds"); 
        require(amount <= balance, "Insufficient funds");
        
        destAddr.transfer(amount);
        balance -= amount;
        emit TransferSent(msg.sender, destAddr, amount);
    }
    
    function transferERC20(address to, uint256 amount) public {
        require(msg.sender == AuthWallet, "you are not the auth wallet");
        require(msg.sender == owner, "Only owner can withdraw funds"); 
        uint256 erc20balance = _token.balanceOf(address(this));
        require(amount <= erc20balance, "balance is low");
        _token.transfer(to, amount);
        emit TransferSent(msg.sender, to, amount);
    }    

}

**Comment by KBryan** [comment]
If you are looking to deploy your contract. Use something like remix online ide to deploy it.

https://remix.ethereum.org/

**Comment by LoStewePupazzi** [comment]
Yes I deployed these two contracts with remixes, Sneakz asked me to report the contracts here because he does some tests too

**Comment by sneakzttv** [comment]
yah i needed this, gonna go through it in a bit

**Comment by sneakzttv** [comment]
Doesn't like it...even if we hardcode the chain id the gas price still needs to be calculated the same way so it won't work.
![image](https://user-images.githubusercontent.com/57473220/176233269-8c350f36-f37c-4723-8e17-59599e790b2f.png)

**Comment by sneakzttv** [comment]
i tried bulk different combinations too

**Comment by LoStewePupazzi** [comment]
I send the screenshot to devs of brise blockchain

**Comment by sneakzttv** [comment]
and your next issue?

**Comment by LoStewePupazzi** [comment]
![image](https://user-images.githubusercontent.com/108241447/176244636-10a9415e-1741-4b4f-9aaf-10372ee6ef52.png)
From this file it should read me who owns the token 0, pass the string account takes the account address saved at the login screen.
But it moves me to the "You Escaped" screen as if I don't have a nft.
In reality, with the connected account, the NFT is present and from the payload I can see that it collects the correct wallet address

**Comment by sneakzttv** [comment]
yah

**Comment by sneakzttv** [comment]
how are you fetching the account at the start to get it in to player prefs, check that

**Comment by LoStewePupazzi** [comment]
![image](https://user-images.githubusercontent.com/108241447/176246730-f9e52505-f9d0-48de-a242-c9082fccf683.png)

**Comment by sneakzttv** [comment]
Debug.Log(account);

**Comment by sneakzttv** [comment]
put one after playerprefs.setaccount and then one in the script where you are calling the function

**Comment by LoStewePupazzi** [comment]
I'm building, I'll notify you as soon as it's done

**Comment by sneakzttv** [comment]
try saving it to something that isnt player prefs, a global script or something and protect that. I dont think it's saving over for you for some reason.

**Comment by LoStewePupazzi** [comment]
Oh my God and how to do it :C

**Comment by sneakzttv** [comment]
the app store has some nice plugins for unhackable playerprefs

**Comment by sneakzttv** [comment]
So create a script called global, add it to an empty object in the first scene and give it the tag "Global" in the top right. In the script declare a public string called account and in the start method just add DontDestroyOnLoad(); Now when you start the game this object will stay alive through scene changes and you can alter the acc variable. In the login script, create a reference to the empty object public GameObject GlobalManager; in start use GlobalManger = GameObject.FindWithTag("Global"); Now in the function you are using, at the start of it you can use string account = GlobalManager.GetComponent<global>().account; This will grab that variable you assigned earlier and you should be good to go for testing.

**Comment by LoStewePupazzi** [comment]
![image](https://user-images.githubusercontent.com/108241447/176256930-04144fc3-10d0-4be5-88d6-358291c1142a.png)
Correct?

**Comment by sneakzttv** [comment]
yup

**Comment by LoStewePupazzi** [comment]
![image](https://user-images.githubusercontent.com/108241447/176257080-71f6eb58-b8a3-4bb0-9363-9bb6821122f2.png)

**Comment by sneakzttv** [comment]
(gameObject)

**Comment by LoStewePupazzi** [comment]
![image](https://user-images.githubusercontent.com/108241447/176257983-42d73a9b-ce12-4fd2-9048-bb3969513eb6.png)
i create this : 

  async void Start()
    {
            GlobalManager = GameObject.FindWithTag("Global");
    }

Correct?

**Comment by sneakzttv** [comment]
yes

**Comment by LoStewePupazzi** [comment]
![image](https://user-images.githubusercontent.com/108241447/176259739-40daeccb-51f2-4f4e-b9f9-f3ca8fe222a8.png)
![image](https://user-images.githubusercontent.com/108241447/176259805-c3b7a245-bb56-42b7-9865-8266713ef79b.png)

**Comment by sneakzttv** [comment]
![image](https://user-images.githubusercontent.com/57473220/176260022-43874d92-85ef-43cb-b414-72802754daf4.png)

**Comment by sneakzttv** [comment]
with the arrow brackets then the ().account

**Comment by sneakzttv** [comment]
Yes, use the global script for testing. Later on you can get an anti cheat engine of some sort, they all have guides on how to protect their version of player prefs. For now anyway, this is solved yay. We can close this issue :D

**Comment by LoStewePupazzi** [comment]
![image](https://user-images.githubusercontent.com/108241447/176264762-67a56eed-4752-461e-ba1e-270ed52346e8.png)
Here I leave it blank rightly because access to metamask has to think about compiling it right?

Now I'm looking for some anticheat guide! thanks as always, you are fantastic!

**Comment by sneakzttv** [comment]
correct

**Comment by sneakzttv** [comment]
issue complete
