### ISSUE TITLE
Suddenly getting Returned error: unsupported block number 16969128 as a return from EVM.Call

### ISSUE THREAD

**Issue by 0xMyst-eth** [ChainSafe/web3.unity#174]
Hi,

I've been using Chainsafe SDK on Arbitrum without issue for the pasts months, using wss://arb1.arbitrum.io/ws as a RPC. 
Didn't log in for 2-3 weeks, and fired up the Unity build last nigth but was getting (400) errors. Digged into the discord and found this was likely a RPC issue. Hence I took a RPC from Infura and is using this instead which seems to work fine.

Nevertheless since then i'm getting a strange error when trying to call returning functions on my contracts: instead of sending me back the json object with the on-chain data i'm getting 

`Returned error: unsupported block number 16969128`

Does anybody know where in the SDK its supposed to return such an error? Nobody seemed to have this error before.

Many thanks !

**Comment by KBryan** [comment]
Have you tried using https instead of wss. Also, where are you passing the infura instance in your code? Can you provide a sample?

**Comment by 0xMyst-eth** [comment]
ps: things to note:
I've hardcoded this rpc url in 
- EVM.cs : `public static async Task<string> TxStatus(string _chain, string _network, string _transaction, string _rpc = "https://arbitrum-mainnet.infura.io/v3/32d8XXXXXXXXXXXXXX5d11")`

- ERC1155.cs : `public static async Task<List<BigInteger>> BalanceOfBatch(string _chain, string _network, string _contract, string[] _accounts, string[] _tokenIds, string _rpc= "https://arbitrum-mainnet.infura.io/v3/32d8XXXXXXXXXXXXXX5d11")`

- ERC1155.cs : `public static async Task<BigInteger> BalanceOf(string _chain, string _network, string _contract, string _account, string _tokenId, string _rpc= "https://arbitrum-mainnet.infura.io/v3/32d8XXXXXXXXXXXXXX5d11")`

**Comment by 0xMyst-eth** [comment]
Plot twist ✨ the Unsupported block number error only happens when using my infura personal rpc..
With https://arb1.arbitrum.io/rpc it doesnt give me the error.
Only issue is that when using that official arbitrum rpc, suddenly it doesnt get txresults correctly anymore.. transaction goes through in metamask but game gets a failure returned

**Comment by KBryan** [comment]
You should follow this guide when working with custom interactions. It looks like you are editing the class methods directly.
https://docs.gaming.chainsafe.io/custom-interactions

**Comment by KBryan** [comment]
If you are using infura and targeting arbitrum make sure you have the paid addon selected.
