### ISSUE TITLE
Consolidated in-game marketplace UI

### ISSUE THREAD

**Issue by FSM1** [ChainSafe/web3.unity#177]
@alexvotofuture commented on [Tue Jun 28 2022](https://github.com/ChainSafe/game-pm/issues/377)

Pending testing of the individual prefabs, determine if there is demand for a full ingame marketplace UI prefab

Kwame is building individual marketplace function pre-fabs that can be mixed and matched to construct a marketplace in-game.

We need to ask users to validate whether a consolidated drag-and-drop marketplace UI could be helpful to wrap these up into a single example solution. Onnce we validate we can focus on making a clean UI.

**Comment by KBryan** [comment]
@alexvotofuture I think this is an area where we could create an enhanced prefab that we could sell to our developers. I had an idea around creating prefabs that are enhancements of the ones that come preconfigured with the SDK.

**Comment by kalambet** [comment]
Not exactly relevant anymore.
