### ISSUE TITLE
All721/1155 via SDK w/ The Graph

### ISSUE THREAD

**Issue by FSM1** [ChainSafe/web3.unity#179]
@alexvotofuture commented on [Mon May 23 2022](https://github.com/ChainSafe/game-pm/issues/345)

Move all Graph queries to the SDK

---

@FSM1 commented on [Mon Jun 27 2022](https://github.com/ChainSafe/game-pm/issues/345#issuecomment-1167340589)

@alexvotofuture @KBryan Is this not a duplicate of #268 ?

**Comment by KBryan** [comment]
I used Rawrshak's SDK to get a single query in this repo. Although, it still needs a lot of work.

https://github.com/Rawrshak/Unity-SDK 
https://github.com/ChainSafe/web3.unity/tree/graph_ql_update/

**Comment by alexvotofuture** [comment]
To be cleaned up for @juans-chainsafe to test

**Comment by alexvotofuture** [comment]
@KBryan to meet with @juans-chainsafe to discuss how to test this so it's ready to merge into the v2 branch.
