### ISSUE TITLE
The referenced script on this Behaviour (Game Object 'LoginScript') is missing!

### ISSUE THREAD

**Issue by XMarn** [ChainSafe/web3.unity#18]
![Screenshot 2021-09-28 112517](https://user-images.githubusercontent.com/6577318/135070160-e294ef33-3751-497f-8f5b-0810c0303696.png)

**Comment by KBryan** [comment]
I uploaded a new package last night. I'm hoping this isn't causing an issue. Can you try downloading the web3.unitypackage and import that and see if you get the same issue.

**Comment by XMarn** [comment]
thank you for your quick response, the new upload didn't work
Error message:
Failed to import package with error: Couldn't decompress the package
![image](https://user-images.githubusercontent.com/6577318/135081302-3efe1b56-3bab-4b56-ad9a-4504c1f1e3ee.png)
the package web3.unitypackage size is 1kb.

**Comment by KBryan** [comment]
Yes, it's handle by LFS this is new to the repo. I think that may be the issue. If click on the web3.unitypackage you will see it's 6.3 mg please download that and give that a try.

**Comment by XMarn** [comment]
the issue was downloading a zip file from GitHub it's not getting all files right, I clone the project from the desktop app and It worked, but I'm back to square one
![image](https://user-images.githubusercontent.com/6577318/135084520-6f834fd8-5850-40c8-84b6-15d08160eb85.png)

**Comment by KBryan** [comment]
There were some updates last night. I tested it on my end and didn't see this. I'm going to look into this further. Sorry for the inconvenience.

**Comment by XMarn** [comment]
thank you I think I found out the issue.
