### ISSUE TITLE
not getting all the ERC721 token applied to a single contract address 

### ISSUE THREAD

**Issue by MayankGameDev** [ChainSafe/web3.unity#181]
**Describe the bug**
cannot get all erc 721 token to a single contract adress

**To Reproduce**
i was trying to fetch the details of nft of an contract address by not applying the account number but it is always showing the first 100 

 string chain = "binance";
        string network = "mainnet"; // mainnet ropsten kovan rinkeby goerli
        string account = "";
        string contract = "0x0eFE71Cc3a6481FFa1240AB27033de7d567c3F36";
        int first = 100;
        int skip = 0;
        string response = await EVM.AllErc721(chain, network, account, contract, first, 0);
        print(response);
        string rsp = await EVM.AllErc721(chain, network, account, contract, first, 100);
        print(rsp);
t

**Comment by KBryan** [comment]
What is the account you are working with?

**Comment by MayankGameDev** [comment]
actually i am leaving the account blank . i am thinking of it as suppose i have 1000 nft made and i want to get the user data who have my nft at the start of the game . so if i put the account field blank it does provide me the detials of first 100 but it doesnt provide me info on the remaining ones

**Comment by KBryan** [comment]
Okay, I see what you are saying. I'm not sure this will be an easy resolution on bsc. I'll need to get back to you on this one.

**Comment by sneakzttv** [comment]
What you need is a solidity mapping when users buy your nft, map that address to the contract array mapping and then run a get call on that in your game and do stuff from there.

Solidity Side:
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.16;
contract NFTContract{
address [] UsersThatOwnNFT1;
function BuyNFT(_address) public returns (bool)
{
UsersThatOwnNFT1.push(_wallet);
return true;
}
}

Unity Side:
string chain = "binance";
string network = "mainnet";
string method = "UsersThatOwnNFT1";
string abi = "abihere";
string contract = "0x0eFE71Cc3a6481FFa1240AB27033de7d567c3F36";
string args = "[]";
string response = await EVM.Call(chain, network, contract, abi, method, args);
print(response);

Run this call for each type of nft you need :) Happy Coding!
