### ISSUE TITLE
Mobile sign transactions + adding mobile sign to prefab with dekstop fallback

### ISSUE THREAD

**Issue by sneakzttv** [ChainSafe/web3.unity#184]
Implementing the mobile sign function into webgl prefab. I'm waiting untill i solve the transaction issues in web3js using the ethers lib. I have it connecting on sign via safepal dapp browser but id like more time to get it working with metamask mobile too. Creating an issue for later/

**Comment by KBryan** [comment]
Can this not be achieved with web3.js?

**Comment by sneakzttv** [comment]
i think it can but we need to make sure that unity is happy with it...like atm we're going through nethereum but if straight web3js works on mobile as the eth connection is already there in the dapp we can just add those in separately and we have webgl working mobile perhaps? Just gotta check what actually works, events was returning empty arrays last i checked, sign works, will see what i can do for transfer and send contract/custom calls.

**Comment by niknikolaou** [comment]
i double check today and looks that  some devices open the url with the browser even before you choose the app and then the url is not there
![305108941_5031294740307689_6217983320749693649_n](https://user-images.githubusercontent.com/83726482/188843901-510ec92a-8ba3-4be0-81cc-9e3c580e5cf1.jpg)

**Comment by KBryan** [comment]
In Web3Wallet.cs there is two URL's. If you default to "https://chainsafe.github.io/game-web3wallet/" it should fix your issue but a user would then have to manually install if they don't have MetaMask wallet installed. Try that and see if that fixes your issue.
