### ISSUE TITLE
JSON parse error trying to get NFT metadata from URI (EVM.AllErc721 )

### ISSUE THREAD

**Issue by asdrubalramirezb** [ChainSafe/web3.unity#189]
**Describe the bug**
I have been working in a project starting from the  AllErc721Example class, I use the EVM.AllErc721 method and from the response I try to get the metadata using a webRequest of the URI. The thing is that it was working fine but now it have a problem 

**To Reproduce**

1. Use WalletLogin scene
2. From the AllErc721Example class
3. Use EVM.AllErc721() method to get all the smart contrats of the User wallet adress
4. Use JsonConvert.DeserializeObject<NFTs[]> to the   NFTs[]  data object
5. Use  UnityWebRequest.Get(erc721s[i].uri); method to get the URI data from each NFT
6. Use  JsonUtility.FromJson<NFTResponse>() method to 

7. See error
The error is a "JSON parse error : Invalid value" and happen in the play  mode of UnityEditor and also in the IOS build. Bellow the line of code that trigger the error. That runs in a Unity web request to get the NFT metadata.

NFTResponse data =
                            JsonUtility.FromJson<NFTResponse>(
                                System.Text.Encoding.UTF8.GetString(webRequest.downloadHandler.data)); 

**Expected behavior**
I should happen that always the request is.

**Screenshots**
<img width="699" alt="Screenshot 2022-07-15 at 3 43 14 PM" src="https://user-images.githubusercontent.com/46140948/179369873-374583f8-070a-484c-adb9-9bc01f00c7bc.png">
<img width="1004" alt="Screenshot 2022-07-15 at 3 52 48 PM" src="https://user-images.githubusercontent.com/46140948/179369879-52a1eb53-3f2d-4ed1-930f-9b2b3deff450.png">

**Desktop (please complete the following information):**

**Additional context**

**Comment by sneakzttv** [comment]
![image](https://user-images.githubusercontent.com/57473220/179375118-25a23f3f-d20a-48c9-996f-d7aee4564c80.png)

**Comment by asdrubalramirezb** [comment]
I have been reconstructing the code  and I am getting the same JSON parse error : Invalid value" in the ERC721.OwnerOf(chain, network, contract, tokenID);  method

**Comment by sneakzttv** [comment]
ok we will look into this for you <3

**Comment by sneakzttv** [comment]
open for a month with no comment, closing as complete
