### ISSUE TITLE
Host url not working.

### ISSUE THREAD

**Issue by lhthardikviradiya** [ChainSafe/web3.unity#190]
**Describe the bug**
I was getting "ArgumentException: JSON parse error: Invalid value." on every methods call of the SDK, So i have dig dipper and found out that the host url(https://api.gaming.chainsafe.io/evm) is not running successfully, Can anyone please look into this.

**Comment by KBryan** [comment]
Thank you for your post. We have been experiencing intermittent issues recently and are looking into it.
