### ISSUE TITLE
Connecting WebGL to metawallet

### ISSUE THREAD

**Issue by MrSymms** [ChainSafe/web3.unity#192]
I'm having issues connecting my metamask to the webGL I created in unity. It uploads and plays on Stitch.io but when I press login I get a prompt with errors from the browser

I'm on a desktop and using the latest versions of both Unity and Chainsafe. 
Please help

**Comment by KBryan** [comment]
What errors are being displayed?

**Comment by cckelly** [comment]
I'm hitting this too, the error is:
```
build-webgl.loader.js:1 exception thrown: TypeError: Cannot read properties of undefined (reading 'connect'),TypeError: Cannot read properties of undefined (reading 'connect')
    at _Web3Connect (http://localhost:63027/Build/build-webgl.framework.js.gz:3:66091)
    at http://localhost:63027/Build/build-webgl.wasm.gz:wasm-function[65892]:0x10d9b71
```

I can't vet the SDK without this working.

**Comment by KBryan** [comment]
This is caused by not assigning the ChainSafeSDK WebGLTemplate to your project. Please follow this installation guide.
https://docs.gaming.chainsafe.io/installation
