### ISSUE TITLE
cannot sign on metamask in Android build by unity

### ISSUE THREAD

**Issue by bohanchan** [ChainSafe/web3.unity#194]
Use the example scene "WalletLogin" build android app by unity
press the "Login" button will jump to metamask app, but not sign in it

Empty project in unity, not exists projects

**Comment by KBryan** [comment]
Are you currently using Android 12? If so this issue was resolved with a MetaMask wallet update. What version of MetaMask are you using also.

**Comment by bohanchan** [comment]
MetaMask 5.3.0
Android 12

> Are you currently using Android 12? If so this issue was resolved with a MetaMask wallet update. What version of MetaMask are you using also.

**Comment by officialsupport-ui** [comment]
Kindly send a Dm to get your issue resolved

**Comment by sneakzttv** [comment]
try this and lmk

scrooge — 07/14/2022
So I just found a fix for Android 12.

Open Android settings , search 'default' and select "Choose Default apps' > "Choose Default apps" > Opening Links > scroll down to MetaMask and tap it > Supported Web addresses > check if links are selected or "verified/trusted" by default (most importantly metamask.app.link). If they are not, then check them.

I also noticed you need to open metamask browser before clicking the Wallet login in the game.

Could be a security issue

**Comment by sneakzttv** [comment]
closing as complete, discussed in discord with user.
