### ISSUE TITLE
Issue with EVM.Call() and msg.sender

### ISSUE THREAD

**Issue by Veuchh** [ChainSafe/web3.unity#195]
**Describe the bug**
When calling a custom smart contract using EVM.Call(), the value of msg.sender on the smart contract side is always 0x0000000000000000000000000000000000000000.
This does not happen using Web3Wallet.SendTransaction(), for instance.

**To Reproduce**
1- Setup a smart contract having a GetAccount method
```
function GetAccount() external view returns (address){
        return msg.sender;
    }
```
2- After logging in to your metamask account, use EVM.Call to call GetAccount
```
public async void GetAccount()
    {
        string response = await EVM.Call(chain, network, contract, abi, "GetAccount", "[]");
        print(response);
    }
```
This bugs happens while building for Desktop and WebGL.

**Comment by sneakzttv** [comment]
you can use this to circumvent by calling a mapping or you use tx origin 

function isPlayerJoined() returns (address) {
      return tx.origin;
   }
"With msg.sender the owner can be a contract.
With tx.origin the owner can never be a contract.
In a simple call chain A->B->C->D, inside D msg.sender will be C, and tx.origin will be A."

OR

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.16;
contract Test {

mapping (address => bool) ThePlayerJoined;

    // set with send contract at start
    function PlayerJoined() public returns (bool) {
          ThePlayerJoined[msg.sender] = true;
          return true;
    }

    // call with evm.call
    function isPlayerJoined() public view returns(bool) {
            return ThePlayerJoined[msg.sender];
    }

    // set with send contract at end
    function PlayerLeft() public returns (bool) {
          ThePlayerJoined[msg.sender] = false;
          return true;
    }
}
