### ISSUE TITLE
Bug: Web Login Template Scene / Web GL Templates

### ISSUE THREAD

**Issue by KBryan** [ChainSafe/web3.unity#20]
Bug 1: 
"LoginButton" in the WebLogin scene is only clickable in its bottom half because it is overlapped by the "Text" GameObject with the instructions. If you move the "Text" GameObject over the "LoginButton" in the hierarchy the problem is solved.
Bug 2: 
@kwame  When I replace <title>{{{ PRODUCT_NAME }}}</title> of index.html in the Web3GL-2019 template folder with the legacy <title>%UNITY_WEB_NAME%</title> the title is named correctly in the Unity 2019 WebGL build. Otherwise, {{{ PRODUCT_NAME }}} is not replaced when I build with Unity 2019 on Mac. Seems Unity 2019 is using the legacy template tags?

**Comment by leon-do** [comment]
fixed https://github.com/ChainSafe/web3.unity/releases/tag/v1.0.3
