### ISSUE TITLE
Torus Wallet - Unity WebGL working inconsistently

### ISSUE THREAD

**Issue by nftpixels** [ChainSafe/web3.unity#200]
**Describe the bug**
Torus will sometimes work when loading a compiled build with Unity WebGL. Up on refreshing either one of 3 things will happen:

1. Torus loads and you can sign in
2. Torus does not appear in the available wallets when loading the scene
3. Torus throws an error saying that it has not been defined. 

**To Reproduce**
1. Build a demo WebGL scene
2. Uncomment the code for trustwallet and Torus in index.js
3. Upload your build to a web server.
4. Load the URL and see if results remain consistent.

**Expected behavior**
Torus should not only be available under the wallets section, but it should load when chosen as the preferred wallet.

**Screenshots**
![image](https://user-images.githubusercontent.com/97366705/180636884-51ef983c-e220-4040-86c6-94b72978b94d.png)

The error above appears randomly. I just tested it and it worked fine, however it seems to be quite on and off. 

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome
 - Version 103.0.5060.134

**Additional context**
The issue comes and goes. I mentioned to Sneakz that perhaps it's timing out on Torus end and is not an issue with the SDK, but wanted to bring this to your attention just in case it IS something. 

The link I used for testing was this: https://untitledplatformer.io/WebGL_Builds/Oceania/OCE_1

Thanks team!

**Comment by KBryan** [comment]
Are you using https://github.com/ChainSafe/game-web3gl for your Torus integration?

**Comment by nftpixels** [comment]
Hi Kwame,

I sure am,

I was mentioning to Sneakz that it seems to work every now and then. So
it's a good 75/25 working to not working ratio.

It's not the worst, but if it *could *be looked into it would be nice. If
you enable a build with Torus Uncommented there is a chance that you'll get
that WASM break error on an Apache server. (I use it on cPanel)

Hope that helps :)

Kind Regards,

Reinhardt Weyers

**Comment by KBryan** [comment]
Sounds good, will investigate this further.

**Comment by sneakzttv** [comment]
closing due to new knowledge gained by NFTpixels regarding the matter
