### ISSUE TITLE
web3gl.jslib is using an obsolete javascript api + throwing a scare warning in the browser console

### ISSUE THREAD

**Issue by longda** [ChainSafe/web3.unity#208]
**Describe the bug**
web3gl.jslib is using an obsolete javascript api + throwing a scare warning in the browser console:

`The JavaScript function 'Pointer_stringify(ptrToSomeCString)' is obsoleted and will be removed in a future Unity version. Please call 'UTF8ToString(ptrToSomeCString)' instead.`

Code still works currently but api could be removed in the future by unity.

**To Reproduce**
1. In a webgl build, call one of the following methods: `SendContractJs, SendTransactionJs, SendTransactionJsData, SignMessage, HashMessage`
2. Open console log and observe the error/warning: `The JavaScript function 'Pointer_stringify(ptrToSomeCString)' is obsoleted and will be removed in a future Unity version. Please call 'UTF8ToString(ptrToSomeCString)' instead.`

**Expected behavior**
Use the new api so the error/warning: `The JavaScript function 'Pointer_stringify(ptrToSomeCString)' is obsoleted and will be removed in a future Unity version. Please call 'UTF8ToString(ptrToSomeCString)' instead.`

**Screenshots**
<img width="962" alt="image" src="https://user-images.githubusercontent.com/320665/183769448-fd60cf80-235e-4172-9a4b-a4caf5f99a9a.png">

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21H2, build 19044.1826
 - Browser: Chrome 
 - Version 104.0.5112.80 (Official Build) (64-bit)

**Additional context**
Code still works currently, more of a minor, low-priority fix.  Looks like a straight forward swap to the new api.

**Comment by sneakzttv** [comment]
These are warnings, the way some of our calls work for the marketplace need the syntax this way. This can safely be ignored, if you're not using the marketplace you can replace the code with the console suggestions to make it go away.
