### ISSUE TITLE
Transfer 721/1155s

### ISSUE THREAD

**Issue by FSM1** [ChainSafe/web3.unity#214]
@alexvotofuture commented on [Wed May 04 2022](https://github.com/ChainSafe/game-pm/issues/334)

We have a prefab for transferring ERC-20 tokens ("Transfer20"), but we do not have an equivalent transfer prefab for 721s/1155s.

We should create prefabs for these.

**Comment by sneakzttv** [comment]
We have both of these now, they may have been added in recently.
![image](https://user-images.githubusercontent.com/57473220/184708451-b5d5481d-cc4e-497e-9905-a16e3b236b6a.png)
![image](https://user-images.githubusercontent.com/57473220/184708530-9f9a9658-de58-4220-8766-2e33d8b7e98a.png)

**Comment by sneakzttv** [comment]
@FSM1 this can be closed I'm pretty sure.
