### ISSUE TITLE
MetaMask Android Login not working

### ISSUE THREAD

**Issue by Soltiplier** [ChainSafe/web3.unity#215]
1. Open your app/game
2. Click login through MetaMask
3. Click sign in MetaMask
4. Click Copy (ChainSafe)
5. Back to app
6. Scene is not changing (all is set as should be)

https://user-images.githubusercontent.com/110931461/184699115-1ef21306-e1f7-46c4-8551-e15f36985e11.mp4

 - Device: Xiaomi Redmi 5A
 - OS: Android 7.12
 - Browser Google Chrome
 - Version (what doest it mean?)

**Comment by sneakzttv** [comment]
solved, not compatible with older versions of android currently, android 9 being the oldest working version.
