### ISSUE TITLE
Research SDK Instantiation inside Unity

### ISSUE THREAD

**Issue by FSM1** [ChainSafe/web3.unity#216]
When the SDK is added to a Unity project a popup should appear allowing the game developer to provide initial configuration options for the SDK:
- Project Id
- Chain Id

**Comment by sneakzttv** [comment]
![image](https://user-images.githubusercontent.com/57473220/185655023-3d288bc2-79d8-4c28-a34b-ec7110bf3229.png)
complete, refer to epic.
