### ISSUE TITLE
Error signing transactions

### ISSUE THREAD

**Issue by delRioFacundo** [ChainSafe/web3.unity#218]
**Describe the bug**
Hello, we have been developing a contract for several months, in which we have several private keys authorized to sign the transactions.
We use the binance network, on testnet it works perfectly, but when we pass it to mainnet it only signs the transactions with the private key of the owner, let's say with which we generated the contract, with the rest we get this POST https://api error. gaming.chainsafe.io/evm/broadcastTransaction 400
POST https://api.gaming.chainsafe.io/evm/txStatus 400.
To move to the mainnet we change the network that is from 97 to 56, from testnet to mainnet and we change the contract, do we need to change something? Or what could be the error?
If we do it from remix it works fine, that's why we think it's a problem with chainSafe or some configuration that we have wrong.

From already thank you very much.

**To Reproduce**
It is reproduced when making a transaction with the authorized private key that is not the owner's

**Expected behavior**
That I generated the transaction with any authorized private key

**Screenshots**
![Captura](https://user-images.githubusercontent.com/97857860/185657445-52ae571f-fca9-468f-a49f-44000b6bd0c0.JPG)

**Desktop (please complete the following information):**
 - OS: [WebGl]
 - Browser [Brave [Versión 1.42.97](https://brave.com/latest/) - Chrome Versión 104.0.5112.81

**Comment by sneakzttv** [comment]
can you show me your solidity code and unity c# code calling this please. you can hide your keys etc

**Comment by delRioFacundo** [comment]
Hello, of course, tomorrow if you can let me know and I'll show you, or I'll send you screenshots?

**Comment by sneakzttv** [comment]
just send screenshots/code here :D

**Comment by delRioFacundo** [comment]
![Captura5](https://user-images.githubusercontent.com/97857860/185913381-d3d68fcb-a4a3-460d-8d88-05543a795374.JPG)
![Captura](https://user-images.githubusercontent.com/97857860/185913384-bb4d5dc4-9d05-44dd-801c-aa83071df1c9.JPG)
![Captura1](https://user-images.githubusercontent.com/97857860/185913390-aedec015-c5cc-4be0-8bc0-ddb79ab00dbe.JPG)
![Captura2](https://user-images.githubusercontent.com/97857860/185913392-e43565f2-566d-449a-a5f5-8c39a40b1df1.JPG)
![Captura3](https://user-images.githubusercontent.com/97857860/185913393-3cc0a3e5-5b34-496c-869e-aa581e51f34d.JPG)
![Captura4](https://user-images.githubusercontent.com/97857860/185913397-3d67b369-e7f8-4f09-92f5-5d7a475612d6.JPG)


If something is not understood, ask me
thank you very much

**Comment by sneakzttv** [comment]
Thanks i'll look at this in a few hours, i have some meetings today.

**Comment by delRioFacundo** [comment]
[interaction with the contract.txt](https://github.com/ChainSafe/web3.unity/files/9395365/interaction.with.the.contract.txt)
[Data Contract.txt](https://github.com/ChainSafe/web3.unity/files/9395366/Data.Contract.txt)
[Contract.txt](https://github.com/ChainSafe/web3.unity/files/9395367/Contract.txt)


If you don't understand something let me know
Thank you very much

**Comment by sneakzttv** [comment]
odd question, but have you assigned the mainnet wallets to be authorized?

**Comment by delRioFacundo** [comment]
yes, it is the first thing we did when creating the contract

**Comment by sneakzttv** [comment]
ok good, and you're still seeing this error right now?

**Comment by sneakzttv** [comment]
![image](https://user-images.githubusercontent.com/57473220/186028223-8e1328c0-27d2-40e5-b4b8-c30d23c63658.png)
Can you click this for me and show me it's response in the network-> response area also, it should give you back some sort of text.

**Comment by delRioFacundo** [comment]
Of course, there I capture and attach it

**Comment by sneakzttv** [comment]
there's another area if you press the network tab up the top, go to the failed red call and press response you should see some text :D

**Comment by delRioFacundo** [comment]
First of all thank you, with this last comment looking for that text we found this text, {"response":"insufficient funds for intrinsic transaction cost"}, for that I apologize for wasting your time since you had asked me and I had said that we had funds in all the authorized wallets, the reality is that we had funds in all of them, as to carry out transactions, we saw how much was spent for each one and it was enough to make more or less 10 transactions, but apparently it needs to have more. When we saw this error we saw in google we saw that the account it makes is this value + gasPrice * gasLimit.. And based on this I make a query, we have gasLimit 6000000, so as not to have gas limit problems, that is not harming this account so you need to have more funds? How much is the recommended gasLimit?
Now we add more funds to the wallets and they work perfectly, again I apologize for wasting your time and thank you very much for solving the problem.

**Comment by sneakzttv** [comment]
oh that's ok :) at least we solved it yay!

**Comment by delRioFacundo** [comment]
Cheers

**Comment by sneakzttv** [comment]
ok so for private key calls you can set the gas limit as default and then call the price

**Comment by sneakzttv** [comment]
oh you are calling it

**Comment by sneakzttv** [comment]
Just up the limit more, it should only use what it needs based on the price. you can also run unit tests on this to see if it blows out.

**Comment by sneakzttv** [comment]
Closing this issue as complete, glad we got it sorted. Great job :D

**Comment by delRioFacundo** [comment]
thank you very much
