### ISSUE TITLE
tuple argument error

### ISSUE THREAD

**Issue by ugurberkecan** [ChainSafe/web3.unity#220]
**Describe the bug**
When I try to run Web3GL.SendContract value I am getting this error and I checked that my inputs are correct also when I try to add my input in remix.ethereum.org it works but chain safe doesn't work
Error: invalid tuple value (argument="tuple", value="10000000", code=INVALID_ARGUMENT, version=abi/5.0.7)

**Expected behavior**
Sending transactions

**Screenshots**
here is the my code: 
https://pasteboard.co/XFpzaPsyLEoo.png 

error : Error: invalid tuple value (argument="tuple", value="10000000", code=INVALID_ARGUMENT, version=abi/5.0.7)

args : [["10000000", "NumberBet", "", "1"]]

**Desktop (please complete the following information):**
 - Browser

**Comment by KBryan** [comment]
Can you also provide the source code for the smart contract you are interacting with? It will help with the debugging process.
