### ISSUE TITLE
Hosting a custom signing page - github setup

### ISSUE THREAD

**Issue by PTTimChadfield** [ChainSafe/web3.unity#221]
**Describe the bug**
_(I initially posted this on the discord channel and was asked to submit it as an issue instead: https://discord.com/channels/593655374469660673/928285739899306024/1019514761735585853)_

I've been following the guide for hosting our own sign in page (https://docs.gaming.chainsafe.io/mobile-and-desktop#hosting-your-own-sign-page)

I think there are some setup steps missing and it's not deploying. I have my own version of the webpage hosted and accessible, however, it errors when loading the web page (screenshot below), displaying the html page but not loading the metamask extension.

I have gone through the following key steps:
1) Created a fork of https://github.com/ChainSafe/game-web3wallet
2) Updated the package.json file to link to the new url (screenshot below)
3) Gone to the github repository setting page and changed to deploy from branch (screenshot below)
4) Updated the web3wallet.cs file to point to the new url
5) Added a simple line of text to the index.html file to be sure it is loading the unique/custom web page
6) Gone through the process with yarn _locally_ (which did raise a few errors):
```
@parcel/core: Unexpected output file type .html in target "main"
C:\Projects\Panda\pand-chainsafe-game-web3wallet\package.json:5:11
  4 |   "private": true,
> 5 |   "main": "index.html",
>   |           ^^^^^^^^^^^^ File extension must be .js, .mjs, or .cjs
The "main" field is meant for libraries. If you meant to output a .html file, either remove the "main" field or choose a different target name.
```
Tried removing the 'main' line. Presumably I shouldn't need to remove it? (also tried changing to index.js' with no luck).

`Browser scripts cannot have imports or exports. Add the type="module" attribute to the <script>tag.`
Tried adding `type="module"` to `<script type=module src="./index.js"></script>` in index.html which helped locally to remove the error at least. Reverted though as assume this isn't necessary when live.

^these are LOCAL errors though which I'm less worried about if we can get this to run remotely.

In terms of the remote deployment though, my assumption is that it isn't running the deployment correctly on github / something isn't right there.

**To Reproduce**
(outlined as above in the description)

**Expected behavior**
When loading the custom signing page, for the metamask extension to appear and no errors in the web browser console.

**Screenshots**
Error in web browser when accessing the signing page (the web page/html appears, but no metamask popup - understandble as seems the js isn't running)
![image](https://user-images.githubusercontent.com/61322771/190113280-c976b449-4f0a-423c-aba4-c9457e1fe396.png)

Package.json file
![image](https://user-images.githubusercontent.com/61322771/190114093-06d34ad9-ef3b-4e87-bc8c-b9b7c02e466c.png)

GitHub pages settings
![image](https://user-images.githubusercontent.com/61322771/190114313-9388845a-adfc-4dba-8ac6-f80c13caadaa.png)
I've tried changing the source  to 'Github Actions'. I then needed to change the node version in the `deploy-to-ghpages.yaml` file as it was erroring (`@parcel/source-map@2.1.0: The engine "node" is incompatible with this module. Expected version "^12.18.3 || >=14". Got "13.14.0")`).
It goes through the workflow successfully but doesn't actually then deploy the page it seems (reverted this as the guide doesn't say this is necessary)

The page does appear to deploy fine (as mentioned at least the html of the page):
![image](https://user-images.githubusercontent.com/61322771/190140588-e064786d-ee3e-4e93-a043-954973fe0d8f.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version Chrome 105

**Smartphone (please complete the following information):**
NA

**Additional context**

**Comment by KBryan** [comment]
It seems that you are not running `yarn build` doing so will create a build directory which you would upload to your server.

**Comment by PTTimChadfield** [comment]
Sorry - could you elaborate please?

**Comment by KBryan** [comment]
In the ReadMe.md file that is an Installation section. Have you run `yarn build` for the project?

**Comment by PTTimChadfield** [comment]
The readme just says: 'yarn to install yarn start to begin yarn build to compile'.

Perhaps I am missing where this build folder is.

If I do 'yarn build' it errors:

```
@parcel/core: Unexpected output file type .html in target "main"
C:\Projects\Panda\pand-chainsafe-game-web3wallet\package.json:5:11
  4 |   "private": true,
> 5 |   "main": "index.html",
>   |           ^^^^^^^^^^^^ File extension must be .js, .mjs, or .cjs
The "main" field is meant for libraries. If you meant to output a .html file, either remove the "main" field or choose a different target name.

```
Tried removing the 'main' line.

That leads to the error:
`Browser scripts cannot have imports or exports. Add the type="module" attribute to the <script>tag.`

Tried adding type="module" to <script type=module src="./index.js"></script> in index.html

After that I continue with another error.

If I do yarn start it loads the page and metamask appears.

Source control; isn't showing any local 'build folder'

I assume this is all running it locally though?

**Comment by PTTimChadfield** [comment]
It does show a load of files in .parcel-cache but I assume these are not needed.
Also, there is no build folder on https://github.com/ChainSafe/game-web3wallet (which I believe is hosting https://chainsafe.github.io/game-web3wallet/)

**Comment by KBryan** [comment]
Yes, there won't be a build folder as you need to run `yarn build` in order to create it. Can you send a copy of what your package.json file looks like?

**Comment by PTTimChadfield** [comment]
Right, ok. Thank you.

The package.json is in the description above.

Just to reiterate: the differences from that on the source rep (https://github.com/ChainSafe/game-web3wallet/blob/main/package.json) are:

1) The urls
2) `"main": "index.html",` - it won't work with this line (error above)
3) The dependency `"parcel": "^2.7.0",` - I've tried with and without and have the same result.

When I build I see: 
![image](https://user-images.githubusercontent.com/61322771/190338801-b1b9f8d2-dd1e-4284-b658-beef5eca02a3.png)

Quite possible the issue is with point #2?

Thank you!

**Comment by KBryan** [comment]
Yes, this is what you should be pushing to your hosting. Make sure the name of the folder is the same as you have declared in your `package.json` file.

**Comment by PTTimChadfield** [comment]
No luck, so I now have:
wc:56fdea7f-7fc5-4516-ae26-73b618ebe340@1?bridge=https%3A%2F%2Fl.bridge.walletconnect.org&key=26adcf74dbc1f08abab2ae3941268d7e447a1fc314e85dec42a0327fca98c1c3
(still the same error)
