### ISSUE TITLE
[V2] WalletConnect (standalone)

### ISSUE THREAD

**Issue by LuaxY** [ChainSafe/web3.unity#224]
Implement WalletConnect standalone version in C#

https://docs.walletconnect.com/
https://github.com/WalletConnect/WalletConnectSharp
https://adriannenu.medium.com/reading-and-generating-qr-codes-with-c-in-unity-3d-the-easy-way-a25e1d85ba51

**Comment by KBryan** [comment]
Hey Yann, I have this working in the example I showed you guys. I'll take on this task.

**Comment by alexvotofuture** [comment]
@KBryan to meet with @juans-chainsafe to discuss how to test this so it's ready to merge into the v2 branch.
