### ISSUE TITLE
Web3GL.SendContract wrong gas estimation.

### ISSUE THREAD

**Issue by ngmisl** [ChainSafe/web3.unity#227]
We have this function to mint an ERC721 from the contract

```
        private async UniTask<string> ExecuteMinting()
        {
            // smart contract method to call
            string method = "mint";
            // abi in json format
            string abi = "[abihere]";
            // address of contract
            string contract = "contracthere";
            // array of arguments for contract
            string args = "[]";
            // value in wei
            string value = "";
            // gas limit OPTIONAL
            string gasLimit = "";
            // gas price OPTIONAL string gasPrice = "";
            string gasPrice = "";
            //connects to user's browser wallet (metamask) to update contract state
            try {
                response = await Web3GL.SendContract(method, abi, contract, args, value, gasLimit, gasPrice);
                Debug.Log(response);
            } catch (Exception e) {
                Debug.LogException(e, this);
            }

            return response;
        }
```

Problem: GAS estimated is off by at least 100x compared to what metamask recommends. 

Is this a bug?

**Comment by sneakzttv** [comment]
you could try hardcoding the amount, also try removing unitask, you shouldn't need that.

**Comment by ngmisl** [comment]
@sneakzttv thanks! We have it hardcoded for now, but it's not an optimal solution.
Can be confusing for new users, and doesn't react well to chain congestions. Would be cool to have a gasestimate function available

**Comment by sneakzttv** [comment]
you can hardcode it to a slightly higher number to deal with congestion, will that work?

**Comment by sneakzttv** [comment]
oh wait this may help, i spoke with kwame and he said you can use:
You can use string gasPrice = await EVM.GasPrice(chain, network, rpc);
There is also one for GasLimit. You can find this in EVM.cs

Just run this for that and you should be golden!

**Comment by ngmisl** [comment]
@sneakzttv many thanks for the solution, hope this finds a way to your docs :)
