### ISSUE TITLE
Smart contract execution reverted ( Trying to claim/withdraw BNB funds from my contract) no refund as well

### ISSUE THREAD

**Issue by xavieracaling** [ChainSafe/web3.unity#228]
**### First of all, I'm not trying to CLAIM any TOKENS.
The purpose of my contract is to only deposit FUNDS worth of BNB and to CLAIM/WITHDRAW.**

Here's my contract it has been deployed on main net, for you to check in case. 
https://bscscan.com/address/0xa70fa106c9552541aeed65d874b3ffb273f67a47

So here's the problem...
I'm trying to claim BNB from my smart contract, for some reason, the transaction becomes a "**success**" and in the other hand it becomes an "**error**", transaction error shows that the transaction execution of the contract is reverted?? I haven't even gotten any refunds as well.

Here's the transaction error link:
https://bscscan.com/tx/0x72b0d7c93db394bb09f21691a40efb938ce728d5c50729a493c280ff05205a4d
Here's the transaction error image:
![image](https://user-images.githubusercontent.com/97587477/190592277-eed818f0-72c8-4ab4-bafa-55d92bcb0b24.png)

I don't think it is a gas issue as well, because if it is , there's always a pop up display of 'gas estimation failed' but there is none.

Also this is my FUNCTION in which I call to withdraw my BNB from the smart contract.
![image](https://user-images.githubusercontent.com/97587477/190592602-139e20a6-124d-4df1-932c-ef99ad239f1c.png)

Here's the thing.. a weird case..
There's a case where the transaction goes success when I withdraw,
There's also a case where the transaction goes failed when I withdraw, which it displays, transaction execution is reverted

I've tried the TEST NET, it works perfectly, no errors, no execution errors reverted nothing.
All success..

I could pay bnb to my smart contract, and I could withdraw it with no errors. The problem is only in the MAIN NET of Binance Smart Chain.

This is frustrating haahhaah... I don't know what's the problem

Please Help!

**Comment by sneakzttv** [comment]
interesting, if it works on testnet it should work on main provided you're referencing the mainnet contracts also. Odd.

**Comment by sneakzttv** [comment]
![image](https://user-images.githubusercontent.com/57473220/190606251-7c02cb18-a756-41ab-aa05-fc6e89b27a5d.png)
 closing issue as user found the problem via trial and error, cannot withdraw over 50% of the available funds, RE: Above
