### ISSUE TITLE
CharacterSelect referencing deleated GameObject

### ISSUE THREAD

**Issue by GamiFiy** [ChainSafe/web3.unity#233]
I am trying to solve a character select issue:

I want to enable users to pick their character based on the NFTs owned by them.

In the first step i am running a script to identify all the NFTs in the connected wallet and destroy the rest:

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Newtonsoft.Json;

public class AllErc721Example : MonoBehaviour
{
    public GameObject Qube;
    public string IPFS = "https://ipfs.io/ipfs/example/1.json";
    private class NFTs
    {
        public string contract { get; set; }
        public string tokenId { get; set; }
        public string uri { get; set; }
        public string balance { get; set; }
    }

    async void Start()
    {
        string chain = "polygon";
        string network = "mainnet"; // mainnet ropsten kovan rinkeby goerli
        string account = PlayerPrefs.GetString("Account");
        string contract = "0x0123example";
        int first = 200;
        int skip = 0;
        string response = await EVM.AllErc721(chain, network, account, contract, first, skip);
        print(response);

        if (response.Contains (IPFS))
        {

        }
        else
        {
            Destroy(Qube);
        }
    }
}

after all the NFTs not owned by the connected wallet have bean destroyed i want to enable the user to pick his character from the remaining NFTs that have not bean destroyed:

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class CharacterSelection : MonoBehaviour
{
    private GameObject[] characterList;
    private int index;

    private void Start()

    {
        characterList = new GameObject[transform.childCount];

        for (int i = 0; i < transform.childCount; i++)
                characterList[i] = transform.GetChild(i).gameObject;

        foreach (GameObject go in characterList)
          go.SetActive(false);

        if (characterList[0])
            characterList[0].SetActive(true);

    }
    
    public void ToggleLeft()
    {
        characterList[index].SetActive(false);

        index--;
        if (index < 0)
            index = characterList.Length - 1;

        characterList[index].SetActive(true);
    }

    public void ToggleRight()
    {
        characterList[index].SetActive(false);

        index++;

        if (index == characterList.Length)

         index = 0;    
           

        characterList[index].SetActive(true);
    }

    public void ConfirmButton()
    {
        SceneManager.LoadScene("");
    }
    
}

The issue i am encountering is that the first contract that is fetching all the NFTs (AllErc721) gets executed after the second one (CharacterSelection). When i start the game and scroll to a object (Character) that was deleted it gives me the error:
 "MissingReferenceException: The object of type 'GameObject' has been destroyed but you are still trying to access it."

Hope you can help me with my issue :)

**Comment by sneakzttv** [comment]
try settings cube to false instead of destroying it, once it's destroyed it disappears from the object and can't be accessed, you can do this with Qube.SetActive(false); instead of destroying it.
![image](https://user-images.githubusercontent.com/57473220/192030827-b8a90cc1-9946-43d5-952a-5410ebbb142f.png)

**Comment by sneakzttv** [comment]
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Newtonsoft.Json;

public class AllErc721Example : MonoBehaviour
{
public GameObject Qube1;
public GameObject Qube2;
public GameObject Qube3;
public string IPFS = "https://ipfs.io/ipfs/example/1.json";
private class NFTs
{
public string contract { get; set; }
public string tokenId { get; set; }
public string uri { get; set; }
public string balance { get; set; }
}

async void Start()
{
    string chain = "polygon";
    string network = "mainnet"; // mainnet ropsten kovan rinkeby goerli
    string account = PlayerPrefs.GetString("Account");
    string contract = "0x0123example";
    int first = 200;
    int skip = 0;
    string response = await EVM.AllErc721(chain, network, account, contract, first, skip);
    print(response);

    if (response.Contains (IPFS))
    {

    }
    else
    {
        Qube1.SetActive(false);
        Qube2.SetActive(false);
        Qube3.SetActive(false);
    }
}
}
![image](https://user-images.githubusercontent.com/57473220/192031727-afa5bff2-58d1-4f70-afe9-f7e16f3d9c59.png)

**Comment by sneakzttv** [comment]
Secondly you're confusing yourself with that code try this and work from there

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class CharacterSelection : MonoBehaviour
{
public GameObject Qube1;
public GameObject Qube2;
public GameObject Qube3;

public void ToggleLeft()
{
    Qube1.SetActive(false);
    Qube3.SetActive(false);
    Qube2.SetActive(true);
}

public void ToggleRight()
{
    Qube1.SetActive(false);
    Qube2.SetActive(false);
    Qube3.SetActive(true);
}

public void ConfirmButton()
{
    SceneManager.LoadScene("");
}
}
```

![image](https://user-images.githubusercontent.com/57473220/192032839-41f0084d-82a9-49ae-8dfe-2b55967e37ff.png)
