### ISSUE TITLE
Investigate Dynamic NFTs

### ISSUE THREAD

**Issue by sneakzttv** [ChainSafe/web3.unity#238]
RE: Conversation with Tim and Jon regarding dynamic NFTs which are explained here
https://ethereum.stackexchange.com/questions/87853/updating-erc-721-tokens-metadata-after-it-was-minted and here https://blog.chain.link/what-is-a-dynamic-nft/ about updating NFT metadata on the fly. I've previously done this via mappings in my side project but I think metadata is the standard way of doing it.

Questions to be answered regarding Dynamic NFTs
- Which persistence technology should be used to generate a stable CID for an NFT - IPNS/Ceramic Streams
- What does the update process look like? Who has permissions to update the NFT?
- What changes need to be made to Storage to enable us to handle this?

**Comment by FSM1** [comment]
I will discuss some of the technical details of this with Peter as he has some ideas on whether we can use IPLD to store this info instead of IPNS.

**Comment by alexvotofuture** [comment]
Closing this epic for now until it is validated. Tracking on the Gaming Roadmap here: https://www.notion.so/chainsafe/Mutable-NFTs-ffedf43084d3418d8caa4694e7b1742e
