### ISSUE TITLE
Newtonsoft is added as a package which causes errors in Unity

### ISSUE THREAD

**Issue by gregorypierce** [ChainSafe/web3.unity#24]
There seems to be a regression of sorts. Newtonsoft was removed in a version because it was causing errors, then it is added in the subsequent release which causes the errors again. Apparently the only way to resolve this in 2021 is to just remove the Newtonsoft directory so that there arent multiple versions as this is something that will exist in the PluginCache

**Comment by amigax** [comment]
but when i delete them and run a scene i get this error:

EntryPointNotFoundException: Web3Connect assembly:<unknown assembly> type:<unknown type> member:(null)
WebLogin.OnLogin () (at Assets/Web3Unity/Scripts/Scenes/WebLogin.cs:23)
UnityEngine.Events.InvokableCall.Invoke () (at <e7c72e4b0bcb4085b636d7e8921f7453>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <e7c72e4b0bcb4085b636d7e8921f7453>:0)
UnityEngine.UI.Button.Press () (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Button.cs:70)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Button.cs:114)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/ExecuteEvents.cs:57)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/ExecuteEvents.cs:272)
UnityEngine.EventSystems.EventSystem:Update() (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/EventSystem.cs:501)

**Comment by Narendera-abhiwan** [comment]
@amigax hey, I am facing the same problem, did you get the solution?

**Comment by amigax** [comment]
> 

I did but I cant recall how, I think I removed the newtonsoft dll that comes with the sdk maybe.
