### ISSUE TITLE
AAB 64bit PlayStore Issues

### ISSUE THREAD

**Issue by ngmisl** [ChainSafe/web3.unity#240]
Unfortunately google requires nowadays AAB & 64 bit, we do not have any issues with the APK version.

However, building this version gives a ton of chainsafe related bugs

![photo_2022-10-05_14-40-25](https://user-images.githubusercontent.com/98217124/194332585-242162f2-6c48-405c-844d-ac91ffd1faca.jpg)
![photo_2022-10-05_14-40-18](https://user-images.githubusercontent.com/98217124/194332589-3e11d511-0c6b-4206-aedb-78403a412398.jpg)
![photo_2022-10-05_14-40-12](https://user-images.githubusercontent.com/98217124/194332600-73750d6d-2d21-47cf-a1da-fa7ac6af64e6.jpg)

ChainSafe v 1.5.0

**Comment by KBryan** [comment]
Re-download 1.5.0 from the releases section. Seemed there was some stripping when making a build from Unity 2020 has been tested on our end and we pushed a hot fix.

**Comment by ngmisl** [comment]
Fixed, thanks!
