### ISSUE TITLE
Ability to Change the Nonce of each trasaction

### ISSUE THREAD

**Issue by Brinis-Unity3D** [ChainSafe/web3.unity#246]
an error appeared "replacement fee too low", after searching in forums,I understood that this error is related to the Nonce,the cause is İ have to execute 2 transaction in the same time.
İ want to have the ability to change the nonce of every transaction to be able to do multiple transactions in the same time
plz add this feature, İ need it ASAP.
you can add to the Nonce an id derive from DateTime or Timestamp by default
:)

**Comment by KBryan** [comment]
This has been added on the API level. We will add a new SDK release on Monday. Although, you can add this to the send transaction method as you mentioned and showed in discord.

**Comment by Brinis-Unity3D** [comment]
Hi,

Thank you for your response,
Happy to hear that,

Cordially
