### ISSUE TITLE
[V2] Add Datadog logging to all SDK v2 Methods (without tying to project ID)

### ISSUE THREAD

**Issue by FSM1** [ChainSafe/web3.unity#249]
Any API methods that are currently logged to Datadog from the `game-api` should be implemented in the V2 SDK using the Datadog logger class

The project Id should be included in all events logged by an instance of the SDK.

**Comment by alexvotofuture** [comment]
Kwame will work on getting logs as a whole working first, then will tie logs to a specific project ID.

**Comment by KBryan** [comment]
The framework for DataDog is currently in v2 of the SDK. Moving this back to complete task #165 before finishing and closing this issue.
