### ISSUE TITLE
Add brand assets, but where? 

### ISSUE THREAD

**Issue by sweetpea22** [ChainSafe/web3.unity#255]
Hiya! ChainSafe Marketing wants brand assets to be readily available for download with the SDK. AFAIK we're not on the unity asset store yet, so should we add brand assets here? it's a 1MB file. where should I drop it?

**Comment by alexvotofuture** [comment]
@sweetpea22 I would create a separate repo in the ChainSafe org (ChainSafe-Gaming-Brand-Assets or something), and we can then put a link to that repo in the web3.unity readme file.

btw we are no longer listed on the Unity Asset Store.

**Comment by sweetpea22** [comment]
Cool sounds good

**Comment by KBryan** [comment]
If you are looking for brand assets. They can be found at this link. Sorry for the late response.
https://docs.gaming.chainsafe.io/media

**Comment by haochizzle** [comment]
Wasn't there supposed to be assets for "Powered by ChainSafe Gaming" and "Made with ChainSafe Gaming"?

**Comment by KBryan** [comment]
I'm not sure if we are creating them we could add them to the media section of our docs.
