### ISSUE TITLE
"Need To Register?" button should redirect to the dashboard URL

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#257]
**Describe the bug**
Inside ChainSafeServerSettings, the "Need To Register?" button is redirecting to the docs instead of the dashboard

**To Reproduce**
1. Go to ChainSafeServerSettings
2. Click on "Need To Register?" button

**Expected behavior**
User is redirected to https://dashboard.gaming.chainsafe.io/

**Screenshots**
<img width="545" alt="Screenshot 2022-11-03 at 09 40 20" src="https://user-images.githubusercontent.com/104365141/199722681-9894d639-d4c9-4428-ae27-d324cbb170dd.png">

**Comment by sneakzttv** [comment]
https://gyazo.com/7945c0ec124f0344ee039dcf0997b6d0 ...?

**Comment by sneakzttv** [comment]
can be changed to this 
![image](https://user-images.githubusercontent.com/57473220/199731905-d0b588a7-16eb-492e-8118-7d3add10279e.png)

**Comment by sneakzttv** [comment]
needs to change to this, do you need a new build?
![image](https://user-images.githubusercontent.com/57473220/199732040-cad6c2a8-3a13-4891-87b0-bbd195168744.png)

**Comment by sneakzttv** [comment]
good find Juan! Closing this as it's minor and a 1 line fix.
