### ISSUE TITLE
Create How to make a release document

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#260]
It should be good to have documented internally, how someone can generate a new build and publish into the web3.unity releases

**Comment by juans-chainsafe** [comment]
I'm working on this in https://www.notion.so/chainsafe/e31b9d91941147e7a864645e97991218?v=a8b0370cc7e04dce89c5913d098c30a5

**Comment by sneakzttv** [comment]
Made some edits for you bro
![image](https://user-images.githubusercontent.com/57473220/200395032-39288e76-4e35-4ce0-9e0e-a4c667e73a30.png)

**Comment by sneakzttv** [comment]
can close this unless you think it needs more? up to you.

**Comment by juans-chainsafe** [comment]
hey! @sneakzttv sorry that I didn't update that document with my changes (I had them in a google doc) so I created a new DRAFT document with my changes here https://www.notion.so/chainsafe/DRAFT-1-How-to-create-a-release-package-for-the-SDK-44cf972b557a4f8098f237f18f44f10c but your steps help me with some stuff haha so thanks! let me know what you think (I will send it to Kwame as well)

**Comment by sneakzttv** [comment]
you need resources and editor now as the pop up files reside there 
![image](https://user-images.githubusercontent.com/57473220/200475285-d7b88466-af76-4dd1-b857-70cd9e0d12c9.png)

**Comment by sneakzttv** [comment]
the rest is good, you can delete the one i was working on if you're happy with the merges you've done <3 gj

**Comment by juans-chainsafe** [comment]
Awesome! @sneakzttv thanks!
Got it, I thought that resources and editor  were needed only for 1.6.0 but makes sense that from now on, we need them always.
