### ISSUE TITLE
SendTransactionData Response Not Returning Properly

### ISSUE THREAD

**Issue by gregbickford** [ChainSafe/web3.unity#261]
**Describe the bug**
When calling the task SendTransactionData in the Web3GL.cs function it does not return the transaction.

The task SendTransctionData tries to get the response from the SendTransactionResponse function in the web3gl.jslib which returns the window.web3gl.sendTransactionResponse which is incorrect. When calling SendTransctionData the response you are looking to get is the window.web3gl.sendTransactionResponseData. 

To fix this in my code simply made a new function in the web3gl.jslib file that is SendTransactionResponseData that returns the window.web3gl.sendTransactionResponseData and properly call this method in the web3GL.cs task SendTransctionData.

**To Reproduce**
1. Call SendTransctionData in the web3GL.cs
2. Build for browser
3. Wait for response. You wont recieve anything but transaction will go through

**Expected behavior**
Supposed to recieve response.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - Browser - Chrome, Safari, Firefox, and most likely all browsers

**Smartphone (please complete the following information):**
 - Browser - Same as above

**Additional context**
My code below even though its not wanted haha

  //Web3GL.cs Replace this SendTransactionData
    [DllImport("__Internal")]
    private static extern string SendTransactionResponseData();

  async public static Task<string> SendTransactionData(string _to, string _value,  string _gasPrice = "",string _gasLimit = "", string _data = "")
    {
        // Set response to empty
        SetTransactionResponseData("");
        SendTransactionJsData(_to, _value, _gasPrice,_gasLimit,_data);
        string response = SendTransactionResponseData();
        while (response == "")
        {
            await new WaitForSeconds(1f);
            response = SendTransactionResponseData();
        }
        SetTransactionResponseData("");
        // check if user submited or user rejected
        if (response.Length == 66) 
        {
            return response;
        } 
        else 
        {
            throw new Exception(response);
        }
    }

    //web3gl.jslib add this
SendTransactionResponseData: function () {
    var bufferSize = lengthBytesUTF8(window.web3gl.sendTransactionResponseData) + 1;
    var buffer = _malloc(bufferSize);
    stringToUTF8(window.web3gl.sendTransactionResponseData, buffer, bufferSize);
    return buffer;
  },

**Comment by FSM1** [comment]
Issue moved to [ChainSafe/game-api #219](https://github.com/ChainSafe/game-api/issues/219) via [**Zenhub**](https://www.zenhub.com/)

**Comment by sneakzttv** [comment]
After deliberation with the team we've decided that this is functioning as intended for 99% of users. As it is an edge case usage, we've decided not to apply this change to the SDK as it would cause errors in places that are currently functional. This can be applied as needed by the user.
