### ISSUE TITLE
Incorrect link to the demo game in the Release tab

### ISSUE THREAD

**Issue by NikitaGedzhua** [ChainSafe/web3.unity#262]
**Describe the bug**
Incorrect link to the demo game in the Release tab

**To Reproduce**
1. Go to 'Release tab.'
2. Click on 'Latest build'
3. Scroll down to 'link to the demo game https://chainsafe.github.io/ChainSafe-Demo/'
4. See error - not found

**Expected behavior**
https://chainsafe.github.io/ChainSafe-Demo-WebGL/ - must be this link

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]
 - Version [ 22]

**Comment by sneakzttv** [comment]
ah, well spotted, thank you <3 we changed the names around when webgl and webwallet came out together. Fixed :D
