### ISSUE TITLE
EVM.AllErc1155() doesn`t work in polygon testnet (mumbai)

### ISSUE THREAD

**Issue by Trelamid** [ChainSafe/web3.unity#263]
** Error description**
Not displaying nft token data on wallet in chain - polygon network - testnet.

**Replay**
Steps to reproduce the behaviour:
1. Go to 'AllErc1155Example.cs'
2. Change chain = ethirium to chain = polygon
2. Change network = rinkeby to chain = testnet
3. Connect a wallet which has nft tokens in this network.
4. Observe, the program does not display them and returns [];

**Expected behaviour**.
Get list of nft tokens on the wallet.

** Desktop (please fill in the following information):**
 - OS: Windows
 - Chrome browser
 - Version of ChainSafe 1.6.0

**Comment by sneakzttv** [comment]
closing as it's graph related.
