### ISSUE TITLE
ERC1155 / ERC20/ ER721 .URI not working

### ISSUE THREAD

**Issue by Lelegithub** [ChainSafe/web3.unity#27]
I am trying to Fetch NFTs from rinkeby network but the the method

        // fetch uri from chain
        string uri = await ERC1155.URI(chain, network, contract, tokenId);

Is bugged and creates a wrong URL. or Sometimes returns a curl error.

for fixing the first  I modified that uri with:
uri = uri.Replace("0x{id}", tokenId + "?format=json");

but still I get errors when fetching these nfts:
https://testnets.opensea.io/assets/0xac1ee64466d3b96eb31d3876ce14082913d94c0b/1
and this:
https://testnets.opensea.io/assets/0x8fe1e2bf904a568231317f738ddfb0939d8aff17/1

Can you fix this method please?

![image](https://user-images.githubusercontent.com/3763810/138174253-b13adb8d-1453-4d16-b7ab-50497b563175.png)

![image](https://user-images.githubusercontent.com/3763810/138174225-c5d753a6-15ab-4744-8cf6-fa4356fe1092.png)

![image](https://user-images.githubusercontent.com/3763810/138173999-9fb998ef-d38f-46f0-bb02-f85e9e06428f.png)

![image](https://user-images.githubusercontent.com/3763810/138173932-1d507d2d-3e81-4486-9993-730f69bf2c2c.png)

**Comment by ecp4224** [comment]
`imageUri` is an IPFS URL which isn't supported by curl. You could do something like this

```
if (imageUri.StartsWith("ipfs://"))
{
    imageUri = imageUri.Replace("ipfs://", "https://ipfs.io/ipfs/");
}
```

**Comment by leon-do** [comment]
What ecp4224 said. thank you
