### ISSUE TITLE
Prefab VoucherMinterWebGL1155

### ISSUE THREAD

**Issue by Tisi22** [ChainSafe/web3.unity#271]
Found the prefab problem, it is in MintWeb3Wallet1155 script function VoucherMintNft1155(), when it calls EVM.CreateMint() the CreateMint() doesn´t return any data.response and we needed to call the next function Web3Wallet.SendTransaction to create the URL. And this is the invalid URL because there is not "to", "value", "data", "gaslimit" and "gasPrice"

After running  VoucherMintNft1155() the URL that opens:

https://chainsafe.github.io/game-web3wallet/?action=send&chainId=5&to=&value=&data=&gasLimit=&gasPrice=
![image](https://user-images.githubusercontent.com/102957880/204005885-4e69517d-c436-42ab-ae52-6dc7269c932a.png)

Debug:
![image](https://user-images.githubusercontent.com/102957880/204005434-7d6fd612-a7c7-43bf-b603-8b4d689b2e7f.png)

![image](https://user-images.githubusercontent.com/102957880/204005362-c8c3d981-2eb0-4d38-9849-0cf12f746a19.png)

How can we solve it?

**Comment by sneakzttv** [comment]
This has been completed, branch is just awaiting testing and will be released within 24 hours.
