### ISSUE TITLE
Skale Integration write up tutorial / blog post

### ISSUE THREAD

**Issue by KBryan** [ChainSafe/web3.unity#273]
Create an onboarding tutorial for the Skale network.

- [x] draft out tutorial outlines
- [x] create a write-up on learning outcomes and an overview of the Skale network.
- [ ] create a video to supplement the implementation and interaction with smart contracts deployed on Skale.

**Comment by game-racing-gofaster** [comment]
Please make a complete tutorial for this precious network. I did a lot of research but couldn't find anything.

**Comment by pparashm** [comment]
Please make tutorials for this valuable network. I searched a lot but did not find any tutorial.
