### ISSUE TITLE
Error 400 In all721 POST request

### ISSUE THREAD

**Issue by Raheel312** [ChainSafe/web3.unity#275]
All of sudden POST request is returning Error 400:

Error is :
"response": "The \"url\" argument must be of type string. Received undefined"

Before that everything was working  fine ,

To resolve this issue I updated to latest sdk. I updated unity project to latest version but same error always.
Pattern we are using for  POST request is
![image](https://user-images.githubusercontent.com/103568897/205077671-5173000e-78fd-458e-aa69-8ba280e62221.png)

**Comment by Afzal-Devstree** [comment]
Hello @Raheel312 , 

We are facing the same issue, Have you got any solution?

If anyone has a solution please share it with us. 

Thanks.

**Comment by Syed-Ali-Shah-Bukhari** [comment]
That's the same issue I am facing.🙂
if anyone finds a solution. kindly send it

![Screenshot 2023-01-06 133254](https://user-images.githubusercontent.com/68770651/210962632-6d9825d3-18d8-4c76-a563-b9168e6a234c.png)
