### ISSUE TITLE
[V2] Get Voucher is not working

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#278]
GetVoucher721 and GetVoucher1155 are throwing the following error:

![Screenshot 2022-12-02 at 10.39.30.png](https://images.zenhubusercontent.com/62699f50d2fb4f7e13688714/4f78d022-5c5e-4f9e-a16f-22faaa69abf9)

**Comment by KBryan** [comment]
Going to edit the PR from Sneakz and get this out today.

**Comment by sneakzttv** [comment]
fixed
