### ISSUE TITLE
Web3 Connect - security flaw?

### ISSUE THREAD

**Issue by chrisciszak** [ChainSafe/web3.unity#28]
Great repository, thanks for your efforts.

Quick question, during your login flow, how do you ensure that the user owns the wallet before you connect it to your app? In general it's very simple to manipulate javascript to change the wallet address. Usually, the only way to ensure that the user owns the account is for the user to sign a message with their wallet, but I dont think this is the case here.

Could you help me understand your login flow?

**Comment by chrisciszak** [comment]
Hi @KBryan sorry to reopen this. We tried to test it but on the login flow it never asks to sign a message, it just basically follows a simple login procedure. Are we missing some configuration?

**Comment by leon-do** [comment]
Hey, you can add additional logic above this line to sign and verify

https://github.com/ChainSafe/web3.unity/blob/ac012dd8610128dff75ee41608a35ae57b81b182/Web3Unity/Scripts/Scenes/WebLogin.cs#L39

Sign
https://chainsafe.github.io/game-docs/#sign-through-webgl

Verify
https://chainsafe.github.io/game-docs/#verify

We also have logic that'll refresh the game if the user tries to inject after the initial login here: https://github.com/ChainSafe/game-web3gl/blob/3bebdd8a58919007fa63992686f0a97c851bb2bf/src/web3gl/index.ts#L61

I hope this answers your question.
