### ISSUE TITLE
Use of Player Prefs Bad Practice

### ISSUE THREAD

**Issue by WoodsFiend** [ChainSafe/web3.unity#292]
**Describe the bug**
The use of PlayerPrefs for storing the ProjectID, ChainId, Chain, Network and RPC is bad practice. PlayerPrefs are meant to be used to save settings that should be retained between player sessions.  The use of PlayerPrefs makes it impossible to push changes to a repository, which in turn makes remote building of the Unity client with this SDK impossible. It also has a greater chance of creating conflicts with other uses of PlayerPrefs that a developer may already have in place. 

My suggestion would be to change ChainsafeServerSettings to a scriptable object, and all values in it that are currently stored as PlayerPrefs to be retrieved from the scriptable object.

**Comment by alexvotofuture** [comment]
@WoodsFiend Thanks for the feedback! We'll take a look and see if there's a way to move these preferences elsewhere, taking into account your suggestion. cc @KBryan

**Comment by sneakzttv** [comment]
fixed and implemented in v2
