### ISSUE TITLE
Secure Player Prefs in Unity3d

### ISSUE THREAD

**Issue by KBryan** [ChainSafe/web3.unity#294]
Update current Player Prefs to Secure data more securely using a simple hashing algorithm on store data.

**Comment by sneakzttv** [comment]
this should help btw https://www.youtube.com/watch?v=7za0tMD5Ffs

**Comment by KBryan** [comment]
https://github.com/ChainSafe/Gaming_SDK_V2/tree/secure_player_prefs

**Comment by sneakzttv** [comment]
fixed and implemented in v2
