### ISSUE TITLE
Create a DataDog endpoint instead of Agentless C#

### ISSUE THREAD

**Issue by KBryan** [ChainSafe/web3.unity#302]
The issue I'm running into with our current DataDog integration is this. When creating log entries and having this client side. We need to store the APIKey and AppKey in the project. A safer and cleaner approach would be to create a DataDog endpoint from our current API. We can leverage what is implemented currently in our API.

**Comment by FSM1** [comment]
Utilizing a proxy API here would only complicate things further, while not providing any improved security or data reliability.
