### ISSUE TITLE
Collections Filter for In-Game Marketplace

### ISSUE THREAD

**Issue by alexvotofuture** [ChainSafe/web3.unity#303]
**Summary**
Most game developers we've spoken to want to show only NFTs relevant to their game when they consider embedding our marketplace.

**Suggested features or ways to address the summary**
Modifying the in-game marketplace prefab to optionally filter by a specified collection that has been created in our marketplace.

**Product Requirements**
- [x] Developer can specify one or more NFT collections they wish to show in their in-game marketplace
- [x] NFTs in the marketplace that do not belong to the collections specified are filtered out, so that they do not appear in the in-game UI
- [x] Support for collections that include ERC-721s, ERC-1155s, or combinations of both
- [x] Users can list/sell and buy from the in-game marketplace as they normally would (maintains feature parity with existing in-game marketplace implementation)
- [x] When listing NFTs to sell in a game that has filtered by collection, only allow users to list NFTs that are in the specified collection

**Potential Blockers**
Graph queries for NFTs might present an issue for this (since we are experiencing outages and delays in the marketplace and All721/1155 prefabs due to Graph sync issues), though this is lessened if we only query the ChainSafe Marketplace.

**Metrics of Success**
3 studios who have considered the in-game marketplace using it with collections. To be measured using prefab counters by project ID.

**Additional context**
- Not sure how developers will search for their collection. Is this a url or ID number that they'll copy-paste from the marketplace web UI? Is there some way of creating collections outside the web UI?

**Comment by sneakzttv** [comment]
I'm amazing
![image](https://user-images.githubusercontent.com/57473220/215655212-11efa812-f4cd-4e47-b45b-ff4a7c421b47.png)
![image](https://user-images.githubusercontent.com/57473220/215655233-19184ad1-05c5-4f93-9677-8fe53507c7c0.png)

**Comment by sneakzttv** [comment]
@KBryan CHECK THIS OUT >:D

**Comment by sneakzttv** [comment]
still needs attention, but almost there. Still need to do listing prefab.

**Comment by sneakzttv** [comment]
awaiting collection id slugs

**Comment by sneakzttv** [comment]
progress update
![image](https://user-images.githubusercontent.com/57473220/226948529-f32f9c36-be75-4e87-9449-52114618f9e9.png)

**Comment by sneakzttv** [comment]
https://github.com/ChainSafe/web3.unity/pull/359

**Comment by sneakzttv** [comment]
docs updated also

**Comment by sneakzttv** [comment]
merged, draft release created https://github.com/ChainSafe/web3.unity/releases/tag/untagged-ef15fd8939f5f4bf3d32
