### ISSUE TITLE
Unity cannot build

### ISSUE THREAD

**Issue by totgard** [ChainSafe/web3.unity#311]
**Describe the bug**
If try build current version of package Unity throw error

```The type or namespace name 'EditorWindow' could not be found (are you missing a using directive or an assembly reference?)```

**To Reproduce**
- Open empty project
- Import ChainSafe package
- Try build with one of scenes

**Expected behavior**
Correct build app

**Screenshots**
![image](https://user-images.githubusercontent.com/7002293/215322758-2b4b8f58-5981-4a3a-9550-eb6414ba07bd.png)
![image](https://user-images.githubusercontent.com/7002293/215322794-9576275c-d831-47b8-a16b-c4e018e37622.png)

**Desktop (please complete the following information):**
 - Chainsafe SDK version: 1.6.3
 - Unity Platform: WebGL
 - Unity version 2022
 - OS Windows

**Additional context**
Add assembly defenition for package and separate editor code.

**Comment by sneakzttv** [comment]
reinstall the sdk from the release package
