### ISSUE TITLE
WebGl does not work

### ISSUE THREAD

**Issue by totgard** [ChainSafe/web3.unity#312]
**Describe the bug**
If build app for WebGL and try user jslib in package browser throw exception:

```The JavaScript function 'Pointer_stringify(ptrToSomeCString)' is obsoleted and will be removed in a future Unity version. Please call 'UTF8ToString(ptrToSomeCString)' instead.```

**Expected behavior**
Correct webgl build

**Screenshots**
![image](https://user-images.githubusercontent.com/7002293/215323823-91ea7608-e9e0-4ce4-9dab-aef541a34d33.png)

**Desktop (please complete the following information):**
 - Chainsafe SDK version: 1.6.3
 - Unity Platform: WebGL
 - Unity version 2022
 - OS Windows

**Additional context**
Need update code in ```https://github.com/ChainSafe/web3.unity/blob/main/Web3Unity/Scripts/Library/WebGL/web3gl.jslib```

**Comment by sneakzttv** [comment]
works just fine, this is a warning and is fixed in v2.
