### ISSUE TITLE
WebGL Template - Wallet Connect v2

### ISSUE THREAD

**Issue by FSM1** [ChainSafe/web3.unity#314]
Since WalletConnect V1 is being deprecated at the end of Feb, we need to update the WebGL template to use WalletConnect V2.

Initial investigations show that we previously referenced a CDN version of the WalletConnect package, but V2 does not seem to be distributed this way. To resolve this we can just run the WalletConnect V2 code through a bundler like Vite/WebPack and include the minified source in the `lib` folder as we have done with web3modal.

We should also update the `web3modal` dependencies located [here](https://github.com/ChainSafe/web3.unity/blob/main/WebGLTemplates/Web3GL-2020x/web3/lib/web3modal.js) as these are very likely also out of date.

@sneakzttv commented on [Mon Jan 30 2023](https://github.com/ChainSafe/game-pm/issues/457)

Updating the sdk to wallet connect v2

---

@sneakzttv commented on [Mon Jan 30 2023](https://github.com/ChainSafe/game-pm/issues/457#issuecomment-1408954963)

To discuss with Mike and Kwame

---

@sneakzttv commented on [Mon Jan 30 2023](https://github.com/ChainSafe/game-pm/issues/457#issuecomment-1408994846)

Mike reaching out to Pedro to assess options

---

@FSM1 commented on [Tue Jan 31 2023](https://github.com/ChainSafe/game-pm/issues/457#issuecomment-1410437618)

Had a couple of ideas on how to approach this, and will do some trial runs to test this out.

**Comment by alexvotofuture** [comment]
Ryan's likely to finish this in the coming 2 weeks. Need to let Krytomon know when we finish, since they need it.

**Comment by FSM1** [comment]
Closed in https://github.com/ChainSafe/web3.unity/pull/348
