### ISSUE TITLE
Can't display Polygon tokens correctly.

### ISSUE THREAD

**Issue by kuhamaven** [ChainSafe/web3.unity#327]
**Describe the bug**
When replacing the contract address and token ID to load an NFT image on runtime, it will throw an exception each time you try to load a Polygon one.

**To Reproduce**
1. Create a new blank unity project
2. Add a quad on scene
3. Add Import NFT Texture Example to the quad
4. Change the scripts Contract to any polygon one (i.e 0xdC0479CC5BbA033B3e7De9F178607150B3AbCe1f)
5. Change the scritps Token ID to the corresponding id (i.e 38720)
6. Change line 20 from ERC1155 to ERC721 if needed (It is needed with the examples gave above)
7. Run the scene

**Expected behavior**
After loading the URI and data, the quad should get the right image set.

**Screenshots**
![image](https://user-images.githubusercontent.com/43881512/218545618-6d330c5b-9947-4e54-9df1-6eac61915083.png)

**Desktop (please complete the following information):**
 - Chainsafe SDK version: 2.0
 - Unity Platform: Windows Editor
 - OS Windows

**Additional context**
This is working correctly on 1.6 as it allows you to manually set the chain and network variables on the URI methods. Since 2.0 it no longer works, even after setting your own RPC api and all. The standard Chainsafe logo example works, but changing it to another contract gives an error in console.

**Comment by KBryan** [comment]
Can you post the code you are using?

**Comment by kuhamaven** [comment]
I posted everything I'm doing: Fresh installation, modified those 3 lines from the script I mentioned, and it wont work.

**Comment by sneakzttv** [comment]
pushing a fix later today that should solve this

**Comment by sneakzttv** [comment]
v2.0.1 has been released that should fix this. Please let us know @kuhamaven
