### ISSUE TITLE
Error in a web application when I try to activate the WebGLSendTransactionExample script

### ISSUE THREAD

**Issue by RostislavStoliarchuk** [ChainSafe/web3.unity#33]
Hey! I have an error in a web application when I try to activate the WebGLSendTransactionExample script. What am I doing wrong? Thank
![456456](https://user-images.githubusercontent.com/88757013/141762881-16583238-9974-46fc-b3c5-3fe978e3390e.png)
s
![344534](https://user-images.githubusercontent.com/88757013/141762897-51127182-99f4-44dd-bf9d-4c6d4d9d81cc.png)
.

**Comment by RostislavStoliarchuk** [comment]
I use the BSC network, the activation works fine, the wallet # display is the same. I can't make a transaction

**Comment by leon-do** [comment]
we discussed this on discord. Is it solved?

**Comment by Votrubec** [comment]
> we discussed this on discord. Is it solved?
@leon-do , I'm also running in to this same issue.

Getting a balance works correctly. But when I try to call this

`string response = await Web3GL.SendContract ( method, abi, contract, args, value, gas );`

I get the response:
```
Uncaught ReferenceError: Pointer_stringify is not defined
    at _SendContractJs (/mint/Build/alpha_v2.93_testmint.framework.js:3)
    at dynCall_viiiiiii (/mint/Build/alpha_v2.93_testmint.wasm)
    at invoke_viiiiiii (/mint/Build/alpha_v2.93_testmint.framework.js:3)
    at Web3GL_SendContractJs_mC21AB0E0EF5AD2BC183A2E09BC41F3A26C412088 (/mint/Build/alpha_v2.93_testmint.wasm)
    at dynCall_viiiiiiii (/mint/Build/alpha_v2.93_testmint.wasm)
    at invoke_viiiiiiii (/mint/Build/alpha_v2.93_testmint.framework.js:3) etc.
```

I've currently set the project with the 2021 WebGL template.

**Comment by leon-do** [comment]
@Votrubec 

Try prefab in Assets > Web3Unity > Prefabs > WebGl > SendContractExampleCanvas

Tell me how it goes

**Comment by Votrubec** [comment]
@leon-do sorry for the delay. I awoke this morning to find a new version of Unity released. Unity 2021.2.3. In the patch notes was this item. Could it be that it's Unity that is somehow 'stripping' the required Pointer_stringify method?
![image](https://user-images.githubusercontent.com/6911496/142494643-69447046-d59c-475f-8548-daa507b11718.png)

**Comment by Votrubec** [comment]
@leon-do and @RostislavStoliarchuk I can confirm that the latest Unity version does allow us to now overcome that issue.

The console does still come with the warning/error though that should probably be addressed sooner, rather than later.
![image](https://user-images.githubusercontent.com/6911496/142507166-4611facf-d5d4-4abd-b2e5-12f0369d0ab4.png)

**Comment by leon-do** [comment]
this is great to know. I can address this new error in a new issue. cheers!
