### ISSUE TITLE
Add manifest package.json to the project

### ISSUE THREAD

**Issue by FSM1** [ChainSafe/web3.unity#333]
**Summary**
Unity Package Manager requires a `package.json` to be included in the package.

**Motivation**
This will improve the ability for developers to import the package from UPM.

**Additional context**
See docs around the structure of the package.json here: https://docs.unity3d.com/Manual/upm-manifestPkg.html

**Comment by kalambet** [comment]
Looks like this might be a subtask for #316

**Comment by Arshia001** [comment]
Blocked until the single-repository core library is ready

**Comment by kalambet** [comment]
Fixed a while ago. See ^HEAD
