### ISSUE TITLE
Enable analytics for which wallet is selected when a user connects

### ISSUE THREAD

**Issue by FSM1** [ChainSafe/web3.unity#334]
It would be quite useful for us to log some events when a user connects their wallet to the SDK, and attempt to identify which wallet they are using (Injected, WalletConnect, Torus, Web3Auth).

If this info is available in the Unity context (it might not be available in WebGL for instance, as the wallet is quite far abstracted from the C# code).

**Comment by empea-careercriminal** [comment]
@FSM1 can you provide some context for the issue?

- Still relevant?
- Which version?
- Any other useful comments?

**Comment by kantagara** [comment]
@boorich Added #794 that makes this ticket redundant.
