### ISSUE TITLE
Gas value setting is not applied to SendContract Method in Web3GL

### ISSUE THREAD

**Issue by lucas-shamrock** [ChainSafe/web3.unity#34]
As i observed, it only applied on Gas Limit but not for Gas Value.

For the code like this
![image](https://user-images.githubusercontent.com/93580812/142131453-bc4933f2-cbb2-49f4-863b-28aa6fa69588.png)

will produce this

![image](https://user-images.githubusercontent.com/93580812/142131553-649b4825-3b3f-4ff1-be29-826edeb4c0cc.png)

For any value i changed, it's not shown on MetaMask

**Comment by leon-do** [comment]
if you set `gas = ""`, metamask will calculate it for you.

**Comment by lucas-shamrock** [comment]
I know, but what if my chain is gas-free, i don't want the automatic gas calculation

**Comment by lucas-shamrock** [comment]
![image](https://user-images.githubusercontent.com/93580812/142147497-7d84bc19-2990-4e67-95cd-80fd2f15576a.png)
In web3.js
i can enter 0 gas value for the case

**Comment by leon-do** [comment]
New release handles gas limit and price 😄 

https://github.com/ChainSafe/web3.unity/releases/tag/v1.0.11
