### ISSUE TITLE
JsonRpcProvider doesn't found our private Blockchain

### ISSUE THREAD

**Issue by Magistrix93** [ChainSafe/web3.unity#349]
Hi,

with the v2 update we've implemented new class JsonRpcProvider due to use Contract calls.

`JsonRpcProvider provider = new JsonRpcProvider(<our BC url>)`

but when we try to call a contract Call we get this error:

KeyNotFoundException: The given key "our chain id" was not present in the dictionary.

Debugging we can't find where the error occurs but we understood that it occurs when DetectNetwork by the provider is called.

**Comment by sneakzttv** [comment]
You could try hardcoding the rpc as it's a private node it may not be present which would make sense, you can see this being done in the prefabs like so, just put your rpc and port there this in the your node area before a call

using Web3Unity.Scripts.Library.Ethers.Providers;
using UnityEngine;

public class WebGLGetGasPrice : MonoBehaviour
{
    public async void GasPrice()
    {
        var provider = new JsonRpcProvider("YOUR_NODE");
        Debug.Log("Gas Price: " + await provider.GetGasPrice());
    }
}

**Comment by Magistrix93** [comment]
> You could try hardcoding the rpc as it's a private node it may not be present which would make sense, you can see this being done in the prefabs like so, just put your rpc and port there this in the your node area before a call
> 
> using Web3Unity.Scripts.Library.Ethers.Providers; using UnityEngine;
> 
> public class WebGLGetGasPrice : MonoBehaviour { public async void GasPrice() { var provider = new JsonRpcProvider("YOUR_NODE"); Debug.Log("Gas Price: " + await provider.GetGasPrice()); } }

Hi, I already create our JsonRpcProvider variable.

Can you confirm me that "YOUR_NODE" should be out blockchain rpc?

        provider = new JsonRpcProvider("our BC rpc");
        Debug.Log(await provider.DetectNetwork());

here the full error:

> KeyNotFoundException: The given key 'our chain id' was not present in the dictionary.
> System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <6073cf49ed704e958b8a66d540dea948>:0)
> Web3Unity.Scripts.Library.Ethers.Providers.JsonRpcProvider._uncachedDetectNetwork () (at <ed0b077372f84407862ff267f6639376>:0)
> Web3Unity.Scripts.Library.Ethers.Providers.JsonRpcProvider.DetectNetwork () (at <ed0b077372f84407862ff267f6639376>:0)
> Web3Unity.Scripts.Library.Ethers.Providers.JsonRpcProvider.<.ctor>b__3_0 () (at <ed0b077372f84407862ff267f6639376>:0)
> System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <6073cf49ed704e958b8a66d540dea948>:0)
> UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <1332c534a8a44623b2e5cc943a0b790e>:0)
> UnityEngine.UnitySynchronizationContext.Exec () (at <1332c534a8a44623b2e5cc943a0b790e>:0)
> UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at <1332c534a8a44623b2e5cc943a0b790e>:0)

**Comment by sneakzttv** [comment]
yes, put your rpc and port there, if you're using ganache you can just copy that directly in.

**Comment by Magistrix93** [comment]
> yes, put your rpc and port there, if you're using ganache you can just copy that directly in.

Ok, so I really don't understand why this error. It's impossible to debug and check this _uncachedDetectNetwork() function because is inside a dll not a unity script.

**Comment by sneakzttv** [comment]
@KBryan may be able to assist a little more

**Comment by Magistrix93** [comment]
> @Magistrix93 The issue here is that your private network isn't listed on ChainList.org so it cannot detect the network as it is private. Yes, the RPC node is the private RPC url you are using to connect to your chain.

Please there is a workaround? If the new sdk is compatible only with public chains it's a problem for us

**Comment by sneakzttv** [comment]
you need to put this onto chainlist 
![image](https://user-images.githubusercontent.com/57473220/223767337-08052c66-2919-4869-8d0d-c91fd7b93430.png)

**Comment by Magistrix93** [comment]
> you need to put this onto chainlist ![image](https://user-images.githubusercontent.com/57473220/223767337-08052c66-2919-4869-8d0d-c91fd7b93430.png)

We can't do it, we need a workaround for using out private network
