### ISSUE TITLE
'Provider not set or invalid' in balance response

### ISSUE THREAD

**Issue by O-Shevtsov** [ChainSafe/web3.unity#35]
Hello!
I start to use that plugin for unity. At now just configured login to metamask wallet and tried to get some wallet balance. But I have 'Provider not set or invalid' in balance response.
Login looks like valid with existing account id.
My code is
`
BigInteger wallet = BigInteger.Zero;

    wallet = await ERC1155.BalanceOf(Chain, Network, Contract, 
        PlayerPrefs.GetString(Account), TokenId);

    Debug.Log(wallet);
`
Calls immedeatly after login.

After that call I have next errors:

POST https://api.gaming.chainsafe.io/evm/call 400 (Bad Request)
Provider not set or invalid
Using Unity 2020.3.17f, web.

Can anyone help me? Maybe I miss something?
Thanks

**Comment by KBryan** [comment]
What chain are you connecting to? It doesn't seem to be set from your error.

**Comment by O-Shevtsov** [comment]
Yeah, thanks...
Mistake in chain, set "etherium" instead "ethereum"
