### ISSUE TITLE
A layer of abstraction targeted at Unity game developers

### ISSUE THREAD

**Issue by oleksandrchainsafe** [ChainSafe/web3.unity#354]
## Summary
A new layer of abstraction can be introduced to abstract away the details of how stuff like Coins and NFTs actually work in terms of blockchain. To accomplish this, we can introduce a number of new classes and interfaces.

## Ways to address the summary

**Web3 Client**
```
interface IWeb3Settings
{
  string AppId { get; }
  int ChainId { get; }
  ...etc...
}
```
Provides Web3 settings. Can be implemented by Web3SettingsScriptableObject.
```
class Web3Client : IWalletAddressProvider
{
  static Web3Client Default { get; private set; }
  static void InitializeDefault(IWeb3Settings);
  static void TerminateDefault();

  Web3Client(IWeb3Settings); // public despite being singleton

  ITokenClient NewTokenClient(string contractAddress);
  INFTClient NewNFTClient(string contractAddress);
  IUniversalClient NewUniversalClient(string contractAddress);
  void SetWalletAddress(string walletAddress);
}
```
The component that allows developers to access decentralized storage and smart-contracts logic. This class is the entry point to SDK. You initialize it with a configuration object and then call `New***Client()` to instantiate a new wrapper for each contract. When you do this, the Web3 component injects all the configuration info into a new client object and returns it back.
It can also have the static `InitializeDefault(configuration)` method for Default instance initialization (semi-singleton) or be constructed dynamically using a regular constructor. It is useful to be able to create new instances of the component when you use Dependency Injection frameworks like Zenject. You can simply create a new instance of Web3Client when needed instead of hacking its singleton nature into DI.

**Contract Clients**
```
class TokenClient (ERC20Client) : ITokenClient { ... }

interface ITokenClient
{
  UniTask<decimal> GetBalance();
  UniTask<decimal> GetBalance(string anotherWalletAddress);
  UniTask<?> SendTransaction(decimal amount, string toAddress);
  ...etc...
}
```
A wrapper class for all interactions with a specific contract. The same goes for the NFT Client (ERC721) and the Universal Client  (ERC1155) classes with some exceptions.
```
class UniversalClient (ERC1155Client) : IUniversalClient { ... }

interface IUniversalClient
{
  ITokenClient GetTokenClient(*not sure*);
  INFTClient GetNFTClient(*not sure*);
  ...etc...
}
```
The Universal client class is a bit different from its siblings as it can interact with a number of different token types and NFTs. The interface example is very rough, but the main idea is there.

**Wallet Address**
Developers can set wallet address with `Web3Client.SetWalletAddress()` method. All the clients get a reference to `IWalletAddressProvider` during construction. It is implemented by Web3Client itself. `IWalletAddressProvider.WalletAddress` property can then be used to obtain the current wallet address when needed.

## Motivation
This approach would be more convenient for Unity game developers, that don't have much knowledge of how tokens actually work under the hood, but rather think in terms of Coin and NFT item.

An oversimplified example of usage could be as follows:
```
private class DemoWeb3Settings : IWeb3Settings
{
  public string AppId => "797da47e-4364-4a8d-8932-77777777777";
  public string ChainId => "11155111";
}

public decimal Gold { get; private set; }
public decimal Gems{ get; private set; }
public NFTData<Card>[] Cards { get; private set; }

private void Awake()
{
  //  initialize Web3Client (singleton version in this case) 
  Web3Client.InitializeDefault(new DemoWeb3Settings());
  
  //  build new clients
  _goldClient = Web3Client.Default.NewTokenClient("gold-contract-address");
  _gemsClient = Web3Client.Default.NewTokenClient("gems-contract-address");
  _cardsClient = Web3Client.Default.NewNFTClient("cards-contract-address");
}

public async UniTask LoadModel()
{
  Gold = await _goldClient.GetBalance();
  Gems = await _gemsClient.GetBalance();
  Cards = await _cardsClient.GetOwnedByUser();
}
```
In real-world projects, there is MVC architecture of some sort (or any other type of architecture) instead of a single MonoBehaviour-derived class. Web3Client in this case would be used by the Business Logic layer (aka Model) of the application.
It should be convenient to initialize Web3 and Contract clients during the application initialization phase with all the data required. Then you set the wallet address to Web3Client. After that, you can use those clients by simply calling their public methods with no need to pass a contract address or a wallet address (except in cases where you need to get info on some other wallet).

**Comment by sneakzttv** [comment]
good read

**Comment by kalambet** [comment]
Modularity and DI implemented one way or another.
