### ISSUE TITLE
Add Web3Exception

### ISSUE THREAD

**Issue by oleksandrchainsafe** [ChainSafe/web3.unity#356]
**Summary**
1. Add Web3Exception.
2. Add throw statements to SDK with detailed info for developers.

**Motivation**
It's easier to solve issues when you know the cause.

**Comment by sneakzttv** [comment]
could be worth looking in to

**Comment by sneakzttv** [comment]
afaik this is done now right? @oleksandrchainsafe

**Comment by empea-careercriminal** [comment]
@oleksandrchainsafe @sneakzttv 

Can someone please comment:

- Still relevant?
- Which version?
- Any other context?
