### ISSUE TITLE
Chainsafe logo image doesn't load

### ISSUE THREAD

**Issue by oleksandrchainsafe** [ChainSafe/web3.unity#357]
**Describe the bug**
Chainsafe logo image doesn't load when Settings window first shown on package import.

**To Reproduce**

1. Download web3.unitypackage
2. Import the package
3. See that logo is not visible

**Expected behavior**
Logo is loaded and visible

**Editor:**
 - Chainsafe SDK version: 2.0.3
 - Unity Platform: Editor
 - Unity version: 2021.3.5f1
 - OS: Windows

**Comment by sneakzttv** [comment]
I can't seem to replicate this, closing this for now.
![image](https://user-images.githubusercontent.com/57473220/228367282-601756ea-ba07-4c41-bb7b-9342b3e3d190.png)
