### ISSUE TITLE
Deprecated Documentation in web3.unitypackage

### ISSUE THREAD

**Issue by oleksandrchainsafe** [ChainSafe/web3.unity#358]
**Describe the bug**
web3.unitypackage contains deprecated documentation.

**To Reproduce**
1. Download and import package
2. Navigate to Web3Unity/Documentation folder in project panel
3. Open "Custom Interactions.pdf"
4. See `EVM.BalanceOf(chain, network, account, rpc)`

**Expected behavior**
Updated pdf documentation or no documentation in the package (it is available online).

**Comment by sneakzttv** [comment]
will remove in the next update, thanks :D
