### ISSUE TITLE
Private account token

### ISSUE THREAD

**Issue by O-Shevtsov** [ChainSafe/web3.unity#36]
Hello!
I have a question. Can we somehow get private account token from ethereum account in unity?
Thanks

**Comment by KBryan** [comment]
I'm not sure what you mean by private account token. Is it possible to provide some more context?

**Comment by O-Shevtsov** [comment]
As example something like that
![image](https://user-images.githubusercontent.com/92991657/142458695-f42127d6-abd1-4acf-b811-9452ca46f0ae.png)

Also maybe some like private signature. It need for clearly identify user for login to our server as example.

**Comment by KBryan** [comment]
Okay, gotcha. Currently, we don't support importing private keys into the SDK at the moment.
