### ISSUE TITLE
redeem voucher error

### ISSUE THREAD

**Issue by MJJHUA** [ChainSafe/web3.unity#361]
** I hope to use my voucher to redeem ,  but below code is wrong . **

    
        string method = "redeem";
        string value = "0";
        string gasLimit = "";
        string gasPrice = "";
        string account = "0x646aF97fBAC15256dF19ec74779400F89A1D40Db";
        string signature = "0x618d46c23e7e681ea4476134d7eb45190cb87bef23a21c24700cb007ecf9b9a2660fc937c99106eb6fe844496a3c27a67bc0576e9ada6fac7b09404a7399c3351c";
        
        (int, int, string, string) tuple = (4,0,'"'+ account+'"','"'+signature+'"');
        string v = tuple.ToString();
        string v1 = v.Replace("(", string.Empty);
        string v2 = v1.Replace(")", string.Empty);
        string args = "[[" + v2 + "]]";
        var contract = new Contract(abi, nftAddress);
        var calldata = contract.Calldata(method, new object[]
        {
            args
        });

        Debug.Log("Contract Data: " + calldata);
        
        var response = await Web3Wallet.SendTransaction(chainId, nftAddress, value, calldata, gasLimit, gasPrice);
        print(response);

**Comment by sneakzttv** [comment]
your code is incomplete, you can ask in the community support section of discord they may be able to help you with your custom function <3
