### ISSUE TITLE
Additional customization options for the log in screen

### ISSUE THREAD

**Issue by sneakzttv** [ChainSafe/web3.unity#368]
Before we were able to assign alternate wallets for the sdk, as everything is minified now we can't. I have asked Ryan if he has a repo of these files pre minification so we can figure out a way to change this for users.

Docs of what we need to be able do:
https://onboard.blocknative.com/docs/wallets/injected#display-unavailable-wallets

Currently blocked due to the minification that our sdk goes through as seen here:
![image.png](https://images.zenhubusercontent.com/62c2b0522d66c2be9602e673/3ac2608a-48ca-4d0f-a5d8-26e7e46324c5)

**Comment by sneakzttv** [comment]
repo is here for ref: https://github.com/ChainSafe/web3.unity-webgl-template

**Comment by KBryan** [comment]
Okay, I'll take a look at this.

**Comment by sneakzttv** [comment]
I managed to remove options and adding them would just involve an import and an initialization. However; to make this happen we would need to make the template repo public and write up docs teaching users how to build out and replace the SDK files. I don't think we should continue down this path as wallet connect is sufficient enough.

**Comment by KBryan** [comment]
We should look into WalletConnectSharp. It has support for the v2 protocol and would also allow us to plug into desktop and mobile.

https://github.com/WalletConnect/WalletConnectSharp

**Comment by sneakzttv** [comment]
interesting, also i think we should discuss removing cronos' template as that's v1 and will be obsolete soon. Also it makes the network.js file bulky needing the second network id.
