### ISSUE TITLE
Webgl boot error

### ISSUE THREAD

**Issue by sneakzttv** [ChainSafe/web3.unity#374]
Webgl is having issues loading the scripts sometimes and just errors ou t. A refresh usually gets over this and I've been through a few iterations with defer and async that load slightly better, but they still error on some older browsers. I'd like to make this cleaner. You can see this here if you spam refresh https://chainsafe.github.io/ChainSafe-Demo-WebGL/

**Comment by sneakzttv** [comment]
merged a temp fix, still needs a little massaging though

**Comment by sneakzttv** [comment]
a user of mine is still reporting errors regarding this as async doesn't work on some older browsers. Playing around with the positioning of the js call for load as i think iit's executing before something else has loaded which is causing the boot error.

**Comment by sneakzttv** [comment]
moved positioning of js calls, testing atm once my user is up.

**Comment by sneakzttv** [comment]
uniminified the js, still erroring, grrrr

**Comment by alexvotofuture** [comment]
From Kwame on standup today: This appears to only be a problem when people create a WebGL build and try to open it on a phone. It works when you use a dApp browser it'll load, but doesn't load if you just use a normal browser. We will tell users this. For now, we'll close this issue.

**Comment by sneakzttv** [comment]
Asked blocknative for support they said it could be a build config issue. Myself and Ry tried everything there with no success. May have to implement something custom ourselves.

**Comment by sneakzttv** [comment]
Ry comments from https://github.com/ChainSafe/web3.unity/issues/416 (dupliciate)

Describe the bug

Intermittently, often with larger games, the 2nd time the game is loaded, it encounters an unexpected token error, but it difficult to assertain what the token is, but the error points to just before an export statement

To Reproduce
Steps to reproduce the behavior:

[Go to CryptoSurfers](https://www.cryptosurferz.com/)
Connect your wallet
Refresh
If error occured, error will display in console
Expected behavior
Refreshing should not affect the stability of the SDK

Screenshots
If applicable, add screenshots or videos to help explain your problem.

Desktop (please complete the following information):

WebGL game, Chrome & Firefox
Current suspicions

Scripts no loading at the right time
Been tinkering with defers, forced sequential loads, combined loads etc
Experimenting with Vite build config as there is a lot of processing in Vite that is different to typical bundlers, @BeroBurny provided a possible solve

**Comment by sneakzttv** [comment]
un-assigning and moving this to backlog until DI is done.
