### ISSUE TITLE
MM SDK ChainSafe v2 Integration

### ISSUE THREAD

**Issue by KBryan** [ChainSafe/web3.unity#379]
Our current Wallet and Desktop implementation require the opening of MetaMask via a deep link to the browser. The newest version of the MetaMask SDK offers a more streamlined approach with full access to eth RPC requests. This removes the copy-to-clipboard method and no longer the need to physically open back up a Unity application running on mobile.

- [x] Integrate MMSDK with ChainSafe v2
- [x] Update sign and send with ChainSafe transaction object.
- [x] Implement Mobile / Desktop, and WebGL builds
- [x] Create a downloadable package for installation and testing.
- [x] deploy the local project to repo for public consumption

**Comment by KBryan** [comment]
https://github.com/ChainSafe/EvmCoreMMSDK

**Comment by alexvotofuture** [comment]
@KBryan could you please answer these questions to help me determine how to proceed with merging this?:
- How will game developers discover this feature? As in, where in the SDK does it show up as an option? What other options appear there?
- What the plan is for web3wallet and backward compatibility for games that have used it. Do we replace it entirely with this MetaMask approach? Have it as an option alongside web3wallet? Somehow merge the two?
- How does a user know what to do with MetaMask to make it connect to the game they're playing? Is there some kind of walkthrough on-screen in Unity, or do they need to follow instructions somewhere? Or is it just obvious?
- How does a user see what needs to be signed and sign it during a game session? Are they going back to the browser extension to approve transactions, are they giving broad permissions to the game dev to approve/spend on their behalf, or is it up to the game dev to come up with a way to present signing and tx history to the user?

I may have additional questions, but those are the main ones I'm curious about right now. Feel free to reply here, or we can set up time to chat. A demo video would probably help a ton to answer some of those as well. Thanks!

**Comment by KBryan** [comment]
@alexvotofuture 
1. This feature will be a replacement for our current WebWallet implementation. You can think of it as a better and more secure way of linking an external EOA with the SDK. 
2. There would still be the original implementation of Web3Wallet. Although, it would be a good idea to deprecate this in future releases.
3. The implementation wouldn't be obvious and we would need to supply game developers with documentation on how to use this upgrade.
4. The user will now be prompted with a QR code to connect their EOA to the game. On further signing and sending of transactions. The user will be prompted on their phone via MetaMask to sign and send transactions.

Hope this answers your questions and please ping me if this isn't fully clear.

**Comment by alexvotofuture** [comment]
I will set up a meeting with Kwame early next week to discuss next steps given his responses above.
