### ISSUE TITLE
Import / Assemblies Issue

### ISSUE THREAD

**Issue by cryptomudd** [ChainSafe/web3.unity#38]
I drag and dropped the web3.unitypackage into my game and its giving me this error: 

"Multiple precompiled assemblies with the same name Newtonsoft.Json.dll included or the current platform. Only one assembly with the same name is allowed per platform. "

**Comment by ToonKru3** [comment]
You need to go to the folder /Plugins/JsonDotNet/Assembiles/   in that folder will have 3 folder AOT, Standalone, Windows  and inside of each folder have same file you nedd delete  Newtonsoft.Json.dll file  2 folder AOT and Standalone. That can be solve for me.

**Comment by ToonKru3** [comment]
> I drag and dropped the web3.unitypackage into my game and its giving me this error:
> 
> "Multiple precompiled assemblies with the same name Newtonsoft.Json.dll included or the current platform. Only one assembly with the same name is allowed per platform. "

another way to solve this problem when u import SDK uncheck JsonDotNet  ==> [https://stackoverflow.com/questions/64321053/unity-multiple-precompiled-assemblies-with-the-same-name-using-external-dll](url)

**Comment by KBryan** [comment]
You shouldn't see this if you are using v1.0.12 of the SDK. Could you also provide the version of Unity 3D you are using?

**Comment by PopviZ** [comment]
I'm using the latest v1.0.12 of the SDK, which include 3 different copies of the Newtonsoft.Json.dll within JsonDotNet 
Importing the web3.unity package into a freshly installed Unity (2021.2.4f1 on Linux) produces an error identical to OP.

Deselecting JsonDotNet before importing works without error.

**Comment by KBryan** [comment]
Yes, this is a known issue. Some versions of Unity provide JsonDotNet and some don't. 2020 LTS versions don't have this. We have found that it's easier just to remove it than to add it back in. We are hoping future LTS releases will have this by default.
