### ISSUE TITLE
web3wallet.sendtrasaction gives erroneous values on metamask once parameters are sent

### ISSUE THREAD

**Issue by dulanmalinda** [ChainSafe/web3.unity#382]
**Describe the bug**
I have a token transfer function that uses the "transfer" method of the token contract. when i do this in android the amount of tokens shown in the wallet is way away than the amount i enter. But in webGL works fine. what might be the issue

**Expected behavior**
if add 100 and 18 decimals as the value in function parameter, on metamask it should show 100 tokens. But now it shows different values along with decimal places for tokens. (way away from expected value) some time it show 4720.102 tokens when I enter as 1 token in the code(along with decimals).

**Screenshots**
![image](https://user-images.githubusercontent.com/20043218/232273103-52a3c07e-7b12-4031-a2d3-0ce7d6055349.png)

**Comment by KBryan** [comment]
Depending on the chain you are working with. You may have to manually set the gas price. Is it possible for you to supply the full script?

**Comment by sneakzttv** [comment]
fixed via discord chat
