### ISSUE TITLE
AllErc721 Not working 

### ISSUE THREAD

**Issue by NikosPetrop** [ChainSafe/web3.unity#383]
**Describe the bug**
I did download v2.1 from releases, and tried out ERC721 prefabs. But i have problem with "AllErc721" prefab. First of all, prefab's reference to script was missing. After i linked it with AllErc721Example.cs, i get this error:

```
Error: The "url" argument must be of type string. Received undefined
UnityEngine.MonoBehaviour:print (object)
AllErc721Example/<Start>d__1:MoveNext () (at Assets/Web3Unity/Scripts/Prefabs/TheGraph/AllErc721Example.cs:34)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<string>:SetResult (string)
Web3Unity.Scripts.Library.ETHEREUEM.Connect.EVM/<AllErc721>d__13:MoveNext ()
System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner:Run ()
IEnumeratorAwaitExtensions:RunOnUnityScheduler (System.Action)
IEnumeratorAwaitExtensions/SimpleCoroutineAwaiter`1<UnityEngine.AsyncOperation>:Complete (UnityEngine.AsyncOperation,System.Exception)
IEnumeratorAwaitExtensions/InstructionWrappers/<ReturnSelf>d__2`1<UnityEngine.AsyncOperation>:MoveNext ()
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)

```
Haven't touced the whole script at all, but even if i change parameters, i still get this error.

**To Reproduce**
1. Start a new project
2. Add the prefab 'AllErc721'
3. Replace missing script reference with "AllErc721Example.cs"
4. Hit "Play"
5. See above error
6. Change "await EVM.AllErc721()" parameters (AllErc721Example.cs :23)
7. Hit "Play"
8. Receive same error

**Expected behavior**
Should return every NFT (ERC721) this account owns ( or filtered with specific contract)

**Desktop (please complete the following information):**
 - Chainsafe SDK version: 2.1.0
 - Unity Platform: Windows
 - Unity version 2021.3.11f1
 - Windows OS 

** Screenshots **
![image](https://user-images.githubusercontent.com/22854058/233352281-77c97c06-dfc8-4084-a176-49181d047475.png)

**Comment by KBryan** [comment]
AllERC721/1155 has been discontinued as there is an issue with the graph that is holding us back from supporting multiple EVMs. This will be removed in the next release. We are planning on releasing something similar. Although, no ETA on this. You can either create a subgraph for your game or use something like Infura's NFT api.

**Comment by NikosPetrop** [comment]
How can we get the account's NFTs? Is there a proper way?

**Comment by KBryan** [comment]
No worries, if you have implemented this. Then implement a call to the function `tokenOfOwnerByIndex(address owner, uint256 index)` You can also call this on the contract itself if you have it verified

**Comment by NikosPetrop** [comment]
```
string method = "tokenOfOwnerByIndex";
JsonRpcProvider provider = RPC.GetInstance.Provider();
Contract contract = new Contract(ERC721.abi, _contract, (IProvider) provider);
object[] contractData = await contract.Call(method, new object[1]
      {
        (object) _account
      });
```
something like that? also what if i don't have contract abi?
