### ISSUE TITLE
Transactions cannot be completed on the Arbitrum chain

### ISSUE THREAD

**Issue by xiaofenyu** [ChainSafe/web3.unity#386]
**Describe the bug**
Transactions cannot be completed on the Arbitrum chain

**To Reproduce**
1. LoginWallet
2.CreateContractData
3.CreateTransaction（Unable to create correct transaction information, resulting in signature errors, resulting in subsequent broadcast errors） 
4.BroadcastTransactionReq

**Expected behavior**
The correct contract information can be created when transferring tokens on Arbitrum Goerli, but the correct transaction information cannot be created, resulting in subsequent failures

**Screenshots**
![image](https://user-images.githubusercontent.com/131635806/233895098-0f23f895-d996-4812-9204-a81a14fd0cd8.png)
![image](https://user-images.githubusercontent.com/131635806/233895112-ae93d25a-3976-4a7e-b40e-44e34f5373f3.png)
![image](https://user-images.githubusercontent.com/131635806/233895185-88bc060c-7937-4c2e-8caa-12def2941b02.png)

**Desktop (please complete the following information):**
 - Chainsafe SDK version: [v1.x]
 - Unity Platform: WebGL
 - Unity version 2019.3.7f1

**Additional context**
Using the previous SDK, refactored the code in EVM.cs, Use the URL https://api.gaming.chainsafe.io/evm.
Both BSC and Ethereum token transfers can be successful in the same way.
The Arbitrum chain has encountered a problem.

**Comment by KBryan** [comment]
You are currently using an older version of the SDK. It would be advantageous to upgrade to v2.
