### ISSUE TITLE
Find a way to route gasless transactions

### ISSUE THREAD

**Issue by Arshia001** [ChainSafe/web3.unity#388]
... in the code/prefabs.

**Comment by KBryan** [comment]
It would be a good idea to research and implement a relayer.  This may be a faster approach for the time being without fully going EIP-4337.  ERC-1077 / ERC-1613 or Gas Station Network. I think there may be an implementation of this somewhere in the old repositories from previous looks into this. If we do go down the EIP-4337 route we would need to implement a paymaster which is basically the same concept as above.

https://docs.openzeppelin.com/contracts/2.x/api/gsn 
https://eips.ethereum.org/EIPS/eip-1077
https://eips.ethereum.org/EIPS/eip-1613

**Comment by giladkah** [comment]
CC @GregTheGreek

**Comment by Arshia001** [comment]
The proposed implementation is as follows:

![Gasless Routing.png](https://images.zenhubusercontent.com/64366e64fe8c5c0c84b194d7/aca97959-6a18-47d3-ba1f-8200db90bc67)
