### ISSUE TITLE
Listen for a successful callback

### ISSUE THREAD

**Issue by 17612491225** [ChainSafe/web3.unity#39]
I have two questions
1. After a successful trade, failure or success, I want to listen for any callbacks
2. I want to interact with the contract, I can suspend the contract, but how does the contract call me? Is there anything that needs to be written separately

**Comment by 17612491225** [comment]
string chain = "ethereum";
        string network = "rinkeby";
        string transaction = "0x911d4ec9193e0dc14d9d034d88c311453112c5097f29c366ccc9c5e5bc7072e1";

        string txStatus = await EVM.TxStatus(chain, network, transaction);
        print(txStatus); // success, fail, pending

How to get transaction？

**Comment by KBryan** [comment]
Are you requesting the transaction hash?

**Comment by KBryan** [comment]
We do not currently support listening to events. We have added it to the roadmap. Closing this issue.
