### ISSUE TITLE
Read NFTs from a given public key

### ISSUE THREAD

**Issue by KubilayHeterometa** [ChainSafe/web3.unity#390]
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/Counters.sol";

contract SimpleNFTMint is ERC721URIStorage, Ownable {
    using Counters for Counters.Counter;
    Counters.Counter private _tokenIds;

    mapping (uint => bool) public mintStatus;

    uint256 public constant MAX_SUPPLY = 18000;
    uint256 public constant MINT_PRICE = 25000000000000000; // 0.025 ETH

    string private _baseTokenURI;

    constructor() ERC721("SimpleNFT", "SNFT") {
        _baseTokenURI = "https://ipfs.io/ipfs/QmVrQYxF5sLQBezoXpZveGLLV8wgCaqPeVHH7GBjFH9ivi/";
    }

    function mint(uint tokenid) public payable {
        require(mintStatus[tokenid] != true);
        require(_tokenIds.current() < MAX_SUPPLY, "Max supply reached");
        require(msg.value >= MINT_PRICE, "Not enough ETH sent");

        _tokenIds.increment();
        uint256 newItemId = tokenid;
        string memory tokenURI = string(abi.encodePacked(_baseTokenURI, Strings.toString(newItemId), ".json"));

        _safeMint(msg.sender, newItemId);
        _setTokenURI(newItemId, tokenURI);
    }

    function withdraw() public onlyOwner {
        uint256 balance = address(this).balance;
        require(balance > 0, "No balance to withdraw");
        payable(owner()).transfer(balance);
    }
}

This is my simple mint contract. It works fine and mints any NFT with given token id. 

        contract = "0xa761f0239beFf9a94F6e10301C0E903d718268D8";
        Debug.Log(await ERC721.OwnerOf(contract,"10"));
        Debug.Log(await ERC721.URI(contract, "10"));

And this is my C# script function in Unity. 

The problem is when I want to get the owner or URI of a tokenid. For examle, I am using; await ERC721.OwnerOf(contract,"10")
But it is returning the owner of tokenid 16.

When I use await ERC721.OwnerOf(contract,"1"), it is fine
When I use await ERC721.OwnerOf(contract,"2"), it is fine

But when I use await ERC721.OwnerOf(contract,"10"), it returns owner of token 16,
await ERC721.OwnerOf(contract,"20"), it returns owner of token 32,
await ERC721.OwnerOf(contract,"21"), it returns owner of token 33.

But when I use await ERC721.URIOf(contract,"10"), it returns URI of token 16,
await ERC721.URI(contract,"20"), it returns 32.json,
await ERC721.URI(contract,"21"), it returns 33.json.

**Comment by whatariver** [comment]
I had the same issue. Token id parameter must be in hexadecimal format. For example, decimal 10 is 16 in hexadecimal. Thats why you are getting uri and owner of id 16, when you call the function with id 10. 

You need to send the token id parameter in hexadecimal.

**Ex:** 
_Debug.Log(await ERC721.URI(contract, 16.ToString("X")));_ 

Will give you the uri of token 16.
