### ISSUE TITLE
Merge web3auth code from chicken demo into the SDK

### ISSUE THREAD

**Issue by Arshia001** [ChainSafe/web3.unity#391]
The chicken demo code is available at: https://github.com/ChainSafe/ChainSafe-Demo-Web3Auth

What needs to be implemented in the SDK:

- [x] web3auth SDK
- [x] signing in via web3auth
- [x] a scene demonstrating web3auth login
- [x] a corresponding variation of the wallet that signs using web3auth keys
- [x] prefabs for signing, sending transactions to demonstrate how to do those interactions with web3auth
- [] Use the new SDK framework for this prefab

**Comment by KBryan** [comment]
This task has an issue with the current SDK core update and is currently running on the current evm core.

**Comment by sneakzttv** [comment]
prefabs complete https://github.com/ChainSafe/web3.unity/pull/428
