### ISSUE TITLE
Make a single sign-in scene with both metamask and web3auth

### ISSUE THREAD

**Issue by Arshia001** [ChainSafe/web3.unity#393]

**Comment by sneakzttv** [comment]
i've included a new scene so that users may chop and change as they wish https://github.com/ChainSafe/web3.unity/pull/428

**Comment by giladkah** [comment]
btw, Do we need designs here btw?
CC @serenaho

**Comment by Arshia001** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ChainSafe-Gaming-60e61b3eabd687000e7ce3b2/issues/ChainSafe/web3.unity/393?planning-poker) with Zenhub @oleksandrchainsafe @RyRy79261 @sneakzttv

**Comment by janegabitova** [comment]
July 21st 2023: ticket to be redistributed

**Comment by sneakzttv** [comment]
Complete
