### ISSUE TITLE
Update prefabs to work with new ISigner interface

### ISSUE THREAD

**Issue by Arshia001** [ChainSafe/web3.unity#394]

**Comment by Arshia001** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ChainSafe-Gaming-60e61b3eabd687000e7ce3b2/issues/ChainSafe/web3.unity/394?planning-poker) with Zenhub @oleksandrchainsafe @RyRy79261 @sneakzttv

**Comment by sneakzttv** [comment]
This needs to be completed first so that i can use it as a reference.
