### ISSUE TITLE
web3auth - make prefabs for signing, sending transactions and minting to demonstrate how to do those interactions with web3auth

### ISSUE THREAD

**Issue by Arshia001** [ChainSafe/web3.unity#401]
sub-task of #391.

**Comment by serenaho** [comment]
@Arshia001 Please include me in conversations for this when it is under way! Interested in discussing user/player-facing aspects to these prefabs.

**Comment by Arshia001** [comment]
@alexvotofuture this reminds me, we were going to do a study of whether devs actually use the UI prefabs we make. I'll make an issue.

**Comment by sneakzttv** [comment]
complete https://github.com/ChainSafe/web3.unity/pull/428
