### ISSUE TITLE
Mobile Webgl Sign In Issue

### ISSUE THREAD

**Issue by PrinceSyed** [ChainSafe/web3.unity#402]
**Describe the bug**
Webgl builds with chainsafe sdk do not work on mobile. Unless you are using a daap browser, example below:

**To Reproduce**
1 .Open a browser on your mobile device (i tested with chrome and safari on ios16)
2. Navigate to  https://chainsafe.github.io/ChainSafe-Demo-WebGL/
3. Try to sign in & you will be able to reproduce the rror

**Expected behavior**
User is logged in without an issue on desktop/non mobile device

I get the same error when i build my webgl project but thought it would be easier to communicate the issue using chainsafe demo example.

**Screenshots**
This is the error I get when trying to login using a mobile browser
![image](https://user-images.githubusercontent.com/8345412/235824619-910596ab-fc1f-4c29-b07a-e33715974a2a.png)

**Desktop (please complete the following information):**
 - Chainsafe SDK version: [2.1.0]
 - Unity Platform: [Windows 11]
 - Unity version [e.g. 2022] (Optional)
 - OS [e.g. Mac, Windows, Linux]

**Additional context**
I know it might seem like a niche use case but I primarily make web3 webgl games as they can be played by anyone without having to download anything. Would definitely help drive adoption :)

**Comment by sneakzttv** [comment]
all webgl mobile games require a dapp browser unless you're building for the app store as it just doesn't know how to talk to a standalone mobile browser, wallet functionality doesn't exist etc
