### ISSUE TITLE
Create Web3 Unity User scenarios document in notion

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#405]
Currently we have user scenarios for Marketplace and Gaming Dashboard but we are missing the user scenarios for Web3 Unity.
The difference between them is that Marketplace and Dashboard are web orientated, so we need to see if we can use the same approach for Web3 Unity.

The document will be located in https://www.notion.so/chainsafe/User-Scenarios-635d5916b7034799995b3a398881bc70

cc @nftpixels

**Comment by nftpixels** [comment]
Thank you @juans-chainsafe

**Comment by juans-chainsafe** [comment]
Being reviewed right now.
