### ISSUE TITLE
Create a template of an interface for letting players manage and view their web3auth wallets

### ISSUE THREAD

**Issue by Arshia001** [ChainSafe/web3.unity#407]
This should result in a prefab that the developers can either drop into their games and use without change or change it and make something that fits their game. We also know that the developer may choose not to include this UI in their game.

**Comment by sneakzttv** [comment]
Complete posting in internal chat as this area is open. Afaik our next steps which ill bring into standup are:

- Tanmoy to create a signup/payment processing area on the website that allows a user to download this.
- Ry to create an API endpoint to check paid status.
- Myself to hook the prefab into the API for enable/disable of the prefab.

**Comment by Arshia001** [comment]
Opening this again since it was not merged into `main`.

**Comment by giladkah** [comment]
![image.png](https://images.zenhubusercontent.com/638859bfd23090539a787fe6/2f379963-2013-438b-8673-99e17bc658d8)

@serenaho take a look at this beauty! 
This is how a player managed their wallet inside the game. 

Question for the future: do you think we can think about the designs inside those games as well for our prfabs/eexamples?

**Comment by Arshia001** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ChainSafe-Gaming-60e61b3eabd687000e7ce3b2/issues/ChainSafe/web3.unity/407?planning-poker) with Zenhub @oleksandrchainsafe @RyRy79261 @sneakzttv

**Comment by serenaho** [comment]
@giladkah Yes for sure, I had some more flushed out designs ready for the overlay. Sneakz wanted to work on the final looks after making sure everything was in place. 

On that note, please let me know when you're ready to work on the next designs @sneakzttv

**Comment by sneakzttv** [comment]
Thanks Serena <3

**Comment by janegabitova** [comment]
23-06-23: template had been created; separate ticket to be created for integration into web3auth package
