### ISSUE TITLE
Meta Mask Mobile Deep Link Issue

### ISSUE THREAD

**Issue by SaadImtiaz786** [ChainSafe/web3.unity#408]
Hey everyone! I've successfully integrated Unity with Web3 and MetaMask using ChainSafe Gaming for WebGL, and it's working perfectly. However, when I export the project for mobile, it only works well for users who have MetaMask installed and set as their default browser. If a user doesn't have MetaMask, the link opens in Google and gets stuck. Has anyone encountered a similar issue or could offer guidance on how to handle this situation for users without MetaMask? Any help or suggestions would be greatly appreciated! Thanks in advance!

**Comment by sneakzttv** [comment]
Fixed in the upcoming release with an alert notifying users to install metamask if selected as the means of login to avoid any confusion.
