### ISSUE TITLE
Implementation of ISigner for web3auth 

### ISSUE THREAD

**Issue by Arshia001** [ChainSafe/web3.unity#422]

**Comment by sneakzttv** [comment]
Talking to Oleksandr today to figure this one out and will create a pr once done.

**Comment by Arshia001** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ChainSafe-Gaming-60e61b3eabd687000e7ce3b2/issues/ChainSafe/web3.unity/422?planning-poker) with Zenhub @oleksandrchainsafe @RyRy79261 @sneakzttv

**Comment by KBryan** [comment]
IEvmSigner interface is being used with Unity waiting on outstanding PR before moving forward.

**Comment by janegabitova** [comment]
23-06-23: prefabs on the client side left over; no longer blocked. to finalize next week

**Comment by alexvotofuture** [comment]
Kwame is mostly wrapped up with this, and it works with new architecture as expected. Just cleanup now - should be ready to test by end of day - testing to happen next week.

**Comment by KBryan** [comment]
https://github.com/ChainSafe/web3.unity/pull/508

**Comment by Arshia001** [comment]
Since we need additional Nethereum libs to make this work, we should be putting code in the `publish-to-unity-*` scripts to actually copy the DLLs from the `libraries` folder to the UPM package folder.

**Comment by kalambet** [comment]
Fixed in #534
