### ISSUE TITLE
Avalanche IDs (43113-43114) don't work well for logging in with metamask. It always throws me the chainId 1 (which is from ethereum)

### ISSUE THREAD

**Issue by xkilerxd** [ChainSafe/web3.unity#43]
**Describe the bug**
Avalanche IDs (43113-43114) don't work well for logging in with metamask. It always throws me the chainId 1 (which is from ethereum). This makes it impossible to login with avalanche networks if they put the corresponding chanId in the Network.js file. It doesn't give me an error itself, just that it recognizes avalanche networks like the ethereum chainId 1, it's a metamask problem (this happens when putting the chainId in the Network.js file of the Webgl template). This happens in all dapps, the only solution I found (for now) was to use the window.ethereum.chainId function, this returns the chainId in Hex format, in this type of format Metamask recognizes it and allows you to log in with networks of avalanches without any problem (this I tested in react.js). But in Unity I can't correct it, I think they should do it in the sdk. Thank you so much

**To Reproduce**
1. Go to 'Network.js file of the Webgl template' and open it.
2. Change 'window.web3NetworkId with 43113 Avalanche Testnet or 43114 Avalanche Mainnet' and save it.
3. Built and run.
4. It remains in "login", only with those variables in the chainId (43113, 43114 ). If you put ChainId = 1, it allows you to log in with avalanche networks.

**Expected behavior**
It should allow you to log in with the avalanche networks when the ChainIds are entered in the Network.Js file of the Webgl template.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Windows
 - Browser [e.g. chrome, safari]: Chrome, Brave.

**Comment by KBryan** [comment]
Thank you for posting. This has been logged and I'm looking into this issue.

**Comment by cryptoguru0104** [comment]
Hi, there
I met the same issue, how can I solve the issue?

**Comment by KBryan** [comment]
This has been updated and a new build will be out today.

**Comment by KBryan** [comment]
A new release has been pushed and this issue has been resolved now. 
https://github.com/ChainSafe/web3.unity/releases/tag/v1.0.14
