### ISSUE TITLE
Move W3A out of the core UPM package

### ISSUE THREAD

**Issue by Arshia001** [ChainSafe/web3.unity#438]

**Comment by KBryan** [comment]
Talked with @Arshia001 will need to be it's own UPM package.

**Comment by janegabitova** [comment]
Jul 7th 2023: as per comment above the scope has changed. ticket moving into the next sprint

**Comment by janegabitova** [comment]
July 21st 2023: other dependencies need to be completed before this can be processed. blockers to be linked @Arshia001
