### ISSUE TITLE
Code generation for ABIs

### ISSUE THREAD

**Issue by Arshia001** [ChainSafe/web3.unity#439]

**Comment by empea-careercriminal** [comment]
@kalambet I will be closing this due to insufficient information unless you can add the missing context.

**Comment by sneakzttv** [comment]
Closing due to insufficient information (no description provided)

**Comment by Arshia001** [comment]
I can provide more context here: we were going to create an in-editor tool that takes in a smart contract ABI and generates C# sources for strongly-typed access to that contract. You may wish to re-open the issue if this is still desirable.

**Comment by sneakzttv** [comment]
Ok great, will keep that in mind, thank you.
