### ISSUE TITLE
I want to interact with the blockchain, I call the contract and the contract calls me, and they send each other arguments. How do I do that

### ISSUE THREAD

**Issue by 17612491225** [ChainSafe/web3.unity#44]
I want to interact with the blockchain, I call the contract and the contract calls me, and they send each other arguments. How do I do that

**Comment by 17612491225** [comment]
I want the contract to call my method,

**Comment by 17612491225** [comment]
It just says I call the contract

**Comment by KBryan** [comment]
This is done by calling the function via the contracts abi and passing the arguments needed to interact with it. This is found in our documentation also as described earlier.
