### ISSUE TITLE
Add MUD Support to Gaming SDK

### ISSUE THREAD

**Issue by KBryan** [ChainSafe/web3.unity#445]
MUD is a framework for ambitious Ethereum applications. It compresses the complexity of building EVM apps with a tightly integrated software stack.

This will add the ability to create fully on chain games. Which is part of the roadmap. I recently did a hackathon and added an extension using our v2 C# codebase.

https://github.com/KBryan/UniMudExtension 

MUD Website and API Reference.

https://mud.dev/

**Comment by empea-careercriminal** [comment]
This is potentially a quick win and valuable from a business perspective. Can we please allocate resources to evaluate if this is still useful? @kantagara @kalambet 

Not a high priority, but definitely worth it.

**Comment by kalambet** [comment]
I think this is a good Feature Driver issue.

**Comment by kantagara** [comment]
@KBryan I'd like to have more details in regards to this. What features are we, as an SDK missing, that MUD has? 
https://github.com/KBryan/UniMudExtension/tree/main based on your examples here, I am pretty sure we have all of those methods, so I just need a bigger picture in regards to this.

**Comment by kantagara** [comment]
Closing this in favor of #1021
