### ISSUE TITLE
Use paket instead of nuget

### ISSUE THREAD

**Issue by Arshia001** [ChainSafe/web3.unity#446]
Paket and NuGet are both package managers used in the .NET ecosystem, but they have some differences in their approach and features. Here's a comparison between the two:

1. **Package Resolution Algorithm**:
   - **NuGet**: NuGet uses a centralized package repository hosted by Microsoft, which contains a vast number of packages. It relies on a version-based resolution algorithm, where packages are typically resolved to the highest version that meets the version constraints specified in your project file.
   - **Paket**: Paket, on the other hand, uses a more flexible approach known as "group-based resolution." It allows you to define groups of packages with specific version constraints. This gives you more control over which versions of packages are used in different parts of your project.

2. **Dependency Management**:
   - **NuGet**: NuGet uses a transitive dependency management model, meaning that when you install a package, it also installs its dependencies. This can lead to a "dependency hell" scenario if different packages depend on conflicting versions of the same dependency.
   - **Paket**: Paket uses an explicit and flat dependency model. It does not automatically install transitive dependencies. Instead, you specify all the dependencies you need explicitly, giving you more control over your project's dependency graph.

3. **Integration with Project Files**:
   - **NuGet**: NuGet integrates with project files like .csproj or .fsproj and modifies them to include package references. This means that your project files are tightly coupled with NuGet.
   - **Paket**: Paket does not modify project files directly. Instead, it uses a separate file (paket.dependencies) to define your project's dependencies. This makes it less intrusive and more flexible, especially when working in larger teams.

4. **NuGet Packages Compatibility**:
   - **NuGet**: NuGet primarily works with packages that are available on the official NuGet repository. While you can use packages from other sources, it's optimized for the NuGet ecosystem.
   - **Paket**: Paket is designed to work with various package sources, including NuGet, GitHub, and Git repositories. It's more agnostic in terms of package sources.

5. **Community and Ecosystem**:
   - **NuGet**: NuGet has a larger community and is the default package manager for many .NET projects. It has a wide selection of packages available on the official repository.
   - **Paket**: Paket has a smaller community but is favored by some developers, especially those who value fine-grained control over dependencies.

6. **Tooling**:
   - **NuGet**: NuGet has extensive tooling support within Visual Studio and other IDEs. It also has a command-line interface (CLI) for package management.
   - **Paket**: Paket primarily relies on its CLI for package management and may have less integrated tooling within IDEs.

Ultimately, the choice between Paket and NuGet depends on your specific project requirements and preferences. NuGet is a good choice for projects that benefit from the convenience of a centralized package repository, while Paket is better suited for those who prioritize fine-grained control over dependencies and want a more flexible resolution system.

**Comment by Arshia001** [comment]
The first attempt at this issue is available in the `feature/paket` branch, but the code doesn't work yet.

**Comment by kalambet** [comment]
After internal team discussion feasibility of this implementation is quite low. Closing till better times.
