### ISSUE TITLE
Failure to Show Connect Window When window.ethereum is Unavailable

### ISSUE THREAD

**Issue by RWeebz** [ChainSafe/web3.unity#449]
**Bug Description**:
When the webgl script is unable to locate the presence of window.ethereum (e.g., Metamask) in the user's browser, the popup window to connect an alternative wallet provider fails to appear.

**Expected behavior**
If the script cannot find window.ethereum, it should display the connect window and allow the user to connect using another provider such as WalletConnect, Torus, etc.

**Screenshots**
<img width="789" alt="image" src="https://github.com/ChainSafe/web3.unity/assets/75969194/71303d95-85c9-4264-9f3a-7707e3328ea3">

**Steps to Reproduce**:
1. Open the web application in a browser without Metamask or any similar wallet extension installed.
2. Trigger the event that should prompt the connect window to appear.

**Actual Result**:
No connect window is shown, preventing the user from connecting through an alternative wallet provider.

**Expected Result**:
When window.ethereum is not found, the script should display the connect window, enabling the user to connect using another wallet provider.

**Desktop (please complete the following information):**
 - Chainsafe SDK version: 2.1.0
 - Unity Platform: WebGL

Thank you for your attention to this matter. Please let me know if any further information is required.

**Comment by sneakzttv** [comment]
Fixed in the upcoming release.
