### ISSUE TITLE
Integrate WebJS as Web3 component for user

### ISSUE THREAD

**Issue by lucas-shamrock** [ChainSafe/web3.unity#45]
As my point of view, there seems no mandatory use of chainsafe gaming api for some contract calls. Why don't we just integate the Web3Js for user to use the customizable and headless SMC things?

**Comment by KBryan** [comment]
Is there something specific that you would like added to the SDK?

**Comment by lucas-shamrock** [comment]
Like those EVM functions you guys implemented via chainsafe gaming api, if the api is down, all goes down. But we could acutually wrap Web3Js to use those functions

**Comment by KBryan** [comment]
We have added a larger goal of decentralization. Thank you for your post. We will keep the community updated on the progress of this.
