### ISSUE TITLE
Update web3.unity GameObjects to Entities

### ISSUE THREAD

**Issue by KBryan** [ChainSafe/web3.unity#454]
With the latest release of Unity3d 2022. ECS is now out of preview mode and is at full release. This changes the way game developers work in Unity and will become the de facto standard moving forward. It would be a good idea to get ahead of the curve and update our tools to support this.

**Comment by empea-careercriminal** [comment]
@oleksandrchainsafe @kantagara What is your opinion on ECS? Worth it or just another hype?

From an on-chain gaming perspective, it is the de-facto standard already. The significant frameworks [MUD](https://mud.dev/) and [Dojo](https://www.dojoengine.org/en/) extensively use it.

**Comment by kantagara** [comment]
It's not a hype. But ECS doesn't make much sense in regards to our own SDK. 
We might add some sort of an ECS support later,  but it's really hard to tell when will that happen.

**Comment by kantagara** [comment]
@boorich MUD and DOJO are frameworks that haven't even been built in Unity and are then of course not using the Unitys ECS stack which OP is mentioning.

**Comment by boorich** [comment]
I agree. This massive change introduces a lot of cognitive overhead for developers and an enormous development and maintenance overhead for us. What we might do instead at a later point in time would be to prototype a specific client for some on-chain world and see if we can make use of Unity's in-build ECS capabilities. If we don't find a worthy problem to tackle with ECS, then it's probably too early to work on it.
