### ISSUE TITLE
EIP 712 - W3A features

### ISSUE THREAD

**Issue by RyRy79261** [ChainSafe/web3.unity#462]
**Summary**

In reference to #444 , this ticket seeks to add EIP712 signatures to Web3Auth's wallet

**Suggested features or ways to address the summary**

Syntactically, this should align with Nethereum since we have access to an in memory private key.

**Comment by janegabitova** [comment]
ticket is blocked by #475 that is about to be merged

**Comment by janegabitova** [comment]
23-06-23: not blocked anymore; should be ready to review by Monday
