### ISSUE TITLE
Add inline code documentation

### ISSUE THREAD

**Issue by Arshia001** [ChainSafe/web3.unity#466]
Add documentation for the SDK API methods and types.

Rules for writing the docsstring:
global.ruleset will enforce the stylecop rule [SA1600](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/DocumentationRules.md) trough most of the code. For some service implementations, like LootboxService that only implements ILootboxService, we should just add #pragma warning disable SA1600 to the top of the .cs file. If you want to restore the rules you should do the #pragma warning restore SA1600 

Things that **must** have docsstring:
* class definition (what it is, what it does)
* public properties
* public methods
* public events and delegates

private things are **not** needed to have comments. Add them if they're essential to some of the public identifiers listed above.

- [x] #667
- [x] #668
- [x] #669
- [x] #670
- [x] #671

**Comment by kalambet** [comment]
We need to understand what Interfaces and Function Signatures needs this type of inline comment and create separate issues for the actual code base update.

**Comment by kalambet** [comment]
This issue is re-used for the Feature Driver initiative and currently covers all the inline code documentation and not only public facing contracts.

The DoD for this feature is near 100% coverage of inline docs in the SDK.

**Comment by empea-careercriminal** [comment]
@kantagara please make sure to assign @nftpixels or @sneakzttv to review once this becomes a PR.

**Comment by sneakzttv** [comment]
Complete with the latest PRs.
