### ISSUE TITLE
Rename namespaces in the core libraries

### ISSUE THREAD

**Issue by Arshia001** [ChainSafe/web3.unity#472]
Currently, we're using a few different namespaces, and none of them make a lot of sense for the overall architecture of the project. We should unify all namespaces and stick to having one root namespace per library, and namespaces inside each library should reflect the folder structure of the code.

**Comment by alexvotofuture** [comment]
@Arshia001 @KBryan @RyRy79261 to review.

**Comment by oleksandrchainsafe** [comment]
Waiting for #534 to be merged in. Then all the changes should be updated for the new format.

**Comment by kalambet** [comment]
Closed as duplicate to #604
