### ISSUE TITLE
HTTP.Get responded with error: HTTP/1.1 404 Not Found in Web3Builder

### ISSUE THREAD

**Issue by KBryan** [ChainSafe/web3.unity#481]
**Describe the bug**

HTTP.Get responded with error: HTTP/1.1 404 Not Found in Web3Builder is thrown when using non infura rpc urls.

**To Reproduce**
Steps to reproduce the behaviour:
1. ChainSafe Server Settings
2. Update RPC url ex. https://staging-faint-slimy-achird.explorer.staging-v3.skalenodes.com/
3. Update server settings
4. HTTP.Get responded with error: HTTP/1.1 404 Not Found shown in the console.

**Expected behaviour**
The developer should be able to use any compatible evm chain within the ChainSafe server settings.

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.
![Screenshot 2023-06-19 174936.png](https://images.zenhubusercontent.com/6137990931d6083b33ca18e9/1feab3a7-70bf-4ac2-a194-6c6b9d9c27f8)

**Desktop (please complete the following information):**
 - Chainsafe SDK version: 2.5 main branch
 - Unity Platform: [Windows, Mac, Linux or WebGL ]
 - Unity version  2022.2.3f1
 - OS [Windows]

**Comment by kalambet** [comment]
Fixed with #534
