### ISSUE TITLE
unable to connect with metamask 

### ISSUE THREAD

**Issue by arslanpixpel** [ChainSafe/web3.unity#482]
I've tried to connect with 2 ways to metamask and getting error for both 2 ways

1 way:
create a new folder within the WebTemplate directory and add the following files from this directory in it. Within the build setting select this new template and tell me if you run into the same issue. Within the network.js file update the chainId to the one you wish to connect 

got error from this method is 
<img width="370" alt="er" src="https://github.com/ChainSafe/web3.unity/assets/135733448/2a1d0219-e67e-4800-80c6-e564aa512298">

2nd way:
described all the stuff in network tab
![err2](https://github.com/ChainSafe/web3.unity/assets/135733448/d818a4ec-a07a-4e26-b7be-9e5cf02b824c)

got error from this is
<img width="463" alt="err3" src="https://github.com/ChainSafe/web3.unity/assets/135733448/808ae294-103d-40a7-b14d-9e2f02c7072c">

Your help will be appreciated

my chainsafe version is v2

**Comment by sneakzttv** [comment]
Fixed in the upcoming release.
