### ISSUE TITLE
Implement multicall on the SDK side

### ISSUE THREAD

**Issue by Arshia001** [ChainSafe/web3.unity#484]
There is an existing implementation in the API, which can be moved to the SDK side. This is the code in question:

https://github.com/ChainSafe/game-api/blob/main/src/routes/evm/multicall.ts

**Comment by kalambet** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ChainSafe-Gaming-60e61b3eabd687000e7ce3b2/issues/ChainSafe/web3.unity/484?planning-poker) with Zenhub @kalambet @oleksandrchainsafe @robGG1997 @RyRy79261 @sneakzttv

**Comment by kalambet** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ChainSafe-Gaming-60e61b3eabd687000e7ce3b2/issues/ChainSafe/web3.unity/484?planning-poker) with Zenhub @kalambet @oleksandrchainsafe @robGG1997 @RyRy79261 @sneakzttv @kantagara
