### ISSUE TITLE
how dow I add and customize the ethereum.on('accountsChanged', (accounts) )

### ISSUE THREAD

**Issue by thienvmo** [ChainSafe/web3.unity#49]
*User Story**
As a [stakeholder persona] I want to [action] so that [goal].

**Suggested features or ways to address the user story**
[A clear and concise description of any potential solutions or features you've considered that might help solve the need/problem above.]

**Completion Criteria**
- [ ] Criteria 1

**Additional context**

**Comment by KBryan** [comment]
We have opened up game-webgl this will allow you more customization please have a look at this repo. https://github.com/ChainSafe/game-web3gl

**Comment by alexvotofuture** [comment]
@thienvmo are you now able to do what you needed to do? If so, could you please close this issue?
