### ISSUE TITLE
Expose fields in ERC20CustomTokenBalance script

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#492]
**Describe the bug**
Currently in **ERC20CustomTokenBalance.cs** we have the variables contractAbi and contractAddress with empty values that we need to set manually before using this script. It will be nice to have these variables public so we can edit them in the Unity editor.

**To Reproduce**
1. Add the ERC20CustomTokenBalance script into a empty game object
2. Try to run the scene

**Expected behavior**
After adding the ERC20CustomTokenBalance script, the developer should be able to add the values for contractAbi and contractAddress using the editor in Unity

**Screenshots**
<img width="1095" alt="Screenshot 2023-06-23 at 16 34 18" src="https://github.com/ChainSafe/web3.unity/assets/104365141/a3d4faa2-fbe2-48c6-a866-1e20cfd72e9a">

**Comment by Arshia001** [comment]
Fixed in #486

**Comment by juans-chainsafe** [comment]
This was fixed, now I'm able to put the contractAddress and contractAbi in the Unity editor.
But, I wasn't able to get the balance of a contract, I always get the error "function not found balanceOf", I created a separate ticket for that: https://github.com/ChainSafe/web3.unity/issues/520
cc @Arshia001
