### ISSUE TITLE
CreateCancelNftTransaction request is failing

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#493]
**Describe the bug**
On EVM.cs the request **/createCancelNftTransaction** in CreateCancelNftTransaction function is failing because 1 of the parameters is wrong.

**Solution**
Change "**tokenId**" with "**itemId**" in the last form field that we add (line 181).
<img width="952" alt="Screenshot 2023-06-23 at 16 38 03" src="https://github.com/ChainSafe/web3.unity/assets/104365141/fb8f510a-f022-41b0-b5a2-265a15a4dd15">

**Comment by Arshia001** [comment]
Fixed in #486

**Comment by juans-chainsafe** [comment]
Nice! @Arshia001 we don't have a prefab or script for this, should be have one?
