### ISSUE TITLE
Prefab for W3A

### ISSUE THREAD

**Issue by RyRy79261** [ChainSafe/web3.unity#494]
**Summary**
A example Prefab for W3A usage

**Comment by KBryan** [comment]
Create an interactive prefab that interacts and displays the following properties.

- [ ]  Sign
- [ ]  Verify
- [ ]  Contract Read
- [ ]  Contract Write
- [ ]  Mint Token
- [ ]  Transfer Token

https://github.com/ChainSafe/web3.unity/pull/508
