### ISSUE TITLE
Create a documentation for V2.5

### ISSUE THREAD

**Issue by oleksandrchainsafe** [ChainSafe/web3.unity#495]
As the API for the SDK was updated dramatically, we have to create a new version of documentation explaining the new way of using the SDK.
The result of this ticket should be a new folder with all the required *.md files inside [game-docs-v2](https://github.com/ChainSafe/game-docs-v2/tree/main/docs) repository.  For each step or topic we want to communicate we'd have to create an *.md file. The output of this task would then be passed to DevRel for further editing & improvement.

**Comment by oleksandrchainsafe** [comment]
As the API for the SDK was updated dramatically, we have to create a new version of documentation explaining the new way of using the SDK.
The result of this ticket should be a new folder with all the required *.md files inside [game-docs-v2](https://github.com/ChainSafe/game-docs-v2/tree/main/docs) repository.  For each step or topic we want to communicate we'd have to create an *.md file. The output of this task would then be passed to DevRel for further editing & improvement.

**Comment by janegabitova** [comment]
Jul 7th 2023: about 60%; to be finished at the end of the next sprint

**Comment by oleksandrchainsafe** [comment]
Need to check all code examples to be in sync with the release version of the API

**Comment by janegabitova** [comment]
July 21st 2023: currently at 7.5 pages, with about 3 more to go. scope adjusts based on findings while drafting. style: manual of how to use + examples

**Comment by janegabitova** [comment]
Aug 4, 2023: pages are complete; last edits under work to be passed off to devrel on Monday

**Comment by oleksandrchainsafe** [comment]
Passed off to DevRel

**Comment by sneakzttv** [comment]
Documentation complete for 2.5.0, just adding changes for 2.5.1 as they're ready.

**Comment by sneakzttv** [comment]
Complete.
