### ISSUE TITLE
Expose fields in IPFSUploadExample script 

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#504]
**Describe the bug**
Currently in **IPFSUploadExample.cs** we have the variables apiKey and YOUR_DATA with empty values that we need to set manually before using this script. It will be nice to have these variables public so we can edit them in the Unity editor.

**To Reproduce**
1. Add the IPFSUploadExample script into a empty game object
2. Try to run the scene

**Expected behavior**
After adding the IPFSUploadExample script, the developer should be able to add the values for apiKey and image data using the editor in Unity

**Screenshots**
<img width="1394" alt="Screenshot 2023-06-29 at 13 47 32" src="https://github.com/ChainSafe/web3.unity/assets/104365141/9a77b476-6087-499d-a86c-6be6f502d80d">

**Comment by Arshia001** [comment]
Fixed in #486

**Comment by juans-chainsafe** [comment]
@Arshia001 thanks for adding this! but I just realise that we should expose as well:

- BUCKET_ID
- File path
- File name
Otherwise they need to modify those values in the cs file.

Something minor, looks like is not considering the path parameter, I added /test so it adds to my test folder in ChainSafe Storage but it adds the file on the root folder anyways (main bucket folder)

**Comment by Arshia001** [comment]
Fields are exposed. Regarding the path, I have no idea, but I can say with certainty that the code was not changed from the previous version.

**Comment by juans-chainsafe** [comment]
Fields exposed correctly
