### ISSUE TITLE
Get nonce and Get tx status asks to switch to eth mainnet

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#506]
**Describe the bug**
The redirect URL that you get from these scripts is making that Metamask asks to switch to ETH mainnet, but I'm on Goerli all the time (even the player settings)

**To Reproduce**
1. Add an empty game object
2. Drag and drop **GetNonce** and **GetTxStatus** to the game object
3. Click play with the LoginScene first
4. Do the login with Metamask
5. See error

**Expected behavior**
Metamask notification appear to sign the transactions

**Additional context**
This is the generated URL: `https://chainsafe.github.io/game-web3wallet/?action=send&chainId=&to=0xaBed4239E4855E120fDA34aDBEABDd2911626BA1&value=100000&data=&gasLimit=&gasPrice=`

This happens with Scripts/Samples/Wallet/GetNonce and Scripts/Samples/Wallet/GetTxStatus 
I found this while testing https://github.com/ChainSafe/web3.unity/pull/486

**Comment by Arshia001** [comment]
Fixed in #486

**Comment by juans-chainsafe** [comment]
Get Nonce is working as expected!

But GetTxStatus it still has a error, I will create a separate issue, because is not related to the switch to mainnet.
