### ISSUE TITLE
Invalid URL for SendArray, ContractCall and Transfer20

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#507]
**Describe the bug**
The redirect URL that you get from these scripts is invalid, probably the error is related

**To Reproduce**
1. Add an empty game object
2. Drag and drop **SendArray**, **ContractCall** and **Transfer20** to the game object
3. Click play with the LoginScene first
4. Do the login with Metamask
5. See error

**Expected behavior**
You are able to sign the transactions for the scripts

**Console errors**
These are the invalid URLs that I get from the scripts:
- SendArray: https://chainsafe.github.io/game-web3wallet/?action=send&chainId=&to=0xc778417e063141139fce010982780140aa0cd5ab&value=&data=0xa9059cbb000000000000000000000000dd4c825203f97984e7867f11eecc813a036089d10000000000000000000000000000000000000000000000001000000000000000&gasLimit=&gasPrice=
- ContractCall: https://chainsafe.github.io/game-web3wallet/?action=send&chainId=&to=0x7286Cf0F6E80014ea75Dbc25F545A3be90F4904F&value=&data=0xb76b97230000000000000000000000000000000000000000000000000000000000000001&gasLimit=&gasPrice=
- Transfer20: https://chainsafe.github.io/game-web3wallet/?action=send&chainId=&to=0x5244d0453A727EDa96299384370359f4A2B5b20a&value=&data=0xd4e6ecb900000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000002000000000000000000000000fb3aecf08940785d4fb3ad87cdc6e1ceb20e9aac00000000000000000000000092d4040e4f3591e60644aaa483821d1bd87001e3&gasLimit=&gasPrice=

**Additional context**
This happens with:
- Scripts/Samples/Wallet/SendArray 
- Scripts/Samples/Wallet/ContractCall
- Scripts/Samples/Wallet/Transfer20

**I found this while testing https://github.com/ChainSafe/web3.unity/pull/486**

**Comment by Arshia001** [comment]
Fixed in #486

**Comment by juans-chainsafe** [comment]
This error is fixed! but the scripts are not working as expected yet, but due to a different issue related to https://github.com/ChainSafe/web3.unity/issues/521#issuecomment-1629355909
