### ISSUE TITLE
Is it possible to provide UPM installation? Or at least tgz release

### ISSUE THREAD

**Issue by Thaina** [ChainSafe/web3.unity#51]
**User Story**

Installing package without messing with project folder structure is advantageous. unitypackage should be considered out of interest

**Suggested features or ways to address the user story**
Please change this repo structure to support upm installing, with `package.json` and folder path specified

Alternatively, at least provide `tgz` release alongside `unitypackage` so we could download and install with upm without import unitypackage into our project

**Completion Criteria**
-

**Additional context**
-

**Comment by KBryan** [comment]
I'm sure it's possible to add installation from a git repo. I'll talk with the team today about adding support for this.

**Comment by Thaina** [comment]
Thank you very much

**Comment by sneakzttv** [comment]
As we're progressing, changing the file structure of the sdk would break prefabs and a bunch of things that have been set up. I don't think this would be possible anymore sorry.
