### ISSUE TITLE
Create an event poller service to monitor and raise events

### ISSUE THREAD

**Issue by Arshia001** [ChainSafe/web3.unity#510]
**Summary**
Support custom smart contract events.

**Description**
The DoD for this issues is to:
1. Provide description of potential solution in a comment
    a. Consider if background process/threads are needed 
    b. Make sure that you took into account mobile (specifically iOS) and WebGL solutions
3. If solution requires complete revisit of the polling operations - create separate implementation issue(s)

**Comment by empea-careercriminal** [comment]
@kantagara and @kalambet ... description is weak. Once this one has been discussed, would you please update the description or close ... 🙏🏼

**Comment by sneakzttv** [comment]
Closing and reopening.
