### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by morybest** [ChainSafe/web3.unity#516]
Connect to wallet in build (android and  stand alone)

I created a new project based on chainSafe unity package  and I created an Android version. but after press login button it stock in first loading page on browser.

I'm using unity 2021.3.17.

![photo_2023-07-03_15-27-49](https://github.com/ChainSafe/web3.unity/assets/34394036/63f6d694-41b9-437a-b003-ab2a53dca668)

Test apk:
https://drive.google.com/file/d/10NwUIBd4Ep7CrdZzfew9jwpyatW51ZBU/view?usp=sharing

**Comment by sneakzttv** [comment]
Fixed in the upcoming release
