### ISSUE TITLE
Drop WebGl template and interact with browser wallets directly

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/web3.unity#517]
**Summary**
Currently, https://github.com/ChainSafe/web3.unity-webgl-template is severely limiting the functionality of SDK and increasing the size of games unnecessarily. 

**Suggested features or ways to address the summary**

Implement interaction with window.ethereum directly. Example: https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Unity.Metamask/NethereumMetamask.jslib

This means we will lose the WalletConnect option which we used through the web interface and instead, we should implement natively in C# using existing libraries (https://github.com/WalletConnect/WalletConnectSharp) which would enable wallet to connect across all platforms and not just on the web.

**Motivation**
[Why is this feature of general interest?]
- faster game loading
- more options for game developers
- less maintenance on our side
- better error control and handling

**Blockers**
(OPTIONAL) [Do you see any blocker that needs to be done before implementing this feature?]

**Additional context**
(OPTIONAL) [Add any other context or screenshots/videos about the feature request here.]

**Comment by sneakzttv** [comment]
Unity unfortunately has no JS environment without a browser present and the webgl template to set the JS bindings. We need to build an environment natively if we want this to happen which afaik hasn't been achieved yet by anyone. It is something we're actively looking into though once we're done with this release.

**Comment by empea-careercriminal** [comment]
Why webGL only might not be enough for many game developers:

**Abstraction Overhead**
WebGL is an abstraction layer between your JavaScript code and the native GPU drivers. While this abstraction is designed to be efficient, there may be some overhead compared to writing native GPU code in languages like C++ or CUDA.

**Browser Compatibility**
WebGL is not supported in all web browsers, although it is widely supported in modern browsers. Compatibility issues could require developers to write fallback code for browsers that do not support WebGL or use alternative technologies.

**Security Concerns**
WebGL exposes low-level graphics capabilities of the GPU to web content, which raises some security concerns. Browser vendors have implemented security measures to mitigate these risks, but developers should be aware of potential security issues.

**Performance Optimization**
While WebGL can deliver excellent performance, optimizing WebGL applications can be challenging. Developers need to have a good understanding of graphics programming techniques and performance profiling tools to achieve optimal results.

**Comment by mpetrunic** [comment]
Keep in mind this issue is not really related to removing webgl. Its about removing our template which is a full blown webapp with heavy dependencies(that exposes complex api to unity) in favour of super light jslib bundled with web3.unity that doesn't have any dependencies and just provide bridge to interact with injected providers.

**Comment by empea-careercriminal** [comment]
This is to be re-visited after WalletConnectV2 has been completed.

**Comment by robGG1997** [comment]
As far as we know Wallet Connect doesn't connect to browser extension wallets, however it connects to mobile and desktop wallets and those sessions might be persisted across platforms if the wallet supports it. We're currently in the process of finalizing Wallet Connect integration using [WalletConnectSharp](https://github.com/WalletConnect/WalletConnectSharp), you can take a look at this pull request to demo it #627

**Comment by kalambet** [comment]
Absence of the WalletConnect WebGL integration right now will be a known limitation.
We need to re-assess our options in 2.5.2 and for 2.5.1 probably keep this template for now unless other opportunities will arise.

**Comment by robGG1997** [comment]
> > Absence of the WalletConnect WebGL integration right now will be a known limitation. We need to re-assess our options in 2.5.2 and for 2.5.1 probably keep this template for now unless other opportunities will arise.
> 
> WalletConnect unity package is not working in WebGL env? (🙄 )

It does, but we can't connect to browser wallets.

**Comment by robGG1997** [comment]
> > > Absence of the WalletConnect WebGL integration right now will be a known limitation. We need to re-assess our options in 2.5.2 and for 2.5.1 probably keep this template for now unless other opportunities will arise.
> > 
> > 
> > WalletConnect unity package is not working in WebGL env? (🙄 )
> 
> It does, but we can't connect to browser wallets.

We intend on implementing browser extension wallet connections separately for specific knows wallets such as MetaMask

**Comment by robGG1997** [comment]
> > > > Absence of the WalletConnect WebGL integration right now will be a known limitation. We need to re-assess our options in 2.5.2 and for 2.5.1 probably keep this template for now unless other opportunities will arise.
> > > 
> > > 
> > > WalletConnect unity package is not working in WebGL env? (🙄 )
> > 
> > 
> > It does, but we can't connect to browser wallets.
> 
> But if you can connect to browser wallets directly with https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Unity.Metamask/NethereumMetamask.jslib why would you need to connect to them with wallet connect? 😄
> 
> The goal of this issue was to remove bloatware: https://github.com/ChainSafe/web3.unity-webgl-template and replace it with [NethereumMetamask.jslib](https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Unity.Metamask/NethereumMetamask.jslib) + WalletConnect unity package.

Exactly, we're aware of the limitation as @kalambet mentioned [here](https://github.com/ChainSafe/web3.unity/issues/517#issuecomment-1757947793) but we've completed WC implementations (it's on main branch), we'll move on to MetaMask implementation next and phase out the webgl-template. This issue is still in progress we've not marked it as completed or closed.

**Comment by mpetrunic** [comment]
@robGG1997 Can https://github.com/ChainSafe/web3.unity-webgl-template be arhived now?
