### ISSUE TITLE
Get Voucher not working on WebGL

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#528]
**Describe the bug**
Get721Voucher and Get1155Voucher are not working correctly on a WebGL build, I get a CORS error on `https://lazy-minting-voucher-signer.herokuapp.com/voucher721?receiver=0xabed4239e4855e120fda34adbeabdd2911626ba1` endpoint

**To Reproduce**
1. Add the **VoucherMinter721** or **VoucherMinter1155** prefab on SampleScene
2. Build and run with WebGL
3. After build finishes, do the login connecting to a wallet on the browser
4. Click on **Get Voucher Mint 721** (or 1155)
5. See console error

**Expected behavior**
Voucher is generated and the user needs to sign the transaction on his wallet

**Screenshots**
<img width="1662" alt="Screenshot 2023-07-19 at 12 44 03" src="https://github.com/ChainSafe/web3.unity/assets/104365141/f566725f-c9f3-444e-9de1-8501cd4cc6dd">

**Desktop (please complete the following information):**
 - Chainsafe SDK version: [latest]
 - Unity Platform: [WebGL ]
 - Unity version [2022]
 - OS [Mac]

**Additional context**
`Access to fetch at 'https://lazy-minting-voucher-signer.herokuapp.com/voucher721?receiver=0xabed4239e4855e120fda34adbeabdd2911626ba1' from origin 'http://localhost:50437' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by Arshia001** [comment]
This needs to be fixed in the heroku app, nothing to do on the SDK side. Do we know who owns that?

**Comment by juans-chainsafe** [comment]
> This needs to be fixed in the heroku app, nothing to do on the SDK side. Do we know who owns that?

yes, @sneakzttv

**Comment by sneakzttv** [comment]
@FSM1 has ownership of this at the moment, the card needs to be refreshed, however i was booting up a local instance with this on docker and it doesn't seem to be happy. I don't think our api endpoint is STORAGE_API_URL="https://api.chainsafe.io/api/v1" anymore as it doesn't seem to be active on simple inspection. 
![image](https://github.com/ChainSafe/web3.unity/assets/57473220/7c7c89d5-52a8-4a88-b24c-1c7958919803)

**Comment by juans-chainsafe** [comment]
> https://api.chainsafe.io/api/v1

For what I see, https://api.chainsafe.io/api/v1/ is working but is using a Bearer authentication

**Comment by sneakzttv** [comment]
This is what i get when i hit that api with insomnia and a bearer token with a local docker instance running
![image](https://github.com/ChainSafe/web3.unity/assets/57473220/dabf332f-2a18-48e9-b34f-90a2c62de166)

**Comment by sneakzttv** [comment]
if we just renew that card on heroku and expense the $5 a month for the dyno hours so it doesn't sleep this issue is resolved xD

**Comment by kalambet** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ChainSafe-Gaming-60e61b3eabd687000e7ce3b2/issues/ChainSafe/web3.unity/528?planning-poker) with Zenhub @kalambet @oleksandrchainsafe @robGG1997 @RyRy79261 @sneakzttv

**Comment by kalambet** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ChainSafe-Gaming-60e61b3eabd687000e7ce3b2/issues/ChainSafe/web3.unity/528?planning-poker) with Zenhub @kalambet @oleksandrchainsafe @robGG1997 @RyRy79261 @sneakzttv @kantagara

**Comment by sneakzttv** [comment]
almost complete

**Comment by sneakzttv** [comment]
merged and complete
