### ISSUE TITLE
Design & Implement a Sample Scene for Lootboxes functionality

### ISSUE THREAD

**Issue by oleksandrchainsafe** [ChainSafe/web3.unity#533]
**Title: Implementing Ethereum loot boxes UI - Unity SDK Integration**

**Issue Description:**

**Overview:**
This GitHub issue aims to focus on implementing the user interface (UI) part for Ethereum Lootboxes functionality as a sample scene within our Unity SDK. The goal is to provide a user-friendly interface for game developers using our Unity SDK, allowing players to browse, purchase, and open loot boxes on the Ethereum blockchain.

**Features and Requirements:**

1. **Lootboxes UI Design:**

- [x] Collaborate with the team responsible for Ethereum loot boxes smart contract logic to understand the required UI elements and user flows.
- [ ] Design intuitive and visually appealing UI elements for browsing available Lootboxes and their contents.

2. **Open Flow:**

- [x] Implement a seamless UI flow for players to open loot boxes using Ethereum

3. **Lootbox Opening Animation:**

- [x] Create simple animations for opening Lootboxes and revealing the acquired items.
- [ ] Ensure smooth and visually appealing transitions to enhance the player experience.

4. **Error Handling and Feedback:**

- [ ] Implement user-friendly error messages and feedback to guide players in case of unsuccessful transactions or network issues.
- [ ] Provide appropriate visual cues to inform players about the status of their actions.

**Expected Deliverables:**

- Fully functional and visually appealing UI for Ethereum Lootboxes integration within the Unity SDK.
- Smooth animations for Lootbox opening and item reveal.
- A well-tested UI implementation

**Comment by empea-careercriminal** [comment]
This would benefit from polishing. Being dependent on a terminal to operate the flow from within Unity is problematic.

Make sure that all user interaction (as a player) happens from within the Unity player and does not require transactions to be made in separate applications to succeed.

**Comment by empea-careercriminal** [comment]
![image](https://github.com/ChainSafe/web3.unity/assets/2900501/74ab42c1-c946-4152-8053-6ed4ec7e2b8d)

**Comment by kantagara** [comment]
@oleksandrchainsafe I'd re-visit this one. 

- [ ] If it's possible, make it easy to generate/deploy lootbox smart contracts directly from the dashboard
- [ ] Then, paste lootbox smart contract address directly into sample scene - that way we don't have to refill lootboxes but devs themselves should be responsible for it
- [ ] Profit

**Comment by kantagara** [comment]
my comment is a duplicate now, closing in favor of #1024
