### ISSUE TITLE
Current state of mobile support 

### ISSUE THREAD

**Issue by lim64952** [ChainSafe/web3.unity#54]
From what I see the mobile branch has no updates for 4 months. Will it merge into main branch soon?

**Comment by KBryan** [comment]
This feature is currently being worked on. It still depends on some outside dependencies. Please follow this link and comment. https://github.com/MetaMask/metamask-mobile/issues/3399

**Comment by moheydy** [comment]
When it works on Android, why did you leave it halfway? i need send and call function for ERC1155

**Comment by ilmarioranen** [comment]
Is that MetaMask the main issue stopping mobile branch from going anywhere? 

I commented on the issue hoping it will get some attention but I would still think that the mobile stuff could maybe move forward technically even while waiting for MetaMask, right?

**Comment by KBryan** [comment]
Unfortunately, it's a blocker atm and we appreciate you commenting on this issue and helping to move this along.

**Comment by Asw-S93** [comment]
I really hope the mobile branch gets an update and has missing scripts refs in the scene fixed ;)

**Comment by cagatayisikcoda** [comment]
Is there any update on this ? There is a tutorial about mobile setup but since this mobile branch has missing references and other issues.  It is unusable right now.

**Comment by leon-do** [comment]
@cagatayisikcoda Seth and I will make sure to update here https://github.com/MetaMask/metamask-mobile/issues/3399

**Comment by cagatayisikcoda** [comment]
@leon-do Thank you, we appreciate all the hard work you guys put in to make us use this great product.

**Comment by KBryan** [comment]
We have made updates to our mobile offerings.  As an update, we are still experiencing a deep linking issue with Android 12 that is documented here. This issue doesn't effect iOS. https://github.com/MetaMask/metamask-mobile/issues/3678
