### ISSUE TITLE
EVM.CreateMint() returns null response

### ISSUE THREAD

**Issue by QuickMaster** [ChainSafe/web3.unity#542]
**Describe the bug**
We were trying to mint the NFT on Eth (Mainnet, Testnets: Rinkbey, Goerli) also on BSC (Testnet)
We used this code:
![image (2)](https://github.com/ChainSafe/web3.unity/assets/106281210/b852d525-09ae-451d-9893-3b7906eadd4c)

But since the response is null we cannot continue on to the transaction, We have tried for Webgl & Desktop but same null response.
Here you can see:
![image (4)](https://github.com/ChainSafe/web3.unity/assets/106281210/62d42c5d-bf43-474f-baaf-f7b85e08c065)

Since the response is null we get an invalid url when tested with Goerli 

![image (5)](https://github.com/ChainSafe/web3.unity/assets/106281210/c48707be-eab0-4dfc-846c-b32d763854cf)

We then tried sending a request to https://api.gaming.chainsafe.io/evm/createMintNFTTransaction. Anyway sending a response directly resulted in the following response:
{"response":"not supported with CIDv0, to support different bases, please migrate the instance do CIDv1, you can do that through cid.toV1()"} 

The cid: **QmSBz7P4CA6bTvJTQsXTGiVoDiP5vcYcFi29TeogCqGXdn** 
which was obtained by uploading a json on chainsafe storage.
We then converted this cidv0 to cidv1
**Converted cid: bafybeihs4vj6dou7egzetzwornmdcx7krwtyxp2a7mr6hzsj2b2ealcs4a**

Using this converted cid resulted in the following response: {"response":"value out-of-bounds (argument=\"id\", value=\"0x01701220f2e553e1ba9f21b249e6ce8b58315fea8da78bbf40fb23e3e649d074402c52e0\", code=INVALID_ARGUMENT, version=abi/5.7.0)"}

but we can access the NFT json using this converted cid https://ipfs.io/ipfs/bafybeihs4vj6dou7egzetzwornmdcx7krwtyxp2a7mr6hzsj2b2ealcs4a

The function still doesn't return the required parameter's, what can be the reason?

Chainsafe version v2.1.0
Unity 2021.3.22f1
Unity platform WebGl, Windows, Mac, Linux

**Comment by ErselanT** [comment]
Hi @sneakzttv , Could you please tell us about this issue, what steps to resolve this or Will this be resolved in your next updated sdk and When it is expected to release? Actually we're stuck in a major implementation of our game due to this issue.

**Comment by sneakzttv** [comment]
Fixed in 2.5.1
