### ISSUE TITLE
Add Trust Wallet Provider

### ISSUE THREAD

**Issue by PrinceSyed** [ChainSafe/web3.unity#547]
**Summary**
Currently the chainsafe sdk does not work with trust wallet

**Suggested features or ways to address the summary**
Add trust wallet provider for webgl
https://github.com/trustwallet/trust-web3-provider

**Motivation**
Trust wallet has a large number of users (especially in asia pacific) and gamers that could access web based games using the DAAP browser in trust wallet. currently that does not work with chainsafe.

**Comment by kalambet** [comment]
Should be fixed with merge of the #627
