### ISSUE TITLE
Fail login with WalletConnect

### ISSUE THREAD

**Issue by Themvp07** [ChainSafe/web3.unity#548]
**Describe the bug**
When trying to use WC as authentication to login, the application fails to connect successfully. The timeout fails and finally it is not possible to make the connection. In the mobile applications from where the connection is attempted, an error message is displayed.
The issue is present in private experiences and it replicated in the main public demo experience
Environment tested: https://chainsafe.github.io/ChainSafe-Demo-WebGL/
**To Reproduce**
1. Deploy any experience using the web3dunity sdk
2. click on the login button
3. select the wallet connect option to view the QR
4. on the mobile device select the wallet connect option to scan the QR
5. connection fails

**Expected behavior**
After scanning the QR, you should have access to the experience displayed by connecting the wallet through WC and on the mobile device you should be able to appreciate the successful connection session

**Screenshots**
[If applicable, add screenshots or videos to help explain your problem]: https://drive.google.com/file/d/1uh5766z-n_pX2GagEyddUxf-0BWm-WyY/view?usp=sharing

**Desktop (please complete the following information):**
 - Chainsafe SDK version: [e.g. 1.5.0]
 - Unity Platform: [Windows, WebGL ]
 - Unity version [e.g. 2022.3.4f1]
 - OS [Windows]

**Additional context**
![MOB2](https://github.com/ChainSafe/web3.unity/assets/44710716/26f0d829-f4ae-410e-903a-2faeb177e803)
![MOB1](https://github.com/ChainSafe/web3.unity/assets/44710716/75d7cc1f-6661-4002-a545-7522893e62a5)

**Comment by sneakzttv** [comment]
Fixed in 2.5.1
