### ISSUE TITLE
[Bug] LoginWallet No prompt with metamask 

### ISSUE THREAD

**Issue by chile109** [ChainSafe/web3.unity#549]
**Describe the bug**
Try use SDK to connect to Polygon.
But when I test on wallet login scene. It is not able to login by metamask.

**To Reproduce**
1. Add the LoginWallet scene.
2. Run Play and click Login on browser.
3. No metamask sign prompt for login.

**Expected behavior**
metamask should prompt for login on Desktop.

**Screenshots**
[Thread] (https://discord.com/channels/593655374469660673/845686120292679761/1139095578077307001)

**Desktop (please complete the following information):**
 - Chainsafe SDK version: 2.1.0
 - Unity Platform: Mac Silcon
 - Unity version 2021.3.22f1
 - OS Mac 2022 M2

**Comment by sneakzttv** [comment]
This is an issue with M2 macbooks, they don't play nicely with many applications.

**Comment by sneakzttv** [comment]
fixed in 2.5.1
