### ISSUE TITLE
webgl on react

### ISSUE THREAD

**Issue by hsjo12** [ChainSafe/web3.unity#55]
Hello, 

I was following the basic chainsafe tutorial, exporting weblogin scene and the scene that the object becomes red when the token balance is more than 1 . 

So I tried to put the exported one on my react with react-unity-webgl.
(my unity editor : 2020.3.24f1(64bit) and webgl template 2020) 

And then now I can see the login button and the skip button on my react, and the skip button is working well to move to the next scene. 

However, when I clicked on the login button , 
The error message popped up, 
**Uncaught TypeError: Cannot read properties of undefined (reading 'connect')
    at _Web3Connect (webForReact.framework.js:2)**

so, I just go into my webForReact.framework.js and I can see **function _Web3Connect(){window.web3gl.connect()}**

so I guess window.web3gl.connect() is undefined... 

Do you have any idea? or can you give me any guide to connect  the webgl  and  react?

**Comment by KBryan** [comment]
Are you selecting the Web3GL Template for your project build?  This error usually refers to an exported game not selecting that and running with the default WebGL template.

**Comment by hsjo12** [comment]
> Are you selecting the Web3GL Template for your project build? This error usually refers to an exported game not selecting that and running with the default WebGL template.

Yeah I did Web3GL Template 2020

**Comment by KBryan** [comment]
The template uses React so the exported .html is what you would get from a React project. I don't see it being an issue but you would have to try it and see how it works.

**Comment by hsjo12** [comment]
> The template uses React so the exported .html is what you would get from a React project. I don't see it being an issue but you would have to try it and see how it works.

So, I have tried to replace the normal index.html with the index.html where I got from webgl. It seems works but I can see the index.html is a bit messy and there is a code to display unity and there is an error saying "Cannot read property 'forEach' of undefined" caused from several script tags in index.html. The error is actually makes react not working well;;

**Comment by hsjo12** [comment]
> The template uses React so the exported .html is what you would get from a React project. I don't see it being an issue but you would have to try it and see how it works.

So, I can see that "web3gl.connect()" is working when I put 4 scripts into the body tag in index.html

  <script src="network.js"></script>

  <script>!function (e) { function r(r) { for (var n, a, f = r[0], b = r[1], d = r[2], i = 0, l = []; i < f.length; i++)a = f[i], Object.prototype.hasOwnProperty.call(c, a) && c[a] && l.push(c[a][0]), c[a] = 0; for (n in b) Object.prototype.hasOwnProperty.call(b, n) && (e[n] = b[n]); for (u && u(r); l.length;)l.shift()(); return o.push.apply(o, d || []), t() } function t() { for (var e, r = 0; r < o.length; r++) { for (var t = o[r], n = !0, f = 1; f < t.length; f++) { var b = t[f]; 0 !== c[b] && (n = !1) } n && (o.splice(r--, 1), e = a(a.s = t[0])) } return e } var n = {}, c = { 21: 0 }, o = []; function a(r) { if (n[r]) return n[r].exports; var t = n[r] = { i: r, l: !1, exports: {} }; return e[r].call(t.exports, t, t.exports, a), t.l = !0, t.exports } a.e = function (e) { var r = [], t = c[e]; if (0 !== t) if (t) r.push(t[2]); else { var n = new Promise((function (r, n) { t = c[e] = [r, n] })); r.push(t[2] = n); var o, f = document.createElement("script"); f.charset = "utf-8", f.timeout = 120, a.nc && f.setAttribute("nonce", a.nc), f.src = function (e) { return a.p + "static/js/" + ({}[e] || e) + "." + { 0: "0a798628", 1: "865bf2e6", 2: "c11416cd", 3: "65798c34", 4: "dc5f8d9f", 5: "3d6cbd23", 6: "b4437de1", 7: "81b2580d", 8: "bdcc9f1e", 9: "7f5313c8", 10: "53f0e036", 11: "4176db13", 12: "43d1ebf0", 13: "55737ecb", 14: "18e7daf2", 15: "c74025be", 16: "b5aec44f", 17: "941848d2", 18: "0167a956", 19: "3629d7bb", 23: "94d12b69", 24: "b7e14fc4", 25: "27515676", 26: "29c08b23", 27: "e8fc63b9", 28: "cec6a2a8", 29: "ebd42ec8", 30: "87cb3f17", 31: "43122843", 32: "dba35db1", 33: "42157789", 34: "ce42bdb0", 35: "03f6d098", 36: "fb537949", 37: "de588ba9", 38: "75b07a3c", 39: "d67d88d5", 40: "4a3ca734", 41: "71b79cca", 42: "739f4fc5", 43: "f883171a", 44: "86cae328", 45: "0cdec5cf", 46: "849865a6", 47: "ed418324", 48: "71295be2", 49: "5610a25b", 50: "df2b666c", 51: "c0496ac0", 52: "0f27e260", 53: "50230abf", 54: "74b399b4", 55: "01c6065c", 56: "030421e5", 57: "18776dd4", 58: "7d17245a", 59: "42e20e5c", 60: "b8c1be62", 61: "de568b07", 62: "bebc50c7", 63: "6e7957e9", 64: "2f1dc9ce", 65: "1f3a68c2", 66: "26854cfa", 67: "3e99a151", 68: "1e521c04", 69: "84f5db00", 70: "57df2c34", 71: "c2765a24", 72: "f9dcb942", 73: "fd1717b5", 74: "a8e7431b", 75: "95789396", 76: "2452bb09", 77: "51d1b1c8", 78: "24a7428f", 79: "2289ab5e", 80: "294d3ae0", 81: "cb8dc4f6", 82: "7130bb3a", 83: "5ea78171", 84: "095919fe" }[e] + ".chunk.js" }(e); var b = new Error; o = function (r) { f.onerror = f.onload = null, clearTimeout(d); var t = c[e]; if (0 !== t) { if (t) { var n = r && ("load" === r.type ? "missing" : r.type), o = r && r.target && r.target.src; b.message = "Loading chunk " + e + " failed.\n(" + n + ": " + o + ")", b.name = "ChunkLoadError", b.type = n, b.request = o, t[1](b) } c[e] = void 0 } }; var d = setTimeout((function () { o({ type: "timeout", target: f }) }), 12e4); f.onerror = f.onload = o, document.head.appendChild(f) } return Promise.all(r) }, a.m = e, a.c = n, a.d = function (e, r, t) { a.o(e, r) || Object.defineProperty(e, r, { enumerable: !0, get: t }) }, a.r = function (e) { "undefined" != typeof Symbol && Symbol.toStringTag && Object.defineProperty(e, Symbol.toStringTag, { value: "Module" }), Object.defineProperty(e, "__esModule", { value: !0 }) }, a.t = function (e, r) { if (1 & r && (e = a(e)), 8 & r) return e; if (4 & r && "object" == typeof e && e && e.__esModule) return e; var t = Object.create(null); if (a.r(t), Object.defineProperty(t, "default", { enumerable: !0, value: e }), 2 & r && "string" != typeof e) for (var n in e) a.d(t, n, function (r) { return e[r] }.bind(null, n)); return t }, a.n = function (e) { var r = e && e.__esModule ? function () { return e.default } : function () { return e }; return a.d(r, "a", r), r }, a.o = function (e, r) { return Object.prototype.hasOwnProperty.call(e, r) }, a.p = "./", a.oe = function (e) { throw console.error(e), e }; var f = this.webpackJsonpweb3gl = this.webpackJsonpweb3gl || [], b = f.push.bind(f); f.push = r, f = f.slice(); for (var d = 0; d < f.length; d++)r(f[d]); var u = b; t() }([])</script>

<script src="./static/js/22.525f7c6b.chunk.js"></script>

<script src="./static/js/main.6702fceb.chunk.js"></script>

However, I have got this error 

react-dom.development.js:24156 Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')
    at startWorkOnPendingInteractions (react-dom.development.js:24156)
    at renderRootSync (react-dom.development.js:22663)
    at performSyncWorkOnRoot (react-dom.development.js:22293)

Do you know how to solve this ?

**Comment by KBryan** [comment]
This seems to be more with your implementation than an issue with the SDK template. I'm closing this issue as it's related to the output build of the SDK.
