### ISSUE TITLE
Unity NUnit tests

### ISSUE THREAD

**Issue by oleksandrchainsafe** [ChainSafe/web3.unity#552]
- Create first iteration of NUnit tests for Unity Test Framework (UTF).
- Make sure all of them are working as expected when executed from UTF window.

Most of those the tests will simply call methods that were developed as a result of #551

**Comment by sneakzttv** [comment]
Afaics this is complete and working on PRs right? @oleksandrchainsafe

**Comment by RyRy79261** [comment]
Lots of technical debt on my part but will look into this if its not done

**Comment by kalambet** [comment]
Instead of this bigger issue 4 smaller were created:
#597 
#598 
#599 
#600
