### ISSUE TITLE
EVM.CreateContractData and EVM.GasLimit throws 400 error saying invalid project ID.

### ISSUE THREAD

**Issue by Berns-s** [ChainSafe/web3.unity#558]
**Describe the bug**
I'm trying to get the GasLimit on 1.6. EVM.CreateContractData and EVM.GasLimit throws 400 error saying invalid project ID. I do call PlayerPrefs.GetString("ProjectID") before hand and it is set. 

**To Reproduce**
  string[] obj = { "0x9B1035160A12878b0A87aAff96578193b24b8A0c" };
        string args = JsonConvert.SerializeObject(obj);

         print("Project id " +PlayerPrefs.GetString("ProjectID"));

        string to = SettingsManager.instance._contract; // acount to send to
        string Value = "0"; // value to send in wei
        string data = await EVM.CreateContractData(SettingsManager.instance._abi, "SetRNDAddress", args);

        string gaslimit = await EVM.GasLimit(chain, network, rpc, to, Value, data);
        print("gaslimit " + gaslimit);

**Comment by sneakzttv** [comment]
This is fixed in 2.5
