### ISSUE TITLE
switch change to inactive account event 

### ISSUE THREAD

**Issue by thienvmo** [ChainSafe/web3.unity#56]
accountsChanged event is just working with all multiple active account
but it does not work when I change from active account to inactive (disconnected) account.
Please anyone give me a way to dectect this  change from active account to inactive account event??

**Comment by KBryan** [comment]
I don't think there is an event for detecting inactive accounts.

**Comment by sneakzttv** [comment]
The best you could do here is run a try catch method and then assign your player prefs to a different value when it catches.

**Comment by sneakzttv** [comment]
in web3gl.jslib add 
![image](https://user-images.githubusercontent.com/57473220/178848733-51209c91-81d8-4b83-bf81-24a0927b817b.png)
in weblogin.cs do this and assign it to a disconnect button
![image](https://user-images.githubusercontent.com/57473220/178848746-90c818d9-5697-4017-bedf-c58a6c063d79.png)
and that'l trigger an account swap in metamask and you can do what you need from there

**Comment by sneakzttv** [comment]
closing as completed

**Comment by thienvmo** [comment]
thanks @sneakzttv  so much. I will try your code.
