### ISSUE TITLE
ERC1155 BalanceOfBatch doesn't return array of balances

### ISSUE THREAD

**Issue by mattarad** [ChainSafe/web3.unity#561]
**Describe the bug**

When fetching more than one piece of data (e.g. balanceOfBatch from ERC1155), the contract only returns just a Big number Debug.Log for the result is below
-649379072
UnityEngine.Debug:Log (object)

I have had the issue on unity versions 2020.3.25 and 2022.3.6
using the BalanceOfBatch prefab, it only returns on big number. This has happened when I have tried fetching arrays from smart contracts.

A temp fix is to just call balanceOf multiple times, but this will slow down the game when you are pulling a lot of balances.

I have also tried pulling data that returns arrays, and I get a similar output.

**To Reproduce** -- simple
1. Add the LoginWallet scene
2. Add the prefab 'BalanceOfBatch1155'
No adjustments need to be made if you use Goerli since it will call BalanceOfBatch on Start and Debug.Log the output
3. See big number(sometimes negative) - in console

**Expected behavior**
Expectation is to the console list each balance using a Debug.Log

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Desktop (please complete the following information):**
 - Chainsafe SDK version: v2.0.1
 - I don't know what version of Chainsafe SDK was used on unity 2020
 - Unity Platform: WebGL 
 - Unity version 2020.3.25  and 2022.3.6
 - OS [e.g. Mac, Windows, Linux]

**Mobile (please complete the following information):**
 - Chainsafe SDK version: [e.g. 1.0.6]
 - Platform: [Android or iOS]
 - Emulator/Simulator - When hitting Play, and also in WebGL build
 - OS version [e.g. 11.6] (Optional)

**Additional context**

**Comment by mattarad** [comment]
did a quick test using version 2.0.3 and the ERC1155 BalanceOfBatch Prefab, and received a similar message in the console:

310526068
UnityEngine.Debug:Log (object)
Web3Unity.Scripts.Library.ETHEREUEM.EIP.ERC1155/<BalanceOfBatch>d__2:MoveNext ()
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<object[]>:SetResult (object[])
Web3Unity.Scripts.Library.Ethers.Contracts.Contract/<Call>d__10:MoveNext ()
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<string>:SetResult (string)
Web3Unity.Scripts.Library.Ethers.Providers.BaseProvider/<Call>d__30:MoveNext ()
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<string>:SetResult (string)
Web3Unity.Scripts.Library.Ethers.Providers.JsonRpcProvider/<Perform>d__11`1<string>:MoveNext ()
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<string>:SetResult (string)
Web3Unity.Scripts.Library.Ethers.Providers.JsonRpcProvider/<Send>d__10`1<string>:MoveNext ()
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<Nethereum.JsonRpc.Client.RpcMessages.RpcResponseMessage>:SetResult (Nethereum.JsonRpc.Client.RpcMessages.RpcResponseMessage)
Web3Unity.Scripts.Library.Ethers.Web.Web/<FetchJson>d__0`1<Nethereum.JsonRpc.Client.RpcMessages.RpcResponseMessage>:MoveNext ()
System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner:Run ()
IEnumeratorAwaitExtensions:RunOnUnityScheduler (System.Action)
IEnumeratorAwaitExtensions/SimpleCoroutineAwaiter`1<UnityEngine.AsyncOperation>:Complete (UnityEngine.AsyncOperation,System.Exception)
IEnumeratorAwaitExtensions/InstructionWrappers/<ReturnSelf>d__2`1<UnityEngine.AsyncOperation>:MoveNext ()
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)

again, I get this error when I try pulling an array of data from a smart contract.

**Comment by sneakzttv** [comment]
fixed in 2.5.1
