### ISSUE TITLE
ImportNFTTexture sample is broken

### ISSUE THREAD

**Issue by oleksandrchainsafe** [ChainSafe/web3.unity#566]
Server returns error 422 when requesting the NFT metadata by NFT's URI. See Erc1155Sample.cs, ImportNftTexture method.

**Comment by RyRy79261** [comment]
@oleksandrchainsafe What parameters are you using, on which network, which contract & which nft id?

**Comment by sneakzttv** [comment]
I'll fix this

**Comment by sneakzttv** [comment]
Creating a new texture for 1155 and 721 to test with this on goerli also as the metadata has become unpinned.

**Comment by juans-chainsafe** [comment]
is this issue the same as https://github.com/ChainSafe/web3.unity/issues/498 ? @sneakzttv @oleksandrchainsafe
