### ISSUE TITLE
iOS opens the default browser instead of the MetaMask browser.

### ISSUE THREAD

**Issue by gialarconv** [ChainSafe/web3.unity#571]
When I click on login in the Sample scene for mobile, the button instead of opening Metamask, opens the default browser of the cell phone.

I install the latest version of ChainSafe, fill the ChainSafeServerSettings with the following data

Project ID: [my project id from the dashboard].
Chain ID: 80001
Chain: MATIC
Network: Testnet
RPC: https://polygon.llamarpc.com

I create the build for iOS, I open XCode, I hit build to my cell phone, when I open the application it happens what you can see in the video that is in the link.

The idea is that it opens MetaMask as it does on Android.

Video of the behaviour: [https://drive.google.com/file/d/1BL_vEE_FuNr_sQyEUk7FzcVkfqhbujiX/view?usp=sharing](url)
MetaMask already installed: [https://drive.google.com/file/d/1BJpBLLTVs3RcEUNhgHK0sPiiswZhQ-Wu/view?usp=sharing](url)

- Unity version 2021.3.10f1
 - Chainsafe SDK version: v2.1.0
 - Platform: iOS
 - Type: iPhone 13 Pro Max
 - OS versioniOS 16.6

**Comment by fareedTahir131** [comment]
i am also facing the same issue from 15 days. I don't know how to resolve this.

**Comment by sneakzttv** [comment]
fixed in 2.5.1
