### ISSUE TITLE
Running ERC20 Sample Test in Test Runner window crashes Unity Editor

### ISSUE THREAD

**Issue by robGG1997** [ChainSafe/web3.unity#573]
**Description**
Running ERC20 sample test in Unity's test runner window crashes Unity

**To Reproduce**
1. Open **Windows > Test Runner** window
2. Select ERC20SampleTest and click Run Selected at the bottom of the window
3. Unity Begins to run and suddenly becomes unresponsive

**Expected behavior**
Test should run and respond with a Pass/Fail result

**Desktop**
 - Chainsafe SDK version: 2.5
 - Unity Platform: Windows
 - Unity version: 2022.3.15f
 - OS: Windows

**Comment by kalambet** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ChainSafe-Gaming-60e61b3eabd687000e7ce3b2/issues/ChainSafe/web3.unity/573?planning-poker) with Zenhub @kalambet @oleksandrchainsafe @RyRy79261 @robGG1997 @sneakzttv

**Comment by oleksandrchainsafe** [comment]
There is a problem with async functions in Unity Test Runner. Needs more research.

**Comment by kalambet** [comment]
The purpose of this issue is to figure out how to run `async` functions from the Unity Test Runner based on ERC20 Example.

**Comment by kantagara** [comment]
@oleksandrchainsafe I did give this one a spin. It's not the async functions, it's actually the web3builder that's causing the issue. Since in the picture below, I do get the BUILDING ASYNC Log, but everything after that halts. So it doesn't even execute the test.
![image](https://github.com/ChainSafe/web3.unity/assets/8202013/3485bc4b-213b-4a1e-bf49-d555ae025a20)

**Comment by robGG1997** [comment]
> The purpose of this issue is to figure out how to run `async` functions from the Unity Test Runner based on ERC20 Example.

My solution was to convert them into UnityTests which run as Coroutines, I'm also trying out Unity's [Awaitable](https://docs.unity3d.com/2023.1/Documentation/ScriptReference/Awaitable.html) class for async

**Comment by sneakzttv** [comment]
coroutines will more than likely work.

**Comment by robGG1997** [comment]
![image](https://github.com/ChainSafe/web3.unity/assets/142783680/50cdf859-becf-4675-96d3-38217431da7f)
Coroutines are working :)

**Comment by sneakzttv** [comment]
Yeah, native is usually the best bet :D

**Comment by kalambet** [comment]
@robGG1997 if there is a solution then I suggest closing this issue and for the Unity Nunit Tests for ERC20 work on #597

**Comment by sneakzttv** [comment]
testing
