### ISSUE TITLE
Use Json for saving login detail Persistently (Remember Me)

### ISSUE THREAD

**Issue by robGG1997** [ChainSafe/web3.unity#575]
**Summary**
Currently we're using PlayerPrefs for saving Login details on device but PlayerPrefs are vulnerable, slow and limited

**Suggested features or ways to address the summary**
We should use a Json file in Application.PersistentDataPath instead

**Motivation**
This will make Login function more robust

**Comment by sneakzttv** [comment]
This is non critical data as it's just the wallet address, all solidity checks are done using message.sender meaning they need to own the wallet. It is also cleared on logout and reset on each login so there is no vulnerability here. I don't think we need to change this.

**Comment by sneakzttv** [comment]
Are we sure we can do this btw? Afaik webgl has permission issues when it comes to saving/loading local json files on desktop. The only work around is via web requests to a backend which is a whole mess we probably dont want to get into for login data,.

**Comment by sneakzttv** [comment]
@robGG1997

**Comment by sneakzttv** [comment]
@robGG1997 Are we sure we can do this btw? Afaik webgl has permission issues when it comes to saving/loading local json files on desktop. The only work around is via web requests to a backend which is a whole mess we probably dont want to get into for login data.

**Comment by robGG1997** [comment]
> @robGG1997 Are we sure we can do this btw? Afaik WebGL has permission issues when it comes to saving/loading local JSON files on desktop. It's part of the reason we use the scriptable object for config as opposed to JSON files. The only work around is via web requests to a backend which is a whole mess we probably don't want to get into for login data.

If we used `Application.PersistentDataPath`, which we are, it should work. I've also tested this on locally on WebGL Build
