### ISSUE TITLE
Is it possible to update metamask deprecate code?

### ISSUE THREAD

**Issue by hsjo12** [ChainSafe/web3.unity#58]
Hello, 

So, I am just wondering if I clicked on the login button to connect to metamask ,

I have got some warnings as follow;  

MetaMask: The event 'networkChanged' is deprecated and may be removed in the future. Use 'chainChanged' instead.
For more information, see: https://eips.ethereum.org/EIPS/eip-1193#chainchanged
_warnOfDeprecation @ inpage.js:1

inpage.js:1 MetaMask: The event 'close' is deprecated and may be removed in the future. Please use 'disconnect' instead.

Is it possible to update the deprecate code ?

I think it is a bit slow to interact with metamask , taking more than a couple of seconds. 
So I guess it is because the deprecate code

**Comment by KBryan** [comment]
I don't think this is related. I do hear you out on updating deprecated code. Can add this to the backlog of todo's
