### ISSUE TITLE
Import Sample for Sample Unity Project

### ISSUE THREAD

**Issue by robGG1997** [ChainSafe/web3.unity#580]
**Summary**
Have the sample unity project be importable from the package manager using just a button

**Suggested features or ways to address the summary**
- This will mostly just require changes in hierarchy for the project. [Creating Custom Samples](https://docs.unity3d.com/Manual/cus-samples.html)

**Motivation**
This is a simpler and more accessible solution for a developer to see examples and samples instead of cloning an entirely new project

**Comment by kalambet** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ChainSafe-Gaming-60e61b3eabd687000e7ce3b2/issues/ChainSafe/web3.unity/580?planning-poker) with Zenhub @robGG1997 @sneakzttv @RyRy79261 @oleksandrchainsafe @kalambet
