### ISSUE TITLE
Login is locked to gelato/w3a chains

### ISSUE THREAD

**Issue by sneakzttv** [ChainSafe/web3.unity#585]
Currently it wont let you login with metamask to any chains outside of gelato/w3a configuration, cronos for example will fail.

Caused by this function in  web3.unity\src\ChainSafe.GamingSdk.Gelato.gelato.cs
Perhaps we remove this or just console.log as its currently in the interface and add a disclaimer saying gelato functions wont work on x chains and list the gelato chains etc
![image](https://github.com/ChainSafe/web3.unity/assets/57473220/947d1fb3-feda-41e6-889a-8119c6693d29)

**Comment by sneakzttv** [comment]
Caused by this function in  C:\Users\Sneakz\Desktop\web3.unity\src\ChainSafe.GamingSdk.Gelato.gelato.cs
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWRsIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2e55602fb73457ffab68a827bdedf7096d2f8824/image.png)

**Comment by kalambet** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ChainSafe-Gaming-60e61b3eabd687000e7ce3b2/issues/ChainSafe/web3.unity/585?planning-poker) with Zenhub @kalambet @oleksandrchainsafe @robGG1997 @RyRy79261 @sneakzttv

**Comment by kalambet** [comment]
1. Check if chain is supported with Gelato API
2. Disable Gealto controls withe the warning if chain is not supported.
