### ISSUE TITLE
Is it possible to listen to an event after transaction is succeeded ?

### ISSUE THREAD

**Issue by hsjo12** [ChainSafe/web3.unity#59]
Hello, 

```
            string response = await Web3GL.SendContract(method, abi, contract, args, value, gasLimit, gasPrice);
            Debug.Log(response);
```
Basically, I could see that the "response" variable indicates transaction hash number. 
Is there anyway to  get an event or to get full detail of the transaction hash ?

**Comment by KBryan** [comment]
We have transactionStatus in our documentation that you can access. Have you tried this? https://chainsafe.github.io/game-docs/#transaction-status

**Comment by JCela** [comment]
is there a way to get the transaction hash of the transaction you just sent through WebGL.SendContract( )   ?

**Comment by JCela** [comment]
so that you can send a transaction, and then wait for the transaction to succeed before triggering an event

**Comment by KBryan** [comment]
Is this what you are looking for? https://chainsafe.github.io/game-docs/#sign-through-webgl
