### ISSUE TITLE
Create ERC721 Unity unit tests

### ISSUE THREAD

**Issue by kalambet** [ChainSafe/web3.unity#598]
From "ERC721" Demo Scene section create following unity tests:
1. BalanceOf
2. OwnerOf
3. OwnerOfBatch
4. URI
5. Call the indexer (if possible)

Call the same logic that is called by the buttons in demo scene.
For the Ethereum simulation use `anvil` in a similar manner how it is done here:
https://github.com/ChainSafe/web3.unity/blob/4bae12c11ce06322bef02b4a63ac0bf7b540c850/src/ChainSafe.GamingSDK.EVM.Tests/ChainsafeRPCTests.cs#L30

**Comment by RyRy79261** [comment]
Large amount of Test related PRs went through since assigning this, waiting for merge to continue
