### ISSUE TITLE
Desktop-Experimental download ws server?

### ISSUE THREAD

**Issue by chismer** [ChainSafe/web3.unity#61]
*User Story**
As a [stakeholder persona] I want to [action] so that [goal].

**Suggested features or ways to address the user story**
[A clear and concise description of any potential solutions or features you've considered that might help solve the need/problem above.]

**Completion Criteria**
- [ ] Criteria 1

**Additional context**

**Comment by KBryan** [comment]
Are you having issues with the desktop branch? It isn't clear what you are trying to achieve. Could you supply more context?

**Comment by chismer** [comment]
I'm sorry.
I understand that to login you need a server (ws://) prepared to listen to requests. What does this example provide? Where can I find it?

![image](https://user-images.githubusercontent.com/20629862/147774581-0512a247-1f41-4b31-9fc0-d7f2dcf62dc4.png)

![image](https://user-images.githubusercontent.com/20629862/147774422-50aed679-23fa-46c8-bf43-c528b4cd3e0c.png)

**Comment by leon-do** [comment]
oh man. this was suppose to be private. still a work in progress 😅. Will make adjustments sometime this week.
