### ISSUE TITLE
ERC-721: EVM method "AllErc721" fails to return an uri

### ISSUE THREAD

**Issue by Snow106** [ChainSafe/web3.unity#62]
**Describe the bug**
When running the "AllErc721Example.cs" script, I noticed that a collection was not returning the uri of each NFT (but was still giving contract, ownership, and tokenid).

**To Reproduce**
1. Attach "AllErc721Example.cs" to an object in scene in Unity.
2. Press play
3. Console output shows "None" for the uri

**Expected behavior**
Console output shows the uri for the nft.

**Screenshots**
![image](https://user-images.githubusercontent.com/9102977/147610193-4bcceb18-b894-494a-ae42-84f98f6e1b70.png)
![image](https://user-images.githubusercontent.com/9102977/147610264-d24610df-ab2d-4c72-a48f-98cee5727164.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - N/A
 - Unity version 2021.1.21f1
 - Chainsafe verison: v1.0.14

**Additional context**
I'm able to get the URI if the method "Call" is called from the ERC721.cs's method "URI" (as shown in the ImportNFTTExtureExample.cs)

**Comment by KBryan** [comment]
Thank you for posting. We will look into this.
