### ISSUE TITLE
Plan Ramp Integration

### ISSUE THREAD

**Issue by kalambet** [ChainSafe/web3.unity#622]
**Summary**
This issue is the starting point of [Ramp](https://ramp.network/) integration.

**Description**
The definition of done for this issue is to provide comment with description of implementation approach and create one or more issues that will be used to implement the Ramp integration.

General steps are:
1. Check Ramp Docs https://docs.ramp.network/
2. Check integration guide PDF
3. Get Integration Key
4. Create new issues that might turn out as a bite size PR
5. Link those issues to this one

For the point (2) and (3) please contact @kalambet

**Comment by kalambet** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ChainSafe-Gaming-60e61b3eabd687000e7ce3b2/issues/ChainSafe/web3.unity/622?planning-poker) with Zenhub @kalambet @oleksandrchainsafe @robGG1997 @RyRy79261 @sneakzttv

**Comment by kalambet** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ChainSafe-Gaming-60e61b3eabd687000e7ce3b2/issues/ChainSafe/web3.unity/622?planning-poker) with Zenhub @kantagara

**Comment by kantagara** [comment]
This one is going to be interesting since ramp doesn't have a Unity plugin, so I guess we'll need to do custom iOS/Android integrations and then plug them into Unity.

**Comment by kantagara** [comment]
Android: #636
Web : #637
Desktop: #638
