### ISSUE TITLE
Refactor Unity tests to use Anvil

### ISSUE THREAD

**Issue by robGG1997** [ChainSafe/web3.unity#625]
**Summary**
Refactor tests to use anvil for signing transactions. Currently we're using a fake/stub response for this in `WebPageWallet.TestResponse`.

**Suggested features or ways to address the summary**
Use Anvil

**Motivation**
Using anvil gives more reliable test results.

**Acceptance Criteria**
Unity Tests don't use static hash values instead they use an actually simulated environment/Anvil.

**Comment by kantagara** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ChainSafe-Gaming-60e61b3eabd687000e7ce3b2/issues/ChainSafe/web3.unity/625?planning-poker) with Zenhub @oleksandrchainsafe @robGG1997
