### ISSUE TITLE
TypeError: window.web3gl is undefined -> Only when trying to run from deployed app

### ISSUE THREAD

**Issue by RafaelCopat** [ChainSafe/web3.unity#63]
**Describe the bug**
Whenever I try to connect my metamask to my deployed webgl APP, this error occurs:

An error occurred running the Unity content on this page. See your browser JavaScript console for more info. The error was:
TypeError: window.web3gl is undefined
_Web3Connect@https://crypto-gladiators.herokuapp.com/Build/BuildGladiator.framework.js:2:56950

and a lot of other errors in the stack.

The thing is, in my local build it works normally so I have no clue on why this is happening.

**To Reproduce**
1. Go to (https://crypto-gladiators.herokuapp.com/)
2. Click on Metamask login

**Expected behavior**
Login normally to metamask

**Screenshots**
![image](https://user-images.githubusercontent.com/14934426/147893071-1383075b-5ba4-4f21-bd4b-500c74d3f04c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser firefox

**Comment by RafaelCopat** [comment]
Any ideas? I can give more info if needed. Thank you for sharing this framework.

**Comment by KBryan** [comment]
I believed you moved this over to discord and you issue is now resolved?

**Comment by RafaelCopat** [comment]
Hey. Yes it is solved. For future reference, the "static" folder must be on the root of the deployed application, otherwise this error occurs. My solution needed me having it on a different "public" folder.
