### ISSUE TITLE
Sign Typed Data using Wallet Connect

### ISSUE THREAD

**Issue by robGG1997** [ChainSafe/web3.unity#633]
**Summary**
Sign typed data using Wallet Connect

**Suggested features or ways to address the summary**
Use `WalletConnectUnity.cs` to refactor `WebPageWallet.SignTypedData` to use Wallet Connect

**Motivation**
Signing using Wallet Connect is more robust than redirecting URLs

**Comment by kalambet** [comment]
After merging this PR `ISigner` and `ITransactionExeutor` WC implementation will be slightly modified in PR #644
