### ISSUE TITLE
Web3Auth monobehavior: "[DllImport("__Internal")] private static extern string GetAddressBarURL()" fails build

### ISSUE THREAD

**Issue by TheOneVries** [ChainSafe/web3.unity#635]
**Describe the bug**
the Web3Auth class has a conditional (the condition being UNITY_WEBGL && !UNITY_EDITOR) Dll import, pulling in that static 'string GetAddresBarURL()"
It seems to not exist.
Trying to build a game that uses this class (for example the sample scenes provided with the package) will cause the build to fail, stating:
"Library\Bee\artifacts\WebGL\build\debug_WebGL_wasm\build.js: undefined symbol: GetAddressBarURL (referenced by top-level compiled C/C++ code)"

Trying to call this line directly in Unity gives the following error:
"EntryPointNotFoundException: GetAddressBarURL assembly:<unknown assembly> type:<unknown type> member:(null)"

**To Reproduce**
1. Importing "web3.unity SDK" and "web3.unity SDK Web3Auth Integration" packages
2. Import samples from "web3.unity SDK"
3. Build webgl project using the sample scenes.

Alternatively, to call that line directly, simply:
1. Create an empty gameobject, attach an empty test script of sorts
2. As an external method, add 	`[DllImport("__Internal")]
	private static extern string GetAddressBarURL();`
3. In the Start() method, simply call GetAddressBarURL() for error.

**Expected behavior**
I would expect the provided sample to simply build. It doesn't. My concern is that the anything build with the package as is will also rely on web3Auth at some point, triggering this issue.

**Desktop: **
 - Chainsafe SDK version: 2.5
 - Unity Platform: target platform is WebGL
 - Unity version: 2022.3.9f1
 - OS: Windows

**Comment by kalambet** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ChainSafe-Gaming-60e61b3eabd687000e7ce3b2/issues/ChainSafe/web3.unity/635?planning-poker) with Zenhub @RyRy79261 @robGG1997 @kantagara @oleksandrchainsafe

**Comment by Votrubec** [comment]
Just mentioning that I also had compilation/linking errors. GetAddresBarURL when I tried to compile a vanilla Samples build. But I also got other undefined symbol errors in my project as well, so it's not just the GetAddresBarURL that's the issue. Thanks.

**Comment by kantagara** [comment]
Hello. @Votrubec and @TheOneVries . The issue reported in the first post has been fixed and you can download the update via openUPM https://openupm.com/packages/io.chainsafe.web3-unity.web3auth/?subPage=readme

**Comment by Votrubec** [comment]
![image](https://github.com/ChainSafe/web3.unity/assets/6911496/72f58772-da26-407b-ba6e-a39ec9eb07e6)
Unfortunately, as mentioned, it's not just ReadAddressBar that was the problem. This issue isn't closed, just the very specific case for the Sample.
