### ISSUE TITLE
Ramp Fiat integration - Web

### ISSUE THREAD

**Issue by kantagara** [ChainSafe/web3.unity#637]
- [ ] Connect Unity side with Ramp
- [ ] Create a new class that inherits from RampIntegrationBase.
- [ ] In RampIntegraionSample add appropriate preprocessor directive to create the instance.
- [ ] Make sure that it's possible to subscribe from Unity to the native API event for when off ramp sale happened, when  onramppurchase happened.

**Comment by oleksandrchainsafe** [comment]
PR #648

**Comment by empea-careercriminal** [comment]
@kantagara please tick off the bullet points in the issue description so we see when this is good to be merged.
