### ISSUE TITLE
ERC721 ownerof (on multiple tokenids)

### ISSUE THREAD

**Issue by PupazziPunk** [ChainSafe/web3.unity#64]
I am trying to use the following script (Erc721Ownerof)
to be able to associate a 3D object to each holder of one of my nft.

I can only do it once because the variable string tokenid = "numbertokenid" I can't repeat it more times.
is there any way to create an if for each tokenid?

thank you

**Comment by KBryan** [comment]
If your contract has implemented the optional tokenOfOwnerByIndex is the best way to enumerate a list of tokenId's owned by a user. https://docs.openzeppelin.com/contracts/2.x/api/token/erc721#ERC721Enumerable-tokenOfOwnerByIndex-address-uint256-

**Comment by PupazziPunk** [comment]
Thanks I managed!
To connect it to the moonriver mainnet is it correct to do so?
Within the CONTRACT and ACCOUNT I will enter my contract and my account

 string chain = "moonriver";
        string network = "mainnet";
        string contract = "CONTRACT";
        string tokenId = "25";
        string account = "ACCOUNT";


Thank you so much

**Comment by KBryan** [comment]
Looks alright, the most important thing is making sure the chainId is set in your network.js file and you are adding the RPC URL for the specific chain you are connecting to.
