### ISSUE TITLE
Implement/Fix missing features for Lootboxes

### ISSUE THREAD

**Issue by kantagara** [ChainSafe/web3.unity#640]
- OpeningLootBoxType method in LootBoxService
- Download erc721 image (my tokenUrl is empty, don't know why);
- Error 'InsufficientPayment()' when openning Epic+ lootboxes.oxes.

**Comment by kantagara** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ChainSafe-Gaming-60e61b3eabd687000e7ce3b2/issues/ChainSafe/web3.unity/640?planning-poker) with Zenhub @oleksandrchainsafe @robGG1997

**Comment by oleksandrchainsafe** [comment]
+ Fix naming, LootBoxes - Lootboxes

**Comment by kantagara** [comment]
This is done.
