### ISSUE TITLE
WalletConnect v2 not working with new project ChainSafe v2.1 on WebGL

### ISSUE THREAD

**Issue by Berns-s** [ChainSafe/web3.unity#643]
I am getting the error, "You are trying to connect to a dapp what uses WC1, which is outdated" with a fresh project with ChainSafe v2.1 installed. (WEBGL)

**To Reproduce**
1. Create a new Unity project
2. Add ChainSafe 2.1
3. Build to webgl
4. Try use WalletConnect, my case I used Ambire
5. See error

 - Chainsafe SDK version: [e.g. 2.1]
 - Platform: WebGL
 - Unity Version 2021.3.13
 - Windows 11

**Comment by sneakzttv** [comment]
We've spoken to the wallet connect team, they've said their WebGL kit should be ready by feb next year. Keeping this issue open until we address it.
