### ISSUE TITLE
Curl Error: IPFS url Error.

### ISSUE THREAD

**Issue by aishwarya-blocsys** [ChainSafe/web3.unity#645]
1. working on the import NFT script, when trying to fetch existing NFT from NFT Marketplace getting an error like -- Curl error 1: Protocol 'ipfs' not supported or disabled in libcurl".` 
2. By using Google I checked this error which is related to the IPFS URL and applied the given solution for this but still faced an error. 
3. when I use the contract address and tokenId of the particular NFT it also gives an error like JSON RPC error.
4.  when I use the direct metadata URL of NFT it gives proper value. so I want to know if my marketplace needs any changes.

**Comment by aishwarya-blocsys** [comment]
1st I tried using the Contract Address and TokenID but it gave me the error so then i directly passed the NFT metadata URL from this i am able to fetch the nft details and image uri.

**Comment by kalambet** [comment]
hey @aishwarya-blocsys!

Have you checked what is returned from the contract itself (for example via etherscan.io)? What is the actual URL that is stored?

Can you please check ERC 1155 sample and this function in particular?
https://github.com/ChainSafe/web3.unity/blob/main/Packages/io.chainsafe.web3-unity/Runtime/Scripts/Samples/Erc1155Sample.cs#L80

You can use code similar to this one to substitute `ipfs://` to `https://ipfs.io/ipfs/` or any other public IPFS gateway you like.

**Comment by aishwarya-blocsys** [comment]
when I checked the NFT details from the contract side it doesn't store any NFT URL. but in the database, it stores metadata JSON URL and image URL like ipfs:// what is wrong with this,

**Comment by sneakzttv** [comment]
fixed in 2.5.1
