### ISSUE TITLE
Remove Json.Net linking in `ChainSafe.Gamming.Unity` for a fix to GameCI Version Issue

### ISSUE THREAD

**Issue by robGG1997** [ChainSafe/web3.unity#650]
**Summary**
Game CI currently uses the generated dll instead of Unity's Json.Net package to resolve version mismatch error during CI, I believe (**NOT CONFIRMED**) this is due to link.xml's including the generated dll inside `ChainSafe.Gamming.Unity`

**Suggested features or ways to address the summary**
Remove link.xml's reference to Json.Net dll and try a GameCI tests action run

**Motivation**
Cleaner to use one single reference for both Game and Test Environment

**Blockers**
(OPTIONAL) [Do you see any blocker that needs to be done before implementing this feature?]

**Additional context**
(OPTIONAL) [Add any other context or screenshots/videos about the feature request here.]

**Comment by kalambet** [comment]
Relevant to #678

**Comment by robGG1997** [comment]
We've moved to testing projects instead of Packages in #678 since it lets us test multiple packages imported in project also including package samples, which in turn fixes this issue
