### ISSUE TITLE
Web3Auth Plugin

### ISSUE THREAD

**Issue by kalambet** [ChainSafe/web3.unity#654]
All the issues related to the Web3Auth.

**Comment by engineer846** [comment]
After I run android resolver, these three libraries from the web3Auth Plugin is duplicated,
Found plugins with same names, Packages/io.chainsafe.web3-unity.web3auth/Runtime/Plugins/Web3AuthSDK/Android/androidx.versionedparcelable.versionedparcelable-1.1.1.aar and Assets/Plugins/Android/androidx.versionedparcelable.versionedparcelable-1.1.1.aar. Delete the one of the duplicate plugins.
UnityEditor.Android.AndroidPluginImporterExtension:CheckFileCollisions (string,string[])
UnityEditorInternal.PluginsHelper:CheckFileCollisions (UnityEditor.BuildTarget,string[])
UnityEditor.GenericMenu:CatchMenu (object,string[],int)
Found plugins with same names, Packages/io.chainsafe.web3-unity.web3auth/Runtime/Plugins/Web3AuthSDK/Android/com.google.guava.listenablefuture-1.0.jar and Assets/Plugins/Android/com.google.guava.listenablefuture-1.0.jar. Delete the one of the duplicate plugins.
UnityEditor.Android.AndroidPluginImporterExtension:CheckFileCollisions (string,string[])
UnityEditorInternal.PluginsHelper:CheckFileCollisions (UnityEditor.BuildTarget,string[])
UnityEditor.GenericMenu:CatchMenu (object,string[],int)
Found plugins with same names, Assets/Plugins/Android/androidx.interpolator.interpolator-1.0.0.aar and Packages/io.chainsafe.web3-unity.web3auth/Runtime/Plugins/Web3AuthSDK/Android/androidx.interpolator.interpolator-1.0.0.aar. Delete the one of the duplicate plugins.
UnityEditor.Android.AndroidPluginImporterExtension:CheckFileCollisions (string,string[])
UnityEditorInternal.PluginsHelper:CheckFileCollisions (UnityEditor.BuildTarget,string[])
UnityEditor.GenericMenu:CatchMenu (object,string[],int)

**Comment by RyRy79261** [comment]
@empea-careercriminal @kalambet Are there any additional tasks for this epic?

**Comment by empea-careercriminal** [comment]
No other related issues. Bugs will be filed separately.

**Comment by engineer846** [comment]
is it resolved?
