### ISSUE TITLE
Investigate providers

### ISSUE THREAD

**Issue by boorich** [ChainSafe/web3.unity#658]
Investigate providers like Ramp and derive Issues for this epic.

These are the only ones we currently care about:

- [ ] https://www.transfi.com/
- [ ] https://transak.com/
- [ ] https://www.moonpay.com/
- [x] https://ramp.network/

@empea-careercriminal: Legal requirements per provider
@kantagara: Technical requirements per provider

Draft Flow: [here](https://www.figma.com/file/urPUjOLjM9rwTLffMkQd2r/Fiat-On%2FOff-Ramp?type=whiteboard&node-id=55%3A147&t=LvA2TsDHqsK7emu9-1)
Draft UI: [here](https://www.figma.com/file/sumXOXHthv4q0Bv42SL8L8/Project-ID-Dashboard?type=design&node-id=3295%3A20192&mode=design&t=15QUVGdRXqoZANdn-1)

**Comment by boorich** [comment]
Depends on successful market reception of Ramp MVP.

**Comment by kantagara** [comment]
I wouldn't say so. Maybe others have better onboarding process, or others have their unity sdk that can be integrated faster?

**Comment by sneakzttv** [comment]
Closed as the issue is redundant now.
