### ISSUE TITLE
Prepare Lootboxes for openUPM package submission

### ISSUE THREAD

**Issue by kantagara** [ChainSafe/web3.unity#660]
There are some small things that need to be tested properly before we submit the package to the open UPM.

- [ ] Change namespace from chainlink.lootboxes to lootboxes.chainlink
- [ ] Test out if you can actually import lootboxes and web3 package by itself to a brand new project so that lootboxes just work

**Comment by sneakzttv** [comment]
picking this up!

**Comment by sneakzttv** [comment]
Namespaces changed and it's importing without errors! Yeet yeet!
We still need to put it all on chain as it's currently connecting and running only locally.
Will wait for Oleksander to return to handle that.
https://github.com/ChainSafe/web3.unity/pull/700
