### ISSUE TITLE
Determine Activity Level

### ISSUE THREAD

**Issue by boorich** [ChainSafe/web3.unity#665]
Identify the repos that receive commits or show other signs of activity.

- [ ] Game-pm
- [ ] analytics-api
- [ ] EthereumRPCSharp
- [ ] game-api
- [ ] game-docs-v2
- [ ] game-landing
- [ ] game-subgraphs
- [ ] game-web3gl
- [ ] game-web3wallet
- [ ] gaming-dashboard
- [ ] gaming-token-deployer
- [ ] kong-plugins
- [ ] lazy-minting-voucher-signer
- [ ] marketplace-contracts
- [ ] marketplace-indexers
- [ ] marketplace-ui
- [ ] nft-api
- [ ] Uplink-Indexer
- [ ] web3.unity
- [ ] web3.unity-webgl-template

**Comment by kantagara** [comment]
I'm closing this since it does seem stale and irrelevant atm
