### ISSUE TITLE
Check for dependencies

### ISSUE THREAD

**Issue by boorich** [ChainSafe/web3.unity#666]
Find and mark the repos that are used as dependencies from within the web3.unity SDK

- [ ] Game-pm
- [ ] analytics-api
- [ ] EthereumRPCSharp
- [ ] game-api
- [X] game-docs-v2
- [ ] game-landing
- [ ] game-subgraphs
- [ ] game-web3gl
- [ ] game-web3wallet
- [ ] gaming-dashboard
- [ ] gaming-token-deployer
- [ ] kong-plugins
- [ ] lazy-minting-voucher-signer
- [X] marketplace-contracts
- [ ] marketplace-indexers
- [ ] marketplace-ui
- [ ] nft-api
- [ ] Uplink-Indexer
- [ ] web3.unity-webgl-template

**Comment by kantagara** [comment]
only game docs is a dependency.
