### ISSUE TITLE
Wallet Responses

### ISSUE THREAD

**Issue by Votrubec** [ChainSafe/web3.unity#67]
*User Story**
Our game is using Web3GL.SendContract to send transactions to our contract. The CSGaming JavaScript side is currently listening to the wallet and returns the string component of the response to the managed C# side. At the moment, either a tx is returned as a string, or an exception is thrown.

**Suggested features or ways to address the user story**
Returning the whole response, code and message, as a JSON object back to the managed C# side would allow us to properly respond to the wallet response. This is simple to then decode from the C# side.

For example, when a user rejects a transaction, we'd like to sensibly react, instead of trying to react to an exception, in an awaited method. The response from MetaMask is:

{code: 4001, message: 'MetaMask Tx Signature: User denied transaction signature.'}

This way, we can know that code 4001 is a user rejected transaction, as opposed to some other error. This way we can give the user the best and most appropriate in-game response.

This is similar to #59.

**Comment by Votrubec** [comment]
I can see in the 'main' js, we've got the `sendContractResponse` value being set:

```
.on("transactionHash", (function(n) {window.web3gl.sendContractResponse=n}))
.on("error", (function(n) {window.web3gl.sendContractResponse=n.message}))
```

**Comment by KBryan** [comment]
HAving some better handling of these is definitely a good idea. Thanks for bringing it up.

**Comment by cryptoleek-eth** [comment]
> some better handling of these is definitely a good idea. Thanks for bringing it

do we have unminified version?

**Comment by sneakzttv** [comment]
Try catch now shows you as a user rejects the transaction. You can create a custom js function and run the catch through that to get back to your wallet.
