### ISSUE TITLE
Automate DLLs export to Unity using CI

### ISSUE THREAD

**Issue by robGG1997** [ChainSafe/web3.unity#678]
**Summary**
Currently we've started to track dlls published and exported to Unity in git. Every time there's a change to one of the solutions in the `src` folder we have to publish and export these dlls to Unity, we should automate this process on remote/GitHub using CI.

**Suggested features or ways to address the summary**
We're already doing this for tests CI in `.github\workflows\unity_tests.yml` we simply need to persist those changes using an extra commit. We also should change workflow ordering. The two workflows with extra commits should run before we run any other actions, we can even optimize workflow to the point where nothing extra needs to run if previous steps have failed.

**Motivation**
This will mean remote's `main` will always have the latest dependencies! And by automating the process we can ignore the Library packages in `.gitignore` again and Dev doesn't have to worry about pushing the latest dependencies.

**Comment by kalambet** [comment]
The solution for this issue we discussed with @robGG1997 is to make a pipeline out of competing workflows.
The pipeline steps are sequential, the next workflow should run not based on push but based on successful completion of the previous one:
1. Duplicate Samples
2. Build Release version of the SDK libraries
3. Run NUnit Tests
4. Run in parallel tests Play Mode and Editor Mode
5. Run Code Analyzer
