### ISSUE TITLE
Technical Debt Collection

### ISSUE THREAD

**Issue by boorich** [ChainSafe/web3.unity#680]
What to do?
Review the following tasks and tick the resolved ones so that we can remove them. When you are done, please add any domain-specific knowledge you might have about the remaining tasks either as a comment or directly within the list:

- [x] Implement callback functionality instead of polling for WebGLWallet. See: [Unity Forum Discussion](https://forum.unity.com/threads/c-jslib-2-way-communication.323629/#post-2100593)
- [x] Update WebPageWallet to use deep links instead of the clipboard (Note: WebPageWallet has been removed)
- [x] Close the web page when a copy/deep link is activated (Note: WebPageWallet has been removed)
- [x] Remove the warning or hint when using WebPageWallet and the user has no wallet installed (Note: WebPageWallet has been removed)
- [x] Change the background color of the WebPageWallet page to Chainsafe's gray (Note: WebPageWallet has been removed)
- [x] Adjust the behavior of ChainsafeServerSettings and WebGLTemplatesInstallerTool
- [x] Eliminate duplicated logic in the Chains class, considering the functionality of ChainProvider
- [x] Prompt users to install WebGLTemplates only when the current platform is WebGL
- [x] Incorporate the "Packages" project (Unity scripts outside the core solution) into the solution for better support during refactoring
- [x] Enable Unity solution updates without launching Unity when publishing to Unity packages
- [x] Create a new exception type for handling wallet connection failures, allowing users to manage these issues
- [x] Add a user-friendly feedback editor window or menu item with a link to facilitate issue reporting for developers
- [x] Refactor the Login class to improve code organization and readability
- [x] Replace occurrences of ***Wallet with ***WalletProvider to avoid potential naming conflicts (e.g., WalletConnectWallet)
- [x] Change `web3Builder.BuildAsync()` to `web3Builder.LaunchAsync()` to better reflect its role in triggering wallet connection procedures
- [x] Confirm whether creating a web3 instance without an ISigner is still possible
- [x] Reevaluate the necessity of Unity tests (Note: May no longer be relevant)
- [x] Generate a class for a contract using its ABI
- [x] Group all menu items under a single parent (e.g., "ChainSafe/Project Settings") for organization and consistency
- [x] Remove Upload button from More examples section

Hint: If you know a good point in time where planned refactoring would make it easy to close one of the above issues, please mention them so that we can introduce those improvements gracefully.

**Comment by RyRy79261** [comment]
>  Update WebPageWallet to use deep links instead of the clipboard (Note: WebPageWallet has been removed)
Deep links dont really work on most devices so I believe we would rather use Wallet Connect

>   Confirm whether creating a web3 instance without an ISigner is still possible

This should be possible as Read actions dont require a signer, as well, for Gelato, you dont need a signer for the Non-ERC2771 interactions. 

> Generate a class for a contract using its ABI

The best for this in my opinion is Nethereum's generator as there are a variety of ways to use it, the resulting code has better workflows for decoding

**Comment by empea-careercriminal** [comment]
> Generate a class for a contract using its ABI
> 
> The best for this in my opinion is Nethereum's generator as there are a variety of ways to use it, the resulting code has better workflows for decoding

@RyRy79261 can you please make an issue from this and tick this off the list?

**Comment by robGG1997** [comment]
> Enable Unity solution updates without launching Unity when publishing to Unity packages

I think this had to do with `.unitypackage` files, we've moved on to OpenUPM so I don't think this is relevant anymore

**Comment by robGG1997** [comment]
> Refactor the Login class to improve code organization and readability

There's already an issue for this #641

**Comment by robGG1997** [comment]
`Replace occurrences of ***Wallet with ***WalletProvider to avoid potential naming conflicts (e.g., WalletConnectWallet)`

We're refactoring/separating "...Wallet" classes into "...TxnExecutor" and "...Signer" so this isn't relevant anymore

**Comment by kantagara** [comment]
> Incorporate the "Packages" project (Unity scripts outside the core solution) into the solution for better support during refactoring

This one is already WIP by Rob https://app.zenhub.com/workspaces/chainsafe-gaming-60e61b3eabd687000e7ce3b2/issues/gh/chainsafe/web3.unity/679

**Comment by kantagara** [comment]
>  Reevaluate the necessity of Unity tests (Note: May no longer be relevant)
I'm still in for them to exist. Why shouldn't they be there?

**Comment by robGG1997** [comment]
> Reevaluate the necessity of Unity tests (Note: May no longer be relevant)

This should be a discussion on the engineering channel

**Comment by RyRy79261** [comment]
https://github.com/ChainSafe/web3.unity/issues/683

**Comment by kalambet** [comment]
> I'm still in for them to exist. Why shouldn't they be there?

@kantagara @robGG1997 this is an old one. I think even before you joined. Back when we were thinking that we might do most of the stuff with just NUnit and not involve full blown Unity UI test. And later we found that Unity NUnit is a thing. So not relevant anymore.

**Comment by sneakzttv** [comment]
I'll see if I can knock these 5 off today

- Group all menu items under a single parent (e.g., "ChainSafe/Project Settings") for organization and consistency
- Remove Upload button from More examples section
- Add a user-friendly feedback editor window or menu item with a link to facilitate issue reporting for developers
- Change web3Builder.BuildAsync() to web3Builder.LaunchAsync() to better reflect its role in triggering wallet connection procedures
- Prompt users to install WebGLTemplates only when the current platform is WebGL

**Comment by sneakzttv** [comment]
Menu items grouped for usability:
![image](https://github.com/ChainSafe/web3.unity/assets/57473220/929a3e15-f71d-404a-b256-2753e993905a)

Upload button removed:
![image](https://github.com/ChainSafe/web3.unity/assets/57473220/e5b154f9-721e-4eab-bcce-c17321e3cedd)

Report bug menu added:
![image](https://github.com/ChainSafe/web3.unity/assets/57473220/cb6f1089-58eb-4728-9dd3-2cfdd51b7844)

Web3Builder.BuildAsync() changed to web3Builder.LaunchAsync() in all occurrences:
![image](https://github.com/ChainSafe/web3.unity/assets/57473220/13a25c5a-232a-4b12-8b6a-7f2d64ff7c12)

Prompt users to install WebGLTemplates only when the current platform is WebGL/Adjust the behavior of ChainsafeServerSettings and WebGLTemplatesInstallerTool:

Removed the WebGL template sync button on startup and server settings as the templates should be updated prior to each release and more than likely wont change. I don't think we need this function it also fixes the annoying template pop up when installing a fresh SDK for testing.
