### ISSUE TITLE
iOS build not working in Xcode

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#686]
**Describe the bug**
After the build is a success in Unity, and you try to run it in a real iPhone device, you get a build error in Xcode

**To Reproduce**
1. Switch platform to iOS
2. Click on Build and Run
3. Wait for build to finish in Unity
4. Switch your development profile in Xcode
5. Start the build in Xcode selecting a real device or simulator

**Expected behavior**
Application is open correctly in the device

**Screenshots**
<img width="1397" alt="Screenshot 2023-10-25 at 11 43 33" src="https://github.com/ChainSafe/web3.unity/assets/104365141/8ea394f9-ffdf-4e21-84d7-449e39a6351f">

**Mobile (please complete the following information):**
 - Chainsafe SDK version: [main]
 - Platform: [iOS]
 - Type: [Real device]
 - iOS version [17.0.3]

**Additional context**
```
Assertion failed: (false && "compact unwind compressed function offset doesn't fit in 24 bits"), function operator(), file Layout.cpp, line 5758.

Linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by juans-chainsafe** [comment]
The issue happens with Xcode 15.0.1 version.
The solution is to downgrade the version or, in Xcode, in the Build Settings section, add the flag "-Id64" to **Other Linker Flags**
<img width="487" alt="Screenshot 2023-10-26 at 10 34 43" src="https://github.com/ChainSafe/web3.unity/assets/104365141/523c8bd1-842b-4e85-8324-f430c66ba38b">

**Comment by EduardMalkhasyan** [comment]
Am using Unity 2022.3.11 MacOs Sonoma 13, M1, Xcode 15.0.1, In my case when I add "-Id64" first time it works, but after on next build it dosent help at all, so I need every time delete Xcode and reinstall and it will help only for one time ((

**Comment by juans-chainsafe** [comment]
> Am using Unity 2022.3.11 MacOs Sonoma 13, M1, Xcode 15.0.1, In my case when I add "-Id64" first time it works, but after on next build it dosent help at all, so I need every time delete Xcode and reinstall and it will help only for one time ((

This happened to me, try closing and restarting XCode and add the flag again, not sure why sometimes XCode recognizes the flag and others not.

**Comment by EduardMalkhasyan** [comment]
> > Am using Unity 2022.3.11 MacOs Sonoma 13, M1, Xcode 15.0.1, In my case when I add "-Id64" first time it works, but after on next build it dosent help at all, so I need every time delete Xcode and reinstall and it will help only for one time ((
> 
> This happened to me, try closing and restarting XCode and add the flag again, not sure why sometimes XCode recognizes the flag and others not.
> 
> Also, please try instead of -Id64, use: "-ld_classic" worked for me everytime so far.

Ok thank you Sir I will try!

**Comment by Clarisse42** [comment]
> The issue happens with Xcode 15.0.1 version. The solution is to downgrade the version or, in Xcode, in the Build Settings section, add the flag "-Id64" to **Other Linker Flags** <img alt="Screenshot 2023-10-26 at 10 34 43" width="487" src="https://user-images.githubusercontent.com/104365141/278357694-523c8bd1-842b-4e85-8324-f430c66ba38b.png">

@juans-chainsafe It work for me, MacOs Sonoma and Xcode 15.0.1 ! Thank you very much 🙏
