### ISSUE TITLE
Can't interact with elements in iOS

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#688]
**Describe the bug**
in a iOS build after the build finishes and the app opens in the device, you can't interact with buttons or do any actions

**To Reproduce**
1. Switch platform to iOS
2. Click on Build and Run
3. Wait for build to finish in Unity
4. Switch your development profile in Xcode
5. Start the build in Xcode selecting a real device or simulator
6. Wait for the app to start in your device
7. Try to click any button in the SampleLogin

**Expected behavior**
User can interact with the interface

**Mobile (please complete the following information):**
 - Chainsafe SDK version: [main]
 - Platform: [iOS]
 - Type: [Real device]
 - iOS version [17.0.3]

**Additional context**
`JsonSerializationException: Unable to find a constructor to use for type ChainSafe.Gaming.WalletConnect.Model`

**Comment by sneakzttv** [comment]
Closed via https://github.com/ChainSafe/web3.unity/pull/689
