### ISSUE TITLE
WebGL Metamask template not working

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#713]
**Describe the bug**
This template should only work with Metamask, but I can't connect to the Metamask wallet using SampleLogin

**Steps**
1. Use the scene [SampleLogin]
2. In Build Settings -> Player Settings -> Player -> Resolution and Presentation -> **Select Web3GL - MetaMask** template
3. Try to login with [Remote wallet]

**Expected behavior**
Metamask wallet appears to connect

**Console errors**
```
[Web3] The WalletConnectCore class is being re-initialized! It's likely a previous instance was not disposed of. It's recommended to re-use the same WalletConnectCore instance for the same project in the same runtime, event listener leaking can occur.
webgl2.framework.js.br:3 ArgumentException: The module Web3.Unity-core-expirer with context Web3.Unity-core-expirer is attempting to create a new EventDelegator that overlaps with an existing EventDelegator
  at WalletConnectSharp.Events.EventDelegator..ctor (WalletConnectSharp.Common.IModule parent) [0x00000] in <00000000000000000000000000000000>:0 
--- End of stack trace from previous location where exception was thrown ---
```

**Screenshots/Video**
<img width="751" alt="Screenshot 2023-11-07 at 10 01 20" src="https://github.com/ChainSafe/web3.unity/assets/104365141/20ff9f9f-3b78-48a6-b40f-f763c764c7c3">

**Desktop (please complete the following information):**
 - Chainsafe SDK version: [main]
 - Operating System: [Mac]

**Additional context**
@kantagara not sure if we will continue supporting this template, so if thats the case, we can close this issue

**Comment by juans-chainsafe** [comment]
@kantagara @robGG1997 this is happening as well with the WebGL - 2020x template, apparently the issue is related to remote wallet login and is returning 0 fetched supported wallets

**Comment by robGG1997** [comment]
Yeah this is a known limitation, [WalletConnectSharp](https://github.com/WalletConnect/WalletConnectSharp) doesn't support WebGL platform
