### ISSUE TITLE
Some samples not working on WebGL build with Web3Auth

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#714]
**Describe the bug**
When you try to execute some samples with a WebGL build (not in the editor), they fail

**Steps**
1. Use the scene [SampleLogin - Web3Auth]
2. Login with [Web3Auth]
3. Go to **More examples** section
4. Click on **ContractSend** for example

**Expected behavior**
Sample is executed successfully 

**Console errors**
```
ChainSafe.Gaming.Web3.Web3Exception: Error occurred when trying to send rpc requests(s): eth_getTransactionCount ---> Nethereum.JsonRpc.Client.RpcClientUnknownException: Error occurred when trying to send rpc requests(s): eth_getTransactionCount ---> System.DllNotFoundException: Unable to load DLL 'libc'. Tried the load the following dynamic libraries: 

   --- End of inner exception stack trace ---
  at Nethereum.JsonRpc.Client.RpcClient.SendAsync (Nethereum.JsonRpc.Client.RpcMessages.RpcRequestMessage request, System.String route) [0x00000] in <00000000000000000000000000000000>:0 
   --- End of inner exception stack trace ---
  at ChainSafe.Gaming.InProcessTransactionExecutor.InProcessTransactionExecutor.SendTransaction (ChainSafe.Gaming.Evm.Transactions.TransactionRequest transaction) [0x00000] in <00000000000000000000000000000000>:0 
```

**Screenshots/Video**
If applicable, add screenshots or screen recordings that help visualize the issue.
<img width="1081" alt="Screenshot 2023-11-07 at 13 49 34" src="https://github.com/ChainSafe/web3.unity/assets/104365141/c44cbfbe-e1a6-43d9-8cbe-ea01f14dc1f5">

**Desktop (please complete the following information):**
 - Chainsafe SDK version: [main]
 - Unity Version: [2022.3]
 - Operating System: [Mac]

**Additional context**
Failing on:

- ContractSend
- GetNonce
- GetTransactionStatus
- Mint721
- Mint1155
- SendArray
- SendTransaction
- TransferErc20
- TransferErc721
- TransferErc1155

**Comment by sneakzttv** [comment]
ill check after merge

**Comment by sneakzttv** [comment]
re-assigned to moving contracts to sepolia, @kantagara will take over here.

**Comment by juans-chainsafe** [comment]
Fixed on https://github.com/ChainSafe/web3.unity/pull/729 but we have a different issue now: https://github.com/ChainSafe/web3.unity/issues/730
