### ISSUE TITLE
All Nfts call error

### ISSUE THREAD

**Issue by sneakzttv** [ChainSafe/web3.unity#719]
![image](https://github.com/ChainSafe/web3.unity/assets/57473220/a46313c5-916a-449f-94de-f79579d8f557)

All Nft call is erroring saying some value is null, will look into this. The endpoint was deprecated afaik and we need to put the new one in.

**Comment by RyRy79261** [comment]
Didn't we deprecate the server for this?

**Comment by sneakzttv** [comment]
Moved to 2.5.2, awaiting turbosquid sync with the api team.
