### ISSUE TITLE
"importNFTTextureExample" - Getting Parse Errors when changing string,network etc.

### ISSUE THREAD

**Issue by JBDsolutions** [ChainSafe/web3.unity#72]
I was able to recreate what was done in the tutorial video with default script included, the chainsafe logo displays on my cube, but when changing the script as shown in the video to my polygon setup (chain, network, contract, and Token ID) I am hit with errors and the cube shows red question marks. 

**From what I can gather its an issue parsing the uri** 

I tried to add an if statement to fix the "ipfs" not supported, which worked to kill the single error but the parsing error stuck around so i reverted to the default example script provided and tried again with the same results. 

Additional Project Info: 

- Attempting to set up for polygon
- The NFT I am working with is on opensea, I was able to successfully complete "Balance Of" tutorial, returning correct values.
- Now trying to map that texture to my object

CONSOLE: 

![image](https://user-images.githubusercontent.com/47954784/149712047-c463e230-36f7-4ed9-bba8-70f7011e9af9.png)
![image](https://user-images.githubusercontent.com/47954784/149714133-65399dc8-2cc4-4ba0-866a-41fd290b19be.png)

If additional info is required I can provide it.

**Comment by KBryan** [comment]
curl won't work you will need to do something like the following.

`
if (imageUri.StartsWith("ipfs://"))
{
    imageUri = imageUri.Replace("ipfs://", "https://ipfs.io/ipfs/");
}
`
