### ISSUE TITLE
Have an ABI class and serialize it into json when making a request

### ISSUE THREAD

**Issue by kantagara** [ChainSafe/web3.unity#720]
Just so that our code will look cleaner and better organized.

**Comment by RyRy79261** [comment]
@sneakzttv

Didn't you experiment with the ABI generators? There are some that we could use from Nethereum for request encoders potentially

**Comment by RyRy79261** [comment]
@sneakzttv

Didn't you experiment with the ABI generators? There are some that we could use from Nethereum for request encoders potentially

I believe this is the same as this issue: https://github.com/ChainSafe/web3.unity/issues/683
