### ISSUE TITLE
Block Blasterz

### ISSUE THREAD

**Issue by boorich** [ChainSafe/web3.unity#723]
We're excited to introduce the Block Blasterz demo to showcase our SDK's capabilities fully. Below are the rough specifications for the demo:

**Game Details**

Name: Block Blasterz
Gameplay Loop: a FPS like Germ Blasters inside of a car garage. Player shoots enemies and unlocks stuff on the way.
Visual Style: Cartoonish, similar to [germ blasters](http://germblaster.xyz/) for a fast-paced experience
Scenery: Mechanics garage for block racers, gloomy and dark
Enemies: Oil blobs, wrench & tire enemies
Goal: Vanquish all enemies in the area to unlock a car part and repair the car
Cross-Game Interactions:

> Related Information about [Block Racers](https://github.com/ChainSafe/BlockRacers)
> After completing the level, the car you repair will have a decal that unlocks in the block racers game.
> Lootboxes containing new weapons & in-game currency for unlocking levels or costumes.
>
> Win races to earn tokens, which can be used to purchase special weapons in Block Blasterz.
> Lootboxes with aesthetic in-game rewards for racing.
> Lootbox Features:
> 
> Different rarities (rare, epic, etc.) can unlock NFTs that serve as weapons in Block Blasterz.
> NFTs can be traded across games through a burning or locking mechanic.
> Cross-platform loot boxes for rewarding items in both games.
> Chain Integration:

Both games will sit on different chains, facilitated by [Sygma](https://github.com/sygmaprotocol/sygma-sdk).

Action Items:

**Implementation of Cross-Game Features:**

- [x] ChainSafe/web3.unity#725
- [x] ChainSafe/web3.unity#763
- [x] ChainSafe/BlockBlasterz#17
- [ ] ChainSafe/BlockBlasterz#16
- [x] Implement the core gameplay loop in Unity

- [x] #833
- [x] #834

**Lootbox Implementation**

- [ ] ChainSafe/BlockBlasterz#8
- [x] #835

**Cross-Platform Integration:**

- [x] #836
- [x] #838

**Chain Integration:**

- [x] #837

**Complete Demo**
- [ ] https://github.com/ChainSafe/BlockBlasterz/issues/37

Additional Information:

- Consider implementing a custom call that mints another NFT in the second game for cross-game rewards.
- Explore the potential for cross-game NFT trading and rewards.

This issue is a comprehensive overview of the tasks needed to implement the Block Blasterz demo and showcase the SDK features effectively. Let's discuss and assign responsibilities accordingly!

**Comment by sneakzttv** [comment]
Continued in game repos
https://github.com/ChainSafe/BlockBlasterz/issues/
