### ISSUE TITLE
Describe the core gameplay loop in a game design document

### ISSUE THREAD

**Issue by kantagara** [ChainSafe/web3.unity#725]
https://www.notion.so/chainsafe/Block-Blasterz-Game-Design-Document-a9eb7801208741709fb6bff02e34931f?pvs=4

**Comment by sneakzttv** [comment]
Complete
![image](https://github.com/ChainSafe/web3.unity/assets/57473220/3ac500b8-628f-46bd-8a88-464fa400e05a)
