### ISSUE TITLE
Ramp MVP Release

### ISSUE THREAD

**Issue by boorich** [ChainSafe/web3.unity#726]
- [ ] #634 
- [x] #637 
- [x] https://github.com/ChainSafe/game-docs-v2/issues/78

**Comment by empea-careercriminal** [comment]
The Ramp Add-On as a minimal viable product does not require any frontend on the dashboard.

It is a pure Unity & Docs thing, exactly like Gasless Transactions Using Gelato.

We can “publish” this as it is right now by:

* updating the docs @sneakzttv 
* merging the sample scenes for web and iOS @kantagara
