### ISSUE TITLE
Show human-readable messages on connection errors for WebGLWallet (JS side)

### ISSUE THREAD

**Issue by oleksandrchainsafe** [ChainSafe/web3.unity#733]
**Summary**
Show human-readable messages on connection errors for WebGLWallet (JS side).

**Suggested features or ways to address the summary**
Find a suitable place to try/catch JS code for WebGLWallet. Display human-readable message to user.

**Motivation**
Right now error messages for WebGLWallet look like this:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEhTQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f8e4254fbc5de1832c433cc92ca1b5c5fb5bb429/image.png)
(at least for development build, haven't checked release builds)

**Comment by kantagara** [comment]
WebGLWallet won't be used, so closing this one as well.
