### ISSUE TITLE
Analytics is not reporting SDK version.

### ISSUE THREAD

**Issue by kalambet** [ChainSafe/web3.unity#740]
**Describe the bug**
Analytics is not reporting SDK version.

**Steps**
1. Login to the DataDog
2. Check `gaming-api-dd-prod` service logs
3. Notice that inside `evm` data structure there is no `version`.

**Expected behavior**
`version` should be presented in the `evm` object.

**Reproducible Code Snippet (if applicable):**
It is quite possible that the problem exists because of this nullable assignment and the only fix would be to make it conditional against empty string and not `null`

https://github.com/ChainSafe/web3.unity/blob/a81e54a91a4da080ef7c249b1c0e502edfc77628/src/ChainSafe.Gaming/Web3/Core/Analytics/ApiAnalyticsClient.cs#L27

**Comment by kantagara** [comment]
I don't have access to DataDog :(

**Comment by kantagara** [comment]
@kalambet I've forced the version to have the = assignment instead of the conditional expression. It's way more robust.
