### ISSUE TITLE
Trust Wallet and Wallet Connect is not working for WebGl Unity build

### ISSUE THREAD

**Issue by princeSuffescom** [ChainSafe/web3.unity#746]
**Describe the bug**
1. Once the user connects the build with Trust Wallet and tries to pay any token, then an error occurs which tells that the Invalid Provider or provider is not set.
2. If the user clicks on the Wallet Connect button then a QR is generated but when a user scans the QR in the Metamask application from their mobile phone, the error appears that this account is not associated with the contract.

**Steps**
1. Run Unity WebGL build.
3. Connect to the Trust Wallet by entering a password. (Using trust wallet extension).
4. After successfully connecting, I call the approve function to approve the contract by using the "Web3GL.SendContract() ".
5. After a few seconds Error occurs on the screen that says "Provider not set or Invalid Provider".
6. Please let me know if I am missing something.

**Console errors**
Invoking error handler due to
Error: Provider not set or invalid
at Object.InvalidProvider (http://127.0.0.1:5500/assets/index-f9496d0e.js:448:24588)

**Screenshot**
<img width="1025" alt="image" src="https://github.com/ChainSafe/web3.unity/assets/151526141/18ef339b-1bc3-4648-aa81-123929dbde9a">

```csharp```
string contractAddress = "CONTRACT_ADDRESS";
        string method = "approve";
        object[] parameters = new object[] { "SENDER_ADDRESSS", AMOUNT_IN_WEI };
        string args = JsonConvert.SerializeObject(parameters);
        string response = await Web3GL.SendContract(method, ABI, contractAddress, args, "0", "", "");

 - Chainsafe SDK version: 2.1.0
 - Unity Version: 2021.3.20f1
 - Operating System: Windows 11

**Additional context**
Please let me know the proper C# code example which is working fine with all the wallet providers (i.e. Trust Wallet, Wallet Connect). I am unable find to the proper code setup for multiple wallet implementation.

**Comment by juans-chainsafe** [comment]
Something going on with wallet connect apparently, is working with Metamask desktop extension but not with the Wallet connect networks

**Comment by princeSuffescom** [comment]
I am working on WebGL build.

**Comment by boorich** [comment]
Unfortunately, fixing this issue is beyond our reach. We are sorry about this and will get back to you if a solution is provided from the 3rd party service.
