### ISSUE TITLE
Compile error when import chainsafe unity sdk

### ISSUE THREAD

**Issue by hmthang0795** [ChainSafe/web3.unity#747]
**Describe the bug**
[error CS0246: The type or namespace name 'PlasticPipe' could not be found (are you missing a using directive or an assembly reference?)](https://github.com/ChainSafe/web3.unity/blob/c9690f82c34e873f297daa17b0c6351383ac87d9/Packages/io.chainsafe.web3-unity/Editor/Startup.cs#L5)

**Steps**
1. When import chainsafe sdk from openupm I have compile error appear

**Console errors**
![image](https://github.com/ChainSafe/web3.unity/assets/151043849/e1dc4905-9a12-46c3-b3ac-3d76efcdf698)

**Desktop (please complete the following information):**
 - Chainsafe SDK version: [e.g., 2.5.0]
 - Unity Version: [e.g., 2021.3.20]
 - Operating System: [e.g., Windows 10]

**Comment by sneakzttv** [comment]
this is an unnecessary include, i think it was being used by something before and was left behind during cleanup. Will fix and close via PR.
