### ISSUE TITLE
Walletconnect does not support Polygon network

### ISSUE THREAD

**Issue by regohiro** [ChainSafe/web3.unity#75]
**Describe the bug**
Wallet connect does not support Polygon. 

**To Reproduce**
1. WebGLTemplates > Web3GL-2020 > network.js line23 change the value of `window.web3NetworkId` to `137` 
2. Build and run
3. Login and select wallet connect
4. Does not show QR code 

**Expected behavior**
Shows QR code

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome 
 - Unity: 2020

**Additional context**
The issue is this code:
https://github.com/ChainSafe/game-web3gl/blob/2020/src/web3gl/index.ts#L72

Infura does not provide Polygon RPC for free unlike Ethereum. 
https://docs.blocknative.com/onboard#wallet-modules

I made a quick fix for this issue:
https://github.com/REGO350/game-web3gl/commit/a9d3362d44fe3a0737399495e9967499de0511d5

**Comment by KBryan** [comment]
We have moved away from WalletConnect in our new release. You should try this new update. https://github.com/ChainSafe/web3.unity/releases/tag/v1.2.0
