### ISSUE TITLE
Implement functionality to support multiple blockchain networks

### ISSUE THREAD

**Issue by kantagara** [ChainSafe/web3.unity#761]
**Motivation**
Because we want developers to easily switch their chains in the editor.

**Suggested features or ways to address the summary**
Essentially, Server Settings should be a scriptable object (like it is now), but it should have a serialized field called CurrentNetwork. Then, you can add new networks and drag and drop them to the Current Network Serialized Field. Project ID should be the same for all of them.

**Acceptance Criteria**
- [ ] Server Settings object should still be in the resources
- [ ] For every new Chain, each of them should be a child of the Server Settings (check [AssetDatabase.AddObjectToAsset](https://docs.unity3d.com/ScriptReference/AssetDatabase.AddObjectToAsset.html))
- [ ] Server Settings should have just project id, and the Current Network should be a serialized field in which you can drag and drop networks.
- [ ] When creating the chain scriptable object, you can give it a name (so that it's easier to search for it)
- [ ] You should also have the list of all the available networks in the server settings editor screen, so that you can easily drag and drop them to the Current Chain. Trough that list, you can also delete the scriptable object asset since you can't delete it manually once it's added to the asset.

**Comment by sneakzttv** [comment]
Ok so a couple of modifications that I'm proposing as the current setup seems counter intuitive :

Standard RPCs from Chainlist seem to work fine for reads and writes so i don't think that setup step is necessary anymore, we can probably remove it or keep it as an optional setup step if users want to use their own. Ontop of this I can generate a list of chains + their respective RPCs from chainlist and allow users to select this via a drop down menu. This would also remove the need to setup and search for scriptable objects.

With the above changes we should see our time to first transaction improve quite a bit.
