### ISSUE TITLE
web3auth login

### ISSUE THREAD

**Issue by RyRy79261** [ChainSafe/web3.unity#765]
# Summary 

For the game demo's, the objective is to present a distinctly Web2 onboarding experience, Social login's only for now.

## Objectives

- [x] #841

## Outstanding considerations

- We may need the user to sign some sort of terms, or acknowledge they have a certain amount of "Game time" Limitation, or "Game credit" Limitation, this is to prevent our Gelato `1Balance` reserve getting depleted too rapidly
  - Transaction funding could be seen as User Acquisition costs

## Documentation

Please refer to the documentation [here](https://docs.gaming.chainsafe.io/current/web2-like-authentication-using-web3auth) .

**Comment by boorich** [comment]
@RyRy79261 please add acceptance criteria 🙏🏼
