### ISSUE TITLE
Assess architecture for AA TX flows

### ISSUE THREAD

**Issue by RyRy79261** [ChainSafe/web3.unity#769]
# Summary 

There are some data flow changes with the way `UserOperations` reach being included in a block, as well as some considerations around `PayMaster` interactions that could require changes to our existing `TransactionExecutor` components.

## Objectives

- [ ] Assess impact of integration on existing DevEx flows 
- [ ] In order to introduce this new workflow for transactions, the user experience should present as familiar to non-poweruser(in respect to blockchain) game developers, while allowing for more nuanced settings, such as custom paymasters, custom MPC structures potentially.
- [ ] Diagram of Login -> Completed transaction produced
  - [ ] For each form of sponsored transaction made available by the initial AA provider

**Comment by sneakzttv** [comment]
Closed as the issue is redundant now.
