### ISSUE TITLE
Bug Tracker 2.5.5 Release

### ISSUE THREAD

**Issue by boorich** [ChainSafe/web3.unity#787]
What to do?
Fix this list from top to bottom unless blockers arise.

- [x] #761
- [x] #730
- [x] #759
- [x] #732 
- [x] #778
- [x] #780
- [x] #757

**Comment by sneakzttv** [comment]
Removed 727 and 729 as #727 seems isolated and #779 sepolia cant be fixed by us. Closing this issue on the next PR merge as everything is complete.
