### ISSUE TITLE
Countly Unity SDK Integration

### ISSUE THREAD

**Issue by kalambet** [ChainSafe/web3.unity#795]
**Summary**
Countly Unity SDK integration is necessary to start keeping analytics in more organized manner.

**Suggested features or ways to address the summary**
The main goal is to integrate [Countly Unity SDK](https://support.count.ly/hc/en-us/articles/360037813851-Unity) Into the our [`ApiAnalyticsClient`](https://github.com/ChainSafe/web3.unity/blob/main/src/ChainSafe.Gaming/Web3/Core/Analytics/ApiAnalyticsClient.cs) and make sure that all the fields are properly mapped and sent to the server side.

**Motivation**
All of our Gaming analytics reporting moving towards Countly.

**Acceptance Criteria**
- Analytics Client implemented using Countly SDK
- All existing events are being sent to the Countly instance

**Blockers**
Infrastructure needs to be set up and ready to receive the data.

**Comment by sneakzttv** [comment]
This is complete and i can see it being initialized in main.
