### ISSUE TITLE
Update analytics sending events

### ISSUE THREAD

**Issue by kalambet** [ChainSafe/web3.unity#796]
**Summary**
Review and update current list of events sent out by Analytics Client

**Suggested features or ways to address the summary**
Beside existing analytics calls on RPC calls several new need to be added:
- [x] Event on pressing "Save" on the web3 Unity SDK Project Settings
- [x] Web3Atuh - event on Initialization
- [x] Gassless - event on Initialization
- [x] Lootboxes - event on Initialization 

**Motivation**
We need to be more precise on finding time to first transaction and some other Product related metrics.

**Acceptance Criteria**
All events mentioned above can be viewed on the the Countly server side

**Blockers**
Blocked by finalization of #795

**Comment by kantagara** [comment]
@kalambet  
> Event on pressing "Save" on the web3 Unity SDK Project Settings
This can't be done in the current way analytics are set up. They only work in runtime, and breaking that flow would severely impact our architecture.
