### ISSUE TITLE
Switch to a Single Scene Samples

### ISSUE THREAD

**Issue by robGG1997** [ChainSafe/web3.unity#810]
**Summary**
Switch our current menu loading system from multiple scenes to a single scene using prefabs and menu regions.

**Suggested features or ways to address the summary**
Use a Manager that loads and unloads different menus as prefabs on certain events.

**Motivation**
We currently have multiple scenes in our multiple samples and we need to unify those under one scene for ease of use and to minimize samples setup.

**Acceptance Criteria**
Samples have to use a single scene to load/unload menus

**Blockers**
(OPTIONAL) [Do you see any blocker that needs to be done before implementing this feature?]

**Dependencies**
(OPTIONAL) [Do you know about dependencies that directly affect this issue?]

**Additional Context**
(OPTIONAL) [Add any other context, files, images (screenshots/videos), diagrams, or documents about the feature request here.]

**Final Steps**
* Give it one of these labels `Type: Feature` `Type: Enhancement`
* Add your estimation

**Estimations**

| Story Point | Amount of effort | Amount of time | Task Complexity | Task Risk or Uncerntainty |
|----------|----------|----------|----------|----------|
| 8 | Severe efort | A week | Medium complexity | Moderate |

**Comment by kantagara** [comment]
@robGG1997 I would also encourage the removal of the scene indexer once single scene loading is done, since scene indexer is giving us more harm than good atm. 
Also, just thinking out loud, that manager should proooobably be part of the samples, but login/logout events should definitely be part of the core SDK.

**Comment by robGG1997** [comment]
> @robGG1997 I would also encourage the removal of the scene indexer once single scene loading is done, since scene indexer is giving us more harm than good atm. Also, just thinking out loud, that manager should proooobably be part of the samples, but login/logout events should definitely be part of the core SDK.

Will do!
