### ISSUE TITLE
failed to install releases 2.1.0 web3.unitypackage

### ISSUE THREAD

**Issue by MikeHatchi** [ChainSafe/web3.unity#814]
**Describe the bug**
When dropping the downloaded package from https://github.com/ChainSafe/web3.unity/releases/tag/v2.1.0 into Unity project Assets folder it produces a bunch of errors which are not the unique expecting one: "Project ID Not Valid Please Go.To.Dashboard.ChainSafe.io..."

**Steps**
1. Dowload releases 2.1.0 web3.unitypackage from [here ](https://github.com/ChainSafe/web3.unity/releases/tag/v2.1.0)
2. Drag it into your unity project Assets folder
3. Immediate Web3Unity/Scripts/Prefabs/... errors 

**Expected behavior**
I should expect the error mentioned in the tutorial installation: https://docs.gaming.chainsafe.io/current/project-id-registration/#open-unity-and-install-the-web3unity-package 

**Console errors**
Assets/Web3Unity/Scripts/Prefabs/ERC20/ERC20TotalSupplyExample.cs(4,7): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)
Assets/Web3Unity/Scripts/Prefabs/WebGL/WebGLTransfer721.cs(3,7): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)
Assets/Web3Unity/Scripts/Prefabs/Minter/GetListedCollectionsWebGL.cs(7,7): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)
Assets/Web3Unity/Scripts/Prefabs/Minter/GetListedNFTWebGL.cs(5,7): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)
...
and so on until
Assets/Web3Unity/Scripts/Prefabs/WebGL/WebGLTransfer721.cs(3,7): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)

**Desktop (please complete the following information):**
 - Chainsafe SDK version: 2.1.0
 - Unity Version: 2022.3.13f1
 - Operating System: macOS 14.1.1 (23B81)

**Comment by kantagara** [comment]
You need to install newtonsoft json library trough unity package manager

**Comment by MikeHatchi** [comment]
Thanks @kantagara I'll close this issue then!!
A little digression here it seems that we cannot add any other networks than the ones propose by ChainSafe.

**Comment by kantagara** [comment]
Can you edit the chainsafe server setting itself in the resources folder, maybe there you can add your own network?

**Comment by MikeHatchi** [comment]
This is more tricky, you need to set your registration at chainsafe.io and there you cannot add any other rpc than the proposed ones. If not, the SDK cannot be unlock in Unity.
So, I'm trying with other SDK providers but the thing is I don't need all the smart contracts proposed in these SDKs.
I just need MetaMask and the ability to connect Unity to my deployed smart contracts and their states.
