### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by kantagara** [ChainSafe/web3.unity#815]
**Summary**
Currently, it seems like our documentation API is severely outdated due to our API Changes, and first-time users have issues with it.

**Motivation**
Our documentation is up-to-date

**Acceptance Criteria**

- [x]  Getting Started is updated and it clearly states how to use signer, transaction executor and how to connect via either web3auth, metamask or WalletConnect.
- [x] Other parts of the docs should be also double checked.

**Comment by boorich** [comment]
There is a repo dedicate tot eh docs @kantagara. We might want to handle the issues for updating there.

**Comment by boorich** [comment]
@kantagara please make sure to keep the release and the docs in sync.

**Comment by oleksandrchainsafe** [comment]
Undocumented code:
- Connecting WalletConnect wallet
- Connecting MetaMask wallet

**Comment by sneakzttv** [comment]
Will go over this later today.
