### ISSUE TITLE
Switch Wallet Connect to Unity Package from OpenUPM

### ISSUE THREAD

**Issue by robGG1997** [ChainSafe/web3.unity#816]
**Summary**
Currently we're using [WalletConnectSharp](https://github.com/WalletConnect/WalletConnectSharp) but we'll need to switch to [WalletConnectUnity](https://github.com/WalletConnect/WalletConnectUnity) the official UPM package also on OpenUPM.

**Suggested features or ways to address the summary**
Move WalletConnect implementation from `ChainSafe.Gamming.WalletConnect` into Unity

**Motivation**
This is an officially supported Unity implementation.

**Acceptance Criteria**
All previously working Wallet Connect features should also work with this new refactor
- Connecting to Wallet with and without remember me
- Signing Message and typed data
- Sending Transactions

**Blockers**
(OPTIONAL) [Do you see any blocker that needs to be done before implementing this feature?]

**Dependencies**
(OPTIONAL) [Do you know about dependencies that directly affect this issue?]

**Additional Context**
(OPTIONAL) [Add any other context, files, images (screenshots/videos), diagrams, or documents about the feature request here.]

**Final Steps**
* Give it one of these labels `Type: Feature` `Type: Enhancement`
* Add your estimation

**Estimations**

| Story Point | Amount of effort | Amount of time | Task Complexity | Task Risk or Uncerntainty |
|----------|----------|----------|----------|----------|
| 5 | Moderate efort | A few days | Mediium complexity | Moderate |

**Comment by oleksandrchainsafe** [comment]
This needs more research before starting work on it.

1. Last time I checked their implementation offered authorization only using QR code. You couldn't auth using locally installed wallet.
2. The overall quality of their solution was not that great.
3. Currently WalletConnect integration is part of the Core solution, meaning this can potentially work outside Unity. Using their solution would limit us to Unity only again.

**Comment by oleksandrchainsafe** [comment]
Work in progress. Currently blocked. Waiting for help from WalletConnect with the issue.

**Comment by kantagara** [comment]
Closing this for now since with the openUPM one success rate was even lower.
