### ISSUE TITLE
Sample output build is not giving a hash

### ISSUE THREAD

**Issue by sneakzttv** [ChainSafe/web3.unity#819]
When sending transactions i.e minterc1155 from the sample scene, we're unable to pull the result out of the sample build output. It's showing up as blank. This was working prior to 2.5.5. A user needs this to be able to do things like open up an etherscan page for a user. You can see the data's there when sending a transaction but it doesn't make it to the output class for some reason.

![image](https://github.com/ChainSafe/web3.unity/assets/57473220/f9fe7e5c-2290-43e4-81d5-5a6dc16bab22)

```
/// <summary>
/// Mint ERC1155 tokens
/// </summary>
public async void MintErc1155()
{
    var response = await Erc1155.MintErc1155(Web3Accessor.Web3, ABI.Erc1155, Contracts.Erc1155, idMint, amountMint);
    var output = SampleOutputUtil.BuildOutputValue(response);
    SampleOutputUtil.PrintResult(output, nameof(Erc1155), nameof(Erc1155.MintErc1155));
}
```

**Comment by RyRy79261** [comment]
@sneakzttv I think the transaction hash is there on the highlighted event, they wouldn't change

**Comment by sneakzttv** [comment]
Hmm if you check the issue here you can see the build output giving a result now, odd

https://github.com/ChainSafe/web3.unity/issues/826
