### ISSUE TITLE
Firefox: Uncaught (in promise) DOMException: Clipboard write was blocked due to lack of user activation.

### ISSUE THREAD

**Issue by quantumsheep** [ChainSafe/web3.unity#82]
**Describe the bug**
Firefox can't access the clipboard, throwing the following error:
```
Uncaught (in promise) DOMException: Clipboard write was blocked due to lack of user activation.
```

**To Reproduce**
1. Run WalletLogin example scene
2. Click on "Login"
3. Sign the message using MetaMask on Firefox
4. *login fails*
5. Go in Firefox dev console to see the error

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: macOS 12.1
 - Browser: Firefox
 - Version: 96.0.2

**Additional context**
Firefox **should** grant clipboard write access by default as explained [here](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText).
> The `"clipboard-write"` permission of the [Permissions API](https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API), is granted automatically to pages when they are in the active tab. 

Also worth mentioning that it do work perfectly fine using Google Chrome.

**Comment by KBryan** [comment]
This you for posting this. Will look into this further.

**Comment by KBryan** [comment]
I'm not receiving this error. Could you try the newest build and see if this issue is still present.

**Comment by quantumsheep** [comment]
The issue is not here anymore, however nothing is automatically put in the clipboard. Looking at the code it seems that `copyToClipboard` is not called after signing.
