### ISSUE TITLE
Issue Tracker 2.6

### ISSUE THREAD

**Issue by boorich** [ChainSafe/web3.unity#820]
- [x] #880
- [ ] #790 
- [ ] #816 
- [x] #831
- [x] #883 
- [ ] #812
- [ ] #878 
- [x] #879
- [ ] #870 
- [x] #818 
- [x] #811 
- [x] #726
- [x] #727
- [x] #779
- [x] #789
- [x] #794 
- [x] #795 
- [x] #796 
- [x] #804 
- [x] #810
- [x] #815 
- [x] #817 
- [x] #819
- [x] #824

**Comment by boorich** [comment]
@kantagara Proititized and sorted.

**Comment by sneakzttv** [comment]
Closing and moving leftover issues to 2.6.1 tracker https://github.com/ChainSafe/web3.unity/issues/1009
