### ISSUE TITLE
getting data as zero in contract call

### ISSUE THREAD

**Issue by 57555** [ChainSafe/web3.unity#826]
**Describe the bug**
I'm using chainsafe sample scene for connecting wallet, and in my main scene, I am trying to call functions on a custom smart contract. 
I have two functions on my smart contract, one of them returns owner address, and the other one returns msg.sender.
I can get result correctly from ownerAddress(). but the result of currentAddress() is always zero. (0x0000000000000000000000000000000000000000)

**Steps**
1. Use the scene [SampleLogin] to login and go to a new scene.
2. place this script in your new scene:
```csharp

using ChainSafe.Gaming.UnityPackage;
using Newtonsoft.Json;
using UnityEngine;

public class callContract : MonoBehaviour
{
    private string contractAddress = "0xe5Bc53Ab7e38e77BEfe90cd934E2e4ceA8789999";
    private string abi = "[{\"inputs\":[],\"stateMutability\":\"nonpayable\",\"type\":\"constructor\"},{\"inputs\":[],\"name\":\"currentAddress\",\"outputs\":[{\"internalType\":\"address\",\"name\":\"_sender\",\"type\":\"address\"}],\"stateMutability\":\"view\",\"type\":\"function\"},{\"inputs\":[],\"name\":\"owner\",\"outputs\":[{\"internalType\":\"address\",\"name\":\"\",\"type\":\"address\"}],\"stateMutability\":\"view\",\"type\":\"function\"},{\"inputs\":[],\"name\":\"ownerAddress\",\"outputs\":[{\"internalType\":\"address\",\"name\":\"_owner\",\"type\":\"address\"}],\"stateMutability\":\"view\",\"type\":\"function\"}]";

    public async void call(string method)
    {
        var contract = Web3Accessor.Web3.ContractBuilder.Build( abi, contractAddress);

        object[] response = await contract.Call(method);

        Debug.Log("current address: " + await Web3Accessor.Web3.Signer.GetAddress());
        Debug.Log(method + " call result: " + JsonConvert.SerializeObject(response));
    }
}

```
3. call ownerAddress() and currentAddress() on this contract:  https://testnet.bscscan.com/address/0xe5bc53ab7e38e77befe90cd934e2e4cea8789999#code

**Expected behavior**
ownerAddress() returns the correct address but currentAddress() returns this: ["0x0000000000000000000000000000000000000000"]

**Console errors**
no error

**Screenshots/Video**
![Capture](https://github.com/ChainSafe/web3.unity/assets/52746504/064356c0-67e0-4c24-ae42-8c872377b7f1)

**Desktop (please complete the following information):**
 - Chainsafe SDK version: [2.5.5]
 - Unity Version: [2022.3.2f1]
 - Operating System: [Windows 10]
 - network: [bnb testnet]

**Additional context**
I installed chainsafe from unity package manager, first method here:
https://docs.gaming.chainsafe.io/current/getting-started
connected trust wallet via "clipboard" option.
also currentAddress() function is fine on the contract, it show the correct value via javascript or remix

am I doing something wrong here or there is a problem with this SDK? 
thanks in advance

**Comment by sneakzttv** [comment]
I'll look into this for you :)

**Comment by 57555** [comment]
@sneakzttv thank you so much sir, I'm pretty sure smart contract has no problem, because I tested it with ethers.js and remix IDE

**Comment by sneakzttv** [comment]
Firstly you should be using inheritance instead of setting the owner manually, this will also give you the ability to change the owner as you wish following standards so it's secure. I have also updated your solidity version and provided comments throughout the contract explaining what everything does.

For the owner you would be calling "owner" as the method, you can also renounce and transfer as needed.

![image](https://github.com/ChainSafe/web3.unity/assets/57473220/1a249c63-f16f-4f52-b595-3bae10420f79)

```
// SPDX-License-Identifier: MIT
pragma solidity 0.8.20;

///@dev This is importing the ownable contract from open zepplin which follows standards
import "@openzeppelin/contracts/access/Ownable.sol";

///@dev Here we're inhetiting from the ownable contract in order to set the owner via the constructor
contract MyTest is Ownable{

    ///@dev Sets the contract owner to the address deploying this contract
    constructor() Ownable(msg.sender) {}

    ///@dev Calls the address interacting with this function
	function currentAddress() public view returns (address) {
    	return msg.sender;
	}
}
```

Please give this a go and let me know :)

**Comment by 57555** [comment]
thank you for your fast response, I tried it but the problem remains the same in unity. 
results in unity: 

owner call result: ["0xE2A580f83f570550F30ae5A5B445EFfDe55a0545"]
currentAddress call result: ["0x0000000000000000000000000000000000000000"]

are you sure everything is correct in C# side?

**Comment by sneakzttv** [comment]
I'm just in meetings for the next hour or so, ill boot this up in unity after and make sure it works for you and come back with a solution :)

**Comment by 57555** [comment]
@sneakzttv thanks so much man

**Comment by 57555** [comment]
yes, that's it, I don't know why this is happening. I saw this while working on a project with a similar smart contract.
I don't have access to their smart contract code, all I know is that their are returning some values, a part of the result is msg.sender , and I'm getting the entire result as zero

**Comment by sneakzttv** [comment]
yeah, it shouldn't be the zero address for sure, it should be the address calling the function. Something's up here.

**Comment by 57555** [comment]
yes, I had the same problem with web3.js , but this shows the correct result with ethers.js

**Comment by sneakzttv** [comment]
This should essentially be your c# code also provided you've imported the sample project

`using System;
using ChainSafe.Gaming.UnityPackage;
using ChainSafe.Gaming.Web3;
using Scripts.EVM.Token;
using UnityEngine;

public class AddressTest : MonoBehaviour
{
    private string abi = "[ { \"inputs\": [], \"stateMutability\": \"nonpayable\", \"type\": \"constructor\" }, { \"inputs\": [ { \"internalType\": \"address\", \"name\": \"owner\", \"type\": \"address\" } ], \"name\": \"OwnableInvalidOwner\", \"type\": \"error\" }, { \"inputs\": [ { \"internalType\": \"address\", \"name\": \"account\", \"type\": \"address\" } ], \"name\": \"OwnableUnauthorizedAccount\", \"type\": \"error\" }, { \"anonymous\": false, \"inputs\": [ { \"indexed\": true, \"internalType\": \"address\", \"name\": \"previousOwner\", \"type\": \"address\" }, { \"indexed\": true, \"internalType\": \"address\", \"name\": \"newOwner\", \"type\": \"address\" } ], \"name\": \"OwnershipTransferred\", \"type\": \"event\" }, { \"inputs\": [], \"name\": \"currentAddress\", \"outputs\": [ { \"internalType\": \"address\", \"name\": \"\", \"type\": \"address\" } ], \"stateMutability\": \"view\", \"type\": \"function\" }, { \"inputs\": [], \"name\": \"owner\", \"outputs\": [ { \"internalType\": \"address\", \"name\": \"\", \"type\": \"address\" } ], \"stateMutability\": \"view\", \"type\": \"function\" }, { \"inputs\": [], \"name\": \"renounceOwnership\", \"outputs\": [], \"stateMutability\": \"nonpayable\", \"type\": \"function\" }, { \"inputs\": [ { \"internalType\": \"address\", \"name\": \"newOwner\", \"type\": \"address\" } ], \"name\": \"transferOwnership\", \"outputs\": [], \"stateMutability\": \"nonpayable\", \"type\": \"function\" } ]";
    private string contract = "0x47c6e35F919c779AdaadaFEb2C341F995CEd8fa4";

    public async void CallingAddressTest()
    {
        try
        {
            var method = "currentAddress";
            var account = await Web3Accessor.Web3.Signer.GetAddress();
            Debug.Log($"Calling method: {method} with account: {account}");
            object[] args = {};
            var response = await Evm.ContractCall(Web3Accessor.Web3, method, abi, contract, args);
            var output = SampleOutputUtil.BuildOutputValue(response);
            SampleOutputUtil.PrintResult(output, nameof(Evm), nameof(Evm.ContractCall));
        }
        catch (Web3Exception e)
        {
            Console.WriteLine(e);
            throw;
        }
    }

    public async void OwnerTest()
    {
        try
        {
            var method = "owner";
            Debug.Log($"Calling method: {method}");
            object[] args = {};
            var response = await Evm.ContractCall(Web3Accessor.Web3, method, abi, contract, args);
            var output = SampleOutputUtil.BuildOutputValue(response);
            SampleOutputUtil.PrintResult(output, nameof(Evm), nameof(Evm.ContractCall));
        }
        catch (Web3Exception e)
        {
            Console.WriteLine(e);
            throw;
        }
    }
}
`

**Comment by 57555** [comment]
thanks for the detailed feedback, I have tried both "Evm.ContractCall" and this:

var contract = Web3Accessor.Web3.ContractBuilder.Build( abi, contractAddress);
object[] response = await contract.Call(method);

but no luck so far, btw, thank you so much for checking it <3

**Comment by sneakzttv** [comment]
yeah, the above is essentially the same, i'm just using the helper function. I'm going try to manually create the transaction object. Bear with me.

**Comment by sneakzttv** [comment]
got it!

**Comment by 57555** [comment]
what happened?

**Comment by sneakzttv** [comment]
Here you go :) I manually created the transaction object to override the base functionality. Once we've updated the dlls we'll push it to main, for now you can use this code.

```
using System;
using ChainSafe.Gaming.Evm.Transactions;
using ChainSafe.Gaming.UnityPackage;
using ChainSafe.Gaming.Web3;
using Scripts.EVM.Token;
using UnityEngine;

public class AddressTest : MonoBehaviour
{
    private string abi = "[ { \"inputs\": [], \"stateMutability\": \"nonpayable\", \"type\": \"constructor\" }, { \"inputs\": [ { \"internalType\": \"address\", \"name\": \"owner\", \"type\": \"address\" } ], \"name\": \"OwnableInvalidOwner\", \"type\": \"error\" }, { \"inputs\": [ { \"internalType\": \"address\", \"name\": \"account\", \"type\": \"address\" } ], \"name\": \"OwnableUnauthorizedAccount\", \"type\": \"error\" }, { \"anonymous\": false, \"inputs\": [ { \"indexed\": true, \"internalType\": \"address\", \"name\": \"previousOwner\", \"type\": \"address\" }, { \"indexed\": true, \"internalType\": \"address\", \"name\": \"newOwner\", \"type\": \"address\" } ], \"name\": \"OwnershipTransferred\", \"type\": \"event\" }, { \"inputs\": [], \"name\": \"currentAddress\", \"outputs\": [ { \"internalType\": \"address\", \"name\": \"\", \"type\": \"address\" } ], \"stateMutability\": \"view\", \"type\": \"function\" }, { \"inputs\": [], \"name\": \"owner\", \"outputs\": [ { \"internalType\": \"address\", \"name\": \"\", \"type\": \"address\" } ], \"stateMutability\": \"view\", \"type\": \"function\" }, { \"inputs\": [], \"name\": \"renounceOwnership\", \"outputs\": [], \"stateMutability\": \"nonpayable\", \"type\": \"function\" }, { \"inputs\": [ { \"internalType\": \"address\", \"name\": \"newOwner\", \"type\": \"address\" } ], \"name\": \"transferOwnership\", \"outputs\": [], \"stateMutability\": \"nonpayable\", \"type\": \"function\" } ]";
    private string contractAddress = "0x47c6e35F919c779AdaadaFEb2C341F995CEd8fa4";

    public async void CallingAddressTest()
    {
        try
        {
            var method = "currentAddress";
            var account = await Web3Accessor.Web3.Signer.GetAddress();
            Debug.Log($"Calling method: {method} with account: {account}");
            object[] args = {};
            var transactionRequest = new TransactionRequest
            {
                To = contractAddress,
                From = account
            };
            var contract = Web3Accessor.Web3.ContractBuilder.Build(abi, contractAddress);
            object[] response = await contract.Call(method, args, transactionRequest);
            var output = SampleOutputUtil.BuildOutputValue(response);
            SampleOutputUtil.PrintResult(output, nameof(Evm), nameof(Evm.ContractCall));
        }
        catch (Web3Exception e)
        {
            Console.WriteLine(e);
            throw;
        }
    }

    public async void OwnerTest()
    {
        try
        {
            var method = "owner";
            Debug.Log($"Calling method: {method}");
            object[] args = {};
            var response = await Evm.ContractCall(Web3Accessor.Web3, method, abi, contractAddress, args);
            var output = SampleOutputUtil.BuildOutputValue(response);
            SampleOutputUtil.PrintResult(output, nameof(Evm), nameof(Evm.ContractCall));
        }
        catch (Web3Exception e)
        {
            Console.WriteLine(e);
            throw;
        }
    }
}
```

**Comment by 57555** [comment]
thank you so much, I owe you one

**Comment by sneakzttv** [comment]
Closing the issue for now and we'll update main tomorrow, happy coding :)

**Comment by 57555** [comment]
thank you so much!
