### ISSUE TITLE
iOS only issue. window.ethereum.request is undefined

### ISSUE THREAD

**Issue by B1Q** [ChainSafe/web3.unity#827]
Hello there, this issue occurs on legacy version 1.6.2 on iOS 15

It works just fine in an android but for some reason iOS refuses to connect to a wallet and throws this error 
![IMG_20240118_135933](https://github.com/ChainSafe/web3.unity/assets/8680173/ffa330a9-191c-4cd0-9830-4f2756cfe320)

**Comment by kantagara** [comment]
Hello, we unfortunately do not support 1.6 anymore. And by the look of this, this is a web browser ?

**Comment by B1Q** [comment]
> Hello, we unfortunately do not support 1.6 anymore. And by the look of this, this is a web browser ?

Thought so, it's a very old version at this point. 

This is indeed a web browser, it's a web game that runs within the metamask or any wallet's integrated browser. 

So you recommend I take a shot at upgrading to the latest version and see if that fixes it? 

One guy claims there's a condition that should be changed/added in js (after compilation)

**Comment by kantagara** [comment]
> One guy claims there's a condition that should be changed/added in js (after compilation)
If you know how to do it, then by all means, do it.
I wouldn't advise you to upgrade to the latest and greatest TBH, since architectures of SDKs are dramatically different. So different that learning curve is steep if you're really comfortable with 1.6.

**Comment by juans-chainsafe** [comment]
hey @B1Q so in order to build this, you are using XCode or how are you building the web app into the iPhone?

**Comment by B1Q** [comment]
> hey @B1Q so in order to build this, you are using XCode or how are you building the web app into the iPhone?

It's a webgl build with WebGL 1.0 enabled 
I solved the problem by downgrading to 1.5

**Comment by sneakzttv** [comment]
Closing this as it's a deprecated issue.
