### ISSUE TITLE
Hyperplay SDK Sample & Integration

### ISSUE THREAD

**Issue by boorich** [ChainSafe/web3.unity#831]
**Summary**
Integrate the Hyperplay SDK into a sample scene and documentation

**Suggested features or ways to address the summary**
Follow the docs and provide a reference implementation of the Hyperplay SDK

**Motivation**
Hyperplay is a relevant component for access to an exciting distribution channel for games built with web3.untiy

**Acceptance Criteria**
- SIWE login via HyperPlay's desktop client launcher.
- Signing and executing transaction via HyperPlay's desktop client launcher.

**Additional Context**
[Ideation](https://www.notion.so/chainsafe/Hyperplay-CS-Gaming-ideation-d6015e28fae7415fbfca359ef3bbae65?pvs=4#a3564f4e2db74492b2584b6562fff198)
[Hyperplay Docs](https://docs.hyperplay.xyz/developer-docs/api)

**Comment by rob1997** [comment]
@boorich The potential integration in the ideation is implemented [here](https://github.com/ChainSafe/web3.unity/pull/955). Does that mean the acceptance criteria has been met?
