### ISSUE TITLE
ERC721.OwnerOfBatch returns error

### ISSUE THREAD

**Issue by mrmooijman** [ChainSafe/web3.unity#832]
Describe the bug
Fresh installation of Chainsafe Web3 SDK version 2.5.5 on Unity 2022.3.16f1, WebGL build, running on MacBook Pro macOS version 13.3.1. Experiencing an ArgumentException error when pressing the 'OwnerOfBatch' button in the SampleMain scene (after connecting through SampleLogin - Metamask) using the WebGL-Metamask template.

Steps to reproduce

Install Chainsafe SDK version 2.5.5 on Unity 2022.3.16f1 (both stable release from package manager or direct download from repo's main branch).
Build using WebGL-Metamask template.
Run SampleLogin - Metamask to connect to Metamask.
Run SampleMain scene.
Press 'OwnerOfBatch' button.

Expected behavior
The button should function without triggering errors. Expecting to retrieve a list of owners of (preconfigured) specific tokenids

Console errors

ArgumentException: length
at System.Array.Copy (System.Array sourceArray, System.Int32 sourceIndex, System.Array destinationArray, System.Int32 destinationIndex, System.Int32 length) [0x00000] in <00000000000000000000000000000000>:0 
--- End of stack trace from previous location where exception was thrown ---

Chainsafe SDK version: 2.5.5
Unity Version: 2022.3.16f1
Operating System: macOS version 13.3.1
Browsers Tested: Google Chrome

Additional context
Issue occurs with unchanged code from the sample scene.

**Comment by mrmooijman** [comment]
using the standard settings, only providing my chainsafe project key to the config
<img width="419" alt="Screenshot 2024-01-22 at 14 08 26" src="https://github.com/ChainSafe/web3.unity/assets/2845720/e6105e16-b25a-427b-9088-e42a213ce114">

**Comment by mrmooijman** [comment]
Tested again with fresh project and clean setup. No issue this time, getting freaky. Will let you know if i can reproduce. Closing issue.

**Comment by juans-chainsafe** [comment]
> Tested again with fresh project and clean setup. No issue this time, getting freaky. Will let you know if i can reproduce. Closing issue.

I suggest using a Chainstack RPC https://docs.gaming.chainsafe.io/current/setting-up-an-rpc-node or https://www.infura.io/ RPC for better usage of the SDK

**Comment by mrmooijman** [comment]
I reproduced using my own chainstack rpc (Ethereum mainnet) and following settings
<img width="421" alt="Screenshot 2024-01-22 at 22 55 08" src="https://github.com/ChainSafe/web3.unity/assets/2845720/a2c221de-1835-47be-ad7f-4c9030d5d447">
i updated the ERC721Call.cs in the sample to use my contract and check for the tokenId I own.
my wallet address is correctly returned by OwnerOf function.
OwnerOfBatch however gives me the error described in the issue:
<img width="751" alt="Screenshot 2024-01-22 at 22 56 55" src="https://github.com/ChainSafe/web3.unity/assets/2845720/b01d678b-ae43-4a02-b9e8-e0ef2b6a8663">

**Comment by mrmooijman** [comment]
tested with other tokenIds, they work fine.
tested with different wallet, same issue
tested with different contract, same issue.
as long as the tokenIds are not in my wallet, it will return the wallet addresses. 

second issue is that it has the Erc721 test wallet hardcoded in the function (OwnerOfBatch in Erc721.cs), it should copy the wallet address send to the function instead.

**Comment by sneakzttv** [comment]
this is due to the bug that is fixed in the upcoming release via this issue here https://github.com/ChainSafe/web3.unity/issues/826
