### ISSUE TITLE
Connectivity Issues with Mobile and Desktop

### ISSUE THREAD

**Issue by AzeemMalik0** [ChainSafe/web3.unity#840]
**Summary**
[in ChainSafe version 2.1.0 it was easy to connect with the Mobile and Desktop but with the latest chainSafe 2.5.5 it is not easy to connect with the mobile and Desktop please track the issue and make it easy to use. I'm using the ExistingWalletConnect Sample Scene to di this but while working for android it connects me to the metamask wallet and get back to the app but after that it throws an error that failed to login but with the chainsafe 2.1.0 this issue was not exist please fix this one and make it to connect with the mobile and desktop]

**Suggested features or ways to address the summary**
[As it was easy in chainsafe 2.1.0 and was compatible with the mobile and Desktop so please take necessary steps to make it happen with the latest chainsafe 2.5.5 as well so i can be useable with the mobile and desktop as well as it was working previously ]

**Motivation**
[Because now a days most of the people are using more mobile then the desktop or webGL so i guess it necessary and will be most preferable to make is happen with the mobile devices and will be much appreciated ]

**Acceptance Criteria**
[It should be compatible with the mobile devices and should be easy like chainsafe 2.1.0 .]

**Blockers**
(OPTIONAL) [Do you see any blocker that needs to be done before implementing this feature?]

**Dependencies**
(OPTIONAL) [Make the Login process smooth for the mobile devices]

**Additional Context**
(OPTIONAL) [Add any other context, files, images (screenshots/videos), diagrams, or documents about the feature request here.]

**Final Steps**
*  label : `Type: Feature`

**Comment by boorich** [comment]
@AzeemMalik0, thanks for your constructive feedback. We will be in touch.

**Comment by AzeemMalik0** [comment]
@boorich sure i'll be waiting for this to be done

**Comment by juans-chainsafe** [comment]
@AzeemMalik0 I was able to reproduce the error in Android, just in case, there is a workaround if you don't check the "Redirect to wallet" checkbox, and you login with the QR code that is generated after clicking on "Continue with existing wallet" button

**Comment by sneakzttv** [comment]
Please make sure you have the scenes in the build added to the build settings, so the log in scene and the next scene you're testing with. Also are you testing with an android device or the emulator? Also please can you update your steps, including the device you're using to test whether it's an android, an emulator etc so we can reproduce it.

Lastly please attach a screenshot of the error log so we can assist you better.
