### ISSUE TITLE
Login modal/screen to log in using the same social providers as the CS sample

### ISSUE THREAD

**Issue by boorich** [ChainSafe/web3.unity#841]
Users should be presented with a login modal/screen where they can log in using the same social providers as the CS sample.

Once logged in, the user's on chain interactions will be facilitated via Gelato's `sponsoredCall Erc2771`. This will allow for on chain interactions with user context without needing the user to fund any accounts.

**Comment by sneakzttv** [comment]
This is already done if they're using the w3a login screen, it also works with gelato. Users can take pieces from that scene or create a similar workflow with canvas object and dropdowns.
