### ISSUE TITLE
Web3Auth not working in Android

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#843]
**Describe the bug**

**Steps**
1. Use the scene [SampleLogin - Web3Auth]
2. Generate a Android build in a real device or emulator
3. Login with [Web3Auth]
4. Stuck in "Please do not reload the page." of Web3Auth

**Expected behavior**
User is redirected back to the app and sees the SampleMain

**Screenshots/Video**
<img width="608" alt="Screenshot 2024-01-24 at 15 55 55" src="https://github.com/ChainSafe/web3.unity/assets/104365141/3b76f414-ad11-45d2-ab91-7468d5e63e2d">

**Mobile (please complete the following information):**
 - Chainsafe SDK version: [2.5.5]
 - Platform: [Android]
 - Device Type: [Emulator]
 - OS Version: [Android API level 33]

**Comment by kantagara** [comment]
I tried to repro this on my android device and no luck :(
