### ISSUE TITLE
Webgl task never responses back

### ISSUE THREAD

**Issue by bamdad-b** [ChainSafe/web3.unity#845]
Hi, thanks for the wonderful library. I'm using unity `Web3GL-2020x` template and I've noticed there is a `Sie` function in `index-b28afd98.js` present in the template for sending transactions.
```js
async function Sie(t, e, r, n, s) {
    (await (await Mf.getSigner()).sendTransaction({
        to: t,
        value: e,
        gasPrice: r || void 0,
        gasLimit: n || void 0,
        data: s || void 0
    })).wait().then(f => {
        if (!f) throw Error("Receipt not found");
            window.web3gl.sendTransactionResponse = f.hash
    })
    .catch(f => window.web3gl.sendTransactionResponseData = f.message)
}
```

Now the problem is, seems like the `wait` function is not working correctly as my task gets missing along the way. `window.web3gl.sendTransactionResponse` is empty forever although the rpc commands are called and logged in network tab. The only way to get it to work is by pausing the debugger (so the async functions can run to completion) and there I'll have my hashID present in `window.web3gl.sendTransactionResponse`. So for now I've placed a call to `debugger;` in my code and asked my testers to open their browser consoles but this can not be a permanent way.  
I have `unitask 2.5.0` installed. Is there anything I should do to make it work?

**Comment by boorich** [comment]
Hello @bamdad-b, and thanks for your feedback. Addressing the issue you described might take us a moment due to the interplay between Unity, the embedded web environment, and asynchronous JavaScript code but we will get back to you next week.

In case you come across more information that you feel could be helpful, please add this in the comments.

@sneakzttv @juans-chainsafe

**Comment by bamdad-b** [comment]
@boorich Thank you, I am using Unity 2022.1.24f1. I was kinda looking for any gotchas, like how to check if Unitask is working properly? Or is there any tricks in building for WebGL that I've overseen?  
The non-write function calls on the contract are working as expected. Though they seem to have the exact same approach for contacting with browser-side js. The only difference is in write functions the user is prompted by the wallet manager and they need to approve the transaction.

**Comment by boorich** [comment]
@bamdad-b From what you said, I would not suspect Unitask or WebGL build settings, but the debugger's impact on the asynchronous flow.

We will know more when @oleksandrchainsafe has a moment to take a look at this.

🙏🏼

**Comment by robGG1997** [comment]
@bamdad-b we've implemented an alternate implementation for WebGL for Metamask browser extension and we're pivoting from WebGLWallet, so if it's possible to pivot we recommend that instead. [Here](https://github.com/ChainSafe/web3.unity/blob/main/src/UnitySampleProject/Assets/Samples/web3.unity%20SDK/2.5.0/Web3.Unity%20Samples/Scripts/Scenes/MetaMaskLogin.cs) is our sample example for usage reference.

**Comment by sneakzttv** [comment]
Yes, please update and use metamask with the thread patcher, this will be fixed :)
