### ISSUE TITLE
OwnerOfBatch wont return (My) wallet adress

### ISSUE THREAD

**Issue by mrmooijman** [ChainSafe/web3.unity#846]
Describe the bug
OwnerOfBatch wont return wallet belonging to tokenID, if wallet is my own.

Fresh installation of Chainsafe Web3 SDK version 2.5.5 on Unity 2022.3.16f1, WebGL build, running on MacBook Pro macOS version 13.3.1. Experiencing an ArgumentException error when pressing the 'OwnerOfBatch' button in the SampleMain scene (after connecting through SampleLogin - Metamask) using the WebGL-Metamask template.

Steps to reproduce

Install Chainsafe SDK version 2.5.5 on Unity 2022.3.16f1 (both stable release from package manager or direct download from repo's main branch).
**configure server Ethereum mainnet and chainstack rpc (ethereum node)** 
set the sample code ERC721Calls.cs to use 
Build using WebGL-Metamask template or use editor.
Run SampleLogin - Metamask to connect to Metamask.
Run SampleMain scene.
Press 'OwnerOfBatch' button.

Expected behavior
The button should function without triggering errors. Expecting to retrieve a list of owners of (preconfigured) specific tokenids

Console errors

ArgumentException: length
at System.Array.Copy (System.Array sourceArray, System.Int32 sourceIndex, System.Array destinationArray, System.Int32 destinationIndex, System.Int32 length) [0x00000] in <00000000000000000000000000000000>:0
--- End of stack trace from previous location where exception was thrown ---

Chainsafe SDK version: 2.5.5
Unity Version: 2022.3.16f1
Operating System: macOS version 13.3.1
Browsers Tested: Google Chrome

Additional context
Issue occurs with unchanged code from the sample scene.

**Comment by sneakzttv** [comment]
this is due to the bug that is fixed in the upcoming release via this issue here https://github.com/ChainSafe/web3.unity/issues/826

**Comment by kantagara** [comment]
@sneakzttv this issue still persists.

**Comment by sneakzttv** [comment]
![image](https://github.com/ChainSafe/web3.unity/assets/57473220/51b60f76-415e-4cae-9373-5c2ed1534f8e)

As far as I can see this works, please check this for me and see if you can get the same results.

`
using ChainSafe.Gaming.UnityPackage;
using Scripts.EVM.Token;
using UnityEngine;
using UnityEngine.UI;

public class BatchTest : MonoBehaviour
{
    // Variables
    private string contractAddress = "0x4f75BB7bdd6f7A0fD32f1b3A94dfF409F5a3F1CC";
    private string[] tokenIds = { "1", "6" };
    public Text ownerText;

    public async void BatchTestCall()
    {
        var data = await Erc721.OwnerOfBatch(Web3Accessor.Web3, contractAddress, tokenIds);
        var response = $"{data.Count} owner(s):\n" + string.Join(",\n", data);
        Debug.Log($"Owners: {response}");
        ownerText.text = response;
    }
}

`
`using System.Numerics;
using ChainSafe.Gaming.UnityPackage;
using Scripts.EVM.Token;
using UnityEngine;
using UnityEngine.UI;

public class OwnerTest : MonoBehaviour
{
    // Variables
    private string contractAddress = "0x4f75BB7bdd6f7A0fD32f1b3A94dfF409F5a3F1CC";
    private string tokenId = "1";
    public Text ownerText;

    public async void OwnerTestCall()
    {
        var response = tokenId.StartsWith("0x") ? 
            await Erc721.OwnerOf(Web3Accessor.Web3, contractAddress, tokenId) 
            : await Erc721.OwnerOf(Web3Accessor.Web3, contractAddress, BigInteger.Parse(tokenId));
        Debug.Log($"Owner: {response}");
        ownerText.text = response;
    }
}
`

**Comment by mrmooijman** [comment]
two things:

1) Erc721.OwnerOfBatch has the test contractID hardcoded
![Screenshot 2024-02-08 at 17 42 21](https://github.com/ChainSafe/web3.unity/assets/2845720/c009257d-6b29-46e0-b868-7c860ee27705)

2) I copied the function into my own script to test with the correct contractAddress

![Screenshot 2024-02-08 at 17 44 13](https://github.com/ChainSafe/web3.unity/assets/2845720/4dae0fb6-3ab5-4976-9e6c-7a7da2066412)


I am testing an ethereum mainnet nft contract: 
0xb61f06bd84b81f7619e5cbcabc0dce53199eb7a2

3) the returned wallet address is mostly wrong, not always

this is testing tokenId '1' for both ownerOf and ownerOfBatch, returning both the same address correctly
<img width="1062" alt="Screenshot 2024-02-08 at 17 46 59" src="https://github.com/ChainSafe/web3.unity/assets/2845720/78d6c7e2-3101-44af-8f56-a540674c3f8a">

testing with tokenId '321' I get different outputs, where the result from ownerOf is correct

<img width="1054" alt="Screenshot 2024-02-08 at 17 47 16" src="https://github.com/ChainSafe/web3.unity/assets/2845720/7d6026e9-d05c-4cf6-9f81-30a7a9ddf56c">

**Comment by mrmooijman** [comment]
also noticed tokenid 0 to 9 work, anything 10 and above doesnt.

**Comment by kantagara** [comment]
That's a great insight! I'll take a look at it.
