### ISSUE TITLE
A Native Collection has not been disposed, resulting in a memory leak

### ISSUE THREAD

**Issue by quantumsheep** [ChainSafe/web3.unity#85]
**Describe the bug**
```
A Native Collection has not been disposed, resulting in a memory leak. Enable Full StackTraces to get more details.
```

**To Reproduce**
1. Make a call to `EVM.Call`

**Expected behavior**
No error.

**Screenshots**
<img width="745" alt="image" src="https://user-images.githubusercontent.com/7271496/151679791-26d11fb5-a772-44ad-83a0-d261413c13cc.png">

**Desktop (please complete the following information):**
 - OS: macOS 12.1

**Comment by KBryan** [comment]
Thanks for posting this. Will look into this today.

**Comment by KBryan** [comment]
Sorry for the late response on this. Can you give me steps to reproduce this error?

**Comment by KBryan** [comment]
This has been updated in the latest release.
