### ISSUE TITLE
Login after doing a logout in Metamask not working

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#857]
**Describe the bug**
This happens only with the Metamask scene in WebGL, basically if you logout and try to login again you will see a error in the console.

**Steps**
1. Use the scene [SampleLogin - Metamask]
2. Build with WebGL
3. Login with [Metamask]
4. Click on 'Logout' button
5. Click on 'Continue with Metamask' button

**Expected behavior**
SampleMain appears after login

**Console errors**
InvalidOperationException

**Screenshots/Video**
<img width="841" alt="Screenshot 2024-02-06 at 12 16 21" src="https://github.com/ChainSafe/web3.unity/assets/104365141/938f1583-cd6e-4b5e-b8a4-609b46cf89b9">

**Desktop (please complete the following information):**
 - Chainsafe SDK version: [main]
 - Platform: [WebGL]
 - Unity Version: [e.g., 2022.1]
 - Operating System: [Mac]

**Additional context**
The **workaround** is to reload the page

**Comment by sneakzttv** [comment]
i'll look into this later

**Comment by rob1997** [comment]
closed by #922
