### ISSUE TITLE
Web3Auth not working in main

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#860]
**Describe the bug**
Web3Auth login is not working in main branch, I believe some of these PRs caused the issue: 

- https://github.com/ChainSafe/web3.unity/pull/858 
- https://github.com/ChainSafe/web3.unity/pull/855
- https://github.com/ChainSafe/web3.unity/pull/853

**Steps**
1. Use the scene [SampleLogin - Web3Auth]
2. Login with [Web3Auth]
3. See console

**Expected behavior**
SampleMain is displayed and user is logged in

**Console errors**
```
PlayerData loaded from path /Users/juanmanuelspoleti/Library/Application Support/DefaultCompany/UnitySampleProject/PlayerData.json.
Countly initialized
Creating Core Instance
```

**Screenshots/Video**
If applicable, add screenshots or screen recordings that help visualize the issue.
<img width="1080" alt="Screenshot 2024-02-07 at 13 42 53" src="https://github.com/ChainSafe/web3.unity/assets/104365141/2e599ead-7545-406b-9fb4-16ccca73b0bc">

**Desktop (please complete the following information):**
 - Chainsafe SDK version: [main]
 - Unity Version: [2022.1]
 - Operating System: [Mac]
 - Platform [Editor and WebGL]

**Comment by sneakzttv** [comment]
I'll look into this later

**Comment by kantagara** [comment]
@juans-chainsafe can you retry again? I did merge my stuff from countly back to main so that might made it work again, since I tested it out and it worked.

**Comment by juans-chainsafe** [comment]
> @juans-chainsafe can you retry again? I did merge my stuff from countly back to main so that might made it work again, since I tested it out and it worked.

Looks like that fixed the issue, Web3Auth working again! Both in Unity editor and WebGL build.
