### ISSUE TITLE
Improve redirection success rate for more wallets in WalletConnect

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#862]
**Describe the bug**
Right now, we have a few wallet providers working as expected with WalletConnect, we should increase this rate.

**Steps**
Steps to reproduce the behavior in **STANDALONE**:
1. Use the scene [ SampleLogin - WalletConnect]
2. Click on [Login with WalletConnect] button
3. Try to login with Zerion - Fireblocks - Torus
4. See the console for the redirect link

Steps to reproduce the behavior in **iOS**:
1. Use the scene [ SampleLogin - WalletConnect]
2. Click on [Login with WalletConnect] button
3. Try to login with Uniswap - Zerion
4. See the console in XCode for the redirect link

**Expected behavior**
User is connected to the wallet and redirected to SampleMain

**Console errors**
Last log that I see is: `Generated deep link: infinity://wc?uri=wc%3aa35fdd8c0d2faed4aad1bc7070e2878d9a701cf0c4d6be27080b1d981d84ab0c%402%3fsymKey%3df00b3c5647e1361a58bbc354b13efc41524288d9f286c762825aa54729daafb2%26relay-protocol%3dirn`

**Desktop (please complete the following information):**
 - Chainsafe SDK version: [[e.g., 2.5.0](https://github.com/ChainSafe/web3.unity/pull/825)]
 - Unity Version: [2022.1]
 - Operating System: [Mac]
 - Build platform: Standalone

**Mobile (please complete the following information):**
 - Chainsafe SDK version: [[e.g., 1.0.6](https://github.com/ChainSafe/web3.unity/pull/825)]
 - Platform: [iOS]
 - Device Type: [Real device]

**Additional context**
We know that is working for:

- Metamask
- Binance wallet
- Torus wallet
- Infinity wallet

**Comment by oleksandrchainsafe** [comment]
Will most likely be fixed by #816

**Comment by kantagara** [comment]
@oleksandrchainsafe can we close this?
