### ISSUE TITLE
Import link.xml into assets with Package

### ISSUE THREAD

**Issue by rob1997** [ChainSafe/web3.unity#867]
**Summary**
Currently for Unity v2021 or less we need link.xml to include certain namespace for a working IL2CPP build on IOS. We should streamline/automate that process on package imported.

**Suggested features or ways to address the summary**
- We should have an editor with `[InitializeOnLoad]` to load on package import (using constructor)
- Encase class in `#if !UNITY_2022_1_OR_NEWER` directive since this issue was fixed in v2022 and up
- Check if link.xml was imported using `EditorPrefs` if not import it

**Motivation**
This decreases complexity and onboarding for DevEx.

**Acceptance Criteria**
Importing link.xml should be streamlined and IOS build must work when package is imported from an empty project

**Blockers**
(OPTIONAL) [Do you see any blocker that needs to be done before implementing this feature?]

**Dependencies**
(OPTIONAL) [Do you know about dependencies that directly affect this issue?]

**Additional Context**
(OPTIONAL) [Add any other context, files, images (screenshots/videos), diagrams, or documents about the feature request here.]

**Final Steps**
* Give it one of these labels `Type: Feature` `Type: Enhancement`
* Add your estimation

**Estimations**

| Story Point | Amount of effort | Amount of time | Task Complexity | Task Risk or Uncerntainty |
|----------|----------|----------|----------|----------|
| 1 | Minimum efort | A few minutes | Little complexity | None |
| 2 | Minimum effort | A few hours | Little complexity | None |
| 3 | Mild efort | A day | Low complexity | Low |
| 5 | Moderate efort | A few days | Mediium complexity | Moderate |
| 8 | Severe efort | A week | Medium complexity | Moderate |
| 13 | Maximum effort | A few month | High complexity | High |

**Comment by kantagara** [comment]
This is not needed anymore.
