### ISSUE TITLE
Countly not working in WebGL with Package manager

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#880]
**Describe the bug**
Logs are not being published into Countly dashboard when WebGL is used, in this case the SDK was imported using Package manager + Git URL

**Steps**
1. Use the scene [SampleLogin - Web3Auth]
2. Login with [Web3Auth]
3. Use some of the examples to get a output

**Expected behavior**
Log is sent to Countly and is displayed in the dashboard.

**Console errors**
One of the errors that I see time to time in the console: `POST https://chainsafe-40aca7b26551e.flex.countly.com/i?app_key=4d2f30cecf1b7e2b8cd909103c1fac971872aa3f&device_id=CLY_xYMQohFp1709216956288&t=1&sdk_name=csharp-unity-webgl&sdk_version=23.12.0&av=0.1&timestamp=1709217377591&hour=11&dow=4&tz=-180&events=[%0A%20%20%7B%0A%20%20%20%20%22key%22:%20%22Gelato%20initialized%22,%0A%20%20%20%20%22count%22:%201,%0A%20%20%20%20%22sum%22:%200.0,%0A%20%20%20%20%22segmentation%22:%20%7B%0A%20%20%20%20%20%20%22chain%22:%20%2211155111%22,%0A%20%20%20%20%20%20%22network%22:%20%22ETH%22,%0A%20%20%20%20%20%20%22project-id%22:%20%226aa5af5a-cf38-4093-b78a-net::ERR_CONNECTION_RESET`

**Screenshots/Video**
![Screenshot 2024-02-29 at 11 40 37](https://github.com/ChainSafe/web3.unity/assets/104365141/b7543f94-e8ae-4462-9075-4a2c042b775b)

**Desktop (please complete the following information):**
 - Chainsafe SDK version: [main branch using Package manager with Git URL]
 - Unity Version: [2022.1]
 - Operating System: [Mac]
 - Platform: [WebGL]

**Additional context**
Didn't test iOS yet, it could be happened there as well or be only a WebGL issue

**Comment by juans-chainsafe** [comment]
This is happening in UnitySampleProject as well

**Comment by kantagara** [comment]
@juans-chainsafe I tried it now on 2021.3 and nothing is showing up. But I'll move to 2022 LTS and confirm if error is there.
It probably is due to that cors issue, but will check

**Comment by juans-chainsafe** [comment]
Issue is not happening anymore, I tried with Metamask login and Web3Auth login in WebGL and Countly worked.
