### ISSUE TITLE
SignVerify is failing to verify the transaction in Metamask login scene

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#882]
**Describe the bug**
Sample SignVerify is always failing to verify the transaction with the output "Failed to verify"

**Steps**
1. Use the scene [SampleLogin - Metamask]
2. Login with [Metamask]
3. Try SignVerify sample in More examples section
4. See console log

**Expected behavior**
Output should be "Verified"

**Console errors**
There are not console errors, but the expected output is not correct

**Screenshots/Video**
<img width="373" alt="Screenshot 2024-02-29 at 12 06 39" src="https://github.com/ChainSafe/web3.unity/assets/104365141/6fe9cc93-29ba-435c-bb46-eeecea35c611">

**Desktop (please complete the following information):**
 - Chainsafe SDK version: [main branch using Package manager with Git URL]
 - Unity Version: [e.g., 2022.1]
 - Operating System: [Mac]
 - Platform: [WebGL with Metamask scene]

**Additional context**

- This is working in every other place, only fails when is using Metamask scene

**Comment by rob1997** [comment]
closed by #922
