### ISSUE TITLE
Ramp not working in SampleMain scene

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#883]
**Describe the bug**
Ramp Exchanger section is not working in SampleMain scene when you try to click any of the buttons.
But is working correctly in SampleRampIntegration scene

**Steps**
1. Use the scene [SampleLogin or SampleLogin - Web3Auth]
2. Login with [Web3Auth or Remote wallet]
3. Try to click on "Try On Ramp" or "Try Off ramp"

**Expected behavior**
Ramp modal is open

**Console errors**
There are not console errors, nothing happens when you click the button

**Screenshots/Video**
<img width="730" alt="Screenshot 2024-02-29 at 13 31 20" src="https://github.com/ChainSafe/web3.unity/assets/104365141/9feeb9f4-e0ef-4104-8fc8-bfb7c0f134df">

**Desktop (please complete the following information):**
 - Chainsafe SDK version: [main branch using Package manager with Git URL]
 - Unity Version: [e.g., 2022.1]
 - Operating System: [Mac]
 - Platform: [WebGL]

**Additional context**
- Working correctly in SampleRampIntegration scene, the problem is with SampleMain scene

**Comment by juans-chainsafe** [comment]
Issue not happening anymore in main branch and 2021 Unity version

**Comment by juans-chainsafe** [comment]
My bad, I forget that this issue happens using Package manager with Git URL and not using UnitySampleProject

**Comment by kantagara** [comment]
@juans-chainsafe no PR but check it out. Now it should work. @rob1997 also removed rampsample scene :)

**Comment by juans-chainsafe** [comment]
> @juans-chainsafe no PR but check it out. Now it should work. @rob1997 also removed rampsample scene :)

Ramp is working again in WebGL with Package manager! I used dev branch, but I see the SampleRampIntegration scene, is not removed apparently, unless is in a different PR.

<img width="1278" alt="Screenshot 2024-05-29 at 10 45 47 AM" src="https://github.com/ChainSafe/web3.unity/assets/104365141/46c4de8f-e755-44d2-a8bb-6b51ca25b31a">
