### ISSUE TITLE
Build 1.2.1 SignMessage WebGL example throws error

### ISSUE THREAD

**Issue by joksa** [ChainSafe/web3.unity#89]
After importing the latest build and opening empty scene pulling Prefab
SignMessageExampleCanvas, build was success on button click to sign message error thrown

**EntryPointNotFoundException: SignMessage assembly:<unknown assembly> type:<unknown type> member:(null)**

1. New Scene
2. Put Prefab on scene
3. Run inside Unity
4. Click on the button to Sign

**Desktop (please complete the following information):**
 - OS: macOS M1
 - Unity 2021.2.9f1

All Web3Wallet examples are working inside unity, but for production I need WebGL

**Comment by KBryan** [comment]
This happens as you need to have access to your wallet in order to sign in WebGL which happens when you build and deploy. Web3Wallet works because it opens up a browser to sign but the game is either Mobile or Desktop.
