### ISSUE TITLE
Web3Auth -> Ensure it's opening in the new tab in webgl.

### ISSUE THREAD

**Issue by kantagara** [ChainSafe/web3.unity#894]
**Summary**
This issue is critical for any game that builds using our SDK and is not immediately on login scene like our sample is.

**Motivation**
Testing out block racers on webGL gives us that problem and the best solution would be to do web3auth in the new tab instead of opening it in the same tab.

**Acceptance Criteria**

- [ ] Web3auth tab opens
- [ ] User logs in 
- [ ] Our game logs in successfully.

**Comment by sneakzttv** [comment]
closing due to conversations with Nikola
