### ISSUE TITLE
Explore UniTask as an alternative to WebGL Threading Patcher

### ISSUE THREAD

**Issue by kantagara** [ChainSafe/web3.unity#906]
**Summary**
Got a suggestion on Discord to actually try [UniTask](https://github.com/Cysharp/UniTask), Seems like a way better solution than threading patcher (less hacky)

**Motivation**
Seems like UniTask supports webGL OOB, so doing async await trough it should be better and less hacky

**Acceptance Criteria**

- [ ] UniTask integrated and WebGL Threading Patcher is out!

**Comment by rob1997** [comment]
After a lot of trial and error it seems [UniTask](https://github.com/Cysharp/UniTask) is a no go to solve the WebGL build async issue, eventhough `UniTask` in itself works on any platform including WebGL converting `Task -> UniTask` doesn't solve our issue even if that task is being awaited in a `UniTask`, the primary issue isn't our libraries in `ChainSafe.Gamming` but rather their dependencies like `NEthereum` and `WalletConnectCore` which aren't supported on WebGL and awaiting their functions in `UniTask` or even converting them to `UniTask` doesn't seem to solve the issue. I've Tried converting  tasks with `Task.AsUniTask` awaiting Tasks in `UniTask` and even `UniTask.ToCoroutine` all didn't work.
