### ISSUE TITLE
Countly initialization lag

### ISSUE THREAD

**Issue by rob1997** [ChainSafe/web3.unity#910]
**Describe the bug**
When we play the game several times, Counlty (our current analytics tool) accumulates a lot of garbage which makes our next session progressively laggy!

**Steps**
1. Run sample scene several times with extended runtime

**Expected behavior**
A consistent initialization wait time.

**Console errors**
None.

**Screenshots/Video**
If applicable, add screenshots or screen recordings that help visualize the issue.

**Reproducible Code Snippet (if applicable):**
If the issue is related to a specific piece of code, provide the relevant code snippet here.

```csharp```
// Your code snippet here

**Desktop (please complete the following information):**
 - Chainsafe SDK version: [e.g., 2.5.0]
 - Unity Version: [e.g., 2022.1]
 - Operating System: [e.g., Windows 10]

**Mobile (please complete the following information):**
 - Chainsafe SDK version: [e.g., 1.0.6]
 - Platform: [e.g., Android/iOS]
 - Device Type: [e.g., Real device or Emulator/Simulator]
 - OS Version: [e.g., Android 11]

**Additional context**
Please add any other relevant context or information about the problem. This could include device specifications, project configuration, or any other details that might be helpful in diagnosing the issue.

**Comment by rob1997** [comment]
We should find a way to dispose of Countly, destroying the analytics GameObject could fix it

**Comment by sneakzttv** [comment]
Would this explain why we have like 200 users from australia? XD is it just me over and over? Haha

**Comment by sneakzttv** [comment]
Moving to sentry as discussed with the team
