### ISSUE TITLE
Smart Contract Methods which require a "signer" or "msg.sender"

### ISSUE THREAD

**Issue by Baruchware** [ChainSafe/web3.unity#92]
Please consider I am learning solidity now and Im learning gradually how works the blockchain.
so maybe this is not a bug but a misunderstanding by my side.

I faced that when I try to call methods in the smart contract which require the authentication using `msg.sender` or `_msgSender()` doesn't work...

is there a specific reasong for that or is there another way to call these methods?
I am using EVM.Call() Method

PLEASE CONSIDER I AM NOT ON WEBGL AND THAT I AM A NOOB
HAPPY IN CASE YOU CAN HELP ME AND UNDERSTAND BETTER AND IF MY FEEDBACK HELPED YOU!

**Comment by KBryan** [comment]
It may be possible that you are writing to the blockchain instead of reading from it which require different methods provided by the SDK. You will use `Web3GL.SendContract` for writing to the blockchain in `EVM.Call` for reading.
