### ISSUE TITLE
Xcode Issue on iOS build ( WalletConnect Login)

### ISSUE THREAD

**Issue by Biso240** [ChainSafe/web3.unity#932]
hi, whenwhen I try to build the login scene( with WalletConnect) on my iPhone, I get errors on xcode that can be solved by adding User.Notification under unity framework, but after several attempts, it continues to give me this error: InvalidOperationException: A suitable constructor for type 'ChainSafe. Gaming.SygmaClient.SygmaClient' could not be located.
I also tried to import it into Apple Vision Pro, which for this type of application should be similar to iOS, and it gives me the same error.

**Comment by rob1997** [comment]
Hi @Biso240 thank you for submitting this issue, we've recently updated our main branch with a fix for this issue. Import your package from there and If you've any more questions please let us know.

**Comment by Biso240** [comment]
i have created a fresh project, imported the two packages in this page top blue advice: https://docs.gaming.chainsafe.io/current/getting-started.
i have imported samples, and build for iOS the WalletConnect-Chainsafe sample Scene, but I have still the same error (before the Xcode issue, after fixing it by adding User.notifications, I have this error on iPhone: 
InvalidOperationException: A suitable constructor for type 'ChainSafe.Gaming.SygmaClient.SygmaClient' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor. I'm in a Mac
with AppleSilicon chip.
<img width="263" alt="Screenshot 2024-04-30 alle 9 42 32 AM" src="https://github.com/ChainSafe/web3.unity/assets/73908461/8f24bdd2-98e1-4bf4-b43f-666ff0150fa4">
<img width="872" alt="Screenshot 2024-04-30 alle 9 43 47 AM" src="https://github.com/ChainSafe/web3.unity/assets/73908461/d08ad111-9c82-45c6-b8d8-cc6292c7a29a">
<img width="795" alt="Screenshot 2024-04-30 alle 12 12 43 AM" src="https://github.com/ChainSafe/web3.unity/assets/73908461/e7a7cd8a-c60c-46f2-84d5-f982f9563fc7">

**Comment by sneakzttv** [comment]
please try once more from the head into a fresh project, the workaround fixes are in and we've attempted to triage this issue also.

**Comment by sneakzttv** [comment]
fixed with code stripping set to minimal
