### ISSUE TITLE
services.UseWebPageWallet() no longer available in 2.5.5, as well as namespaces ChainSafe.Gaming.Build and ChainSafe.Gaming.Configuration;

### ISSUE THREAD

**Issue by TheOneVries** [ChainSafe/web3.unity#936]
as described in https://docs.gaming.chainsafe.io/current/configuration
we should configure our Web3Builder using something like 
`await new Web3Builder(projectConfig)
        .Configure(services =>
        {
            services.UseUnityEnvironment();
            services.UseRpcProvider();
            services.UseWebPageWallet();
        })`

That 'UseWebPageWallet' is no longer available in 2.5.5. This might have to do with namespaces we should be including that are no longer available either; ChainSafe.Gaming.Build and ChainSafe.Gaming.Configuration
Either this is a bug or some serious code changes took place which is not reflected in documentation.

**Comment by sneakzttv** [comment]
Webpage wallet has been deprecated in favor of wallet connect, you can select a wallet from there and deep link into it like so:

![image](https://github.com/ChainSafe/web3.unity/assets/57473220/8fba015f-9e52-4ae4-86ad-0c3849db6376)
![image](https://github.com/ChainSafe/web3.unity/assets/57473220/e1ef7ffc-983e-402e-8544-a56baaae501a)

```
public Web3Builder ConfigureServices(Web3Builder web3Builder)
    {
        return web3Builder.Configure(services =>
        {
            var rememberSession = rememberSessionToggle.isOn || storedSessionAvailable;

            services.UseWalletConnect(walletConnectConfig.WithRememberSession(rememberSession))
                .UseWalletConnectSigner()
                .UseWalletConnectTransactionExecutor();
        });
    }
```

Thank you for pointing out that our documentation needs updating there.

@JAlbertCode Please make a note of this so we can update it.
