### ISSUE TITLE
Ramp is stuck in a loading loop in WebGL

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#941]
**Describe the bug**
When you try to use Ramp samples in main or the ramp sample scene, Ramp starts loading but is stuck in that loading spinner forever.

**Steps**
1. Use the scene [SampleLogin - Metamask or SampleLogin - Web3Auth]
2. Login with [Web3Auth or Metamask]
3. Click on Try Off Ramp or Try On Ramp or Try On/Off Ramp button

**Expected behavior**
Ramp main screen appears after the loading spinner

**Screenshots/Video**
![Screenshot 2024-05-03 at 10 38 29 AM](https://github.com/ChainSafe/web3.unity/assets/104365141/08a857d1-f706-44ee-8562-6c8592d9962d)

**Desktop (please complete the following information):**
 - Chainsafe SDK version: [https://github.com/ChainSafe/web3.unity/pull/938]
 - Build platform [WebGL]
 - Unity Version: [e.g., 2022.3]
 - Operating System: [Mac]

**Additional context**

- Ramp is working in iOS using web3auth or wallet connect.
- This issue https://github.com/ChainSafe/web3.unity/issues/883 is not happening anymore, we can close it when the PR is merged

**Comment by kantagara** [comment]
@juans-chainsafe is this only on 2022? is it working on 2021?

**Comment by juans-chainsafe** [comment]
> @juans-chainsafe is this only on 2022? is it working on 2021?

Is working in main that the version is 2021, and its failing in #938 that is using 2022

**Comment by juans-chainsafe** [comment]
This is actually a Unity issue. You can find more information [here](https://support.vuplex.com/articles/webgl-cross-origin-embedder-policy)

Workaround for this in Unity 2022 can be found here: https://github.com/ChainSafe/web3.unity/pull/938#issuecomment-2104741794

**Comment by rob1997** [comment]
We're working with Ramp for a possible fix in the meantime please upvote the Unity issue [here](https://issuetracker.unity3d.com/issues/webgl-cross-origin-embedder-policy-require-corp-http-header-is-included-when-multithreading-is-off)
