### ISSUE TITLE
Helper/util methods to convert Eth/Erc20 balances into useable numbers

### ISSUE THREAD

**Issue by mdotstrange** [ChainSafe/web3.unity#95]
There are several conversions that need to be done to lets say take a token balance and its decimals and convert into a usable number to be displayed in a Ui etc

Would be useful is there were some built in conversion methods that could be used for example to...

Return an Eth balance in a format (float?) with the proper decimal places
So return 0.08875 instead of 8875000000000000 etc

The same for erc20 balances-

Something like this would save a lot of time- thanks- love the web3 lib!

**Comment by KBryan** [comment]
Hi, please take a look at our docs. It listed in there on ways to convert eth to wei and wei to eth. https://chainsafe.github.io/game-docs/#convert-wei-to-eth-and-eth-to-wei
