### ISSUE TITLE
Throw error if upload file or metadata to ChainSafe IPFS fails 

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#951]
**Describe the bug**
If you are using IPFS samples and a failed response happens from Storage API, we are not catching that error and we return the IPFS anyways, so the dev doesn't now that something failed.

**Steps**
1. In SampleMain set in IPFS Calls script the Bucket ID and API key from https://app.storage.chainsafe.io/
2. Use the scene [SampleLogin or SampleLogin - Web3Auth]
3. Login with [Web3Auth or Remote wallet]
4. Click on "Upload Metadata" sample
5. Click again in "Upload Metadata" sample

**Expected behavior**

- An error is displayed based on the API response due that there is a conflict with the file (because is duplicated)
- We need to verify the "status" field inside "file_details" object in the API response and show the "message" field if status is "failed"

**Console errors**
This is the API response in case of a conflict:
```
{
    "path": "/test",
    "files_details": [
        {
            "path": "/test/package.json",
            "cid": "QmbqtW6GFZofCGa41rqDhhyznFLKoGZ5LPSBAhxFeGH2gV",
            "content_type": "application/json",
            "size": 2103,
            "status": "failed",
            "error_code": 409,
            "message": "path:/test/package.json, conflict, entry can't be added",
            "suggestion": "/test/package(1).json"
        }
    ]
}
```

**Screenshots/Video**
![329930806-68bff7d7-b541-4aa5-bf81-807949638209](https://github.com/ChainSafe/web3.unity/assets/104365141/05e5c706-9a3b-4067-91e0-44290c18c9c3)

**Comment by juans-chainsafe** [comment]
Issue is related to https://github.com/ChainSafe/web3.unity/pull/949

**Comment by juans-chainsafe** [comment]
> I'm getting a different response unity side when uploading the same metadata file twice
> 
> ```
> {
> "content": 
> {
> "name":"MetaData.json",
> "cid":"Qmdf8XcXn8HepJpWFA1cYmiXVQa6t6YSto2GN7GLskwFUY",
> "content_type":"application/octet-stream",
> "size":379,
> "version":1,
> "created_at":1715576819
> },
> "persistent":null,"messages":null
> }
> ```

Looks like we will need this ticket to be done first https://github.com/ChainSafe/ui-monorepo/issues/2270

**Comment by sneakzttv** [comment]
will check back later then, i should just be able to do this in IPFS.cs at the end of the upload function

`return data.content.status == "failed" ? $"Error uploading: {data.content.message}" : data.content.cid;`

**Comment by juans-chainsafe** [comment]
> > I'm getting a different response unity side when uploading the same metadata file twice
> > ```
> > {
> > "content": 
> > {
> > "name":"MetaData.json",
> > "cid":"Qmdf8XcXn8HepJpWFA1cYmiXVQa6t6YSto2GN7GLskwFUY",
> > "content_type":"application/octet-stream",
> > "size":379,
> > "version":1,
> > "created_at":1715576819
> > },
> > "persistent":null,"messages":null
> > }
> > ```
> 
> Looks like we will need this ticket to be done first [ChainSafe/ui-monorepo#2270](https://github.com/ChainSafe/ui-monorepo/issues/2270)

My bad, this is for the Storage UI, not the API.
We should be able to see the error details in the response of the /upload endpoint and not the /file endpoint
cc @sneakzttv
