### ISSUE TITLE
IPFS/Marketplace image uploads for samples in WebGL & other platforms

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#959]
**Describe the bug**
Right now iPFS samples works for the editor and iOS build but we need to implement them to work in WebGL

**Steps**
1. Set your bucket ID and API key in IPFS calls (SampleMain scene)
2. Build with WebGL
3. Use the scene [SampleLogin or SampleLogin - Web3Auth]
4. Login with [Web3Auth or Remote wallet]
5. Click on each of the IPFS samples

**Expected behavior**

- Upload Image works
- Upload Metadata works
- Upload Image & Metadata works

**Desktop (please complete the following information):**
 - Chainsafe SDK version: [dev]
 - Platform [WebGL]
 - Unity Version: [e.g., 2022.1]
 - Operating System: [Mac]

**Comment by sneakzttv** [comment]
Will implement a JS function to hook around this after the marketplace. It's happening because webgl has limited system access due to it's environment.

**Comment by juans-chainsafe** [comment]
This is breaking Desktop builds as well
```
/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/EVM/IPFS/IPFS.cs(65,33): error CS0234: The type or namespace name 'EditorUtility' does not exist in the namespace 'UnityEditor' (are you missing an assembly reference?)

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/EVM/IPFS/IPFS.cs(125,33): error CS0234: The type or namespace name 'EditorUtility' does not exist in the namespace 'UnityEditor' (are you missing an assembly reference?)
```

Make sure to work both for WebGL and Desktop

**Comment by sneakzttv** [comment]
My mistake, assumed we checked over this in the last PR, will fix now.
