### ISSUE TITLE
Samples that require gas fee not working with Web3Auth and WebGL

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#960]
**Describe the bug**
In dev branch, after building in WebGL with Web3Auth, samples that require gas fee are not working.

**Steps**
1. Use the scene [SampleLogin - Web3Auth]
2. Login with [Web3Auth]
3. Click on any sample that require gass fee, for example: **GetNonce**

**Expected behavior**

- Expected output is displayed in the console without errors, like the nonce (if you click on GetNonce)

**Console errors**
```
webgl3.framework.js.gz:10 DllNotFoundException: Unable to load DLL 'libc'. Tried the load the following dynamic libraries: 
Rethrow as RpcClientUnknownException: Error occurred when trying to send rpc requests(s): eth_getTransactionCount
  at Nethereum.JsonRpc.Client.SimpleRpcClient.SendAsync (Nethereum.JsonRpc.Client.RpcMessages.RpcRequestMessage request, System.String route) [0x00000] in <00000000000000000000000000000000>:0 
Rethrow as Web3Exception: Error occurred when trying to send rpc requests(s): eth_getTransactionCount
  at ChainSafe.Gaming.InProcessTransactionExecutor.InProcessTransactionExecutor.SendTransaction (ChainSafe.Gaming.Evm.Transactions.TransactionRequest transaction)
```

**Screenshots/Video**
<img width="1552" alt="Screenshot 2024-05-15 at 12 18 31 PM" src="https://github.com/ChainSafe/web3.unity/assets/104365141/f9fe8ba9-63fb-4440-85eb-95329fd395e5">

**Desktop (please complete the following information):**
 - Chainsafe SDK version: [dev]
 - Platform: [WebGL]
 - Unity Version: [2021.1]
 - Operating System: [Mac]

**Additional context**

- This is working in the editor
- Sepolia was working very bad today, can be that the issue?

**Comment by kantagara** [comment]
reopening the issue.

**Comment by rob1997** [comment]
@juans-chainsafe this is already fixed, right?
