### ISSUE TITLE
Countly - Don't send Project ID with every event but rather send it with the user ID.

### ISSUE THREAD

**Issue by kantagara** [ChainSafe/web3.unity#968]
**Summary**
Countly - Don't send Project ID with every event but rather send it with the user ID.

**Motivation**
Analytics team asked me to do it like that 😄 

**Acceptance Criteria**
Project ID should appear with a user rather than sent via every single event

**Comment by boorich** [comment]
@stonecharioteer please add some context so I can follow along.

**Comment by kantagara** [comment]
The context is that we are sending with every event the project id, and I think Anas suggested that we should send project id per user, rather than with every event.
