### ISSUE TITLE
ERC721.URI (EVM.Call I believe) fails

### ISSUE THREAD

**Issue by ShinyUser123** [ChainSafe/web3.unity#98]
**Describe the bug**
When calling ERC721.URI(chain, network, contract, tokenId); it randomly fails giving the following error: 
`Invalid JSON RPC response: "<html>/r/n<head><title>504 Gateway Time-out</title></head>/r/n<body>/r/n<center><h1>504 Gateway Time-out</h1></center>/r/n</body>/r/n</html>/r/n"`

**To Reproduce**
1. Call ERC721.URI(chain, network, contract, tokenId);

**WebGL**
-WebGL build on mozilla, or chrome. In unity editor it just returns an empty string (I use the `webRequest.downloadHandler.text`)

**Comment by KBryan** [comment]
Can you give a code snippet and where are you hosting your MetaData and images ?
