### ISSUE TITLE
Buy listed NFT not working 

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#998]
**Describe the bug**
I set the data to buy the NFT based on the previously listed NFT, but I get a error.

@sneakzttv buy NFT is not in gaming dashboard, are we sure that this functionality is working? we can skip it otherwise for now.

**Steps**
1. Use the scene [SampleLogin or SampleLogin - Web3Auth]
2. Login with [Web3Auth or Remote wallet]
3. Click on Purchase NFT button in Marketplace section

**Expected behavior**
Transaction is success and the NFT is owned by the new address

**Console errors**
```
FormatException: The value could not be parsed.
System.Numerics.BigNumber.ParseBigInteger (System.ReadOnlySpan`1[T] value, System.Globalization.NumberStyles style, System.Globalization.NumberFormatInfo info) (at <4e334f13171643b6a8290d57ecc16bd7>:0)
System.Numerics.BigNumber.ParseBigInteger (System.String value, System.Globalization.NumberStyles style, System.Globalization.NumberFormatInfo info) (at <4e334f13171643b6a8290d57ecc16bd7>:0)
System.Numerics.BigInteger.Parse (System.String value, System.Globalization.NumberStyles style, System.IFormatProvider provider) (at <4e334f13171643b6a8290d57ecc16bd7>:0)
System.Numerics.BigInteger.Parse (System.String value, System.Globalization.NumberStyles style) (at <4e334f13171643b6a8290d57ecc16bd7>:0)
System.Numerics.BigInteger.Parse (System.String value) (at <4e334f13171643b6a8290d57ecc16bd7>:0)
Scripts.EVM.Marketplace.Marketplace.PurchaseNft (System.String _marketplaceContract, System.String _itemId, System.String _amountToSend) (at ./Library/PackageCache/io.chainsafe.web3-unity.marketplace@8365aedec2/Runtime/Scripts/Marketplace/Marketplace.cs:377)
MarketplaceCalls.PurchaseNftFromMarketplace () (at Assets/Samples/web3.unity SDK/2.6.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Marketplace/MarketplaceCalls.cs:268)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <e307bbb467104258887a104f6151f183>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:153)
UnityEngine.UnitySynchronizationContext.Exec () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:83)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:107)

```

**Screenshots/Video**
<img width="586" alt="Screenshot 2024-06-03 at 10 44 14 AM" src="https://github.com/ChainSafe/web3.unity/assets/104365141/a25a5886-5dc3-4b92-b940-4cf3395b575d">

**Comment by juans-chainsafe** [comment]
@sneakzttv in case we want to fix this, we should rename this section to "Buy NFT marketplace calls"
<img width="593" alt="Screenshot 2024-06-03 at 10 47 17 AM" src="https://github.com/ChainSafe/web3.unity/assets/104365141/46e7a779-a621-4cd8-bb05-60951c6baa78">

**Comment by sneakzttv** [comment]
Yes works, list an nft and fill out the buy info, should purchase and transfer provided the nft is listed. Of course it needs a buy function.

**Comment by juans-chainsafe** [comment]
> Yes works, list an nft and fill out the buy info, should purchase and transfer provided the nft is listed. Of course it needs a buy function.

ok, what I did is to use the same data that I used to list the NFT, so first I listed the NFT and then I tried the buy function, but i got that format error, I think is having issues with the "wei" number format, but I used the same value that I have in list nft sample
<img width="625" alt="Screenshot 2024-06-03 at 10 54 43 AM" src="https://github.com/ChainSafe/web3.unity/assets/104365141/28b8ea48-7461-4137-a850-bf3bcbaf3579">

**Comment by sneakzttv** [comment]
i'll check :)
